import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// EEAT / Trust pages — /company/[slug]
// Experience, Expertise, Authoritativeness, Trust. Heritage-framed: a
// third-generation, family-owned carpet-making legacy since 1965 — NOT the legal
// entity founded in 1965. Each page is unique and substantive.
// ─────────────────────────────────────────────────────────────────────────────

const REL_PRODUCTS = ['hand-tufted-carpet', 'hand-knotted-carpet', 'wall-to-wall-carpets']
const REL_INDUSTRIES = ['hotel-carpets', 'office-carpets']

export const COMPANY_PAGES: SeoLanding[] = [
  {
    slug: 'factory', kind: 'company', label: 'Our Factory', heroImage: '/images/manufacturing-rug-img.webp',
    eyebrow: 'Bhadohi Manufacturing Facility',
    tagline: 'An 80,000 sq ft integrated carpet manufacturing facility in Bhadohi — the heart of a three-generation family legacy.',
    seoTitle: 'Our Carpet Factory in Bhadohi, India | Manufacturing Facility — Tapis Global',
    seoDescription: 'Inside the Tapis Global carpet factory in Bhadohi, India — an 80,000 sq ft integrated facility for hand tufting, knotting, dyeing and finishing. A third-generation, family-owned manufacturer since 1965. Request a visit or catalogue.',
    seoKeywords: ['carpet factory India', 'carpet manufacturing facility Bhadohi', 'carpet factory Bhadohi', 'rug factory India', 'carpet manufacturer facility'],
    h1: 'Our Carpet Manufacturing Facility in Bhadohi',
    intro: 'Tapis Global International operates an 80,000 sq ft integrated carpet and rug manufacturing facility in Bhadohi, Uttar Pradesh — the heart of a third-generation, family-owned carpet-making legacy that began in 1965. Every stage, from yarn dyeing to final finishing, happens under our own roof.',
    overview: 'Vertical integration is what lets us guarantee quality, consistency and accountability. Rather than outsourcing or trading, we control hand tufting, hand knotting, dyeing, washing, carving and finishing in-house — supported by a skilled artisan community and disciplined quality systems. This is what it means to buy direct from the manufacturer.',
    sections: [
      { h2: 'An Integrated Campus', body: 'Our Bhadohi campus brings dyeing, weaving, tufting, washing, carving, finishing, QC and warehousing onto one integrated site. Materials and work-in-progress are tracked end-to-end, giving full traceability from raw yarn to packed order.' },
      { h2: 'Skilled Artisan Community', body: 'Over 500 skilled craftspeople — tufters, knotters, weavers, dyers and finishers — work across our divisions, many from weaving families rooted in Bhadohi\'s heritage. Generational skill is the foundation of our quality.' },
      { h2: 'Built for Projects & Scale', body: 'The facility is geared for both bespoke single pieces and large contract, hospitality and tender volumes — with the capacity to hold dye-lots, phase production and meet fixed programme dates.' },
    ],
    applications: [
      { title: 'In-House Dyeing', desc: 'Yarn dyeing with lab-dip colour matching for accuracy and consistency.' },
      { title: 'Weaving & Tufting', desc: 'Hand knotting, hand tufting and broadloom across dedicated divisions.' },
      { title: 'Washing & Finishing', desc: 'Washing, carving, shearing and binding for a premium finish.' },
      { title: 'QC & Warehousing', desc: 'Multi-stage inspection and climate-aware storage before dispatch.' },
    ],
    whyPoints: [
      { title: 'Vertically Integrated', desc: 'Every stage in-house for quality and traceability.' },
      { title: 'Three Generations', desc: 'Family carpet-making knowledge since 1965.' },
      { title: 'Project Capacity', desc: 'Bespoke to bulk under one Bhadohi roof.' },
    ],
    faqs: [
      { q: 'Where is your carpet factory located?', a: 'Our integrated manufacturing facility is in Bhadohi, Uttar Pradesh — India\'s largest handwoven carpet cluster. We are a third-generation, family-owned manufacturer continuing a legacy since 1965.' },
      { q: 'Do you manufacture in-house or outsource?', a: 'We manufacture in-house. Dyeing, tufting, knotting, washing, carving, finishing and QC all happen at our own Bhadohi facility — we are a direct manufacturer, not a trader.' },
      { q: 'Can buyers visit the factory?', a: 'Yes. We welcome serious buyers, architects and procurement teams to visit our Bhadohi facility by appointment. Contact us to arrange a visit.' },
      { q: 'How large is your facility?', a: 'Our integrated campus spans approximately 80,000 sq ft with 500+ skilled artisans across all production divisions.' },
    ],
    relatedProducts: REL_PRODUCTS, relatedIndustries: REL_INDUSTRIES,
    relatedCompany: ['manufacturing-process', 'production-capacity', 'why-bhadohi'],
  },
  {
    slug: 'manufacturing-process', kind: 'company', label: 'Manufacturing Process', heroImage: '/images/tufting-carpet.webp',
    eyebrow: 'How We Make Carpets',
    tagline: 'From yarn to finished carpet — our handmade manufacturing process, refined over three generations.',
    seoTitle: 'Carpet Manufacturing Process | How Our Carpets Are Made — Tapis Global',
    seoDescription: 'How Tapis Global manufactures carpets in Bhadohi — design, dyeing, hand tufting and knotting, washing, carving and finishing. A transparent, in-house, three-generation manufacturing process. Request a catalogue.',
    seoKeywords: ['carpet manufacturing process', 'how carpets are made', 'hand tufting process', 'hand knotting process', 'carpet making process India'],
    h1: 'Our Carpet Manufacturing Process',
    intro: 'Every Tapis Global carpet follows a disciplined, largely handmade manufacturing process refined across three generations of family carpet-making since 1965. Understanding the process is the best way to understand our quality.',
    overview: 'From the first lab-dip to the final inspection, each stage is controlled in-house at our Bhadohi facility. This transparency lets architects, designers and procurement teams specify with confidence and verify exactly how their carpets are produced.',
    sections: [
      { h2: 'Design & Colour Development', body: 'We translate artwork, mood boards and Pantone references into production maps, then lab-dip yarn colours for approval before any bulk production begins — so the finished carpet matches the intent exactly.' },
      { h2: 'Weaving, Tufting & Knotting', body: 'Depending on construction, artisans hand-knot on vertical looms, hand-guide tufting across stretched backing, or weave flatweaves and broadloom — each technique with its own craft and quality controls.' },
      { h2: 'Washing, Finishing & QC', body: 'Carpets are washed for lustre, sheared and hand-carved where required, edge-finished, then passed through multi-stage and 100% pre-dispatch inspection before packing.' },
    ],
    applications: [
      { title: '01 · Design & Lab-Dip', desc: 'Artwork to production map; yarn lab-dipped to Pantone.' },
      { title: '02 · Weave / Tuft / Knot', desc: 'Construction built by hand to the approved design.' },
      { title: '03 · Wash & Finish', desc: 'Washing, carving, shearing and edge finishing.' },
      { title: '04 · Inspect & Pack', desc: 'Multi-stage and 100% pre-dispatch QC.' },
    ],
    whyPoints: [
      { title: 'Transparent', desc: 'Every stage visible and verifiable.' },
      { title: 'Handmade Craft', desc: 'Skilled artisan work at the core.' },
      { title: 'Approve Before Bulk', desc: 'Lab-dips and samples signed off first.' },
    ],
    faqs: [
      { q: 'What are the main steps in carpet manufacturing?', a: 'Design and lab-dip colour development; weaving, tufting or knotting; washing, carving and finishing; then multi-stage and pre-dispatch quality control — all in-house at our Bhadohi facility.' },
      { q: 'Can I approve colours and a sample before production?', a: 'Yes. We lab-dip yarn to your Pantone references and produce a sample for approval before any bulk production begins.' },
      { q: 'Is the process handmade or machine-made?', a: 'Our core constructions — hand knotted, hand tufted and handwoven flatweave — are handmade by skilled artisans; broadloom and tiles use wide-width production. We advise per product.' },
      { q: 'How do you ensure consistency across a large order?', a: 'We hold dye-lots, document specifications and apply multi-stage plus 100% pre-dispatch inspection so large and phased orders stay consistent.' },
    ],
    relatedProducts: REL_PRODUCTS, relatedIndustries: REL_INDUSTRIES,
    relatedCompany: ['factory', 'quality-control', 'custom-manufacturing'],
  },
  {
    slug: 'quality-control', kind: 'company', label: 'Quality Control', heroImage: '/images/vibrant-wool-dying.webp',
    eyebrow: 'Quality Assurance',
    tagline: 'Multi-stage quality control and 100% pre-dispatch inspection on every carpet we manufacture.',
    seoTitle: 'Carpet Quality Control & Assurance | Tapis Global International',
    seoDescription: 'Tapis Global\'s carpet quality control — batch-tested raw materials, in-process checks, OEKO-TEX compliance and 100% pre-dispatch inspection. Quality systems for architects, hospitality and export buyers. Request details.',
    seoKeywords: ['carpet quality control', 'carpet quality assurance', 'OEKO-TEX carpet manufacturer', 'ISO 9001 carpet manufacturer', 'carpet inspection process'],
    h1: 'Carpet Quality Control & Assurance',
    intro: 'Quality is non-negotiable for premium interiors, hospitality audits and export buyers. Tapis Global applies multi-stage quality control and 100% pre-dispatch inspection to every carpet, backed by three generations of manufacturing discipline.',
    overview: 'Our quality systems begin before production — with batch-tested raw materials — and continue through every stage to a documented final inspection. This gives architects, hotel brands, procurement teams and importers verifiable assurance on every order.',
    sections: [
      { h2: 'From Raw Material In', body: 'Wool, silk, viscose, cotton and jute are batch-tested for quality before entering production. AZO-free dyes and OEKO-TEX-aligned practices ensure textile safety from the start.' },
      { h2: 'In-Process Controls', body: 'Checks at dyeing, weaving/tufting, washing and finishing catch deviations early — protecting colour accuracy, density, dimensions and finish across the order.' },
      { h2: 'Documented Pre-Dispatch Review', body: 'Every order passes a 100% pre-dispatch inspection against its specification, with documentation that supports architect submissions, hospitality standards, tender compliance and import requirements.' },
    ],
    applications: [
      { title: 'Material Testing', desc: 'Batch-tested fibres and AZO-free dyes before production.' },
      { title: 'In-Process Checks', desc: 'Colour, density, dimension and finish controls at each stage.' },
      { title: 'Pre-Dispatch Inspection', desc: '100% inspection against specification before packing.' },
      { title: 'Compliance Docs', desc: 'Fire-rating, OEKO-TEX and export documentation.' },
    ],
    whyPoints: [
      { title: 'Multi-Stage QC', desc: 'Controls from raw material to final pack.' },
      { title: '100% Inspection', desc: 'Every order reviewed pre-dispatch.' },
      { title: 'Certified Practices', desc: 'ISO 9001:2015 and OEKO-TEX aligned.' },
    ],
    faqs: [
      { q: 'How do you control carpet quality?', a: 'Through batch-tested raw materials, in-process checks at every production stage, and a documented 100% pre-dispatch inspection against each order\'s specification.' },
      { q: 'Are your carpets certified?', a: 'Our processes are ISO 9001:2015 aligned and we manufacture with OEKO-TEX Standard 100 compliance and AZO-free dyes. Fire-rating and other certifications are available per requirement.' },
      { q: 'Do you provide quality documentation for projects?', a: 'Yes. We provide documentation supporting architect submissions, hospitality brand standards, tender compliance and export import requirements.' },
      { q: 'What happens if a carpet fails inspection?', a: 'Items that do not meet specification are corrected or remade before dispatch — our 100% pre-dispatch review exists to catch issues before they reach you.' },
    ],
    relatedProducts: REL_PRODUCTS, relatedIndustries: REL_INDUSTRIES,
    relatedCompany: ['certifications', 'manufacturing-process', 'export-process'],
  },
  {
    slug: 'export-process', kind: 'company', label: 'Export Process', heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Global Supply',
    tagline: 'How we export carpets from India — documentation, packing and freight handled end to end.',
    seoTitle: 'Carpet Export Process from India | How We Export — Tapis Global International',
    seoDescription: 'Tapis Global\'s carpet export process — order, sampling, manufacturing, compliance documentation, export packing and freight to 45+ countries. A reliable Indian carpet exporter for importers and projects. Request details.',
    seoKeywords: ['carpet export process India', 'how to export carpets from India', 'carpet exporter process', 'Indian carpet export documentation', 'carpet shipping from India'],
    h1: 'Our Carpet Export Process',
    intro: 'Exporting handmade carpets reliably is about more than production — it is documentation, compliance, consistent quality and dependable logistics. Tapis Global manages the full export chain in-house for buyers in 45+ countries.',
    overview: 'While the majority of our business serves projects across India, we run established export programmes. Overseas importers, distributors and project buyers receive the right product, on time, with the right paperwork — backed by three generations of manufacturing experience.',
    sections: [
      { h2: 'Order, Sample & Approval', body: 'We confirm specification, develop lab-dips and samples for approval, and agree commercial terms — so there are no surprises before manufacturing begins.' },
      { h2: 'Manufacturing & Compliance', body: 'We manufacture to destination-market standards, including fire-rating where specified, and prepare the commercial and compliance documentation each shipment requires.' },
      { h2: 'Packing & Freight', body: 'Carpets are packed for safe international transit and freight is coordinated to your preferred port and terms, with phased dispatch for large or multi-lot orders.' },
    ],
    applications: [
      { title: 'Enquiry & Quotation', desc: 'Specification, samples and transparent quotation.' },
      { title: 'Manufacturing', desc: 'Production to destination-market standards with QC.' },
      { title: 'Documentation', desc: 'Commercial and compliance paperwork for customs.' },
      { title: 'Packing & Freight', desc: 'Export packing and coordinated sea/air freight.' },
    ],
    whyPoints: [
      { title: 'Full Chain In-House', desc: 'Production to documentation to freight.' },
      { title: 'Compliance-Ready', desc: 'Destination-standard manufacturing and paperwork.' },
      { title: '45+ Countries', desc: 'Established international supply experience.' },
    ],
    faqs: [
      { q: 'How does your carpet export process work?', a: 'Enquiry and quotation; sample and approval; manufacturing to destination standards with QC; compliance documentation; export packing; and coordinated freight to your port and terms.' },
      { q: 'What documentation do you provide for exports?', a: 'The commercial and compliance documentation international shipments require, including fire-rating certification where specified.' },
      { q: 'What payment terms do you accept for exports?', a: 'We accept TT, LC, DA and DP and deal in USD, EUR, GBP and INR. Terms are negotiable for established buyers.' },
      { q: 'Which countries do you export to?', a: 'We export to 45+ countries including the USA, UK, Germany, France, Italy, Spain, Netherlands, Belgium, Australia, UAE, Saudi Arabia and Qatar.' },
    ],
    relatedProducts: REL_PRODUCTS, relatedIndustries: ['hotel-carpets', 'retail-carpets'],
    relatedCompany: ['certifications', 'quality-control', 'production-capacity'],
  },
  {
    slug: 'certifications', kind: 'company', label: 'Certifications', heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Standards & Compliance',
    tagline: 'ISO 9001:2015, OEKO-TEX, fair-labour and AZO-free — the standards behind our carpets.',
    seoTitle: 'Carpet Certifications | ISO 9001, OEKO-TEX, Fair Labour — Tapis Global',
    seoDescription: 'Tapis Global carpet certifications and compliance — ISO 9001:2015, OEKO-TEX Standard 100, AZO-free dyes, fair-labour practices and fire-rating options. Standards for architects, hospitality and export buyers.',
    seoKeywords: ['carpet certifications', 'OEKO-TEX carpet', 'ISO 9001 carpet manufacturer', 'GoodWeave carpet', 'fire rated carpet certification'],
    h1: 'Our Certifications & Compliance Standards',
    intro: 'Certifications turn quality claims into verifiable assurance. Tapis Global manufactures to recognised standards for quality, textile safety, fair labour and fire performance — the compliance architects, hospitality brands and export buyers require.',
    overview: 'As a third-generation manufacturer we treat compliance as foundational, not optional. Our certifications and documented practices support specification, audits, tenders and international import requirements across every market we serve.',
    sections: [
      { h2: 'Quality & Textile Safety', body: 'Our processes are ISO 9001:2015 aligned, and we manufacture with OEKO-TEX Standard 100 compliance and AZO-free dyes — ensuring textiles tested safe for harmful substances.' },
      { h2: 'Fair Labour & Sustainability', body: 'We support fair-labour practices and ethical sourcing across our artisan community, with GoodWeave-aligned principles and sustainable natural-fibre options.' },
      { h2: 'Fire-Rating & Project Compliance', body: 'Fire-rated constructions with supporting documentation are available for hospitality, commercial and public-building specifications, alongside REACH and import compliance for exports.' },
    ],
    applications: [
      { title: 'ISO 9001:2015', desc: 'Quality management aligned manufacturing.' },
      { title: 'OEKO-TEX Standard 100', desc: 'Textiles tested for harmful substances.' },
      { title: 'AZO-Free & Fair Labour', desc: 'Safe dyes and ethical artisan practices.' },
      { title: 'Fire-Rating', desc: 'Certified fire-rated options on request.' },
    ],
    whyPoints: [
      { title: 'Verifiable', desc: 'Documented standards, not just claims.' },
      { title: 'Project-Ready', desc: 'Compliance for audits and tenders.' },
      { title: 'Export-Ready', desc: 'REACH and import documentation.' },
    ],
    faqs: [
      { q: 'What certifications do your carpets carry?', a: 'Our processes are ISO 9001:2015 aligned, with OEKO-TEX Standard 100 compliance, AZO-free dyes and fair-labour practices. Fire-rating and other certifications are available per requirement.' },
      { q: 'Are your carpets safe and non-toxic?', a: 'Yes. We manufacture with OEKO-TEX-compliant, AZO-free dyes, meaning textiles are tested for harmful substances.' },
      { q: 'Can you provide fire-rated carpets with documentation?', a: 'Yes. We manufacture fire-rated constructions and provide supporting documentation for hospitality, commercial and public buildings.' },
      { q: 'Do you support fair-labour and ethical sourcing?', a: 'Yes. We support fair-labour practices and ethical sourcing across our artisan community, with GoodWeave-aligned principles.' },
    ],
    relatedProducts: REL_PRODUCTS, relatedIndustries: ['hotel-carpets', 'government-carpets'],
    relatedCompany: ['quality-control', 'sustainability', 'export-process'],
  },
  {
    slug: 'sustainability', kind: 'company', label: 'Sustainability', heroImage: '/images/jute-rugs-manufacturing.webp',
    eyebrow: 'Responsible Manufacturing',
    tagline: 'Natural fibres, AZO-free dyes, fair labour and low-waste craft — sustainability rooted in tradition.',
    seoTitle: 'Sustainable Carpet Manufacturing | Eco-Friendly Rugs — Tapis Global',
    seoDescription: 'Sustainable carpet manufacturing at Tapis Global — natural jute, sisal and wool fibres, AZO-free dyes, fair-labour craft and low-waste handmade production. Eco-conscious carpets for responsible projects.',
    seoKeywords: ['sustainable carpet manufacturer', 'eco-friendly rugs India', 'natural fibre carpets', 'AZO-free carpet manufacturer', 'ethical carpet manufacturer'],
    h1: 'Sustainable & Responsible Carpet Manufacturing',
    intro: 'Handmade carpet-making is inherently low-energy and low-waste, and Tapis Global builds on that with natural fibres, safe dyes and fair-labour craft — sustainability rooted in three generations of traditional manufacturing.',
    overview: 'Responsible manufacturing matters to the designers, hospitality groups and conscious buyers we serve. We combine renewable natural materials, AZO-free dyes, ethical artisan practices and minimal-waste handcraft to offer genuinely responsible flooring.',
    sections: [
      { h2: 'Natural & Renewable Materials', body: 'We work extensively with renewable, biodegradable natural fibres — jute, sisal, seagrass, wool and cotton — sourced from certified suppliers for genuinely sustainable products.' },
      { h2: 'Safe Dyes & Low-Waste Craft', body: 'AZO-free vegetable and chrome dyes reduce chemical impact, while handmade production is inherently low-energy and generates minimal waste compared with industrial alternatives.' },
      { h2: 'People & Fair Labour', body: 'Sustainability includes people. We support fair-labour practices and ethical livelihoods across our Bhadohi artisan community, sustaining traditional skills for future generations.' },
    ],
    applications: [
      { title: 'Renewable Fibres', desc: 'Jute, sisal, seagrass, wool and cotton.' },
      { title: 'AZO-Free Dyes', desc: 'Reduced chemical impact, safer textiles.' },
      { title: 'Low-Waste Handcraft', desc: 'Low-energy production, minimal waste.' },
      { title: 'Fair Livelihoods', desc: 'Ethical artisan practices and skills.' },
    ],
    whyPoints: [
      { title: 'Natural Materials', desc: 'Renewable, biodegradable fibres.' },
      { title: 'Safer Chemistry', desc: 'AZO-free dyes throughout.' },
      { title: 'Ethical Craft', desc: 'Fair labour and traditional skills.' },
    ],
    faqs: [
      { q: 'Are your carpets sustainable?', a: 'Yes. We use renewable natural fibres, AZO-free dyes, fair-labour craft and low-waste handmade production — sustainability rooted in traditional manufacturing.' },
      { q: 'Which sustainable materials do you offer?', a: 'Renewable, biodegradable jute, sisal, seagrass, wool and cotton, sourced from certified suppliers.' },
      { q: 'Are your dyes eco-friendly?', a: 'We use AZO-free vegetable and chrome dyes to reduce chemical impact and ensure textile safety.' },
      { q: 'How is handmade carpet-making sustainable?', a: 'Handmade production is inherently low-energy and low-waste versus industrial alternatives, and it sustains traditional artisan livelihoods and skills.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'flat-weaves', 'hand-knotted-carpet'],
    relatedIndustries: ['office-carpets', 'hotel-carpets'],
    relatedCompany: ['certifications', 'manufacturing-process', 'why-bhadohi'],
  },
  {
    slug: 'custom-manufacturing', kind: 'company', label: 'Custom Manufacturing', heroImage: '/images/handtufted-img-2.webp',
    eyebrow: 'Bespoke Capability',
    tagline: 'Any size, colour, pattern and construction — full custom carpet manufacturing capability.',
    seoTitle: 'Custom Carpet Manufacturing Capability | Bespoke Carpets — Tapis Global',
    seoDescription: 'Tapis Global custom carpet manufacturing — any size, colour, pattern, pile and construction, with lab-dips, samples and design development. Bespoke capability for architects, designers and projects. Request a quote.',
    seoKeywords: ['custom carpet manufacturing', 'bespoke carpet capability', 'custom rug manufacturer', 'made to order carpets', 'design development carpets'],
    h1: 'Custom Carpet Manufacturing Capability',
    intro: 'Bespoke is at the core of what we do. Tapis Global manufactures carpets to any size, colour, pattern, pile and construction — with a structured design-development service refined across three generations of family carpet-making.',
    overview: 'Off-the-shelf rarely fits a real project. Our custom capability gives architects, designers, hospitality groups and retailers exactly the carpet a space needs, with the in-house control to develop, sample and produce it accurately.',
    sections: [
      { h2: 'Everything Is Customisable', body: 'Size and shape (including round, runner and oversized), Pantone/RAL colour matching, cut/loop/carved textures, pile height and density, borders and medallions — across hand tufted, hand knotted, flatweave and broadloom.' },
      { h2: 'Structured Development', body: 'We turn artwork into production maps, develop yarn lab-dips against references, and produce a physical sample for sign-off before bulk — documented and QC\'d against the approved specification.' },
      { h2: 'From One Piece to Programmes', body: 'We make single bespoke pieces for designers and homes as well as large custom programmes for hospitality, commercial and retail rollouts, with dye-lot consistency.' },
    ],
    applications: [
      { title: 'Custom Size & Shape', desc: 'Any dimension, including round and oversized.' },
      { title: 'Colour Matching', desc: 'Pantone/RAL lab-dips approved before bulk.' },
      { title: 'Texture & Construction', desc: 'Cut, loop, carved, knotted and flatweave.' },
      { title: 'Branding & Medallions', desc: 'Logos, crests and bespoke patterns.' },
    ],
    whyPoints: [
      { title: 'Total Flexibility', desc: 'Size, colour, pattern, pile, construction.' },
      { title: 'Approve First', desc: 'Lab-dips and samples before production.' },
      { title: 'Single to Bulk', desc: 'One piece or full programmes.' },
    ],
    faqs: [
      { q: 'What can you customise on a carpet?', a: 'Size, shape, Pantone/RAL colour, pattern, texture, pile height and density, borders, medallions and construction — across hand tufted, hand knotted, flatweave and broadloom.' },
      { q: 'Can I approve a sample before bulk?', a: 'Yes. We develop lab-dips and a physical sample for approval before manufacturing, and QC production against the approved specification.' },
      { q: 'Do you make one-off custom pieces?', a: 'Yes — single bespoke pieces for designers and homes, as well as large custom programmes for projects and rollouts.' },
      { q: 'How long does a custom carpet take?', a: 'Typically 30–90 days depending on construction, size and quantity; custom samples usually within 2–3 weeks. Share your deadline for confirmation.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'hand-knotted-carpet', 'area-rugs'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets'],
    relatedCompany: ['oem-private-label', 'manufacturing-process', 'production-capacity'],
  },
  {
    slug: 'oem-private-label', kind: 'company', label: 'OEM & Private Label', heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'OEM / Private Label',
    tagline: 'White-label carpet and rug manufacturing — your brand, our craft, under confidentiality.',
    seoTitle: 'OEM & Private Label Carpet Manufacturer India | White-Label Rugs — Tapis Global',
    seoDescription: 'OEM and private-label carpet and rug manufacturer in India. White-label production with custom branding, labelling and packaging for retailers, importers and brands — under confidentiality. Request a quote.',
    seoKeywords: ['OEM carpet manufacturer', 'private label rug manufacturer', 'white label carpet manufacturer India', 'private label carpets', 'OEM rug supplier'],
    h1: 'OEM & Private Label Carpet Manufacturing',
    intro: 'Tapis Global is an OEM and private-label carpet and rug manufacturer, producing under retailers\' and brands\' own labels with custom branding, packaging and confidentiality — backed by three generations of manufacturing craft.',
    overview: 'For retailers, importers, e-commerce brands and designers, private-label manufacturing means selling genuine handmade quality under your own identity. We provide the craft, consistency and discretion that white-label partnerships require.',
    sections: [
      { h2: 'Your Brand, Our Craft', body: 'We manufacture to your designs and specifications and finish with your branding, labelling and packaging — so the product is unmistakably yours while built on our manufacturing quality.' },
      { h2: 'Consistency & Confidentiality', body: 'We hold dye-lots and apply QC for batch-consistent repeat supply, and work under confidentiality agreements to protect your designs and commercial relationships.' },
      { h2: 'Retail to Contract', body: 'From private-label retail collections and e-commerce ranges to contract and hospitality programmes, we scale OEM production to your channel and volume.' },
    ],
    applications: [
      { title: 'Custom Branding', desc: 'Your labels, packaging and brand identity.' },
      { title: 'Design to Spec', desc: 'Manufactured to your designs and standards.' },
      { title: 'Repeat Consistency', desc: 'Held dye-lots and QC for reorders.' },
      { title: 'Confidentiality', desc: 'NDA-backed design and commercial protection.' },
    ],
    whyPoints: [
      { title: 'True White-Label', desc: 'Your brand on genuine handmade quality.' },
      { title: 'Discreet', desc: 'Confidentiality across designs and terms.' },
      { title: 'Scalable', desc: 'Retail collections to contract volumes.' },
    ],
    faqs: [
      { q: 'Do you offer private-label carpet manufacturing?', a: 'Yes. We manufacture under your brand with custom branding, labelling and packaging, under confidentiality — full OEM and private-label service.' },
      { q: 'Can you manufacture to our designs?', a: 'Yes. We produce to your designs and specifications, developing lab-dips and samples for approval before bulk.' },
      { q: 'Will my designs be kept confidential?', a: 'Yes. We work under confidentiality agreements to protect your designs and commercial relationships.' },
      { q: 'What volumes do you support for OEM?', a: 'From private-label retail collections to large contract and hospitality programmes, scaled to your channel and volume.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'shaggy-rugs', 'jute-sisal-rugs'],
    relatedIndustries: ['retail-carpets', 'hotel-carpets'],
    relatedCompany: ['custom-manufacturing', 'production-capacity', 'quality-control'],
  },
  {
    slug: 'production-capacity', kind: 'company', label: 'Production Capacity', heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Scale & Capacity',
    tagline: '80,000 sq ft, 500+ artisans and bulk capacity — built for projects, tenders and export volumes.',
    seoTitle: 'Carpet Production Capacity | Bulk & Contract Manufacturing — Tapis Global',
    seoDescription: 'Tapis Global carpet production capacity — an 80,000 sq ft Bhadohi facility, 500+ artisans, held dye-lots and phased delivery for bulk, contract, tender and export volumes. Request capacity for your project.',
    seoKeywords: ['carpet production capacity', 'bulk carpet manufacturer', 'contract carpet manufacturing capacity', 'large volume carpet supplier', 'carpet factory capacity India'],
    h1: 'Our Production Capacity',
    intro: 'Scale matters for projects, tenders and export programmes. Tapis Global combines an 80,000 sq ft Bhadohi facility, 500+ skilled artisans and disciplined planning to deliver large volumes without compromising handmade quality.',
    overview: 'Capacity is not just output — it is the ability to hold dye-lots, phase production and hit fixed programme dates while maintaining consistency. Our integrated facility and experienced project team give buyers confidence on large and recurring orders.',
    sections: [
      { h2: 'Facility & Workforce', body: 'An 80,000 sq ft integrated campus with 500+ artisans across tufting, knotting, flatweave, dyeing and finishing divisions provides substantial, flexible manufacturing capacity.' },
      { h2: 'Bulk, Contract & Tender', body: 'We manufacture large hospitality, commercial, institutional and tender volumes with batch consistency, competitive pricing and the documentation project and procurement buyers require.' },
      { h2: 'Phased & On-Time Delivery', body: 'We hold dye-lots and plan phased production and dispatch aligned to construction and tender programmes, so multi-phase and multi-lot orders stay consistent and on schedule.' },
    ],
    applications: [
      { title: '80,000 Sq Ft Campus', desc: 'Integrated facility across all divisions.' },
      { title: '500+ Artisans', desc: 'Skilled workforce for flexible capacity.' },
      { title: 'Held Dye-Lots', desc: 'Colour consistency across large runs.' },
      { title: 'Phased Delivery', desc: 'Dispatch aligned to programme dates.' },
    ],
    whyPoints: [
      { title: 'Real Scale', desc: '80,000 sq ft and 500+ artisans.' },
      { title: 'Consistency', desc: 'Dye-lots held across volume orders.' },
      { title: 'On-Time', desc: 'Phased delivery to programme dates.' },
    ],
    faqs: [
      { q: 'How large are your production volumes?', a: 'Our 80,000 sq ft Bhadohi facility and 500+ artisans manufacture large hospitality, commercial, institutional, tender and export volumes with batch consistency.' },
      { q: 'Can you handle large project and tender orders?', a: 'Yes. We manufacture bulk volumes, hold dye-lots and deliver in phases aligned to construction and tender programme dates.' },
      { q: 'Do large orders compromise handmade quality?', a: 'No. Our integrated facility and QC systems let us scale without compromising the handmade character and consistency of our carpets.' },
      { q: 'How do you ensure on-time delivery at scale?', a: 'We plan production and phased dispatch against fixed programme dates and hold dye-lots so later phases match earlier ones.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'carpet-tiles'],
    relatedIndustries: ['hotel-carpets', 'office-carpets'],
    relatedCompany: ['factory', 'custom-manufacturing', 'export-process'],
  },
  {
    slug: 'why-bhadohi', kind: 'company', label: 'Why Bhadohi', heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'The Carpet Capital of India',
    tagline: 'Why Bhadohi is the carpet capital of India — and why buying at source matters.',
    seoTitle: 'Why We Manufacture in Bhadohi | Sourcing Advantage — Tapis Global International',
    seoDescription: 'Why Bhadohi is the carpet capital of India — the GI-recognised heart of handwoven carpet-making, with deep heritage, skilled artisans and source-direct quality. Tapis Global manufactures here. Learn more.',
    seoKeywords: ['why Bhadohi carpet capital', 'Bhadohi carpet city', 'Bhadohi carpet industry', 'carpet capital of India', 'Bhadohi handwoven carpets'],
    h1: 'Why We Manufacture in Bhadohi — The Sourcing Advantage',
    intro: 'Bhadohi, in Uttar Pradesh, is the carpet capital of India — the largest handwoven carpet-manufacturing cluster in South Asia and a GI-recognised centre of weaving heritage. Tapis Global manufactures here, at source, continuing a three-generation family legacy.',
    overview: 'Buying carpets from Bhadohi means buying from the source — generations of concentrated skill, authentic construction and source-direct pricing. Understanding Bhadohi is understanding why our carpets carry the craft and value they do.',
    sections: [
      { h2: 'A Centre of Weaving Heritage', body: 'Bhadohi and its surrounding belt have woven carpets for centuries. This concentration of generational skill — passed through weaving families — is unmatched anywhere in India, and it is the foundation of authentic handmade quality.' },
      { h2: 'GI Recognition & Scale', body: 'Bhadohi handmade carpets hold Geographical Indication recognition, and the region is India\'s largest carpet-manufacturing and export cluster, supported by deep supply chains for yarn, dyeing and finishing.' },
      { h2: 'Why Buying at Source Matters', body: 'Manufacturing in Bhadohi removes intermediaries: better pricing, direct quality control, authentic construction and access to the skilled artisan community that defines the region\'s craft.' },
    ],
    applications: [
      { title: 'Generational Skill', desc: 'Centuries of concentrated weaving heritage.' },
      { title: 'GI Recognition', desc: 'Geographically protected handmade carpets.' },
      { title: 'Deep Supply Chains', desc: 'Yarn, dyeing and finishing at source.' },
      { title: 'Source-Direct Value', desc: 'Better pricing and quality, no middlemen.' },
    ],
    whyPoints: [
      { title: 'Carpet Capital', desc: 'India\'s largest handwoven carpet cluster.' },
      { title: 'Heritage', desc: 'Generational, GI-recognised craft.' },
      { title: 'At Source', desc: 'We manufacture in Bhadohi itself.' },
    ],
    faqs: [
      { q: 'Why is Bhadohi called the carpet capital of India?', a: 'Bhadohi is India\'s largest handwoven carpet-manufacturing and export cluster, with centuries of concentrated weaving heritage and Geographical Indication recognition for its handmade carpets.' },
      { q: 'Why buy carpets from Bhadohi?', a: 'Buying from Bhadohi means buying at source — generations of skill, authentic handmade construction and source-direct pricing without intermediaries.' },
      { q: 'Do you manufacture in Bhadohi?', a: 'Yes. Tapis Global is a third-generation, family-owned manufacturer based in Bhadohi, continuing a carpet-making legacy since 1965.' },
      { q: 'What is GI recognition for Bhadohi carpets?', a: 'Geographical Indication recognition protects "Bhadohi handmade carpet" as originating from the region, signifying authentic local craftsmanship.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'dhurrie-rugs'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets'],
    relatedCompany: ['factory', 'manufacturing-process', 'sustainability'],
  },
]
