import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// Export-market landing pages — /countries/[country]
// Each page is written around the specific market: its design preferences, key
// buyer sectors, compliance notes and logistics — not templated keyword swaps.
// India remains the primary business; these target genuine export demand.
// ─────────────────────────────────────────────────────────────────────────────

const PRODUCTS_CORE = ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets']

export const COUNTRIES: SeoLanding[] = [
  {
    slug: 'usa',
    kind: 'country',
    label: 'United States',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Export to the USA',
    tagline: 'Carpet and rug export from India to the USA — for designers, hospitality groups, importers and retailers.',
    seoTitle: 'Carpet & Rug Exporter to USA | Indian Manufacturer — Tapis Global International',
    seoDescription: 'Indian carpet and rug exporter to the USA. Hand knotted, hand tufted and custom carpets from Bhadohi for US designers, hospitality, importers and retailers — full documentation, container programmes. Request a catalogue.',
    seoKeywords: ['carpet exporter to USA', 'Indian rug exporter USA', 'wholesale rugs USA importer', 'hand knotted carpets USA', 'custom carpets USA supplier'],
    h1: 'Carpet & Rug Exporter from India to the USA',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi, India to the United States — supplying interior designers, hospitality groups, importers and retailers. We combine authentic Indian craftsmanship with the documentation, consistency and logistics US buyers expect.',
    overview: 'The US market spans high-design residential, large hospitality programmes and a mature rug retail and import sector. As a manufacturer-exporter we serve all three — bespoke pieces for designers, contract carpets for hotels, and bulk private-label programmes for importers and retailers — with container shipping and the paperwork US customs and buyers require.',
    sections: [
      { h2: 'Built for US Design Tastes', body: 'American interiors range from transitional and contemporary to bold maximalism. Our studio develops to US designer briefs — custom colours, sizes (including US standard rug dimensions) and styles — with lab-dips approved before production.' },
      { h2: 'Importer & Retail Programmes', body: 'For US importers and retail chains we offer private-label manufacturing, consistent bulk supply and container-load programmes, with the documentation needed for smooth customs clearance.' },
    ],
    applications: [
      { title: 'Interior Designers', desc: 'Bespoke rugs developed to US residential and commercial design schemes.' },
      { title: 'Hospitality Groups', desc: 'Contract carpet programmes for US hotels and resorts.' },
      { title: 'Importers & Distributors', desc: 'Bulk, container-load programmes with full export documentation.' },
      { title: 'Retailers & E-commerce', desc: 'Private-label rug collections for US retail and online sellers.' },
    ],
    whyPoints: [
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
      { title: 'US-Ready Documentation', desc: 'Export paperwork for smooth US customs clearance.' },
      { title: 'Container Programmes', desc: 'Bulk and repeat supply with coordinated freight.' },
    ],
    faqs: [
      { q: 'Do you export carpets to the United States?', a: 'Yes. We export handmade carpets and rugs from Bhadohi to the USA for designers, hospitality groups, importers and retailers, with full export documentation and container shipping.' },
      { q: 'Can you produce US standard rug sizes?', a: 'Yes. We manufacture to US standard and fully custom dimensions, with lab-dips approved before bulk production.' },
      { q: 'Do you offer private-label for US importers and retailers?', a: 'Yes. We provide OEM and private-label manufacturing with custom branding and packaging for US retail and e-commerce brands.' },
      { q: 'What payment terms do you accept for US buyers?', a: 'We accept TT, LC, DA and DP and deal in USD. Terms are negotiable for established buyers.' },
      { q: 'How is shipping to the USA handled?', a: 'We pack for safe international transit and coordinate sea freight to your preferred US port and terms.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'retail-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'wholesale-carpet-supplier'],
    relatedCountries: ['uk', 'germany', 'australia'],
  },
  {
    slug: 'uk',
    kind: 'country',
    label: 'United Kingdom',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Export to the UK',
    tagline: 'Carpet and rug export from India to the United Kingdom — for designers, hospitality and trade buyers.',
    seoTitle: 'Carpet & Rug Exporter to UK | Indian Manufacturer — Tapis Global International',
    seoDescription: 'Indian carpet and rug exporter to the UK. Hand knotted, hand tufted, wool and custom carpets from Bhadohi for British designers, hotels and trade buyers — documentation and freight handled. Request a catalogue.',
    seoKeywords: ['carpet exporter to UK', 'Indian rug supplier UK', 'wholesale rugs UK trade', 'hand knotted carpets UK', 'custom carpets UK supplier'],
    h1: 'Carpet & Rug Exporter from India to the UK',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to the United Kingdom — supplying interior designers, hospitality projects and trade buyers with bespoke and contract-grade flooring backed by reliable documentation and logistics.',
    overview: 'British interiors prize heritage craft, natural fibres and refined, often understated design. As a manufacturer-exporter we develop to UK trade and designer briefs — wool and wool-silk pieces, natural-fibre rugs and contract carpets — with the consistency and paperwork UK importers and specifiers require.',
    sections: [
      { h2: 'Heritage Craft for UK Interiors', body: 'The UK market values authentic handmade construction and natural materials. Our hand knotted and wool pieces, and our jute and sisal rugs, suit British residential and heritage-property schemes, all customisable to designer specification.' },
      { h2: 'Trade & Contract Supply', body: 'For UK trade buyers and hospitality projects we provide reliable bulk and contract supply, fire-rated carpets where required, and documentation for smooth import.' },
    ],
    applications: [
      { title: 'Interior Designers', desc: 'Bespoke wool and silk rugs for UK residential schemes.' },
      { title: 'Hospitality & Heritage', desc: 'Contract carpets for hotels and heritage properties.' },
      { title: 'Trade & Wholesale', desc: 'Reliable bulk supply for UK rug trade buyers.' },
      { title: 'Natural-Fibre Retail', desc: 'Jute and sisal collections for sustainable UK retail.' },
    ],
    whyPoints: [
      { title: 'Authentic Handcraft', desc: 'Genuine handmade construction valued by UK buyers.' },
      { title: 'Reliable Supply', desc: 'Consistent bulk and contract programmes with documentation.' },
      { title: 'Natural Materials', desc: 'Wool, silk, jute and sisal sustainably sourced.' },
    ],
    faqs: [
      { q: 'Do you export carpets to the UK?', a: 'Yes. We export handmade carpets and rugs from Bhadohi to the UK for designers, hospitality projects and trade buyers, with full documentation and freight coordination.' },
      { q: 'Do you supply UK trade and wholesale buyers?', a: 'Yes. We provide reliable bulk and contract supply for UK rug trade buyers, including private-label.' },
      { q: 'Can you supply fire-rated carpets for UK hotels?', a: 'Yes. We manufacture fire-rated contract carpets and provide supporting documentation for UK hospitality projects.' },
      { q: 'What materials suit the UK market?', a: 'Wool, wool-silk, and natural fibres (jute, sisal) align with UK tastes for heritage craft and sustainability — all customisable.' },
      { q: 'How is shipping to the UK arranged?', a: 'We pack for international transit and coordinate sea freight to your preferred UK port and terms.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'jute-sisal-rugs', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'office-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'luxury-carpets'],
    relatedCountries: ['usa', 'germany', 'france'],
  },
  {
    slug: 'germany',
    kind: 'country',
    label: 'Germany',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Export to Germany',
    tagline: 'Carpet and rug export from India to Germany — quality-driven supply for designers, contract and retail.',
    seoTitle: 'Carpet & Rug Exporter to Germany | Indian Manufacturer — Tapis Global International',
    seoDescription: 'Indian carpet and rug exporter to Germany. Quality wool, hand knotted and custom carpets from Bhadohi for German designers, contract projects and retail — OEKO-TEX, documentation, reliable freight. Request a catalogue.',
    seoKeywords: ['carpet exporter to Germany', 'Indian rug supplier Germany', 'OEKO-TEX carpets Germany', 'wholesale rugs Germany', 'wool carpets Germany supplier'],
    h1: 'Carpet & Rug Exporter from India to Germany',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to Germany — serving designers, contract projects and retail buyers in one of Europe\'s most quality- and sustainability-conscious markets.',
    overview: 'German buyers demand verifiable quality, material safety and reliable, precise supply. As a manufacturer-exporter we meet these expectations with OEKO-TEX-compliant, AZO-free production, consistent quality control and dependable documentation and logistics — for clean contemporary designs and natural fibres that suit German interiors.',
    sections: [
      { h2: 'Quality & Material Safety', body: 'We manufacture with OEKO-TEX Standard 100 compliance and AZO-free dyes, providing the material-safety assurance German buyers and regulations prioritise.' },
      { h2: 'Precision & Reliability', body: 'German trade and contract buyers value consistency and on-time supply. Our in-house QC, held dye-lots and disciplined logistics deliver the precision this market expects.' },
    ],
    applications: [
      { title: 'Designers & Architects', desc: 'Clean contemporary and natural-fibre rugs for German schemes.' },
      { title: 'Contract Projects', desc: 'Quality-assured contract carpets for offices and hospitality.' },
      { title: 'Retail & Trade', desc: 'OEKO-TEX-compliant collections for German rug retail.' },
      { title: 'Sustainable Interiors', desc: 'Natural jute and sisal for eco-conscious projects.' },
    ],
    whyPoints: [
      { title: 'OEKO-TEX Compliant', desc: 'Material-safety assurance for the German market.' },
      { title: 'Precision Supply', desc: 'Consistent QC and on-time, documented delivery.' },
      { title: 'Sustainable Options', desc: 'AZO-free dyes and natural-fibre collections.' },
    ],
    faqs: [
      { q: 'Are your carpets OEKO-TEX certified for Germany?', a: 'We manufacture with OEKO-TEX Standard 100 compliance and AZO-free dyes, providing the material-safety assurance German buyers prioritise.' },
      { q: 'Do you export carpets to Germany?', a: 'Yes. We export from Bhadohi to Germany for designers, contract projects and retail, with full documentation and reliable freight.' },
      { q: 'Can you guarantee consistent quality for German trade buyers?', a: 'Yes. In-house multi-stage QC and held dye-lots ensure batch-consistent quality across orders.' },
      { q: 'Do you offer sustainable natural-fibre rugs?', a: 'Yes — jute, sisal and seagrass rugs with AZO-free dyes suit Germany\'s sustainability focus.' },
      { q: 'What payment and shipping terms apply?', a: 'We accept TT, LC, DA, DP in EUR and coordinate sea freight to your preferred German port and terms.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'jute-sisal-rugs', 'flat-weaves'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'retail-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'commercial-carpet-manufacturer'],
    relatedCountries: ['france', 'netherlands', 'belgium'],
  },
  {
    slug: 'france',
    kind: 'country',
    label: 'France',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'Export to France',
    tagline: 'Carpet and rug export from India to France — refined craft for designers, luxury and hospitality.',
    seoTitle: 'Carpet & Rug Exporter to France | Indian Manufacturer — Tapis Global International',
    seoDescription: 'Indian carpet and rug exporter to France. Refined hand knotted, silk and custom carpets from Bhadohi for French designers, luxury interiors and hospitality — bespoke development, documentation, freight. Request a catalogue.',
    seoKeywords: ['carpet exporter to France', 'Indian rug supplier France', 'luxury rugs France', 'silk carpets France', 'custom carpets France supplier'],
    h1: 'Carpet & Rug Exporter from India to France',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to France — serving interior designers, luxury residences and hospitality projects in a market defined by refined taste and craftsmanship.',
    overview: 'France pairs a deep appreciation of artisanal craft with leadership in luxury and design. As a manufacturer-exporter we develop refined hand knotted, silk and bespoke pieces to French designer briefs, supplying luxury interiors and prestige hospitality with the elegance and quality this market expects.',
    sections: [
      { h2: 'Refined, Bespoke Craft', body: 'French luxury and design favour subtlety, fine materials and bespoke development. Our silk and wool-silk hand knotted pieces, developed to exact colour and design, suit French residential and luxury projects.' },
      { h2: 'Hospitality & Heritage', body: 'For French hotels and heritage interiors we provide bespoke and contract carpets — classical reproductions and contemporary commissions — with documentation and reliable freight.' },
    ],
    applications: [
      { title: 'Luxury Interiors', desc: 'Refined silk and wool-silk rugs for French luxury homes.' },
      { title: 'Interior Designers', desc: 'Bespoke development to French designer briefs.' },
      { title: 'Prestige Hospitality', desc: 'Custom and classical carpets for French hotels.' },
      { title: 'Boutique Retail', desc: 'Designer rug collections for French retail.' },
    ],
    whyPoints: [
      { title: 'Artisanal Quality', desc: 'Fine hand knotting and material integrity.' },
      { title: 'Bespoke Development', desc: 'Refined custom design to French briefs.' },
      { title: 'Reliable Export', desc: 'Documentation and freight handled end to end.' },
    ],
    faqs: [
      { q: 'Do you export luxury carpets to France?', a: 'Yes. We export refined hand knotted, silk and bespoke carpets from Bhadohi to France for luxury interiors, designers and hospitality, with full documentation.' },
      { q: 'Can you develop bespoke rugs for French designers?', a: 'Yes. We develop to exact colour and design with lab-dips and samples approved before production.' },
      { q: 'Do you produce fine silk rugs?', a: 'Yes — pure silk and wool-silk hand knotted pieces at high knot densities for the French luxury market.' },
      { q: 'What payment terms do you accept?', a: 'We accept TT, LC, DA, DP in EUR, negotiable for established buyers.' },
      { q: 'How is shipping to France arranged?', a: 'We pack for international transit and coordinate sea freight to your preferred French port and terms.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'leather-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['villa-carpets', 'hotel-carpets', 'retail-carpets'],
    relatedSolutions: ['luxury-carpets', 'carpet-exporter-india'],
    relatedCountries: ['italy', 'uk', 'germany'],
  },
  {
    slug: 'italy',
    kind: 'country',
    label: 'Italy',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Export to Italy',
    tagline: 'Carpet and rug export from India to Italy — design-led craft for luxury, hospitality and retail.',
    seoTitle: 'Carpet & Rug Exporter to Italy | Indian Manufacturer — Tapis Global International',
    seoDescription: 'Indian carpet and rug exporter to Italy. Design-led hand knotted, silk and custom carpets from Bhadohi for Italian designers, luxury interiors and hospitality — bespoke, documented, freight handled. Request a catalogue.',
    seoKeywords: ['carpet exporter to Italy', 'Indian rug supplier Italy', 'luxury rugs Italy', 'designer carpets Italy', 'custom carpets Italy supplier'],
    h1: 'Carpet & Rug Exporter from India to Italy',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to Italy — a market that lives and breathes design. We supply Italian designers, luxury interiors and hospitality with bespoke, design-led pieces crafted to exacting standards.',
    overview: 'Italy\'s design culture demands originality, quality and a strong point of view. As a manufacturer-exporter we partner with Italian designers and brands to develop distinctive hand knotted, silk and contemporary pieces, supplying luxury and hospitality projects with craft that matches Italian expectations.',
    sections: [
      { h2: 'Design-Led Collaboration', body: 'Italian designers expect a manufacturer who can realise a strong creative vision. We develop bold, original designs faithfully — across fine hand knotting and contemporary constructions.' },
      { h2: 'Luxury & Hospitality', body: 'For Italian luxury interiors and hospitality we provide bespoke and contract carpets with the material quality and finishing this discerning market requires.' },
    ],
    applications: [
      { title: 'Design Brands & Studios', desc: 'Original bespoke pieces realised to Italian design briefs.' },
      { title: 'Luxury Interiors', desc: 'Fine hand knotted and silk rugs for Italian luxury homes.' },
      { title: 'Hospitality', desc: 'Custom contract carpets for Italian hotels.' },
      { title: 'Design Retail', desc: 'Distinctive designer collections for Italian retail.' },
    ],
    whyPoints: [
      { title: 'Faithful to Design', desc: 'Bold, original designs reproduced accurately.' },
      { title: 'Material Quality', desc: 'Fine fibres and finishing for the Italian market.' },
      { title: 'Export Reliability', desc: 'Documentation and freight handled end to end.' },
    ],
    faqs: [
      { q: 'Do you export carpets to Italy?', a: 'Yes. We export bespoke and design-led carpets from Bhadohi to Italy for designers, luxury interiors and hospitality, with full documentation.' },
      { q: 'Can you realise original Italian design briefs?', a: 'Yes. We reproduce bold, original designs faithfully across fine hand knotting and contemporary constructions, with samples approved before production.' },
      { q: 'Do you supply Italian design brands?', a: 'Yes — we partner with design studios and brands on bespoke and collection development, including private-label.' },
      { q: 'What payment terms apply for Italy?', a: 'We accept TT, LC, DA, DP in EUR, negotiable for established buyers.' },
      { q: 'How is shipping to Italy handled?', a: 'We pack for international transit and coordinate sea freight to your preferred Italian port and terms.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'leather-carpets'],
    relatedIndustries: ['villa-carpets', 'hotel-carpets', 'retail-carpets'],
    relatedSolutions: ['designer-rugs', 'luxury-carpets'],
    relatedCountries: ['france', 'spain', 'uk'],
  },
  {
    slug: 'spain',
    kind: 'country',
    label: 'Spain',
    heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Export to Spain',
    tagline: 'Carpet and rug export from India to Spain — for designers, hospitality and contract projects.',
    seoTitle: 'Carpet & Rug Exporter to Spain | Indian Manufacturer — Tapis Global International',
    seoDescription: 'Indian carpet and rug exporter to Spain. Hand tufted, hand knotted and custom carpets from Bhadohi for Spanish designers, hospitality and contract projects — documentation and freight handled. Request a catalogue.',
    seoKeywords: ['carpet exporter to Spain', 'Indian rug supplier Spain', 'wholesale rugs Spain', 'hospitality carpets Spain', 'custom carpets Spain supplier'],
    h1: 'Carpet & Rug Exporter from India to Spain',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to Spain — supplying interior designers, hospitality groups and contract projects across a vibrant design and tourism-driven market.',
    overview: 'Spain\'s strong hospitality and tourism sector drives demand for durable, design-led contract carpets, alongside a lively residential design market. As a manufacturer-exporter we supply both — fire-rated hospitality programmes and bespoke designer pieces — with documentation and reliable freight.',
    sections: [
      { h2: 'Hospitality-Driven Demand', body: 'Spain\'s hotels and resorts need durable, fire-rated, design-led carpets at scale. We manufacture contract programmes with phased delivery and the documentation Spanish projects require.' },
      { h2: 'Design & Retail', body: 'For Spanish designers and retail we develop bespoke and contemporary rugs in custom colours, supplied reliably for residential and boutique projects.' },
    ],
    applications: [
      { title: 'Hotels & Resorts', desc: 'Fire-rated contract carpets for Spain\'s hospitality sector.' },
      { title: 'Interior Designers', desc: 'Bespoke designer rugs for Spanish residential schemes.' },
      { title: 'Contract Projects', desc: 'Durable, documented carpets for commercial projects.' },
      { title: 'Retail & Trade', desc: 'Contemporary collections for Spanish rug retail.' },
    ],
    whyPoints: [
      { title: 'Contract-Ready', desc: 'Fire-rated hospitality programmes with documentation.' },
      { title: 'Bespoke Design', desc: 'Custom colours and designs for Spanish projects.' },
      { title: 'Reliable Freight', desc: 'Coordinated shipping to Spanish ports.' },
    ],
    faqs: [
      { q: 'Do you export carpets to Spain?', a: 'Yes. We export from Bhadohi to Spain for designers, hospitality groups and contract projects, with full documentation and freight coordination.' },
      { q: 'Can you supply fire-rated carpets for Spanish hotels?', a: 'Yes. We manufacture fire-rated contract carpets and provide documentation for Spain\'s hospitality projects.' },
      { q: 'Do you handle phased delivery for large Spanish projects?', a: 'Yes. We hold dye-lots and coordinate phased dispatch aligned to your installation programme.' },
      { q: 'What payment terms apply for Spain?', a: 'We accept TT, LC, DA, DP in EUR, negotiable for established buyers.' },
      { q: 'How is shipping to Spain arranged?', a: 'We pack for international transit and coordinate sea freight to your preferred Spanish port and terms.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'hand-knotted-carpet'],
    relatedIndustries: ['hotel-carpets', 'restaurant-carpets', 'villa-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'carpet-exporter-india'],
    relatedCountries: ['italy', 'france', 'netherlands'],
  },
  {
    slug: 'netherlands',
    kind: 'country',
    label: 'Netherlands',
    heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Export to the Netherlands',
    tagline: 'Carpet and rug export from India to the Netherlands — sustainable, design-led supply for trade and contract.',
    seoTitle: 'Carpet & Rug Exporter to Netherlands | Indian Manufacturer — Tapis Global',
    seoDescription: 'Indian carpet and rug exporter to the Netherlands. Sustainable wool, natural-fibre and custom carpets from Bhadohi for Dutch designers, trade and contract — OEKO-TEX, documentation, freight. Request a catalogue.',
    seoKeywords: ['carpet exporter to Netherlands', 'Indian rug supplier Netherlands', 'sustainable rugs Netherlands', 'wholesale rugs Netherlands', 'natural fibre rugs Netherlands'],
    h1: 'Carpet & Rug Exporter from India to the Netherlands',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to the Netherlands — supplying Dutch designers, trade buyers and contract projects in a market known for clean design and strong sustainability values.',
    overview: 'Dutch buyers favour clean, functional design and sustainable materials, and the Netherlands is a key European trade and logistics hub. As a manufacturer-exporter we supply OEKO-TEX-compliant wool and natural-fibre rugs and contract carpets, with efficient freight through Dutch ports.',
    sections: [
      { h2: 'Sustainable & Clean Design', body: 'We supply AZO-free, OEKO-TEX-compliant wool and natural-fibre rugs in the clean, functional designs Dutch interiors favour, all customisable.' },
      { h2: 'European Trade Hub', body: 'The Netherlands is a major logistics gateway. We coordinate efficient freight to Dutch ports for onward European distribution, with full documentation.' },
    ],
    applications: [
      { title: 'Designers & Trade', desc: 'Clean, sustainable rugs for Dutch design and trade buyers.' },
      { title: 'Contract Projects', desc: 'Documented contract carpets for offices and hospitality.' },
      { title: 'Natural-Fibre Retail', desc: 'Jute and sisal collections for sustainable retail.' },
      { title: 'European Distribution', desc: 'Bulk supply via the Netherlands logistics hub.' },
    ],
    whyPoints: [
      { title: 'Sustainable Materials', desc: 'OEKO-TEX, AZO-free, natural-fibre options.' },
      { title: 'Efficient Freight', desc: 'Coordinated shipping via Dutch ports.' },
      { title: 'Reliable Quality', desc: 'Consistent QC and documentation.' },
    ],
    faqs: [
      { q: 'Do you export carpets to the Netherlands?', a: 'Yes. We export from Bhadohi to the Netherlands for designers, trade buyers and contract projects, with full documentation and efficient freight.' },
      { q: 'Are your carpets sustainable and OEKO-TEX compliant?', a: 'Yes. We manufacture with OEKO-TEX compliance and AZO-free dyes, and offer natural-fibre jute and sisal rugs.' },
      { q: 'Can you supply for onward European distribution?', a: 'Yes. We coordinate bulk supply to Dutch ports for onward European distribution.' },
      { q: 'What payment terms apply?', a: 'We accept TT, LC, DA, DP in EUR, negotiable for established buyers.' },
      { q: 'How is shipping arranged?', a: 'We pack for international transit and coordinate sea freight to your preferred Dutch port and terms.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'hand-tufted-carpet', 'flat-weaves'],
    relatedIndustries: ['office-carpets', 'retail-carpets', 'hotel-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'carpet-exporter-india'],
    relatedCountries: ['belgium', 'germany', 'uk'],
  },
  {
    slug: 'belgium',
    kind: 'country',
    label: 'Belgium',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Export to Belgium',
    tagline: 'Carpet and rug export from India to Belgium — craft and contract supply for a carpet-literate market.',
    seoTitle: 'Carpet & Rug Exporter to Belgium | Indian Manufacturer — Tapis Global International',
    seoDescription: 'Indian carpet and rug exporter to Belgium. Hand knotted, wool and custom carpets from Bhadohi for Belgian designers, trade and contract projects — documentation, quality, freight handled. Request a catalogue.',
    seoKeywords: ['carpet exporter to Belgium', 'Indian rug supplier Belgium', 'wholesale rugs Belgium', 'wool carpets Belgium', 'custom carpets Belgium supplier'],
    h1: 'Carpet & Rug Exporter from India to Belgium',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to Belgium — a country with deep carpet and textile heritage, supplying designers, trade buyers and contract projects with craft and quality they recognise.',
    overview: 'Belgium\'s strong textile tradition means buyers truly understand carpet construction and quality. As a manufacturer-exporter we meet that expertise with authentic handmade craftsmanship, material integrity and reliable documentation, supplying design, trade and contract projects.',
    sections: [
      { h2: 'Craft for a Carpet-Literate Market', body: 'Belgian buyers appreciate construction detail and quality. Our authentic hand knotted and wool pieces, made with material integrity, suit this knowledgeable market — all customisable.' },
      { h2: 'Trade & Contract Supply', body: 'For Belgian trade and contract buyers we provide consistent bulk supply, contract carpets and documentation, with efficient freight via Belgian and neighbouring ports.' },
    ],
    applications: [
      { title: 'Designers & Trade', desc: 'Authentic craft rugs for Belgium\'s knowledgeable buyers.' },
      { title: 'Contract Projects', desc: 'Documented contract carpets for commercial projects.' },
      { title: 'Luxury Interiors', desc: 'Fine hand knotted pieces for Belgian luxury homes.' },
      { title: 'Trade Distribution', desc: 'Bulk supply for Belgian and European trade.' },
    ],
    whyPoints: [
      { title: 'Authentic Craft', desc: 'Construction quality a textile market recognises.' },
      { title: 'Material Integrity', desc: 'Premium fibres, transparent quality.' },
      { title: 'Reliable Export', desc: 'Documentation and efficient freight.' },
    ],
    faqs: [
      { q: 'Do you export carpets to Belgium?', a: 'Yes. We export from Bhadohi to Belgium for designers, trade buyers and contract projects, with full documentation and efficient freight.' },
      { q: 'Why choose an Indian maker for a carpet-literate market like Belgium?', a: 'Belgian buyers value construction and quality, which our authentic handmade craft and material integrity deliver — with full transparency and customisation.' },
      { q: 'Do you supply Belgian trade and contract buyers?', a: 'Yes — consistent bulk and contract supply, including private-label, with documentation.' },
      { q: 'What payment terms apply?', a: 'We accept TT, LC, DA, DP in EUR, negotiable for established buyers.' },
      { q: 'How is shipping arranged?', a: 'We pack for international transit and coordinate sea freight to your preferred port and terms.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'flat-weaves'],
    relatedIndustries: ['villa-carpets', 'office-carpets', 'hotel-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'wholesale-carpet-supplier'],
    relatedCountries: ['netherlands', 'germany', 'france'],
  },
  {
    slug: 'australia',
    kind: 'country',
    label: 'Australia',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Export to Australia',
    tagline: 'Carpet and rug export from India to Australia — for designers, hospitality, builders and retail.',
    seoTitle: 'Carpet & Rug Exporter to Australia | Indian Manufacturer — Tapis Global International',
    seoDescription: 'Indian carpet and rug exporter to Australia. Hand tufted, hand knotted, wool and custom carpets from Bhadohi for Australian designers, hospitality, builders and retail — documentation and freight handled. Request a catalogue.',
    seoKeywords: ['carpet exporter to Australia', 'Indian rug supplier Australia', 'wholesale rugs Australia', 'wool rugs Australia', 'custom carpets Australia supplier'],
    h1: 'Carpet & Rug Exporter from India to Australia',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to Australia — supplying interior designers, hospitality groups, builders and retailers across a market with strong residential construction and design demand.',
    overview: 'Australia combines a robust residential and hospitality construction sector with a design market that favours natural materials and relaxed, contemporary style. As a manufacturer-exporter we supply wool and natural-fibre rugs, bespoke designer pieces and contract carpets, with documentation and reliable sea freight.',
    sections: [
      { h2: 'Natural & Contemporary Style', body: 'Australian interiors favour natural fibres, wool and relaxed contemporary design. Our wool, jute and contemporary rugs, customisable to brief, suit this aesthetic.' },
      { h2: 'Builders, Hospitality & Retail', body: 'For Australian builders, hospitality and retail we provide bespoke and contract supply, fire-rated carpets where required, and documentation for smooth import.' },
    ],
    applications: [
      { title: 'Interior Designers', desc: 'Bespoke wool and contemporary rugs for Australian schemes.' },
      { title: 'Builders & Developers', desc: 'Coordinated rug and carpet supply for residential projects.' },
      { title: 'Hospitality', desc: 'Fire-rated contract carpets for Australian hotels.' },
      { title: 'Retail & Trade', desc: 'Natural-fibre and contemporary collections for retail.' },
    ],
    whyPoints: [
      { title: 'Natural Materials', desc: 'Wool and natural fibres for Australian tastes.' },
      { title: 'Bespoke & Contract', desc: 'Designer pieces and contract programmes.' },
      { title: 'Reliable Freight', desc: 'Documented sea freight to Australian ports.' },
    ],
    faqs: [
      { q: 'Do you export carpets to Australia?', a: 'Yes. We export from Bhadohi to Australia for designers, builders, hospitality and retail, with full documentation and sea freight.' },
      { q: 'Do you supply natural-fibre and wool rugs for Australia?', a: 'Yes — wool, jute and sisal rugs suit Australian tastes for natural materials, all customisable.' },
      { q: 'Can you supply builders and developers?', a: 'Yes. We coordinate bulk rug and carpet supply for Australian residential projects.' },
      { q: 'What payment terms apply for Australia?', a: 'We accept TT, LC, DA, DP and deal in USD/AUD by arrangement, negotiable for established buyers.' },
      { q: 'How is shipping to Australia arranged?', a: 'We pack for international transit and coordinate sea freight to your preferred Australian port and terms.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'jute-sisal-rugs', 'shaggy-rugs'],
    relatedIndustries: ['villa-carpets', 'hotel-carpets', 'retail-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'custom-carpets'],
    relatedCountries: ['usa', 'uk', 'uae'],
  },
  {
    slug: 'uae',
    kind: 'country',
    label: 'United Arab Emirates',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Export to the UAE',
    tagline: 'Carpet and rug export from India to the UAE — luxury and large-scale hospitality, mosque and commercial supply.',
    seoTitle: 'Carpet & Rug Exporter to UAE | Hotel & Mosque Carpets Dubai — Tapis Global',
    seoDescription: 'Indian carpet and rug exporter to the UAE. Luxury, hotel, mosque and commercial carpets from Bhadohi for Dubai, Abu Dhabi and across the Emirates — custom, fire-rated, bulk, documented. Request a catalogue.',
    seoKeywords: ['carpet exporter to UAE', 'hotel carpet supplier Dubai', 'mosque carpet supplier UAE', 'luxury rugs UAE', 'custom carpets Abu Dhabi'],
    h1: 'Carpet & Rug Exporter from India to the UAE',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to the United Arab Emirates — supplying Dubai, Abu Dhabi and the wider Emirates with luxury, hospitality, mosque and commercial carpets at scale.',
    overview: 'The UAE is one of the most important markets for premium and large-scale carpet supply — driven by luxury residential, world-class hospitality, grand mosques and major commercial development. As a manufacturer-exporter we serve all of these with custom luxury pieces, fire-rated hospitality programmes, bespoke mosque (saff) carpets and bulk commercial supply.',
    sections: [
      { h2: 'Luxury & Hospitality at Scale', body: 'Gulf luxury and hospitality demand opulent design, premium materials and large-volume delivery. We manufacture custom luxury rugs and fire-rated hospitality carpets with the grandeur and scale UAE projects require.' },
      { h2: 'Mosque & Commercial Carpets', body: 'We manufacture custom mosque carpets with precise prayer-row (saff) layouts for the UAE\'s prayer halls, plus bulk commercial carpets for the region\'s extensive development — all with documentation and coordinated freight.' },
    ],
    applications: [
      { title: 'Luxury Residences', desc: 'Opulent custom rugs for UAE villas and palaces.' },
      { title: 'Hotels & Hospitality', desc: 'Fire-rated, grand-scale carpets for Gulf hospitality.' },
      { title: 'Mosques & Prayer Halls', desc: 'Custom saff prayer carpets for UAE mosques.' },
      { title: 'Commercial & Towers', desc: 'Bulk commercial carpets for UAE development.' },
    ],
    whyPoints: [
      { title: 'Scale & Grandeur', desc: 'Large-volume luxury and contract manufacturing.' },
      { title: 'Mosque Expertise', desc: 'Precise custom saff prayer-carpet production.' },
      { title: 'Fast, Documented Freight', desc: 'Efficient shipping to UAE ports with paperwork.' },
    ],
    faqs: [
      { q: 'Do you supply hotel carpets in Dubai and the UAE?', a: 'Yes. We manufacture and export fire-rated, large-scale hospitality carpets to Dubai, Abu Dhabi and across the UAE with documentation and coordinated freight.' },
      { q: 'Do you make custom mosque carpets for the UAE?', a: 'Yes. We design custom prayer-row (saff) carpets to exact hall dimensions and orientation for UAE mosques and prayer halls.' },
      { q: 'Can you handle large-volume Gulf projects?', a: 'Yes. Our Bhadohi campus manufactures large luxury and contract volumes with phased delivery for major UAE projects.' },
      { q: 'What payment terms apply for the UAE?', a: 'We accept TT, LC, DA, DP in USD/AED by arrangement, negotiable for established buyers.' },
      { q: 'How fast can you ship to the UAE?', a: 'Sea freight to UAE ports is efficient from India; we pack for transit and coordinate freight to your terms, with timelines confirmed at order.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['hotel-carpets', 'mosque-carpets', 'villa-carpets'],
    relatedSolutions: ['luxury-carpets', 'commercial-carpet-manufacturer'],
    relatedCountries: ['saudi-arabia', 'qatar', 'usa'],
  },
  {
    slug: 'saudi-arabia',
    kind: 'country',
    label: 'Saudi Arabia',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Export to Saudi Arabia',
    tagline: 'Carpet and rug export from India to Saudi Arabia — mosque, hospitality and giga-project supply.',
    seoTitle: 'Carpet & Rug Exporter to Saudi Arabia | Mosque & Hotel Carpets — Tapis Global',
    seoDescription: 'Indian carpet and rug exporter to Saudi Arabia. Custom mosque (saff), hotel and commercial carpets from Bhadohi for KSA mosques, hospitality and giga-projects — fire-rated, bulk, documented. Request a catalogue.',
    seoKeywords: ['carpet exporter to Saudi Arabia', 'mosque carpet supplier Saudi Arabia', 'hotel carpet supplier KSA', 'prayer carpet manufacturer Saudi', 'custom carpets Riyadh'],
    h1: 'Carpet & Rug Exporter from India to Saudi Arabia',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to Saudi Arabia — supplying mosques, hospitality and the Kingdom\'s major development projects with custom, large-scale carpet manufacturing.',
    overview: 'Saudi Arabia combines profound demand for mosque carpets with a fast-growing hospitality sector and transformative giga-projects. As a manufacturer-exporter we specialise in custom mosque (saff) carpets, fire-rated hospitality programmes and bulk commercial supply at the scale the Kingdom\'s projects require.',
    sections: [
      { h2: 'Mosque Carpet Specialists', body: 'We manufacture custom mosque carpets with precise prayer-row (saff) layouts, comfortable durable pile and dignified design — to the exact dimensions and orientation of Saudi prayer halls, at any scale.' },
      { h2: 'Hospitality & Giga-Projects', body: 'For KSA hospitality and major development we provide fire-rated contract carpets and bulk supply with phased delivery, documentation and coordinated freight.' },
    ],
    applications: [
      { title: 'Mosques & Prayer Halls', desc: 'Custom saff prayer carpets at any scale for KSA.' },
      { title: 'Hotels & Hospitality', desc: 'Fire-rated contract carpets for Saudi hospitality.' },
      { title: 'Giga & Development Projects', desc: 'Bulk commercial supply for major KSA projects.' },
      { title: 'Luxury Residences', desc: 'Opulent custom rugs for Saudi luxury homes.' },
    ],
    whyPoints: [
      { title: 'Mosque Specialists', desc: 'Precise custom saff carpets at any scale.' },
      { title: 'Project Scale', desc: 'Bulk capacity for hospitality and giga-projects.' },
      { title: 'Documented Freight', desc: 'Efficient shipping to KSA ports with paperwork.' },
    ],
    faqs: [
      { q: 'Do you manufacture mosque carpets for Saudi Arabia?', a: 'Yes. We are mosque carpet specialists — custom prayer-row (saff) layouts to the exact dimensions and orientation of Saudi prayer halls, comfortable and durable, at any scale.' },
      { q: 'Can you supply large KSA hospitality and giga-projects?', a: 'Yes. We manufacture fire-rated hospitality carpets and bulk commercial supply with phased delivery for major Saudi projects.' },
      { q: 'Do you export carpets to Riyadh, Jeddah and across KSA?', a: 'Yes. We export across Saudi Arabia with documentation and coordinated freight to KSA ports.' },
      { q: 'What payment terms apply for Saudi Arabia?', a: 'We accept TT, LC, DA, DP in USD/SAR by arrangement, negotiable for established buyers.' },
      { q: 'Can you match specific mosque colours and designs?', a: 'Yes. We develop custom colourways and motifs with lab-dip approval to suit each mosque\'s interior.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-knotted-carpet', 'hand-tufted-carpet'],
    relatedIndustries: ['mosque-carpets', 'hotel-carpets', 'villa-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'luxury-carpets'],
    relatedCountries: ['uae', 'qatar', 'usa'],
  },
  {
    slug: 'qatar',
    kind: 'country',
    label: 'Qatar',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'Export to Qatar',
    tagline: 'Carpet and rug export from India to Qatar — luxury, hospitality and mosque carpet supply.',
    seoTitle: 'Carpet & Rug Exporter to Qatar | Hotel & Mosque Carpets Doha — Tapis Global',
    seoDescription: 'Indian carpet and rug exporter to Qatar. Luxury, hotel, mosque and commercial carpets from Bhadohi for Doha and across Qatar — custom, fire-rated, bulk, documented. Request a catalogue or quote.',
    seoKeywords: ['carpet exporter to Qatar', 'hotel carpet supplier Qatar', 'mosque carpet supplier Qatar', 'luxury rugs Doha', 'custom carpets Qatar'],
    h1: 'Carpet & Rug Exporter from India to Qatar',
    intro: 'Tapis Global International exports handmade carpets and rugs from Bhadohi to Qatar — supplying Doha and the wider country with luxury, hospitality, mosque and commercial carpets crafted to the Gulf\'s exacting standards.',
    overview: 'Qatar\'s investment in luxury hospitality, prestige residential and grand mosques drives strong demand for premium, large-scale carpet supply. As a manufacturer-exporter we deliver custom luxury rugs, fire-rated hospitality carpets and bespoke mosque (saff) carpets, with documentation and efficient freight to Qatar.',
    sections: [
      { h2: 'Luxury & Prestige Hospitality', body: 'Qatar\'s luxury and hospitality projects demand opulent design and premium materials at scale. We manufacture custom luxury rugs and fire-rated hospitality carpets to match this ambition.' },
      { h2: 'Mosque & Commercial Supply', body: 'We manufacture custom mosque carpets with precise saff layouts for Qatar\'s prayer halls, plus bulk commercial carpets for development — with documentation and coordinated freight.' },
    ],
    applications: [
      { title: 'Luxury Residences', desc: 'Opulent custom rugs for Qatari villas and palaces.' },
      { title: 'Hotels & Hospitality', desc: 'Fire-rated, grand-scale carpets for Qatar hospitality.' },
      { title: 'Mosques & Prayer Halls', desc: 'Custom saff prayer carpets for Qatar mosques.' },
      { title: 'Commercial Development', desc: 'Bulk commercial carpets for Qatari projects.' },
    ],
    whyPoints: [
      { title: 'Premium at Scale', desc: 'Luxury and contract manufacturing in volume.' },
      { title: 'Mosque Expertise', desc: 'Precise custom saff prayer-carpet production.' },
      { title: 'Documented Freight', desc: 'Efficient shipping to Qatar with paperwork.' },
    ],
    faqs: [
      { q: 'Do you supply hotel and luxury carpets in Qatar?', a: 'Yes. We manufacture and export custom luxury and fire-rated hospitality carpets to Doha and across Qatar, with documentation and coordinated freight.' },
      { q: 'Do you make custom mosque carpets for Qatar?', a: 'Yes. We design custom prayer-row (saff) carpets to the exact dimensions and orientation of Qatari prayer halls.' },
      { q: 'Can you handle large Qatari projects?', a: 'Yes. Our Bhadohi campus manufactures large luxury and contract volumes with phased delivery for major Qatar projects.' },
      { q: 'What payment terms apply for Qatar?', a: 'We accept TT, LC, DA, DP in USD/QAR by arrangement, negotiable for established buyers.' },
      { q: 'How is shipping to Qatar arranged?', a: 'We pack for international transit and coordinate sea freight to Qatari ports on your terms.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['hotel-carpets', 'mosque-carpets', 'villa-carpets'],
    relatedSolutions: ['luxury-carpets', 'commercial-carpet-manufacturer'],
    relatedCountries: ['uae', 'saudi-arabia', 'usa'],
  },
]
