import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// Dhurrie & Tat Patti SEO silo — /dhurries/[slug]
// A dedicated topical silo targeting the high-intent, low-competition
// government-tender, NGO, school and institutional floor-covering market —
// Tapis Global's strongest untapped lead-gen cluster. Each page is unique,
// written around a specific buyer intent or material, with tender/government
// supply capability woven in. No doorway/thin/duplicate content.
// ─────────────────────────────────────────────────────────────────────────────

const REL_PRODUCTS = ['dhurrie-rugs', 'tat-patti', 'jute-sisal-rugs']
const REL_INDUSTRIES = ['school-carpets', 'government-carpets', 'hospital-carpets']

export const DHURRIES: SeoLanding[] = [
  {
    slug: 'tat-patti-manufacturer', kind: 'dhurrie', label: 'Tat Patti Manufacturer', heroImage: '/images/jute-rugs-manufacturing.webp',
    eyebrow: 'Tat Patti — Floor Matting',
    tagline: 'Tat Patti manufacturer in India — durable woven floor matting for schools, institutions and tender supply.',
    seoTitle: 'Tat Patti Manufacturer India | School & Institutional Floor Matting — Tapis Global',
    seoDescription: 'Tat Patti manufacturer and supplier in India. Durable woven cotton and jute tat patti floor matting from Bhadohi for schools, hostels, NGOs and government tenders — bulk, low-cost, fast supply. Request a quote.',
    seoKeywords: ['tat patti manufacturer India', 'tat patti supplier', 'school tat patti manufacturer', 'tat patti exporter', 'floor matting manufacturer India', 'cotton tat patti'],
    h1: 'Tat Patti Manufacturer in India',
    intro: 'Tapis Global International is a Tat Patti manufacturer and supplier based in Bhadohi, India, producing durable woven floor matting for schools, hostels, NGOs, institutions and government-tender supply. Tat Patti is the practical, economical floor-seating and floor-covering solution for high-volume institutional use, and we manufacture it at scale with consistent quality.',
    overview: 'Tat Patti (also spelt tatpatti or durry matting) is a flat, hard-wearing woven floor covering traditionally used for floor seating in schools, anganwadis, assembly halls, places of worship and relief programmes. As a direct manufacturer we weave Tat Patti in cotton and jute to institutional specifications, supplying the large, repeatable volumes that government and NGO buyers require — at genuine factory pricing with no trading middlemen.',
    sections: [
      { h2: 'Materials & Construction', body: 'We weave Tat Patti in cotton, jute and cotton-jute blends on traditional looms, in flat, tightly-woven constructions built for heavy floor seating and foot traffic. Standard rolls and cut sizes are available, with custom widths and lengths to suit classroom, hall and tender specifications.' },
      { h2: 'Built for Institutional & Tender Supply', body: 'Government schools, tribal welfare departments, anganwadis and NGOs buy Tat Patti in large, recurring volumes. Our 80,000 sq ft Bhadohi facility delivers bulk quantities with batch consistency, competitive tender pricing, the documentation tenders require and the capacity to meet supply deadlines.' },
      { h2: 'MOQ, Lead Time & Pricing', body: 'We accommodate institutional bulk orders with competitive per-unit pricing that scales with volume. Lead times are typically 2–4 weeks depending on quantity and specification; tender and emergency relief timelines can be discussed. Share your tender or requirement for an exact quotation.' },
    ],
    applications: [
      { title: 'Government & Public Schools', desc: 'Floor-seating matting for classrooms and assembly halls at scale.' },
      { title: 'Anganwadis & Ashram Schools', desc: 'Durable, economical matting for child and residential education.' },
      { title: 'NGOs & Relief Programmes', desc: 'Bulk Tat Patti for community, relief and rural development supply.' },
      { title: 'Places of Worship & Halls', desc: 'Hard-wearing floor matting for congregational seating.' },
    ],
    whyPoints: [
      { title: 'Direct Manufacturer', desc: 'Factory pricing for tender-competitive bulk supply.' },
      { title: 'Tender-Ready', desc: 'Documentation, samples and deadline capacity.' },
      { title: 'Bulk Consistency', desc: 'Batch-consistent quality across large orders.' },
    ],
    faqs: [
      { q: 'What is Tat Patti used for?', a: 'Tat Patti is a flat woven floor matting used for floor seating and floor covering in schools, anganwadis, hostels, halls, places of worship and relief camps. It is economical, durable and ideal for high-volume institutional use.' },
      { q: 'Do you supply Tat Patti for government tenders?', a: 'Yes. We manufacture Tat Patti to tender specifications in bulk, with competitive pricing, samples and documentation, and the capacity to meet government and NGO supply deadlines.' },
      { q: 'What materials is your Tat Patti made from?', a: 'We weave Tat Patti in cotton, jute and cotton-jute blends, in flat tightly-woven constructions built for heavy floor seating and foot traffic.' },
      { q: 'What is the minimum order and lead time?', a: 'We focus on institutional bulk orders with volume-based pricing; lead time is typically 2–4 weeks depending on quantity. Tender and relief timelines can be discussed.' },
      { q: 'Do you export Tat Patti?', a: 'Yes — alongside pan-India supply we export Tat Patti with documentation and coordinated freight.' },
    ],
    relatedProducts: ['tat-patti', 'dhurrie-rugs', 'jute-sisal-rugs'],
    relatedIndustries: REL_INDUSTRIES,
    relatedSolutions: ['wholesale-carpet-supplier', 'carpet-exporter-india'],
    relatedDhurries: ['school-tat-patti-supplier', 'government-tender-tat-patti-supplier', 'ngo-dhurrie-supplier'],
  },
  {
    slug: 'government-tender-dhurrie-supplier', kind: 'dhurrie', label: 'Government Tender Dhurrie Supplier', heroImage: '/images/manufacturing-rug-img.webp',
    eyebrow: 'Tender Supply',
    tagline: 'Government tender dhurrie supplier — spec-compliant bulk dhurries with documentation and deadline capacity.',
    seoTitle: 'Government Tender Dhurrie Supplier India | Bulk Tender Dhurries — Tapis Global',
    seoDescription: 'Government tender dhurrie supplier in India. Spec-compliant cotton, wool and jute dhurries from Bhadohi for government, tribal welfare and institutional tenders — bulk, competitive pricing, documentation. Request a quote.',
    seoKeywords: ['government tender dhurrie supplier', 'tender dhurrie manufacturer', 'bulk dhurrie tender supply', 'institutional dhurrie supplier India', 'government dhurrie supplier'],
    h1: 'Government Tender Dhurrie Supplier in India',
    intro: 'Tapis Global International is a government-tender dhurrie supplier and manufacturer in Bhadohi, India. We supply spec-compliant cotton, wool and jute dhurries in bulk for government departments, tribal welfare, education and institutional tenders — with the documentation, sampling and deadline capacity tender processes demand.',
    overview: 'Winning and fulfilling a government dhurrie tender depends on meeting the written specification exactly, offering competitive pricing, providing approved samples and documentation, and delivering the full quantity on time. As a direct manufacturer we control every stage and provide a transparent, accountable supply chain that procurement officers can rely on.',
    sections: [
      { h2: 'Specification-Exact Manufacturing', body: 'We manufacture dhurries to the exact written tender specification — material, weight, size, colour, weave and construction — and provide samples and documentation for evaluation and award.' },
      { h2: 'Tender Pricing & Documentation', body: 'Direct manufacturing gives us competitive tender pricing without middleman margins. We support submissions with specification sheets, samples, quotations and the documentation public procurement requires.' },
      { h2: 'Bulk Capacity & On-Time Delivery', body: 'Our 80,000 sq ft Bhadohi facility manufactures large tender volumes with batch consistency and delivers to fixed programme dates, with phased dispatch for multi-lot awards.' },
    ],
    applications: [
      { title: 'Government Departments', desc: 'Spec-compliant dhurries for departmental tender supply.' },
      { title: 'Tribal Welfare & Education', desc: 'Bulk dhurries for welfare and education tenders.' },
      { title: 'Institutional Tenders', desc: 'Documented supply for institutional procurement.' },
      { title: 'Multi-Lot Awards', desc: 'Phased delivery across large tender lots.' },
    ],
    whyPoints: [
      { title: 'Spec-Exact', desc: 'Manufactured precisely to tender specification.' },
      { title: 'Competitive Pricing', desc: 'Factory-direct, tender-competitive rates.' },
      { title: 'On-Time Bulk', desc: 'Volume capacity to fixed programme dates.' },
    ],
    faqs: [
      { q: 'Do you supply dhurries for government tenders?', a: 'Yes. We manufacture spec-compliant dhurries in bulk for government, tribal welfare, education and institutional tenders, with samples, quotations and documentation.' },
      { q: 'Can you meet exact tender specifications?', a: 'Yes — we manufacture to the precise written specification (material, weight, size, colour, weave) and provide samples for evaluation before award.' },
      { q: 'Is your pricing competitive for tenders?', a: 'Yes. Direct manufacturing removes middleman margins, giving competitive tender pricing that scales with volume.' },
      { q: 'Can you deliver large tender quantities on time?', a: 'Yes. Our Bhadohi facility manufactures large volumes with batch consistency and delivers to fixed programme dates, including phased dispatch for multi-lot awards.' },
      { q: 'What documentation do you provide for tenders?', a: 'Specification sheets, samples, quotations and the commercial documentation public procurement requires.' },
    ],
    relatedProducts: REL_PRODUCTS,
    relatedIndustries: REL_INDUSTRIES,
    relatedSolutions: ['wholesale-carpet-supplier', 'contract-carpet-supplier'],
    relatedDhurries: ['government-tender-tat-patti-supplier', 'school-dhurrie-supplier', 'ngo-dhurrie-supplier'],
  },
  {
    slug: 'government-tender-tat-patti-supplier', kind: 'dhurrie', label: 'Government Tender Tat Patti Supplier', heroImage: '/images/jute-rugs-manufacturing.webp',
    eyebrow: 'Tender Supply',
    tagline: 'Government tender Tat Patti supplier — bulk institutional floor matting to tender specification.',
    seoTitle: 'Government Tender Tat Patti Supplier India | Bulk Floor Matting — Tapis Global',
    seoDescription: 'Government tender Tat Patti supplier in India. Bulk cotton and jute tat patti floor matting from Bhadohi for government schools, tribal welfare and institutional tenders — spec-compliant, documented, on time. Request a quote.',
    seoKeywords: ['government tender tat patti supplier', 'tat patti tender supply', 'bulk tat patti supplier', 'government school tat patti', 'institutional tat patti supplier'],
    h1: 'Government Tender Tat Patti Supplier in India',
    intro: 'Tapis Global International is a government-tender Tat Patti supplier and manufacturer in Bhadohi, India. We supply bulk cotton and jute Tat Patti floor matting to government schools, tribal welfare departments and institutional tenders — manufactured to specification with documentation and on-time delivery.',
    overview: 'Tat Patti is a recurring high-volume requirement in government education and welfare programmes. As a direct manufacturer we offer the spec-compliance, competitive pricing, sampling, documentation and bulk capacity that public Tat Patti tenders demand — making us a dependable, accountable tender partner.',
    sections: [
      { h2: 'Tender-Specification Manufacturing', body: 'We weave Tat Patti to exact tender specifications — material, weight, size and construction — and provide samples and documentation for evaluation and award.' },
      { h2: 'Bulk Government Supply', body: 'Government school and welfare tenders run to very large quantities. Our Bhadohi facility delivers bulk Tat Patti with batch consistency, competitive pricing and phased dispatch to programme dates.' },
      { h2: 'Documentation & Accountability', body: 'We support tender submissions with specification sheets, samples, quotations and commercial documentation, and provide a transparent manufacturer supply chain procurement officers can rely on.' },
    ],
    applications: [
      { title: 'Government Schools', desc: 'Bulk Tat Patti floor seating for public education tenders.' },
      { title: 'Tribal & Ashram Schools', desc: 'Institutional matting for welfare education programmes.' },
      { title: 'Anganwadis', desc: 'Economical floor matting for early-childhood centres.' },
      { title: 'Welfare Departments', desc: 'Large-volume tender supply for state welfare schemes.' },
    ],
    whyPoints: [
      { title: 'Spec-Compliant', desc: 'Woven exactly to tender specification.' },
      { title: 'Bulk Capacity', desc: 'Very large volumes to programme dates.' },
      { title: 'Accountable', desc: 'Transparent manufacturer supply chain.' },
    ],
    faqs: [
      { q: 'Do you supply Tat Patti for government tenders?', a: 'Yes. We manufacture bulk Tat Patti to tender specification for government schools, tribal welfare and institutional tenders, with samples and documentation.' },
      { q: 'Can you handle very large Tat Patti tender volumes?', a: 'Yes. Our Bhadohi facility delivers bulk quantities with batch consistency and phased dispatch to fixed programme dates.' },
      { q: 'Is your Tat Patti tender pricing competitive?', a: 'Yes — factory-direct manufacturing gives competitive pricing that scales with tender volume.' },
      { q: 'What documentation do you provide?', a: 'Specification sheets, samples, quotations and commercial documentation for public procurement.' },
      { q: 'Can you meet tender delivery deadlines?', a: 'Yes. We plan production and phased dispatch to meet fixed tender programme dates.' },
    ],
    relatedProducts: ['tat-patti', 'dhurrie-rugs', 'jute-sisal-rugs'],
    relatedIndustries: REL_INDUSTRIES,
    relatedSolutions: ['wholesale-carpet-supplier', 'contract-carpet-supplier'],
    relatedDhurries: ['tat-patti-manufacturer', 'government-tender-dhurrie-supplier', 'school-tat-patti-supplier'],
  },
  {
    slug: 'school-dhurrie-supplier', kind: 'dhurrie', label: 'School Dhurrie Supplier', heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Education Supply',
    tagline: 'School dhurrie supplier — durable, safe floor-seating dhurries for classrooms and assembly halls.',
    seoTitle: 'School Dhurrie Supplier & Manufacturer India | Classroom Dhurries — Tapis Global',
    seoDescription: 'School dhurrie supplier and manufacturer in India. Durable, safe cotton dhurries from Bhadohi for classrooms, assembly halls and residential schools — bulk, economical, tender-ready. Request a quote.',
    seoKeywords: ['school dhurrie supplier', 'school dhurrie manufacturer', 'classroom dhurrie supplier', 'government school dhurrie', 'residential school dhurrie'],
    h1: 'School Dhurrie Supplier & Manufacturer in India',
    intro: 'Tapis Global International is a school dhurrie supplier and manufacturer in Bhadohi, India, producing durable, safe, economical floor-seating dhurries for classrooms, assembly halls and residential schools. We supply government and private schools at scale, including tender supply.',
    overview: 'Schools rely on dhurries for floor seating in classrooms, libraries and assemblies — they must be comfortable for children, safe, easy to clean, hard-wearing and affordable in bulk. As a direct manufacturer we weave school dhurries to specification and supply them in the large volumes education buyers and tenders require.',
    sections: [
      { h2: 'Safe & Comfortable for Children', body: 'We weave dhurries in soft yet durable cotton with non-toxic, AZO-free dyes, comfortable for floor seating and safe for children, in cheerful or specified colourways.' },
      { h2: 'Durable & Easy to Maintain', body: 'School dhurries endure constant daily use and frequent cleaning. We build hard-wearing, reversible flatweaves that tolerate washing and last across school years.' },
      { h2: 'Bulk & Tender Supply', body: 'From a single school to a state education tender, we manufacture in bulk with batch consistency, competitive pricing, samples and documentation, delivered to programme dates.' },
    ],
    applications: [
      { title: 'Classrooms', desc: 'Comfortable, durable floor-seating dhurries for daily learning.' },
      { title: 'Assembly & Multipurpose Halls', desc: 'Large dhurries for school assemblies and events.' },
      { title: 'Residential & Ashram Schools', desc: 'Hard-wearing dhurries for boarding education.' },
      { title: 'Libraries & Activity Rooms', desc: 'Easy-care dhurries for reading and activity spaces.' },
    ],
    whyPoints: [
      { title: 'Child-Safe', desc: 'Soft cotton, AZO-free non-toxic dyes.' },
      { title: 'Durable & Washable', desc: 'Built for daily use and frequent cleaning.' },
      { title: 'Bulk & Tender', desc: 'Economical volume supply with documentation.' },
    ],
    faqs: [
      { q: 'Do you supply dhurries to schools in bulk?', a: 'Yes. We manufacture and supply school dhurries in bulk for government and private schools, including tender supply, with competitive pricing and documentation.' },
      { q: 'Are your school dhurries safe for children?', a: 'Yes. We weave soft, durable cotton with non-toxic, AZO-free dyes, comfortable and safe for floor seating.' },
      { q: 'Are the dhurries washable and durable?', a: 'Yes — hard-wearing reversible flatweaves that tolerate frequent washing and last across school years.' },
      { q: 'Can you supply government school tenders?', a: 'Yes. We manufacture to tender specification in bulk with samples, quotations and documentation.' },
      { q: 'What sizes do you offer for classrooms?', a: 'Custom sizes to suit classroom and hall dimensions, including large floor-seating dhurries.' },
    ],
    relatedProducts: REL_PRODUCTS,
    relatedIndustries: ['school-carpets', 'government-carpets', 'library-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'contract-carpet-supplier'],
    relatedDhurries: ['school-tat-patti-supplier', 'hostel-dhurrie-supplier', 'government-tender-dhurrie-supplier'],
  },
  {
    slug: 'school-tat-patti-supplier', kind: 'dhurrie', label: 'School Tat Patti Supplier', heroImage: '/images/jute-rugs-manufacturing.webp',
    eyebrow: 'Education Supply',
    tagline: 'School Tat Patti supplier — economical, durable floor matting for government and public schools.',
    seoTitle: 'School Tat Patti Supplier & Manufacturer India | Government School Matting — Tapis Global',
    seoDescription: 'School Tat Patti supplier and manufacturer in India. Economical, durable cotton and jute tat patti for government and public schools, anganwadis and assemblies — bulk, tender-ready. Request a quote.',
    seoKeywords: ['school tat patti supplier', 'school tat patti manufacturer', 'government school tat patti', 'tat patti for schools', 'anganwadi tat patti supplier'],
    h1: 'School Tat Patti Supplier & Manufacturer in India',
    intro: 'Tapis Global International is a school Tat Patti supplier and manufacturer in Bhadohi, India, producing economical, durable floor matting for government and public schools, anganwadis and assembly halls. We specialise in the bulk, tender-driven supply this segment requires.',
    overview: 'Tat Patti is the standard, cost-effective floor-seating solution across government and public schools. It must be tough enough for daily classroom use, economical at scale, and available in the very large volumes education departments procure. As a direct manufacturer we deliver exactly that, to tender specification.',
    sections: [
      { h2: 'Economical & Durable', body: 'We weave Tat Patti in cotton and jute, flat and tightly constructed for heavy daily floor seating, at the economical price point bulk school supply demands.' },
      { h2: 'Government & Public School Supply', body: 'Education departments procure Tat Patti in large recurring volumes. We manufacture to specification in bulk with batch consistency, competitive tender pricing and documentation.' },
      { h2: 'Sizes, MOQ & Delivery', body: 'Standard and custom sizes are available; we focus on institutional bulk orders with volume pricing and lead times of 2–4 weeks, scaled to tender deadlines.' },
    ],
    applications: [
      { title: 'Government Schools', desc: 'Bulk floor matting for public classroom seating.' },
      { title: 'Anganwadis', desc: 'Economical matting for early-childhood centres.' },
      { title: 'Assembly Halls', desc: 'Large Tat Patti for school assemblies and events.' },
      { title: 'Residential Schools', desc: 'Durable matting for boarding and ashram schools.' },
    ],
    whyPoints: [
      { title: 'Economical at Scale', desc: 'Factory pricing for bulk school supply.' },
      { title: 'Daily-Use Durable', desc: 'Tough construction for classroom seating.' },
      { title: 'Tender-Ready', desc: 'Spec-compliant with documentation.' },
    ],
    faqs: [
      { q: 'Do you supply Tat Patti to government schools?', a: 'Yes. We manufacture and supply Tat Patti in bulk for government and public schools, anganwadis and assemblies, to tender specification.' },
      { q: 'Is school Tat Patti economical in bulk?', a: 'Yes. Factory-direct manufacturing gives an economical price point that scales with school-supply volume.' },
      { q: 'Is it durable for daily classroom use?', a: 'Yes — flat, tightly woven cotton and jute constructions built for heavy daily floor seating.' },
      { q: 'Can you meet education tender deadlines?', a: 'Yes. We manufacture bulk volumes with phased dispatch to fixed tender programme dates.' },
      { q: 'What sizes are available?', a: 'Standard and custom sizes to suit classroom and hall dimensions.' },
    ],
    relatedProducts: ['tat-patti', 'dhurrie-rugs', 'jute-sisal-rugs'],
    relatedIndustries: ['school-carpets', 'government-carpets', 'library-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'contract-carpet-supplier'],
    relatedDhurries: ['tat-patti-manufacturer', 'school-dhurrie-supplier', 'government-tender-tat-patti-supplier'],
  },
  {
    slug: 'ngo-dhurrie-supplier', kind: 'dhurrie', label: 'NGO Dhurrie & Floor Mats Supplier', heroImage: '/images/manufacturing-rug-img.webp',
    eyebrow: 'NGO & Relief Supply',
    tagline: 'NGO dhurrie and floor-mats supplier — bulk, economical dhurries and matting for community and relief programmes.',
    seoTitle: 'NGO Dhurrie & Floor Mats Supplier India | Relief Programme Matting — Tapis Global',
    seoDescription: 'NGO dhurrie and floor mats supplier in India. Bulk, economical cotton and jute dhurries and tat patti from Bhadohi for NGOs, relief camps and rural development programmes — fast, documented supply. Request a quote.',
    seoKeywords: ['NGO dhurrie supplier', 'NGO floor mats supplier', 'relief camp dhurrie supplier', 'rural development dhurrie', 'NGO tat patti supplier'],
    h1: 'NGO Dhurrie & Floor Mats Supplier in India',
    intro: 'Tapis Global International is an NGO dhurrie and floor-mats supplier and manufacturer in Bhadohi, India, providing bulk, economical dhurries and Tat Patti matting for NGOs, relief camps and rural development programmes. We support the fast, large-volume, budget-conscious supply this sector depends on.',
    overview: 'NGOs and relief programmes need durable floor coverings and seating mats in large quantities, quickly, and within tight budgets — for camps, shelters, community centres and rural projects. As a direct manufacturer we deliver economical dhurries and Tat Patti at scale, with the responsiveness humanitarian and development timelines require.',
    sections: [
      { h2: 'Economical Bulk Supply', body: 'We manufacture cotton and jute dhurries and Tat Patti at genuine factory pricing, helping NGOs stretch budgets across large quantities for camps, shelters and community programmes.' },
      { h2: 'Fast Response for Relief', body: 'Relief and development programmes move quickly. Our Bhadohi capacity supports fast bulk production and dispatch, with timelines discussed against the urgency of each programme.' },
      { h2: 'Documentation & Partnership', body: 'We provide samples, quotations and documentation for NGO procurement and grant requirements, and work as a transparent, reliable manufacturing partner for recurring programmes.' },
    ],
    applications: [
      { title: 'Relief Camps & Shelters', desc: 'Bulk dhurries and mats for emergency and relief housing.' },
      { title: 'Community Centres', desc: 'Durable floor coverings for NGO community spaces.' },
      { title: 'Rural Development', desc: 'Economical matting for rural programme distribution.' },
      { title: 'Welfare Distribution', desc: 'Large-volume dhurries and Tat Patti for welfare schemes.' },
    ],
    whyPoints: [
      { title: 'Budget-Friendly', desc: 'Factory pricing to stretch NGO budgets.' },
      { title: 'Fast Bulk', desc: 'Responsive production for relief timelines.' },
      { title: 'Procurement-Ready', desc: 'Samples, quotes and documentation.' },
    ],
    faqs: [
      { q: 'Do you supply dhurries and floor mats to NGOs?', a: 'Yes. We manufacture bulk, economical dhurries and Tat Patti for NGOs, relief camps and rural development programmes, with samples and documentation.' },
      { q: 'Can you respond quickly for relief programmes?', a: 'Yes. Our Bhadohi capacity supports fast bulk production and dispatch; timelines are discussed against each programme\'s urgency.' },
      { q: 'Is the pricing suitable for NGO budgets?', a: 'Yes — factory-direct manufacturing gives economical pricing that stretches budgets across large quantities.' },
      { q: 'Do you provide documentation for NGO procurement?', a: 'Yes. We provide samples, quotations and documentation for NGO procurement and grant requirements.' },
      { q: 'Can you supply recurring NGO programmes?', a: 'Yes. We partner reliably for recurring bulk supply across ongoing programmes.' },
    ],
    relatedProducts: REL_PRODUCTS,
    relatedIndustries: ['government-carpets', 'school-carpets', 'hospital-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'carpet-exporter-india'],
    relatedDhurries: ['relief-camp-dhurrie-supplier', 'government-tender-dhurrie-supplier', 'tat-patti-manufacturer'],
  },
  {
    slug: 'relief-camp-dhurrie-supplier', kind: 'dhurrie', label: 'Relief Camp Dhurrie Supplier', heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Relief & Emergency Supply',
    tagline: 'Relief camp dhurrie supplier — rapid bulk dhurries and mats for emergency shelters and camps.',
    seoTitle: 'Relief Camp Dhurrie Supplier India | Emergency Shelter Mats — Tapis Global',
    seoDescription: 'Relief camp dhurrie supplier in India. Rapid bulk cotton and jute dhurries and tat patti from Bhadohi for relief camps, emergency shelters and disaster response — economical, fast, documented. Request a quote.',
    seoKeywords: ['relief camp dhurrie supplier', 'emergency shelter mats supplier', 'disaster relief dhurrie', 'camp floor mats supplier India', 'bulk relief dhurrie'],
    h1: 'Relief Camp Dhurrie Supplier in India',
    intro: 'Tapis Global International is a relief-camp dhurrie supplier and manufacturer in Bhadohi, India, providing rapid bulk dhurries and Tat Patti matting for relief camps, emergency shelters and disaster response. We prioritise speed, volume and economy when it matters most.',
    overview: 'Disaster relief and emergency shelter programmes need floor coverings and seating mats in very large quantities, at short notice, within constrained budgets. As a direct manufacturer with significant in-house capacity, we can mobilise bulk dhurrie and Tat Patti production quickly for government agencies, NGOs and relief partners.',
    sections: [
      { h2: 'Rapid Bulk Mobilisation', body: 'Our Bhadohi facility can prioritise and scale dhurrie and Tat Patti production for urgent relief needs, with dispatch coordinated to reach camps and shelters quickly.' },
      { h2: 'Economical & Durable for Field Use', body: 'We weave hard-wearing cotton and jute dhurries and matting that withstand field conditions, at economical pricing suited to large relief distributions.' },
      { h2: 'Agency & NGO Partnership', body: 'We support relief agencies, government bodies and NGOs with samples, quotations and documentation, and act as a dependable manufacturing partner for emergency and recurring programmes.' },
    ],
    applications: [
      { title: 'Emergency Shelters', desc: 'Rapid bulk dhurries and mats for shelter flooring.' },
      { title: 'Disaster Relief Camps', desc: 'Economical floor coverings for displaced communities.' },
      { title: 'Government Relief', desc: 'Large-volume supply for state disaster response.' },
      { title: 'NGO Field Programmes', desc: 'Durable matting for humanitarian distribution.' },
    ],
    whyPoints: [
      { title: 'Rapid Capacity', desc: 'In-house scale for urgent bulk needs.' },
      { title: 'Field-Durable', desc: 'Tough constructions for camp conditions.' },
      { title: 'Economical', desc: 'Factory pricing for large distributions.' },
    ],
    faqs: [
      { q: 'Can you supply dhurries quickly for relief camps?', a: 'Yes. Our Bhadohi facility can prioritise and scale bulk dhurrie and Tat Patti production for urgent relief needs, with coordinated rapid dispatch.' },
      { q: 'Are the dhurries durable for field conditions?', a: 'Yes — hard-wearing cotton and jute constructions built to withstand camp and shelter use.' },
      { q: 'Do you work with government and relief agencies?', a: 'Yes. We support government bodies, NGOs and relief partners with samples, quotations and documentation.' },
      { q: 'Is the pricing suitable for large relief distributions?', a: 'Yes — economical factory-direct pricing for very large quantities.' },
      { q: 'Can you handle recurring relief programmes?', a: 'Yes, as a dependable manufacturing partner for emergency and ongoing programmes.' },
    ],
    relatedProducts: REL_PRODUCTS,
    relatedIndustries: ['government-carpets', 'hospital-carpets', 'school-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'carpet-exporter-india'],
    relatedDhurries: ['ngo-dhurrie-supplier', 'hostel-dhurrie-supplier', 'government-tender-dhurrie-supplier'],
  },
  {
    slug: 'hostel-dhurrie-supplier', kind: 'dhurrie', label: 'Hostel Dhurrie Supplier', heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Institutional Supply',
    tagline: 'Hostel dhurrie supplier — durable, economical dhurries and mats for hostels and residential institutions.',
    seoTitle: 'Hostel Dhurrie & Floor Mats Supplier India | Residential Institution Matting — Tapis Global',
    seoDescription: 'Hostel dhurrie and floor mats supplier in India. Durable, economical cotton dhurries and tat patti from Bhadohi for hostels, residential and ashram schools and dormitories — bulk, tender-ready. Request a quote.',
    seoKeywords: ['hostel dhurrie supplier', 'hostel floor mats supplier', 'dormitory dhurrie manufacturer', 'residential school dhurrie', 'ashram school dhurrie supplier'],
    h1: 'Hostel Dhurrie & Floor Mats Supplier in India',
    intro: 'Tapis Global International is a hostel dhurrie and floor-mats supplier and manufacturer in Bhadohi, India, producing durable, economical dhurries and Tat Patti for hostels, dormitories and residential and ashram schools. We supply institutional volumes, including tender supply.',
    overview: 'Hostels and residential institutions need floor coverings that withstand heavy continuous use by many occupants, are easy to clean, and are affordable across hundreds of rooms and common areas. As a direct manufacturer we weave durable dhurries and matting to specification and supply them in the bulk volumes these institutions require.',
    sections: [
      { h2: 'Durable for Continuous Use', body: 'Hostel dhurries face constant daily use. We build hard-wearing, washable cotton flatweaves and jute matting that endure dormitory and common-area conditions.' },
      { h2: 'Economical Institutional Volumes', body: 'We supply hostels, ashram and residential schools and dormitories at economical factory pricing across large room counts and common spaces.' },
      { h2: 'Bulk & Tender Supply', body: 'For institutional and government residential programmes we manufacture to specification in bulk, with samples, documentation and delivery to programme dates.' },
    ],
    applications: [
      { title: 'Hostels & Dormitories', desc: 'Durable dhurries and mats for shared residential rooms.' },
      { title: 'Residential & Ashram Schools', desc: 'Economical matting for boarding education.' },
      { title: 'Common & Study Areas', desc: 'Hard-wearing floor coverings for shared spaces.' },
      { title: 'Welfare Hostels', desc: 'Bulk supply for government welfare residential schemes.' },
    ],
    whyPoints: [
      { title: 'Heavy-Use Durable', desc: 'Built for continuous occupant use.' },
      { title: 'Economical Bulk', desc: 'Factory pricing across many rooms.' },
      { title: 'Tender-Ready', desc: 'Spec-compliant institutional supply.' },
    ],
    faqs: [
      { q: 'Do you supply dhurries to hostels in bulk?', a: 'Yes. We manufacture durable, economical dhurries and Tat Patti for hostels, dormitories and residential schools at institutional volumes, including tender supply.' },
      { q: 'Are the dhurries durable for heavy hostel use?', a: 'Yes — hard-wearing, washable cotton flatweaves and jute matting built for continuous occupant use.' },
      { q: 'Can you supply residential and ashram schools?', a: 'Yes, at economical factory pricing across large room counts and common areas.' },
      { q: 'Do you handle government residential tenders?', a: 'Yes. We manufacture to specification in bulk with samples and documentation for welfare residential programmes.' },
      { q: 'What sizes are available for hostels?', a: 'Custom sizes for rooms, dormitories and common areas.' },
    ],
    relatedProducts: REL_PRODUCTS,
    relatedIndustries: ['school-carpets', 'senior-living-carpets', 'government-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'contract-carpet-supplier'],
    relatedDhurries: ['school-dhurrie-supplier', 'ngo-dhurrie-supplier', 'bulk-dhurrie-supplier'],
  },
  {
    slug: 'cotton-dhurrie-manufacturer', kind: 'dhurrie', label: 'Cotton Dhurrie Manufacturer', heroImage: '/images/rug3.webp',
    eyebrow: 'By Material — Cotton',
    tagline: 'Cotton dhurrie manufacturer — soft, washable, handwoven cotton dhurries in any design and colour.',
    seoTitle: 'Cotton Dhurrie Manufacturer, Supplier & Exporter India — Tapis Global',
    seoDescription: 'Cotton dhurrie manufacturer, supplier and exporter in India. Soft, washable, handwoven cotton dhurries from Bhadohi — stripes, geometrics, custom colours, bulk and export. Request a catalogue or quote.',
    seoKeywords: ['cotton dhurrie manufacturer', 'cotton dhurrie supplier', 'cotton dhurrie exporter', 'handwoven cotton dhurrie', 'cotton floor dhurrie manufacturer'],
    h1: 'Cotton Dhurrie Manufacturer, Supplier & Exporter in India',
    intro: 'Tapis Global International is a cotton dhurrie manufacturer, supplier and exporter in Bhadohi, India, handweaving soft, washable cotton dhurries in stripes, geometrics and custom designs. We serve retail, institutional, tender and export buyers at any volume.',
    overview: 'Cotton dhurries are prized for their softness, washability and casual versatility — ideal for homes, children\'s spaces, institutions and floor seating. As a direct manufacturer we weave cotton dhurries to your design, colour and size, with the consistency and capacity for bulk, tender and export supply.',
    sections: [
      { h2: 'Soft, Washable Cotton', body: 'We weave dhurries in durable, soft cotton that tolerates frequent washing — practical for homes, schools and institutions — with AZO-free dyes in any colourway.' },
      { h2: 'Designs & Customisation', body: 'Classic stripes, geometrics and contemporary patterns, in custom sizes and colours including the popular red-black stripe institutional design, all to your specification.' },
      { h2: 'Bulk, Tender & Export', body: 'We supply cotton dhurries from single design runs to large institutional, tender and export programmes, with samples, documentation and reliable freight.' },
    ],
    applications: [
      { title: 'Homes & Lifestyle Retail', desc: 'Soft, washable cotton dhurries for casual interiors.' },
      { title: 'Schools & Institutions', desc: 'Durable floor-seating dhurries for education.' },
      { title: 'Floor Seating', desc: 'Comfortable cotton dhurries for floor-seating use.' },
      { title: 'Export & Wholesale', desc: 'Bulk cotton dhurrie programmes for global buyers.' },
    ],
    whyPoints: [
      { title: 'Soft & Washable', desc: 'Practical cotton for frequent cleaning.' },
      { title: 'Any Design', desc: 'Stripes, geometrics and custom colourways.' },
      { title: 'Bulk to Export', desc: 'Single runs to tender and export volumes.' },
    ],
    faqs: [
      { q: 'Are you a direct cotton dhurrie manufacturer?', a: 'Yes. We handweave cotton dhurries in our Bhadohi facility and supply and export direct — better pricing, quality control and customisation.' },
      { q: 'Are cotton dhurries washable?', a: 'Yes. We weave durable, soft cotton that tolerates frequent washing, ideal for homes, schools and institutions.' },
      { q: 'Can you make custom designs and colours?', a: 'Yes — stripes, geometrics, contemporary patterns and custom colours including red-black institutional stripes, to your specification.' },
      { q: 'Do you supply cotton dhurries in bulk and for export?', a: 'Yes. We supply from single runs to large institutional, tender and export programmes with documentation.' },
      { q: 'What are your MOQ and lead times?', a: 'Flexible by order type; institutional bulk typically 2–4 weeks. Share your requirement for an exact quote.' },
    ],
    relatedProducts: ['dhurrie-rugs', 'flat-weaves', 'jute-sisal-rugs'],
    relatedIndustries: ['school-carpets', 'government-carpets', 'apartment-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'carpet-exporter-india'],
    relatedDhurries: ['wool-dhurrie-manufacturer', 'jute-dhurrie-manufacturer', 'handloom-dhurrie-manufacturer'],
  },
  {
    slug: 'wool-dhurrie-manufacturer', kind: 'dhurrie', label: 'Wool Dhurrie Manufacturer', heroImage: '/images/rug5.webp',
    eyebrow: 'By Material — Wool',
    tagline: 'Wool dhurrie manufacturer — premium handwoven wool dhurries with warmth, texture and durability.',
    seoTitle: 'Wool Dhurrie Manufacturer & Supplier India | Handwoven Wool Dhurries — Tapis Global',
    seoDescription: 'Wool dhurrie manufacturer and supplier in India. Premium handwoven wool dhurries from Bhadohi — tribal, geometric and contemporary designs, custom colours, bulk and export. Request a catalogue or quote.',
    seoKeywords: ['wool dhurrie manufacturer', 'wool dhurrie supplier', 'handwoven wool dhurrie', 'premium wool dhurrie', 'wool flatweave manufacturer India'],
    h1: 'Wool Dhurrie Manufacturer & Supplier in India',
    intro: 'Tapis Global International is a wool dhurrie manufacturer and supplier in Bhadohi, India, handweaving premium wool dhurries that combine warmth, rich texture and durability. We serve designers, retail, hospitality and export buyers with custom and collection wool dhurries.',
    overview: 'Wool dhurries sit at the premium end of the flatweave market — warmer, richer and more durable than cotton, with a depth of colour that suits design-led interiors. As a direct manufacturer we weave wool dhurries to bespoke designs and palettes, with the quality control and capacity for retail and export programmes.',
    sections: [
      { h2: 'Premium Wool Quality', body: 'We weave dhurries in quality wool with AZO-free vegetable and chrome dyes, delivering rich, durable, design-led flatweaves with excellent colour depth.' },
      { h2: 'Tribal to Contemporary Design', body: 'From classic tribal and geometric motifs to restrained contemporary patterns, we develop wool dhurrie designs to artwork and palettes, in custom sizes.' },
      { h2: 'Retail, Hospitality & Export', body: 'We supply wool dhurries for design retail, boutique hospitality and export, from bespoke pieces to consistent production runs with documentation.' },
    ],
    applications: [
      { title: 'Designer Interiors', desc: 'Premium wool dhurries for design-led residential schemes.' },
      { title: 'Boutique Hospitality', desc: 'Characterful wool flatweaves for design hotels.' },
      { title: 'Design Retail', desc: 'Wool dhurrie collections, including private-label.' },
      { title: 'Export Programmes', desc: 'Quality wool dhurries for international buyers.' },
    ],
    whyPoints: [
      { title: 'Premium Wool', desc: 'Rich, durable, design-led flatweaves.' },
      { title: 'Bespoke Design', desc: 'Tribal to contemporary, to your palette.' },
      { title: 'Retail to Export', desc: 'Bespoke pieces and production runs.' },
    ],
    faqs: [
      { q: 'Are you a direct wool dhurrie manufacturer?', a: 'Yes. We handweave wool dhurries in Bhadohi and supply and export direct, with full quality control and customisation.' },
      { q: 'What makes wool dhurries premium?', a: 'Wool offers warmth, rich texture, durability and superior colour depth versus cotton, suiting design-led interiors.' },
      { q: 'Can you weave custom wool dhurrie designs?', a: 'Yes — tribal, geometric and contemporary designs developed to your artwork and palette, in custom sizes.' },
      { q: 'Do you supply wool dhurries for retail and export?', a: 'Yes. We supply design retail, hospitality and export, from bespoke pieces to production runs with documentation.' },
      { q: 'What dyes do you use?', a: 'AZO-free vegetable and chrome dyes for rich, safe colour.' },
    ],
    relatedProducts: ['dhurrie-rugs', 'flat-weaves', 'kilim-rugs'],
    relatedIndustries: ['villa-carpets', 'hotel-carpets', 'retail-carpets'],
    relatedSolutions: ['designer-rugs', 'carpet-exporter-india'],
    relatedDhurries: ['cotton-dhurrie-manufacturer', 'jute-dhurrie-manufacturer', 'handloom-dhurrie-manufacturer'],
  },
  {
    slug: 'jute-dhurrie-manufacturer', kind: 'dhurrie', label: 'Jute Dhurrie Manufacturer', heroImage: '/images/jute-rugs-manufacturing.webp',
    eyebrow: 'By Material — Jute',
    tagline: 'Jute dhurrie manufacturer — natural, sustainable, hard-wearing jute dhurries and floor coverings.',
    seoTitle: 'Jute Dhurrie Manufacturer & Supplier India | Natural Jute Dhurries — Tapis Global',
    seoDescription: 'Jute dhurrie manufacturer and supplier in India. Natural, sustainable, hard-wearing jute dhurries and floor coverings from Bhadohi — eco-friendly, bulk, export. Request a catalogue or quote.',
    seoKeywords: ['jute dhurrie manufacturer', 'jute dhurrie supplier', 'natural jute dhurrie', 'sustainable dhurrie manufacturer', 'jute floor covering India'],
    h1: 'Jute Dhurrie Manufacturer & Supplier in India',
    intro: 'Tapis Global International is a jute dhurrie manufacturer and supplier in Bhadohi, India, weaving natural, sustainable, hard-wearing jute dhurries and floor coverings. We serve eco-conscious retail, institutional and export buyers at any volume.',
    overview: 'Jute dhurries combine natural texture and sustainability with real durability, making them popular for eco-led interiors, institutional use and value bulk supply. As a direct manufacturer we weave jute and jute-blend dhurries to specification, sustainably sourced and AZO-free, for retail, tender and export programmes.',
    sections: [
      { h2: 'Natural & Sustainable', body: 'Jute is a renewable, biodegradable fibre. We source certified jute and weave durable, natural dhurries with AZO-free finishes for genuinely sustainable supply.' },
      { h2: 'Hard-Wearing & Economical', body: 'Jute dhurries are tough and cost-effective in bulk, suiting institutional floor covering, value retail and high-traffic areas.' },
      { h2: 'Bulk, Tender & Export', body: 'We supply jute dhurries from retail collections to large institutional, tender and export programmes, with documentation and reliable freight.' },
    ],
    applications: [
      { title: 'Eco-Led Retail', desc: 'Sustainable natural jute dhurries for conscious retail.' },
      { title: 'Institutional Floor Covering', desc: 'Economical, durable jute dhurries for institutions.' },
      { title: 'Coastal & Organic Interiors', desc: 'Natural-texture dhurries for relaxed schemes.' },
      { title: 'Export & Wholesale', desc: 'Bulk jute dhurrie programmes for global buyers.' },
    ],
    whyPoints: [
      { title: 'Sustainable', desc: 'Renewable, biodegradable certified jute.' },
      { title: 'Tough & Economical', desc: 'Durable and cost-effective in bulk.' },
      { title: 'Bulk to Export', desc: 'Retail runs to tender and export volumes.' },
    ],
    faqs: [
      { q: 'Are you a direct jute dhurrie manufacturer?', a: 'Yes. We weave jute dhurries in Bhadohi and supply and export direct, with quality control and customisation.' },
      { q: 'Are jute dhurries sustainable?', a: 'Yes. Jute is renewable and biodegradable; we source certified fibre and use AZO-free finishes.' },
      { q: 'Are jute dhurries durable?', a: 'Yes — tough and well-suited to institutional floor covering and high-traffic areas, and economical in bulk.' },
      { q: 'Do you supply jute dhurries in bulk and for export?', a: 'Yes. From retail collections to large institutional, tender and export programmes with documentation.' },
      { q: 'Can jute dhurries be dyed?', a: 'Yes — natural and dyed jute colourways with AZO-free dyes.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'dhurrie-rugs', 'coco-coir'],
    relatedIndustries: ['school-carpets', 'government-carpets', 'retail-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'carpet-exporter-india'],
    relatedDhurries: ['cotton-dhurrie-manufacturer', 'wool-dhurrie-manufacturer', 'tat-patti-manufacturer'],
  },
  {
    slug: 'handloom-dhurrie-manufacturer', kind: 'dhurrie', label: 'Handloom Dhurrie Manufacturer', heroImage: '/images/vibrant-wool-dying.webp',
    eyebrow: 'Craft — Handloom',
    tagline: 'Handloom dhurrie manufacturer — authentic flat-weave dhurries handwoven on traditional looms.',
    seoTitle: 'Handloom Dhurrie Manufacturer India | Traditional Flat Weave Dhurries — Tapis Global',
    seoDescription: 'Handloom dhurrie manufacturer in India. Authentic traditional flat-weave dhurries handwoven on traditional looms in Bhadohi — cotton and wool, custom designs, bulk and export. Request a catalogue.',
    seoKeywords: ['handloom dhurrie manufacturer', 'flat weave dhurrie manufacturer', 'traditional Indian dhurrie manufacturer', 'handwoven dhurrie India', 'handloom flat weave dhurrie'],
    h1: 'Handloom Dhurrie Manufacturer in India',
    intro: 'Tapis Global International is a handloom dhurrie manufacturer in Bhadohi, India, handweaving authentic traditional flat-weave dhurries on traditional looms. We combine genuine handloom craft with the consistency and capacity buyers need for retail, institutional and export supply.',
    overview: 'Handloom dhurries carry the authenticity and character that machine-made products cannot replicate — genuine flat-weave construction, traditional Indian motifs and the irregular beauty of handcraft. As a direct manufacturer we preserve this craft while delivering the quality control, customisation and volume modern buyers require.',
    sections: [
      { h2: 'Authentic Handloom Craft', body: 'Our weavers handweave dhurries on traditional looms — genuine flat-weave construction in cotton and wool, with the authenticity and character of true handloom craft.' },
      { h2: 'Traditional & Custom Designs', body: 'We reproduce traditional Indian dhurrie motifs and develop custom designs to artwork and palette, in any size, preserving heritage technique.' },
      { h2: 'Craft at Scale', body: 'We balance handloom authenticity with the consistency and capacity for retail collections, institutional supply and export programmes.' },
    ],
    applications: [
      { title: 'Heritage & Craft Retail', desc: 'Authentic handloom dhurries for craft-led retail.' },
      { title: 'Designer Interiors', desc: 'Traditional and custom handloom dhurries for design schemes.' },
      { title: 'Export & Wholesale', desc: 'Genuine handloom dhurries for global craft buyers.' },
      { title: 'Institutional Supply', desc: 'Handwoven dhurries for institutional and tender use.' },
    ],
    whyPoints: [
      { title: 'Genuine Handloom', desc: 'Authentic traditional flat-weave craft.' },
      { title: 'Heritage Designs', desc: 'Traditional motifs and custom development.' },
      { title: 'Craft at Scale', desc: 'Authenticity with consistency and capacity.' },
    ],
    faqs: [
      { q: 'Are your dhurries genuinely handloom?', a: 'Yes. Our weavers handweave dhurries on traditional looms — genuine flat-weave construction with authentic handloom character.' },
      { q: 'Can you reproduce traditional Indian dhurrie designs?', a: 'Yes — traditional motifs and bespoke custom designs to artwork and palette, in any size.' },
      { q: 'Can handloom dhurries be supplied at scale?', a: 'Yes. We balance handloom authenticity with consistency and capacity for retail, institutional and export volumes.' },
      { q: 'What materials do you handweave?', a: 'Cotton and wool handloom dhurries, with AZO-free dyes.' },
      { q: 'Do you export handloom dhurries?', a: 'Yes, with documentation and coordinated freight.' },
    ],
    relatedProducts: ['dhurrie-rugs', 'flat-weaves', 'kilim-rugs'],
    relatedIndustries: ['retail-carpets', 'villa-carpets', 'museum-gallery-carpets'],
    relatedSolutions: ['designer-rugs', 'carpet-exporter-india'],
    relatedDhurries: ['cotton-dhurrie-manufacturer', 'wool-dhurrie-manufacturer', 'floor-seating-dhurrie-manufacturer'],
  },
  {
    slug: 'floor-seating-dhurrie-manufacturer', kind: 'dhurrie', label: 'Floor Seating Dhurrie Manufacturer', heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Floor Seating',
    tagline: 'Floor seating dhurrie manufacturer — comfortable, durable dhurries and mats for floor-seating use.',
    seoTitle: 'Floor Seating Dhurrie Manufacturer India | Floor Seating Mats — Tapis Global',
    seoDescription: 'Floor seating dhurrie and mats manufacturer in India. Comfortable, durable cotton and jute floor-seating dhurries and tat patti from Bhadohi for schools, events, worship and institutions. Request a quote.',
    seoKeywords: ['floor seating dhurrie manufacturer', 'floor seating mats supplier', 'educational floor seating mats', 'floor seating dhurrie India', 'institutional floor seating'],
    h1: 'Floor Seating Dhurrie & Mats Manufacturer in India',
    intro: 'Tapis Global International is a floor-seating dhurrie and mats manufacturer in Bhadohi, India, producing comfortable, durable dhurries and Tat Patti for floor-seating use in schools, events, places of worship and institutions. We supply at scale, including tender supply.',
    overview: 'Floor seating is central to Indian schools, assemblies, religious gatherings and events — and it demands floor coverings that are comfortable to sit on for long periods, durable under constant use, easy to clean and economical in volume. As a direct manufacturer we weave purpose-suited floor-seating dhurries and matting to specification.',
    sections: [
      { h2: 'Comfortable for Seated Use', body: 'We weave dhurries and matting with the right balance of cushioning and firmness for comfortable, prolonged floor seating in classrooms, halls and gatherings.' },
      { h2: 'Durable & Easy to Clean', body: 'Floor-seating coverings face constant use; we build hard-wearing, washable cotton flatweaves and jute matting that stay presentable and hygienic.' },
      { h2: 'Bulk, Institutional & Tender', body: 'From schools to event venues and worship spaces, we manufacture floor-seating dhurries and Tat Patti in bulk to specification, with samples and documentation for tenders.' },
    ],
    applications: [
      { title: 'Schools & Assemblies', desc: 'Comfortable floor-seating dhurries for classrooms and halls.' },
      { title: 'Places of Worship', desc: 'Durable seating mats for congregational gatherings.' },
      { title: 'Events & Functions', desc: 'Bulk floor seating for cultural and community events.' },
      { title: 'Institutions & Tenders', desc: 'Spec-compliant floor-seating supply at scale.' },
    ],
    whyPoints: [
      { title: 'Seating Comfort', desc: 'Balanced for prolonged floor seating.' },
      { title: 'Durable & Hygienic', desc: 'Washable, hard-wearing constructions.' },
      { title: 'Bulk & Tender', desc: 'Spec-compliant volume supply.' },
    ],
    faqs: [
      { q: 'Do you make dhurries for floor seating?', a: 'Yes. We weave comfortable, durable floor-seating dhurries and Tat Patti for schools, events, worship and institutions, at scale and for tenders.' },
      { q: 'Are floor-seating dhurries comfortable for long periods?', a: 'Yes — we balance cushioning and firmness for comfortable, prolonged seated use.' },
      { q: 'Are they durable and easy to clean?', a: 'Yes. We build hard-wearing, washable cotton flatweaves and jute matting that stay hygienic and presentable.' },
      { q: 'Can you supply floor seating in bulk for tenders?', a: 'Yes — spec-compliant bulk supply with samples and documentation.' },
      { q: 'What sizes are available?', a: 'Custom sizes for classrooms, halls, worship spaces and events.' },
    ],
    relatedProducts: ['dhurrie-rugs', 'tat-patti', 'jute-sisal-rugs'],
    relatedIndustries: ['school-carpets', 'temple-carpets', 'mosque-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'contract-carpet-supplier'],
    relatedDhurries: ['school-dhurrie-supplier', 'tat-patti-manufacturer', 'handloom-dhurrie-manufacturer'],
  },
  {
    slug: 'bulk-dhurrie-supplier', kind: 'dhurrie', label: 'Bulk & Wholesale Dhurrie Supplier', heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Bulk & Wholesale',
    tagline: 'Bulk and wholesale dhurrie supplier — factory-direct volume supply for distributors, retailers and institutions.',
    seoTitle: 'Bulk & Wholesale Dhurrie Supplier India | Factory-Direct Dhurries — Tapis Global',
    seoDescription: 'Bulk and wholesale dhurrie supplier in India. Factory-direct cotton, wool and jute dhurries from Bhadohi for distributors, retailers, institutions and tenders — competitive pricing, private label. Request a quote.',
    seoKeywords: ['bulk dhurrie supplier', 'wholesale dhurrie supplier', 'dhurrie wholesaler India', 'bulk dhurrie manufacturer', 'wholesale dhurrie manufacturer'],
    h1: 'Bulk & Wholesale Dhurrie Supplier in India',
    intro: 'Tapis Global International is a bulk and wholesale dhurrie supplier and manufacturer in Bhadohi, India, providing factory-direct cotton, wool and jute dhurries to distributors, retailers, institutions and tender buyers — with competitive pricing and private-label options.',
    overview: 'Bulk and wholesale buyers need dependable quality, the right price and reliable volume supply. Because we manufacture in-house rather than trade, we offer genuine factory pricing, batch-consistent quality across large and repeat orders, and private-label flexibility for retail and distribution.',
    sections: [
      { h2: 'Factory-Direct Pricing', body: 'No middlemen sit between you and production. Bulk and wholesale buyers get genuine manufacturer pricing, scaled to order volume, with margin intact.' },
      { h2: 'Consistent Volume Supply', body: 'We hold consistency and apply QC across large and repeat dhurrie orders, in cotton, wool and jute, so your supply and brand stay dependable.' },
      { h2: 'Private Label & Tender', body: 'We offer OEM and private-label dhurrie manufacturing with custom packaging, and supply institutional and government tenders in bulk with documentation.' },
    ],
    applications: [
      { title: 'Distributors', desc: 'Batch-consistent bulk dhurries for distribution.' },
      { title: 'Retailers & Chains', desc: 'Private-label dhurrie collections for retail.' },
      { title: 'Institutions & Tenders', desc: 'Bulk spec-compliant dhurrie supply.' },
      { title: 'Exporters & Importers', desc: 'Export-ready bulk programmes with documentation.' },
    ],
    whyPoints: [
      { title: 'True Factory Price', desc: 'Manufacturer-direct wholesale pricing.' },
      { title: 'Batch Consistency', desc: 'QC across large and repeat orders.' },
      { title: 'Private Label', desc: 'OEM with your branding and packaging.' },
    ],
    faqs: [
      { q: 'Do you sell dhurries wholesale direct from the factory?', a: 'Yes. We are the manufacturer — bulk and wholesale buyers get factory-direct pricing with no middlemen, scaled to volume.' },
      { q: 'Can you guarantee consistency on large dhurrie orders?', a: 'Yes. We hold consistency and apply QC across large and repeat orders in cotton, wool and jute.' },
      { q: 'Do you offer private-label dhurries?', a: 'Yes — OEM and private-label manufacturing with custom branding and packaging.' },
      { q: 'Do you supply institutional and government tenders in bulk?', a: 'Yes, spec-compliant with samples and documentation.' },
      { q: 'What are your wholesale MOQs?', a: 'MOQ varies by material and design; we structure bulk and repeat-supply programmes — share your requirement for specifics.' },
    ],
    relatedProducts: REL_PRODUCTS,
    relatedIndustries: ['retail-carpets', 'school-carpets', 'government-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'carpet-exporter-india'],
    relatedDhurries: ['cotton-dhurrie-manufacturer', 'dhurrie-exporter-india', 'government-tender-dhurrie-supplier'],
  },
  {
    slug: 'dhurrie-exporter-india', kind: 'dhurrie', label: 'Dhurrie Exporter India', heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Export',
    tagline: 'Dhurrie exporter from India — cotton, wool and jute dhurries shipped worldwide with documentation.',
    seoTitle: 'Dhurrie Exporter India | Cotton, Wool & Jute Dhurrie Export — Tapis Global',
    seoDescription: 'Dhurrie exporter from India. Cotton, wool and jute dhurries handwoven in Bhadohi and exported worldwide for importers, retailers and designers — documentation, packing and freight handled. Request a catalogue.',
    seoKeywords: ['dhurrie exporter India', 'Indian dhurrie exporter', 'export dhurrie manufacturer', 'wholesale dhurrie export', 'handwoven dhurrie exporter'],
    h1: 'Dhurrie Exporter from India',
    intro: 'Tapis Global International is a dhurrie exporter based in Bhadohi, India, handweaving cotton, wool and jute dhurries and exporting them worldwide to importers, retailers and designers — with the documentation, packing and freight coordination international trade requires.',
    overview: 'Exporting dhurries reliably means consistent quality buyers can trust from afar, faithful design reproduction, compliant documentation and dependable logistics. As a manufacturer-exporter we control the full chain in-house, giving overseas buyers authentic Indian handwoven dhurries delivered correctly and on time.',
    sections: [
      { h2: 'Authentic Indian Dhurries', body: 'We export genuine handwoven cotton, wool and jute dhurries — traditional and contemporary designs — with the authenticity international buyers seek from Indian craft.' },
      { h2: 'Quality & Documentation', body: 'Multi-stage QC and batch consistency give remote buyers confidence, and we provide the commercial and compliance documentation export shipments require.' },
      { h2: 'Packing & Freight', body: 'We pack dhurries for safe international transit and coordinate freight to your preferred port and terms, for bulk and repeat export programmes.' },
    ],
    applications: [
      { title: 'International Importers', desc: 'Bulk dhurrie export programmes with documentation.' },
      { title: 'Overseas Retailers', desc: 'Private-label dhurrie collections for global retail.' },
      { title: 'Designers Abroad', desc: 'Bespoke dhurries developed and exported to brief.' },
      { title: 'Distributors', desc: 'Consistent repeat dhurrie export supply.' },
    ],
    whyPoints: [
      { title: 'Authentic Craft', desc: 'Genuine Indian handwoven dhurries.' },
      { title: 'Remote-Trust Quality', desc: 'QC and consistency for overseas buyers.' },
      { title: 'Logistics Handled', desc: 'Packing and freight to your terms.' },
    ],
    faqs: [
      { q: 'Do you export dhurries from India?', a: 'Yes. We handweave and export cotton, wool and jute dhurries worldwide for importers, retailers and designers, with full documentation.' },
      { q: 'How do you ensure quality for overseas buyers?', a: 'Multi-stage in-house QC and batch consistency give remote buyers confidence in every shipment.' },
      { q: 'Do you handle export packing and freight?', a: 'Yes. We pack for safe international transit and coordinate freight to your preferred port and terms.' },
      { q: 'Can you produce private-label dhurries for export?', a: 'Yes — OEM and private-label with custom packaging for overseas retail.' },
      { q: 'What payment terms do you accept?', a: 'TT, LC, DA, DP in USD/EUR/GBP, negotiable for established buyers.' },
    ],
    relatedProducts: REL_PRODUCTS,
    relatedIndustries: ['retail-carpets', 'villa-carpets', 'hotel-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'wholesale-carpet-supplier'],
    relatedDhurries: ['cotton-dhurrie-manufacturer', 'wool-dhurrie-manufacturer', 'bulk-dhurrie-supplier'],
  },
  {
    slug: 'dhurrie-manufacturer-bhadohi', kind: 'dhurrie', label: 'Dhurrie Manufacturer Bhadohi', heroImage: '/images/manufacturing-rug-img.webp',
    eyebrow: 'Bhadohi — The Carpet City',
    tagline: 'Dhurrie manufacturer in Bhadohi — India\'s carpet city, the authentic source for handwoven dhurries.',
    seoTitle: 'Dhurrie Manufacturer in Bhadohi, India | Handwoven Dhurries at Source — Tapis Global',
    seoDescription: 'Dhurrie manufacturer in Bhadohi, India — the heart of India\'s handwoven carpet and dhurrie industry. Cotton, wool and jute dhurries direct from source, for bulk, tender and export. Request a catalogue.',
    seoKeywords: ['dhurrie manufacturer Bhadohi', 'Bhadohi dhurrie supplier', 'dhurrie manufacturer Uttar Pradesh', 'handwoven dhurrie Bhadohi', 'Bhadohi carpet city dhurrie'],
    h1: 'Dhurrie Manufacturer in Bhadohi, India',
    intro: 'Tapis Global International is a dhurrie manufacturer based in Bhadohi, India — the historic heart of India\'s handwoven carpet and dhurrie industry. Buying from Bhadohi means buying at source, from generations of weaving expertise, with the authenticity, quality and pricing only a true manufacturing hub delivers.',
    overview: 'Bhadohi, in Uttar Pradesh, is India\'s largest handwoven floor-covering cluster — a GI-recognised carpet city with deep weaving heritage and skilled artisan communities. As a third-generation, family-owned Bhadohi manufacturer continuing a legacy since 1965, we offer authentic source-direct dhurries with the craft, capacity and accountability that define the region.',
    sections: [
      { h2: 'Authentic Source-Direct', body: 'Manufacturing in Bhadohi means our dhurries come straight from the source — generations of weaving skill, authentic construction and source-direct pricing without intermediaries.' },
      { h2: 'Heritage & Capacity', body: 'Bhadohi combines craft heritage with industrial capacity. Our 80,000 sq ft facility and skilled weaver network deliver everything from bespoke pieces to large tender and export volumes.' },
      { h2: 'Full Range from One Hub', body: 'From cotton, wool and jute dhurries to Tat Patti and the wider carpet range, we supply the complete handwoven floor-covering spectrum from one accountable Bhadohi manufacturer.' },
    ],
    applications: [
      { title: 'Retail & Designers', desc: 'Authentic Bhadohi dhurries for retail and design.' },
      { title: 'Institutions & Tenders', desc: 'Source-direct bulk supply for institutional buyers.' },
      { title: 'Exporters & Importers', desc: 'Bhadohi-origin dhurries for global trade.' },
      { title: 'Hospitality & Projects', desc: 'Craft dhurries for hospitality and project use.' },
    ],
    whyPoints: [
      { title: 'Buying at Source', desc: 'Direct from India\'s carpet city.' },
      { title: 'Family Heritage Since 1965', desc: 'Three generations of Bhadohi manufacturing.' },
      { title: 'Craft + Capacity', desc: 'Bespoke to bulk from one hub.' },
    ],
    faqs: [
      { q: 'Why buy dhurries from Bhadohi?', a: 'Bhadohi is India\'s largest handwoven floor-covering cluster with deep weaving heritage. Buying here means authentic source-direct dhurries, craft quality and pricing without intermediaries.' },
      { q: 'Are you an established Bhadohi manufacturer?', a: 'Yes — Tapis Global is a third-generation, family-owned Bhadohi manufacturer continuing a carpet-making legacy since 1965, with an 80,000 sq ft facility and skilled weaver network.' },
      { q: 'What dhurries do you make in Bhadohi?', a: 'Cotton, wool and jute dhurries, Tat Patti and the wider handwoven carpet range, from bespoke pieces to bulk and export volumes.' },
      { q: 'Do you supply tenders and exports from Bhadohi?', a: 'Yes — source-direct bulk supply for institutional tenders and international export with documentation.' },
      { q: 'Is source-direct pricing better?', a: 'Yes. Manufacturing at source removes intermediary margins, giving better pricing and quality control.' },
    ],
    relatedProducts: REL_PRODUCTS,
    relatedIndustries: ['school-carpets', 'government-carpets', 'retail-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'wholesale-carpet-supplier'],
    relatedDhurries: ['cotton-dhurrie-manufacturer', 'handloom-dhurrie-manufacturer', 'dhurrie-exporter-india'],
  },
]
