import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// Pan-India commercial market landing pages — /india/[location]
//
// Positioning (stated honestly): Tapis Global International MANUFACTURES
// made-to-order carpets and rugs in Bhadohi, Uttar Pradesh, and PRODUCES FOR
// B2B buyers and projects in each city below. We are a manufacturer/supplier,
// not a ready-stock retailer.
//
// Claim discipline for these NEW pages:
//   - Capability wording only ("we manufacture in Bhadohi for buyers in X"),
//     never fabricated local presence, offices, showrooms, projects, customers,
//     delivery history, production-capacity figures or certifications per city.
//   - NO hard payment-term / currency claims (terms are enquiry-based).
//   - NO "held dye-lots" / "phased delivery" guarantees, NO fire-rating
//     documentation guarantees — technical requirements are discussed per project.
//   - Lead times are described as made-to-order and confirmed per enquiry, never
//     asserted as a fixed promise.
//   - NO LocalBusiness schema is emitted for these cities (route emits only
//     WebPage + BreadcrumbList + FAQPage). Bhadohi is our genuine base and is
//     described as such.
// ─────────────────────────────────────────────────────────────────────────────

/** Shared hub intro (used by the /india hub page). */
export const INDIA_HUB_INTRO =
  'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi, Uttar Pradesh, and produces for commercial buyers and projects across India. We are a manufacturer and supplier — not a ready-stock retailer — making each order to its own design, size, colour, material, quality and quantity for architects, interior designers, hotels, developers, procurement teams and trade buyers nationwide.'

export const INDIA_LOCATIONS: SeoLanding[] = [
  // ── Delhi NCR (regional hub city; parent of Gurugram / Noida sub-markets) ──
  {
    slug: 'delhi-ncr',
    kind: 'india',
    label: 'Delhi NCR',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for Delhi',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Delhi\'s government ministries, embassies, corporate headquarters and five-star hospitality.',
    seoTitle: 'Carpet Manufacturer for Delhi | Tapis Global',
    seoDescription: 'Made-to-order carpet manufacturer for Delhi — government buildings, embassies, corporate HQs and five-star hotels. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Delhi', 'government tender carpet Delhi', 'embassy carpet supplier Delhi', 'corporate carpet Delhi', 'five star hotel carpet Delhi'],
    h1: 'Carpet & Rug Manufacturer for Delhi',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Delhi — central government ministries and civic buildings, foreign embassies and diplomatic missions, corporate headquarters in Lutyens\' Delhi and Connaught Place, and the capital\'s five-star hospitality corridor. Each order is made to your design, size and specification; we hold no ready stock.',
    overview: 'Delhi concentrates a genuinely singular commercial market: central government ministries and institutions, one of the world\'s densest clusters of foreign embassies and diplomatic missions, established corporate headquarters in the capital\'s historic commercial core, and a five-star hospitality corridor serving both. As a manufacturer we supply documented, tender-ready carpet for government and institutional settings, culturally attuned bespoke rugs for diplomatic missions, and refined contract carpet for corporate and hospitality projects — all produced in Bhadohi and dispatched to Delhi.',
    sections: [
      { h2: 'Government, Ministries & Diplomatic Missions', body: 'Delhi\'s central ministries, civic institutions and foreign embassies require carpet manufactured to documented specification, with the paperwork government and diplomatic procurement processes expect. We develop bespoke rugs reflecting a mission\'s own national character where required, alongside durable institutional-grade carpet for ministry and civic buildings.' },
      { h2: 'Corporate Headquarters & Five-Star Hospitality', body: 'Delhi\'s established corporate headquarters around Connaught Place and the capital\'s five-star hotel corridor both specify refined, design-led carpet. We manufacture contract-grade broadloom and carpet tile for corporate fit-outs, and design-forward custom carpet for five-star guestrooms and public areas.' },
    ],
    applications: [
      { title: 'Government & Institutional Buildings', desc: 'Documented, tender-ready carpet for ministries and civic buildings.' },
      { title: 'Embassies & Diplomatic Missions', desc: 'Bespoke rugs reflecting a mission\'s own national character.' },
      { title: 'Corporate Headquarters', desc: 'Refined contract carpet for Connaught Place and central Delhi offices.' },
      { title: 'Five-Star Hospitality', desc: 'Design-forward custom carpet for Delhi\'s luxury hotel corridor.' },
    ],
    whyPoints: [
      { title: 'Tender-Ready', desc: 'Documented specification to support government procurement.' },
      { title: 'Culturally Attuned', desc: 'Bespoke development reflecting a mission\'s own character.' },
      { title: 'Manufacturer-Direct', desc: 'Made in our own Bhadohi facility, no middlemen.' },
    ],
    faqs: [
      { q: 'Can you support government tender or procurement requirements for Delhi buildings?', a: 'Yes. We produce to documented specification and can supply samples and specification sheets to support tender submissions for government and institutional projects.' },
      { q: 'Can you develop a rug reflecting an embassy\'s own national character?', a: 'Yes. We develop bespoke pieces to an embassy or mission\'s exact colour, motif and cultural references, with samples approved before production.' },
      { q: 'Do you supply corporate offices in Connaught Place or central Delhi?', a: 'Yes. We manufacture contract-grade broadloom and carpet tile to specification for corporate fit-outs.' },
      { q: 'Can you make carpets for a Delhi five-star hotel?', a: 'Yes. We manufacture made-to-order contract carpets to your design, size and specification; fire-safety construction can be discussed and specified per project.' },
      { q: 'Do you have a showroom or office in Delhi?', a: 'No. We manufacture in Bhadohi and produce to order for projects across Delhi. We do not run a ready-stock retail showroom; we work from samples, catalogues and specifications.' },
      { q: 'Do you offer wholesale or private-label programmes for Delhi trade buyers?', a: 'Yes. Delhi\'s established trade and distribution base is well served by our bulk wholesale and private-label manufacturing programmes, with custom branding and packaging available.' },
      { q: 'How long does a made-to-order carpet take?', a: 'Because every piece is manufactured to order, the timeline depends on design, size, quantity and finish, and is confirmed when we quote your enquiry.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'banquet-hall-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'wholesale-carpet-supplier'],
    relatedCompany: ['certifications'],
    relatedIndia: ['gurugram', 'noida', 'faridabad'],
    importProcess: 'We confirm specification and any cultural, diplomatic or tender-documentation requirements, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment to Delhi.',
    shipping: 'Freight is coordinated from Bhadohi to Delhi NCR by road, with documentation prepared to support institutional, diplomatic and government-procurement receipt requirements at your site.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved — institutional and diplomatic projects with fixed dates are planned around accordingly.',
    popularStyles: ['Documented institutional broadloom', 'Culturally referenced embassy rugs', 'Refined corporate headquarters carpet', 'Design-forward five-star hospitality carpet', 'Classical Delhi-appropriate patterns'],
    buyerSegments: [
      { label: 'Government Procurement', body: 'Documented, tender-ready carpet manufactured to specification for central ministries and civic buildings.' },
      { label: 'Architects', body: 'Custom carpet and rug specification support for architectural and design-build projects across Delhi.' },
      { label: 'Corporate Offices', body: 'Refined contract carpet for Connaught Place and central Delhi corporate headquarters.' },
      { label: 'Hospitality', body: 'Design-forward custom carpet for Delhi\'s five-star hotel corridor.' },
      { label: 'Interior Designers', body: 'Bespoke rug development reflecting diplomatic, institutional and corporate design briefs.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Delhi\'s established trade and distribution base.' },
    ],
    customSizesNote: 'We manufacture custom rugs and carpet to institutional, diplomatic and embassy specifications, including culturally significant motifs and colourways, with samples approved before production.',
    materialRecommendations: ['indian-wool', 'wool-viscose', 'nz-wool', 'cotton'],
    constructionRecommendations: ['hand-knotted', 'machine-made', 'dhurrie'],
  },

  // ── Faridabad (NCR industrial/manufacturing satellite — distinct from
  //    Delhi/Gurugram/Noida) ─────────────────────────────────────────────────
  {
    slug: 'faridabad',
    kind: 'india',
    label: 'Faridabad',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for Faridabad',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Faridabad\'s industrial estates, warehousing facilities and value-driven institutional buyers.',
    seoTitle: 'Carpet Manufacturer for Faridabad | Tapis Global',
    seoDescription: 'Made-to-order carpet manufacturer for Faridabad — industrial estates, institutional buildings and mid-market residential. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Faridabad', 'industrial carpet supplier Faridabad', 'institutional carpet Faridabad', 'commercial carpet NCR', 'wholesale carpet Faridabad'],
    h1: 'Carpet & Rug Manufacturer for Faridabad',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Faridabad — industrial estates and manufacturing facilities, municipal and civic institutions, and the city\'s mid-market residential and commercial developments. Each order is made to your specification; we hold no ready stock.',
    overview: 'Faridabad is NCR\'s industrial and manufacturing satellite — a genuinely distinct market from the corporate towers of Gurugram or the IT campuses of Noida. Its economy is built on industrial estates, warehousing and back-office facilities, alongside a steady base of schools, hospitals and civic buildings and a growing mid-market residential and commercial sector. As a manufacturer we supply durable, value-conscious carpet suited to this practical, procurement-led buyer base.',
    sections: [
      { h2: 'Industrial Estates & Institutional Buildings', body: 'Faridabad\'s industrial estates, warehousing facilities and civic institutions favour durable, value-conscious carpet manufactured to documented specification. We supply schools, hospitals and municipal buildings with practical constructions built for sustained use.' },
      { h2: 'Mid-Market Residential & Commercial Growth', body: 'Faridabad\'s expanding residential and back-office commercial sector calls for reliable, budget-conscious carpet supply. We manufacture broadloom and custom rugs to specification, coordinated with build and fit-out schedules.' },
    ],
    applications: [
      { title: 'Industrial Estates', desc: 'Durable, value-conscious carpet for warehousing and back-office facilities.' },
      { title: 'Institutional & Civic Buildings', desc: 'Practical, documented carpet for schools, hospitals and municipal buildings.' },
      { title: 'Corporate Offices', desc: 'Reliable contract carpet for Faridabad\'s back-office and mid-market commercial sector.' },
      { title: 'Builders & Developers', desc: 'Carpet supply coordinated with residential and commercial build schedules.' },
    ],
    whyPoints: [
      { title: 'Value-Conscious', desc: 'Practical constructions for procurement-led, budget-aware buyers.' },
      { title: 'Institutional-Grade', desc: 'Durable carpet built for sustained civic and industrial use.' },
      { title: 'Manufacturer-Direct', desc: 'Made in our own Bhadohi facility, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Faridabad industrial estates?', a: 'Yes. We manufacture made-to-order, durable carpet to specification for warehousing, back-office and industrial-estate facilities across Faridabad.' },
      { q: 'Can you supply Faridabad schools, hospitals and municipal buildings?', a: 'Yes. We manufacture practical, documented carpet for civic and institutional buildings, with samples and specification sheets available for procurement teams.' },
      { q: 'Can you support municipal or government tender requirements?', a: 'Yes. We produce to documented specification and can supply samples and specification sheets to support tender submissions.' },
      { q: 'Do you offer wholesale programmes for Faridabad trade buyers?', a: 'Yes. We provide bulk, batch-consistent wholesale supply for Faridabad\'s trade and distribution sector.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline depends on design, size, quantity and finish, and is confirmed at quotation.' },
      { q: 'Do you have a showroom or office in Faridabad?', a: 'No. We manufacture in Bhadohi and produce to order for projects across Faridabad. We do not run a ready-stock retail showroom.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'flat-weaves'],
    relatedIndustries: ['office-carpets', 'school-carpets', 'hospital-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'wholesale-carpet-supplier'],
    relatedCompany: ['production-capacity'],
    relatedIndia: ['delhi-ncr', 'gurugram', 'noida'],
    importProcess: 'We confirm specification against the industrial, institutional or residential brief, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment.',
    shipping: 'Freight is coordinated from Bhadohi to Faridabad by road, with documentation prepared for smooth receipt at industrial estates, civic buildings and project sites.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved.',
    popularStyles: ['Durable industrial-estate broadloom', 'Practical institutional carpet', 'Value-conscious civic-building constructions', 'Mid-market residential rugs', 'Reliable back-office commercial carpet'],
    buyerSegments: [
      { label: 'Government Procurement', body: 'Documented, practical carpet manufactured to specification for municipal and civic tenders.' },
      { label: 'Architects', body: 'Custom carpet and rug specification support for industrial and institutional design-build projects in Faridabad.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for large industrial and institutional programmes.' },
      { label: 'Corporate Offices', body: 'Reliable contract carpet for Faridabad\'s back-office and mid-market commercial sector.' },
      { label: 'Builders', body: 'Carpet supply coordinated with build schedules for industrial, civic and residential developments.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Faridabad\'s trade and distribution sector.' },
    ],
    customSizesNote: 'We manufacture to standard institutional and residential dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['indian-wool', 'pet', 'jute'],
    constructionRecommendations: ['machine-made', 'dhurrie'],
  },

  // ── Mumbai ──────────────────────────────────────────────────────────────────
  {
    slug: 'mumbai',
    kind: 'india',
    label: 'Mumbai',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for Mumbai',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Mumbai\'s luxury residential, five-star hospitality and corporate interiors.',
    seoTitle: 'Carpet Manufacturer for Mumbai | Tapis Global',
    seoDescription: 'Made-to-order carpet manufacturer for Mumbai — luxury residences, five-star hotels, corporate offices and design studios. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Mumbai', 'luxury rug supplier Mumbai', 'five star hotel carpet Mumbai', 'corporate carpet Mumbai', 'designer rugs Mumbai'],
    h1: 'Carpet & Rug Manufacturer for Mumbai',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Mumbai — luxury residential towers, flagship five-star hospitality, corporate headquarters and the design studios that specify for them. Each order is made to your exact brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'As India\'s financial capital, Mumbai concentrates some of the country\'s highest-value residential towers, flagship five-star hotels and premium corporate headquarters, where specification and finish matter enormously. As a manufacturer we develop bespoke hand knotted and hand tufted rugs, luxury custom pieces and contract carpet to designer briefs, all made in Bhadohi for supply into the city.',
    sections: [
      { h2: 'Luxury Residential Towers', body: 'Mumbai\'s premium apartments and residential towers call for refined, bespoke rugs. We develop fine hand knotted and wool-silk pieces to exact colour, size and design for the city\'s interior designers and private clients.' },
      { h2: 'Five-Star Hospitality & Corporate Headquarters', body: 'For Mumbai\'s flagship hotels and corporate headquarters we manufacture made-to-order contract carpets — durable, design-led and specification-exact; fire-safety and other technical requirements are discussed and specified per project.' },
    ],
    applications: [
      { title: 'Luxury Residential', desc: 'Bespoke rugs for Mumbai\'s premium towers and apartments.' },
      { title: 'Five-Star Hotels', desc: 'Made-to-order contract carpets for flagship hospitality.' },
      { title: 'Corporate Headquarters', desc: 'Custom broadloom for premium office fit-outs.' },
      { title: 'Interior Designers', desc: 'Fine bespoke pieces to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Refined Craft', desc: 'Fine hand knotting and premium materials.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and colour.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply luxury rugs in Mumbai?', a: 'Yes. We manufacture bespoke hand knotted and wool-silk rugs to exact colour, size and design in Bhadohi, for supply to Mumbai. We do not hold ready stock — each piece is made to order.' },
      { q: 'Can you make carpets for a Mumbai five-star hotel?', a: 'Yes. We produce made-to-order contract carpets to specification; fire-safety and technical requirements are discussed and specified per project.' },
      { q: 'Do you supply Mumbai corporate headquarters?', a: 'Yes. We manufacture contract-grade broadloom and carpet tile to specification for corporate fit-outs.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects the design, size, quantity and finish and is confirmed at the quotation stage.' },
      { q: 'Do you work with Mumbai interior designers directly?', a: 'Yes. We work directly with designers and private clients, with lab-dips and samples approved before production.' },
      { q: 'Do you offer wholesale or private-label programmes for Mumbai buyers?', a: 'Yes. We provide OEM and private-label manufacturing with custom branding and packaging, alongside bulk wholesale programmes suited to Mumbai\'s trade sector.' },
      { q: 'Are you a retail carpet store?', a: 'No. We are a manufacturer and supplier producing made-to-order carpets and rugs for projects and trade buyers.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'leather-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'office-carpets'],
    relatedSolutions: ['luxury-carpets', 'designer-rugs'],
    relatedCompany: ['custom-manufacturing'],
    relatedIndia: ['pune', 'ahmedabad', 'goa'],
    importProcess: 'We confirm specification, construction and quantity, then develop lab-dips and a sample for sign-off before production begins — the same process for a single bespoke residential rug as for a hotel-wide hospitality programme. Production runs with staged quality checks and a documented pre-dispatch inspection.',
    shipping: 'Freight is coordinated from Bhadohi to Mumbai by road, with documentation prepared for smooth receipt at your project site, and consolidated shipments suited to individual design and residential orders.',
    leadTime: 'Because every piece is made to order, lead time follows the construction, size and quantity specified — confirmed once your specification and samples are approved, not before.',
    popularStyles: ['Fine hand-knotted statement rugs', 'Wool-silk luxury residential pieces', 'Design-forward hospitality carpet', 'Contract broadloom for corporate towers', 'Bespoke designer-studio collaborations'],
    buyerSegments: [
      { label: 'Luxury Residential', body: 'Bespoke fine rugs for Mumbai\'s premium towers and high-value apartments.' },
      { label: 'Hospitality', body: 'Design-forward made-to-order carpet for Mumbai\'s flagship five-star hotels.' },
      { label: 'Corporate Offices', body: 'Contract-grade broadloom and carpet tile for corporate headquarters fit-outs.' },
      { label: 'Interior Designers', body: 'Fine bespoke rugs developed directly with Mumbai\'s design studios and private clients.' },
      { label: 'Architects', body: 'Custom carpet and rug specification support for architectural and design-build projects across Mumbai.' },
      { label: 'Government Procurement', body: 'Documented, specification-compliant carpet for Maharashtra state and municipal institutional buildings.' },
      { label: 'Retail', body: 'Custom carpet and rug fit-out for Mumbai\'s premium retail and showroom developments.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Mumbai importers and trade distributors.' },
    ],
    customSizesNote: 'We manufacture to standard rug dimensions as well as fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['nz-wool', 'bamboo-silk', 'wool-viscose', 'tencel'],
    constructionRecommendations: ['hand-knotted', 'hand-tufted'],
  },

  // ── Bengaluru ───────────────────────────────────────────────────────────────
  {
    slug: 'bengaluru',
    kind: 'india',
    label: 'Bengaluru',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Bengaluru',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Bengaluru\'s tech campuses, coworking, hospitality and modern residential interiors.',
    seoTitle: 'Carpet Manufacturer for Bengaluru | Tapis Global',
    seoDescription: 'Made-to-order carpet manufacturer for Bengaluru — tech campuses, coworking spaces, hospitality and modern residences. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Bengaluru', 'office carpet supplier Bangalore', 'carpet tiles Bengaluru', 'coworking carpet Bangalore', 'commercial carpet Bengaluru'],
    h1: 'Carpet & Rug Manufacturer for Bengaluru',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Bengaluru — tech campuses, coworking operators, hospitality and modern residential projects. Everything is made to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Bengaluru\'s IT and startup economy drives sustained demand for office broadloom, carpet tiles and coworking flooring, alongside a modern residential and boutique-hospitality market that favours contemporary design. As a manufacturer we supply custom office carpets, carpet tiles and contemporary rugs to the city\'s architects and fit-out contractors, produced in Bhadohi.',
    sections: [
      { h2: 'Tech Campuses & Coworking Flooring', body: 'For Bengaluru\'s tech campuses and coworking spaces we manufacture durable custom broadloom and carpet tiles in modular, easy-maintenance formats and current palettes, made to specification and dye-lot consistency across large floorplates.' },
      { h2: 'Modern Residential & Boutique Hospitality', body: 'For the city\'s contemporary homes and boutique hotels we develop modern and contemporary rugs to exact colour and size, plus made-to-order hospitality carpets suited to Bengaluru\'s design-forward taste.' },
    ],
    applications: [
      { title: 'Tech Campuses & Offices', desc: 'Custom broadloom and carpet tiles for workspaces.' },
      { title: 'Coworking Operators', desc: 'Durable, modular flooring for coworking floors.' },
      { title: 'Hospitality', desc: 'Made-to-order carpets for boutique hotels.' },
      { title: 'Modern Residential', desc: 'Contemporary rugs to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Workspace-Ready', desc: 'Durable broadloom and tiles for high-traffic tech campuses.' },
      { title: 'Contemporary Design', desc: 'Modern palettes and patterns developed to brief.' },
      { title: 'Manufacturer-Direct', desc: 'Made in our own Bhadohi facility, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets and tiles in Bengaluru?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification in Bhadohi, for supply to Bengaluru, with dye-lot consistency across large orders.' },
      { q: 'Can you supply coworking and tech-campus fit-outs?', a: 'Yes. We make durable, modular custom carpet for high-traffic workspaces, produced to your requirement.' },
      { q: 'Can you support architect specification and tender documentation?', a: 'Yes. We produce to documented specification and can supply samples and specification sheets to support architect and procurement submissions.' },
      { q: 'How are lead times decided?', a: 'As everything is made to order, the timeline depends on design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you make modern residential rugs?', a: 'Yes. We develop contemporary rugs to exact colour and size for Bengaluru homes.' },
      { q: 'Do you offer wholesale programmes for Bengaluru trade buyers?', a: 'Yes. We provide bulk, batch-consistent wholesale supply and private-label manufacturing.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is manufactured to your project\'s design, size, material and quantity.' },
    ],
    relatedProducts: ['carpet-tiles', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['office-carpets', 'coworking-carpets', 'hotel-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'modern-rugs'],
    relatedCompany: ['production-capacity'],
    relatedIndia: ['hyderabad', 'chennai', 'pune'],
    importProcess: 'We confirm specification and volume, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection — the same disciplined process for a large tech-campus fit-out as for a single residential rug.',
    shipping: 'Freight is coordinated from Bhadohi to Bengaluru by road, with documentation prepared for smooth receipt at your project site or warehouse.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved.',
    popularStyles: ['Modular carpet tile for tech campuses', 'Durable coworking-floor broadloom', 'Contemporary residential rugs', 'Design-forward boutique hospitality carpet', 'Easy-maintenance workspace constructions'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Custom broadloom and carpet tile manufactured to specification for Bengaluru tech campuses and offices.' },
      { label: 'Architects', body: 'Custom carpet and rug specification support for architectural and design-build projects across Bengaluru.' },
      { label: 'Interior Designers', body: 'Contemporary rugs developed to exact colour and design briefs for modern residential and commercial schemes.' },
      { label: 'Government Procurement', body: 'Documented, specification-compliant carpet for civic and institutional tenders.' },
      { label: 'Builders', body: 'Carpet supply coordinated with build schedules for residential and commercial developments.' },
      { label: 'Retail', body: 'Custom carpet and rug fit-out for Bengaluru\'s retail and showroom sector.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Bengaluru distributors and trade buyers.' },
    ],
    customSizesNote: 'We manufacture to standard carpet-tile and rug dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['wool-viscose', 'pet', 'tencel'],
    constructionRecommendations: ['machine-made', 'hand-tufted'],
  },

  // ── Hyderabad ───────────────────────────────────────────────────────────────
  {
    slug: 'hyderabad',
    kind: 'india',
    label: 'Hyderabad',
    heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Carpets & Rugs for Hyderabad',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Hyderabad\'s IT corridors, hospitality and heritage-luxury interiors.',
    seoTitle: 'Carpet Manufacturer for Hyderabad | Tapis Global',
    seoDescription: 'Made-to-order carpet manufacturer for Hyderabad — HITEC City offices, hotels, palaces and luxury apartments. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Hyderabad', 'office carpet supplier Hyderabad', 'hotel carpet Hyderabad', 'HITEC City carpet supplier', 'luxury apartment rugs Hyderabad'],
    h1: 'Carpet & Rug Manufacturer for Hyderabad',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Hyderabad — IT-corridor offices around HITEC City and Gachibowli, hotels, and the city\'s distinctive heritage-luxury apartments and interiors. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Hyderabad pairs a large IT corridor generating steady office and coworking demand with a hospitality sector and a heritage-luxury tradition rooted in the city\'s palatial interiors and Nizami-era design vocabulary. As a manufacturer we supply custom office carpets and tiles, contract hospitality carpets and opulent hand knotted rugs, produced in Bhadohi for supply into the city.',
    sections: [
      { h2: 'HITEC City & IT Corridor', body: 'For Hyderabad\'s office parks and coworking spaces around HITEC City and Gachibowli we manufacture durable custom broadloom and carpet tiles to specification, in contemporary, workspace-appropriate designs with dye-lot consistency across large orders.' },
      { h2: 'Hospitality & Heritage-Luxury Interiors', body: 'For the city\'s hotels and heritage-luxury apartments we develop bespoke hand knotted rugs and made-to-order contract carpets, rich or restrained, to exact colour and dimension — drawing on classical pattern development where a project calls for it.' },
    ],
    applications: [
      { title: 'IT & Office Parks', desc: 'Custom broadloom and tiles for HITEC City workspaces.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets for Hyderabad hotels.' },
      { title: 'Heritage-Luxury Apartments', desc: 'Opulent hand knotted rugs to exact brief.' },
      { title: 'Interior Designers', desc: 'Bespoke pieces for residential and commercial schemes.' },
    ],
    whyPoints: [
      { title: 'Custom Craft', desc: 'From workspace tiles to opulent hand knots.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets in Hyderabad?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification in Bhadohi, for supply to Hyderabad and the HITEC City corridor.' },
      { q: 'Can you make opulent hand knotted rugs for heritage-luxury interiors?', a: 'Yes. We craft bespoke hand knotted rugs to exact colour, motif and dimension, including classical pattern development.' },
      { q: 'Can you support architect and developer specification for luxury apartments?', a: 'Yes. We develop lab-dips and samples to exact colour and design before production, working directly with architects and developers.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you supply hotels and hospitality projects?', a: 'Yes. We produce made-to-order contract carpets to specification for Hyderabad hospitality.' },
      { q: 'Do you offer wholesale or private-label programmes?', a: 'Yes. We provide bulk, batch-consistent wholesale supply and OEM/private-label manufacturing with custom branding.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'carpet-tiles', 'wall-to-wall-carpets'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'villa-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'luxury-carpets'],
    relatedCompany: ['custom-manufacturing'],
    relatedIndia: ['bengaluru', 'chennai', 'mumbai'],
    importProcess: 'We confirm specification against the office, hospitality or heritage-residential brief, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment.',
    shipping: 'Freight is coordinated from Bhadohi to Hyderabad by road, with documentation prepared for smooth receipt at your project site.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved — heritage hand-knotted commissions are scheduled with the additional time fine knotting requires.',
    popularStyles: ['Modular IT-corridor carpet tile', 'Opulent heritage hand-knotted rugs', 'Design-forward hospitality carpet', 'Classical Nizami-inspired pattern work', 'Contemporary luxury-apartment rugs'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Custom broadloom and carpet tile manufactured to specification for HITEC City and Gachibowli offices.' },
      { label: 'Hospitality', body: 'Made-to-order contract carpet for Hyderabad\'s hotel sector.' },
      { label: 'Luxury Residential', body: 'Opulent bespoke hand knotted rugs for Hyderabad\'s heritage-luxury apartments.' },
      { label: 'Interior Designers', body: 'Bespoke rug development for residential and commercial design schemes.' },
      { label: 'Architects', body: 'Custom carpet and rug specification support for architectural and design-build projects across Hyderabad.' },
      { label: 'Government Procurement', body: 'Documented, specification-compliant carpet for institutional and civic tenders.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Hyderabad distributors and trade buyers.' },
    ],
    customSizesNote: 'We manufacture to standard carpet-tile and rug dimensions as well as fully custom heritage-appropriate sizes, with samples approved before bulk production.',
    materialRecommendations: ['nz-wool', 'wool-viscose', 'bamboo-silk'],
    constructionRecommendations: ['hand-knotted', 'hand-tufted', 'machine-made'],
  },

  // ── Chennai ─────────────────────────────────────────────────────────────────
  {
    slug: 'chennai',
    kind: 'india',
    label: 'Chennai',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'Carpets & Rugs for Chennai',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Chennai\'s port-linked industrial base, corporate offices and hospitality sector.',
    seoTitle: 'Carpet Manufacturer for Chennai | Tapis Global',
    seoDescription: 'Made-to-order carpet manufacturer for Chennai — industrial and port-linked trade, offices, hotels and developers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Chennai', 'industrial carpet supplier Chennai', 'hotel carpet supplier Chennai', 'office carpet Chennai', 'port trade carpet Chennai'],
    h1: 'Carpet & Rug Manufacturer for Chennai',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Chennai — the city\'s substantial industrial and manufacturing base, port-linked trade and logistics operations, corporate offices and a steady hospitality sector. We make to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Chennai combines one of South India\'s largest industrial and automotive-manufacturing bases with a major port and logistics gateway, alongside established corporate offices and a steady hospitality sector along its expanding commercial corridors. As a manufacturer we supply durable contract carpet for industrial and corporate settings, trade-ready product for the city\'s port-linked import-export sector, and made-to-order hospitality carpets, all produced in Bhadohi.',
    sections: [
      { h2: 'Industrial Base & Port-Linked Trade', body: 'Chennai\'s automotive and industrial manufacturing base, alongside its major port and logistics gateway, supports genuine wholesale and export-adjacent trade demand. We manufacture bulk, batch-consistent carpet and rugs for distributors and trade buyers, with freight routed efficiently through the city\'s port and logistics network.' },
      { h2: 'Corporate Offices & Hospitality', body: 'For Chennai\'s corporate offices and hotels we manufacture durable made-to-order carpets to specification; fire-safety and technical requirements are discussed and specified per project.' },
    ],
    applications: [
      { title: 'Industrial & Manufacturing', desc: 'Durable contract carpet for industrial and corporate facilities.' },
      { title: 'Port-Linked Trade', desc: 'Bulk, batch-consistent supply for Chennai\'s import-export sector.' },
      { title: 'Corporate Offices', desc: 'Custom broadloom and tiles for commercial fit-outs.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets for Chennai hotels.' },
    ],
    whyPoints: [
      { title: 'Trade-Ready', desc: 'Freight routed efficiently through Chennai\'s port and logistics network.' },
      { title: 'Industrial-Grade', desc: 'Durable constructions built for manufacturing-sector facilities.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply carpets for Chennai\'s industrial and manufacturing facilities?', a: 'Yes. We manufacture made-to-order, durable carpet to specification for industrial and corporate facilities across Chennai.' },
      { q: 'Can you supply Chennai\'s port-linked trade and distribution sector?', a: 'Yes. We provide bulk, batch-consistent wholesale supply and OEM/private-label manufacturing, with freight routed efficiently through Chennai\'s port and logistics network.' },
      { q: 'Do you supply hotel carpets in Chennai?', a: 'Yes. We manufacture made-to-order contract carpets to specification in Bhadohi, for supply to Chennai; fire-safety and technical requirements are discussed and specified per project.' },
      { q: 'Can you supply office and commercial fit-outs?', a: 'Yes. We make custom broadloom and carpet tiles for Chennai commercial projects.' },
      { q: 'How are lead times decided?', a: 'As every piece is made to order, the timeline depends on design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you work with Chennai designers and developers?', a: 'Yes. We supply designers, developers and procurement teams directly, with samples approved before production.' },
      { q: 'Do you hold ready stock?', a: 'No. Every carpet and rug is made to your project\'s requirements.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'jute-sisal-rugs'],
    relatedIndustries: ['hotel-carpets', 'office-carpets', 'restaurant-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'contract-carpet-supplier'],
    relatedCompany: ['export-process'],
    relatedIndia: ['bengaluru', 'kochi', 'hyderabad'],
    importProcess: 'We confirm specification and volume, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection — the same disciplined process for a bulk trade programme as for a single hospitality order.',
    shipping: 'Freight is coordinated from Bhadohi to Chennai, with routing efficient for the city\'s port-linked distribution network and consolidated shipments for smaller hospitality and design orders.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved.',
    popularStyles: ['Durable industrial-facility carpet', 'Bulk trade-ready broadloom', 'Made-to-order hospitality carpet', 'Practical corporate-office constructions', 'Custom designer residential rugs'],
    buyerSegments: [
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for industrial and manufacturing-sector projects.' },
      { label: 'Wholesale', body: 'Bulk, batch-consistent programmes for Chennai\'s port-linked trade and distribution sector.' },
      { label: 'Corporate Offices', body: 'Custom broadloom and carpet tile for Chennai commercial fit-outs.' },
      { label: 'Hospitality', body: 'Made-to-order contract carpet for Chennai\'s hotel sector.' },
      { label: 'Architects', body: 'Custom carpet and rug specification support for architectural and design-build projects across Chennai.' },
      { label: 'Government Procurement', body: 'Documented, specification-compliant carpet for institutional and civic tenders.' },
      { label: 'Builders', body: 'Carpet supply coordinated with build schedules for commercial and residential developments.' },
    ],
    customSizesNote: 'We manufacture to standard and fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['indian-wool', 'pet', 'jute'],
    constructionRecommendations: ['machine-made', 'flatweave'],
  },

  // ── Pune ────────────────────────────────────────────────────────────────────
  {
    slug: 'pune',
    kind: 'india',
    label: 'Pune',
    heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Carpets & Rugs for Pune',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Pune\'s automotive-sector corporate campuses, IT offices and residential real estate.',
    seoTitle: 'Carpet Manufacturer for Pune | Tapis Global',
    seoDescription: 'Made-to-order carpet manufacturer for Pune — automotive and IT corporate campuses, developers, hotels and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Pune', 'office carpet supplier Pune', 'automotive corporate carpet Pune', 'residential carpet Pune', 'commercial carpet Pune'],
    h1: 'Carpet & Rug Manufacturer for Pune',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Pune — automotive-sector corporate campuses, IT offices, residential developers, hotels and designers. We make to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Pune combines one of India\'s largest automotive-manufacturing corporate bases with a substantial IT sector and one of the country\'s most active residential real-estate markets, alongside a growing hospitality sector. As a manufacturer we supply durable contract carpet for automotive and IT corporate campuses, coordinated rug programmes for residential developers, and made-to-order hospitality carpets, produced in Bhadohi for supply into the city.',
    sections: [
      { h2: 'Automotive & IT Corporate Campuses', body: 'For Pune\'s automotive-sector corporate campuses and IT offices we manufacture durable custom broadloom and carpet tiles to specification, with dye-lot consistency across large multi-building programmes.' },
      { h2: 'Residential Real Estate & Hospitality', body: 'For Pune\'s residential developers and hotels we develop made-to-order rugs and contract carpets to exact colour and size, coordinated with your project timeline.' },
    ],
    applications: [
      { title: 'Automotive & Corporate Campuses', desc: 'Durable custom broadloom and tiles for Pune workspaces.' },
      { title: 'IT Offices', desc: 'Custom broadloom and carpet tiles for IT-sector fit-outs.' },
      { title: 'Residential Developers', desc: 'Coordinated rug supply for new developments.' },
      { title: 'Hospitality', desc: 'Made-to-order carpets for Pune hotels.' },
    ],
    whyPoints: [
      { title: 'Workspace-Ready', desc: 'Durable broadloom and tiles for automotive and IT campuses.' },
      { title: 'Development-Ready', desc: 'Coordinated rug supply timed to build schedules.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply carpets for Pune automotive-sector corporate campuses?', a: 'Yes. We manufacture made-to-order, durable contract carpet to specification for Pune\'s automotive and IT corporate campuses, with dye-lot consistency across large orders.' },
      { q: 'Can you coordinate rug supply for residential developers?', a: 'Yes. We make custom rugs and carpets coordinated with your project timeline.' },
      { q: 'Do you supply office carpets in Pune?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification in Bhadohi, for supply to Pune.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you supply hotels in Pune?', a: 'Yes. We produce made-to-order contract carpets to specification for Pune hospitality.' },
      { q: 'Do you offer wholesale programmes for Pune buyers?', a: 'Yes. We provide bulk, batch-consistent wholesale supply and private-label manufacturing.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is made to your project\'s requirements.' },
    ],
    relatedProducts: ['carpet-tiles', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['office-carpets', 'apartment-carpets', 'hotel-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'custom-carpets'],
    relatedCompany: ['production-capacity'],
    relatedIndia: ['mumbai', 'bengaluru', 'ahmedabad'],
    importProcess: 'We confirm specification against the automotive-campus, IT-office or residential brief, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment.',
    shipping: 'Freight is coordinated from Bhadohi to Pune by road, with documentation prepared for smooth receipt at your project site.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved.',
    popularStyles: ['Durable automotive-campus contract carpet', 'IT-office carpet tile', 'Coordinated residential-development rugs', 'Made-to-order hospitality carpet', 'Practical multi-building broadloom'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Durable contract carpet manufactured to specification for Pune\'s automotive and IT corporate campuses.' },
      { label: 'Luxury Residential', body: 'Coordinated rug and carpet supply for Pune\'s residential development sector.' },
      { label: 'Builders', body: 'Carpet supply coordinated with build schedules for commercial and residential developments.' },
      { label: 'Hospitality', body: 'Made-to-order contract carpet for Pune\'s hotel sector.' },
      { label: 'Interior Designers', body: 'Custom rug development to Pune residential and commercial design briefs.' },
      { label: 'Architects', body: 'Custom carpet and rug specification support for architectural and design-build projects across Pune.' },
      { label: 'Government Procurement', body: 'Documented, specification-compliant carpet for Maharashtra state and Pune Municipal Corporation institutional tenders.' },
      { label: 'Retail', body: 'Custom carpet and rug fit-out for Pune\'s retail and showroom sector.' },
    ],
    customSizesNote: 'We manufacture to standard carpet-tile and rug dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['wool-viscose', 'indian-wool', 'pet'],
    constructionRecommendations: ['machine-made', 'hand-tufted'],
  },

  // ── Indore (new — Madhya Pradesh's largest retail/trade hub, emerging IT-ITES) ──
  {
    slug: 'indore',
    kind: 'india',
    label: 'Indore',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Indore',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Indore\'s emerging IT-ITES offices, retail trade and institutional buyers.',
    seoTitle: 'Carpet Manufacturer for Indore | Tapis Global',
    seoDescription: 'Made-to-order carpet manufacturer for Indore — IT offices, retail showrooms, institutions and residential developers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Indore', 'office carpet supplier Indore', 'retail carpet Indore', 'institutional carpet Madhya Pradesh', 'commercial carpet Indore'],
    h1: 'Carpet & Rug Manufacturer for Indore',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Indore — the city\'s emerging IT-ITES corporate offices, its position as Madhya Pradesh\'s largest retail and trade hub, and a steady institutional and residential base. Each order is made to your specification; we hold no ready stock.',
    overview: 'Indore is Madhya Pradesh\'s largest commercial centre — a growing IT-ITES corporate base layered over the city\'s long-established role as the state\'s principal retail and trade hub, alongside a steady institutional and residential development sector. As a manufacturer we supply custom office carpet for the city\'s growing corporate base, trade-ready carpet for its retail and wholesale sector, and durable institutional carpet, all produced in Bhadohi.',
    sections: [
      { h2: 'Emerging IT-ITES Offices', body: 'Indore\'s growing IT-ITES corporate base favours reliable, contract-grade carpet. We manufacture custom broadloom and carpet tile to specification, with the consistency corporate procurement teams expect.' },
      { h2: 'Retail Trade & Institutional Buyers', body: 'As Madhya Pradesh\'s largest retail and trade hub, Indore has genuine wholesale and retail-fit-out demand alongside a steady base of schools, hospitals and civic institutions. We supply bulk wholesale programmes and durable, documented carpet for institutional buyers.' },
    ],
    applications: [
      { title: 'IT-ITES Offices', desc: 'Custom broadloom and carpet tiles for Indore\'s growing corporate base.' },
      { title: 'Retail & Trade', desc: 'Bulk, batch-consistent supply for Madhya Pradesh\'s largest trade hub.' },
      { title: 'Institutional Buildings', desc: 'Durable, documented carpet for schools, hospitals and civic buildings.' },
      { title: 'Residential Developers', desc: 'Coordinated rug supply for new developments.' },
    ],
    whyPoints: [
      { title: 'Trade-Ready', desc: 'Bulk wholesale supply suited to Indore\'s retail-hub role.' },
      { title: 'Institutional-Grade', desc: 'Durable, documented carpet for civic and educational use.' },
      { title: 'Manufacturer-Direct', desc: 'Made in our own Bhadohi facility, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Indore IT-ITES offices?', a: 'Yes. We manufacture made-to-order contract carpet to specification for Indore\'s growing IT-ITES corporate offices.' },
      { q: 'Do you supply Indore\'s retail and wholesale trade sector?', a: 'Yes. We provide bulk, batch-consistent wholesale supply and private-label manufacturing suited to Madhya Pradesh\'s largest trade hub.' },
      { q: 'Can you supply Indore schools, hospitals and civic buildings?', a: 'Yes. We manufacture institutional-grade carpet to documented specification, with samples for procurement teams.' },
      { q: 'Can you support government or institutional tender requirements?', a: 'Yes. We produce to documented specification and can supply samples and specification sheets to support tender submissions.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline depends on design, size, quantity and finish, and is confirmed at quotation.' },
      { q: 'Do you have a showroom or office in Indore?', a: 'No. We manufacture in Bhadohi and produce to order for projects across Indore. We do not run a ready-stock retail showroom.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'flat-weaves'],
    relatedIndustries: ['office-carpets', 'retail-carpets', 'school-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'commercial-carpet-manufacturer'],
    relatedCompany: ['oem-private-label'],
    relatedIndia: ['ahmedabad', 'jaipur', 'lucknow'],
    importProcess: 'We confirm specification and volume, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection — the same disciplined process for a bulk wholesale programme as for a single institutional order.',
    shipping: 'Freight is coordinated from Bhadohi to Indore by road, with documentation prepared for smooth receipt at your project site or trade warehouse.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved.',
    popularStyles: ['Contract-grade IT-office broadloom', 'Bulk trade-ready wholesale collections', 'Durable institutional carpet', 'Retail-showroom carpet tile', 'Coordinated residential-development rugs'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Custom broadloom and carpet tile manufactured to specification for Indore\'s growing IT-ITES offices.' },
      { label: 'Wholesale', body: 'Bulk, batch-consistent programmes for Indore\'s retail and trade sector.' },
      { label: 'Government Procurement', body: 'Documented, specification-compliant carpet for civic and institutional tenders.' },
      { label: 'Architects', body: 'Custom carpet and rug specification support for architectural and design-build projects across Indore.' },
      { label: 'Retail', body: 'Custom carpet and rug fit-out for Indore\'s retail showrooms.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging, under confidentiality.' },
      { label: 'Builders', body: 'Carpet supply coordinated with build schedules for commercial and residential developments.' },
    ],
    customSizesNote: 'We manufacture to standard and fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['wool-viscose', 'pet', 'tencel'],
    constructionRecommendations: ['machine-made', 'hand-tufted'],
  },

  // ── Bhadohi (actual manufacturing base) ─────────────────────────────────────
  {
    slug: 'bhadohi',
    kind: 'india',
    label: 'Bhadohi',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Our Manufacturing Base',
    tagline: 'Carpet and rug manufacturer based in Bhadohi — India\'s carpet belt — producing to order for trade buyers, exporters and projects sourcing at source.',
    seoTitle: 'Carpet Manufacturer in Bhadohi | Our Manufacturing Base — Tapis Global International',
    seoDescription: 'Tapis Global International is a carpet and rug manufacturer based in Bhadohi, Uttar Pradesh — India\'s carpet-weaving belt. Made-to-order hand knotted, hand tufted and custom carpets for trade buyers, exporters and projects sourcing at source. Request a catalogue.',
    seoKeywords: ['carpet manufacturer Bhadohi', 'Bhadohi carpet supplier', 'hand knotted carpet Bhadohi', 'rug manufacturer Bhadohi', 'carpet belt India manufacturer'],
    h1: 'Carpet & Rug Manufacturer in Bhadohi',
    intro: 'Bhadohi is our home. Tapis Global International manufactures made-to-order carpets and rugs here, in Uttar Pradesh\'s historic carpet-weaving belt, for trade buyers, exporters and projects that prefer to source directly at the point of production.',
    overview: 'Bhadohi — often called the carpet city of India — is the country\'s largest hand-knotted and hand-tufted carpet manufacturing cluster, and the location of our production. Sourcing here means buying manufacturer-direct at source: control over design, materials, construction and quality, without intermediaries. We make hand knotted, hand tufted, wall-to-wall and custom carpets to order, for domestic trade, projects and export.',
    sections: [
      { h2: 'Sourcing at Source', body: 'Buyers and trade sourcing from Bhadohi work directly with the maker — reviewing materials, construction and samples, and specifying design, size and quality without layers of intermediaries. As a Bhadohi manufacturer, that is exactly how we operate.' },
      { h2: 'The Bhadohi Carpet Belt', body: 'The region\'s generations-deep weaving skill underpins the quality of Indian handmade carpets. We draw on this local craft base to produce hand knotted and hand tufted carpets to exacting, made-to-order specification.' },
    ],
    applications: [
      { title: 'Trade & Wholesale Buyers', desc: 'Manufacturer-direct sourcing at source in Bhadohi.' },
      { title: 'Exporters & Importers', desc: 'Made-to-order production for export programmes.' },
      { title: 'Projects & Procurement', desc: 'Custom carpets specified directly with the maker.' },
      { title: 'Designers', desc: 'Bespoke development at the point of production.' },
    ],
    whyPoints: [
      { title: 'At Source', desc: 'Buy manufacturer-direct in the carpet belt.' },
      { title: 'Full Control', desc: 'Design, material, construction and quality.' },
      { title: 'Made to Order', desc: 'Your specification and quantity.' },
    ],
    faqs: [
      { q: 'Are you actually based in Bhadohi?', a: 'Yes. Bhadohi, Uttar Pradesh is our manufacturing base — India\'s carpet-weaving belt. We produce hand knotted, hand tufted and custom carpets to order here.' },
      { q: 'Can trade buyers source directly from Bhadohi?', a: 'Yes. We work manufacturer-direct with trade buyers, exporters and projects sourcing at source, with samples and specification support.' },
      { q: 'How are lead times decided?', a: 'Everything is made to order, so the timeline depends on design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you export from Bhadohi?', a: 'We manufacture in Bhadohi and support export enquiries; see our export markets for country-specific information.' },
      { q: 'Do you hold ready stock?', a: 'No. We manufacture to order — every carpet is made to your specification.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'office-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'wholesale-carpet-supplier'],
    relatedCompany: ['why-bhadohi', 'factory'],
    relatedIndia: ['delhi-ncr', 'lucknow', 'mumbai'],
  },

  // ── Kolkata ─────────────────────────────────────────────────────────────────
  {
    slug: 'kolkata',
    kind: 'india',
    label: 'Kolkata',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Carpets & Rugs for Kolkata',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Kolkata\'s hospitality, heritage interiors and cultural institutions.',
    seoTitle: 'Carpet Manufacturer for Kolkata | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Kolkata. Custom hand knotted, hand tufted and hospitality carpets from our Bhadohi factory for hotels, clubs, institutions and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Kolkata', 'hotel carpet supplier Kolkata', 'custom rugs Kolkata', 'club carpet Kolkata', 'commercial carpet Kolkata'],
    h1: 'Carpet & Rug Manufacturer for Kolkata',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Kolkata — hotels, heritage clubs, cultural institutions and residential projects. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Kolkata\'s deep cultural heritage shapes a market that values traditional craft, rich interiors and institutional grandeur — heritage hotels, clubs, auditoria and cultural buildings, alongside contemporary commercial growth. We make bespoke hand knotted rugs, hospitality carpets and auditorium/institutional carpets, produced in Bhadohi for supply into the city.',
    sections: [
      { h2: 'Heritage & Institutional Interiors', body: 'For Kolkata\'s heritage hotels, clubs, auditoria and cultural institutions we manufacture bespoke and contract carpets to exact design and dimension, honouring traditional aesthetics where required.' },
      { h2: 'Hospitality & Residential', body: 'For the city\'s hotels and residences we develop made-to-order rugs and carpets to specification, from classical to contemporary.' },
    ],
    applications: [
      { title: 'Heritage Hotels & Clubs', desc: 'Bespoke carpets for Kolkata\'s heritage venues.' },
      { title: 'Cultural Institutions', desc: 'Made-to-order auditorium and institutional carpets.' },
      { title: 'Hospitality', desc: 'Custom contract carpets for hotels.' },
      { title: 'Interior Designers', desc: 'Bespoke rugs to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Traditional Craft', desc: 'Classical designs realised faithfully.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply carpets for Kolkata heritage hotels and clubs?', a: 'Yes. We manufacture bespoke and contract carpets to exact design and dimension in Bhadohi, for supply to Kolkata.' },
      { q: 'Can you make auditorium and institutional carpets?', a: 'Yes. We produce made-to-order auditorium and institutional carpets to specification.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you make traditional designs?', a: 'Yes. We realise classical and traditional designs faithfully, alongside contemporary work.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'auditorium-carpets', 'clubhouse-carpets'],
    relatedSolutions: ['custom-carpets', 'commercial-carpet-manufacturer'],
    relatedIndia: ['delhi-ncr', 'mumbai', 'lucknow'],
  },

  // ── Ahmedabad ───────────────────────────────────────────────────────────────
  {
    slug: 'ahmedabad',
    kind: 'india',
    label: 'Ahmedabad',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for Ahmedabad',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Ahmedabad\'s commercial, hospitality and premium residential projects.',
    seoTitle: 'Carpet Manufacturer for Ahmedabad | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Ahmedabad. Custom hand tufted, wall-to-wall and commercial carpets from our Bhadohi factory for offices, hotels, developers and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Ahmedabad', 'office carpet supplier Ahmedabad', 'custom rugs Ahmedabad', 'commercial carpet Ahmedabad', 'hotel carpet Ahmedabad'],
    h1: 'Carpet & Rug Manufacturer for Ahmedabad',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Ahmedabad — commercial developments, offices, hotels and premium residences. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Ahmedabad — a historic textile city with a strong entrepreneurial and commercial base and the emerging GIFT City hub — has growing demand for office, hospitality and premium residential flooring. As a manufacturer with textile roots ourselves, we make custom broadloom, contract carpets and bespoke rugs for the city\'s architects and developers, produced in Bhadohi.',
    sections: [
      { h2: 'Commercial & Office Supply', body: 'For Ahmedabad\'s commercial and office developments we manufacture durable custom broadloom and carpet tiles to specification.' },
      { h2: 'Hospitality & Premium Residential', body: 'For the city\'s hotels and premium homes we develop made-to-order contract carpets and bespoke rugs to exact colour and size.' },
    ],
    applications: [
      { title: 'Offices & Commercial', desc: 'Custom broadloom and tiles for Ahmedabad fit-outs.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets.' },
      { title: 'Premium Residential', desc: 'Bespoke rugs for premium homes.' },
      { title: 'Developers & Designers', desc: 'Coordinated custom supply to brief.' },
    ],
    whyPoints: [
      { title: 'Textile Heritage', desc: 'A manufacturer that understands cloth and craft.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and colour.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply commercial carpets in Ahmedabad?', a: 'Yes. We manufacture made-to-order broadloom and carpet tiles to specification in Bhadohi, for supply to Ahmedabad.' },
      { q: 'Can you supply hotels and premium residences?', a: 'Yes. We produce made-to-order contract carpets and bespoke rugs to exact colour and size.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you work with developers and designers?', a: 'Yes. We supply developers and designers directly, with samples approved before production.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'carpet-tiles'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'retail-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'custom-carpets'],
    relatedIndia: ['surat', 'mumbai', 'jaipur'],
  },

  // ── Jaipur ──────────────────────────────────────────────────────────────────
  {
    slug: 'jaipur',
    kind: 'india',
    label: 'Jaipur',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for Jaipur',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Jaipur\'s heritage hotels, palaces and luxury hospitality.',
    seoTitle: 'Carpet Manufacturer for Jaipur | Heritage & Luxury Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Jaipur. Custom hand knotted, hand tufted and hospitality carpets from our Bhadohi factory for heritage hotels, palaces, resorts and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Jaipur', 'heritage hotel carpet Jaipur', 'luxury rugs Jaipur', 'custom carpets Jaipur', 'palace carpet supplier Rajasthan'],
    h1: 'Carpet & Rug Manufacturer for Jaipur',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Jaipur — heritage hotels, palace conversions, luxury resorts and designers. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Jaipur is one of India\'s premier heritage-tourism and luxury-hospitality destinations, where palace hotels, boutique resorts and Rajasthani interiors call for rich, bespoke carpets. We develop opulent hand knotted rugs, custom hospitality carpets and heritage-inspired designs to exact colour and dimension, produced in Bhadohi.',
    sections: [
      { h2: 'Heritage & Palace Hospitality', body: 'For Jaipur\'s heritage and palace hotels we manufacture bespoke hand knotted and custom contract carpets — rich, intricate and specification-exact — realising traditional Rajasthani and classical motifs faithfully.' },
      { h2: 'Luxury Resorts & Designers', body: 'For the city\'s luxury resorts and interior designers we develop made-to-order rugs to exact colour, motif and size; technical requirements are specified per project.' },
    ],
    applications: [
      { title: 'Heritage & Palace Hotels', desc: 'Opulent bespoke carpets for Jaipur\'s heritage venues.' },
      { title: 'Luxury Resorts', desc: 'Made-to-order contract carpets to specification.' },
      { title: 'Interior Designers', desc: 'Bespoke heritage-inspired rugs to brief.' },
      { title: 'Palace Residences', desc: 'Custom rugs for luxury Rajasthani interiors.' },
    ],
    whyPoints: [
      { title: 'Heritage Craft', desc: 'Rich, intricate designs realised faithfully.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and motif.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply carpets for Jaipur heritage and palace hotels?', a: 'Yes. We manufacture bespoke hand knotted and custom contract carpets to exact design and dimension in Bhadohi, for supply to Jaipur.' },
      { q: 'Can you realise traditional Rajasthani motifs?', a: 'Yes. We faithfully realise heritage and classical motifs, with samples approved before production.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you supply luxury resorts?', a: 'Yes. We produce made-to-order contract carpets to specification for Jaipur hospitality.' },
      { q: 'Do you hold ready stock?', a: 'No. Every carpet and rug is made to your project\'s requirements.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'restaurant-carpets'],
    relatedSolutions: ['luxury-carpets', 'custom-carpets'],
    relatedIndia: ['delhi-ncr', 'ahmedabad', 'lucknow'],
  },

  // ── Surat ───────────────────────────────────────────────────────────────────
  {
    slug: 'surat',
    kind: 'india',
    label: 'Surat',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Surat',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Surat\'s commercial, hospitality and HNI residential projects.',
    seoTitle: 'Carpet Manufacturer for Surat | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Surat. Custom hand tufted, wall-to-wall and luxury rugs from our Bhadohi factory for commercial projects, hotels, HNI residences and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Surat', 'custom rugs Surat', 'luxury carpet Surat', 'commercial carpet Surat', 'hotel carpet Surat'],
    h1: 'Carpet & Rug Manufacturer for Surat',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Surat — commercial developments, hotels and high-net-worth residences. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Surat\'s diamond and textile wealth drives a strong market for premium residential interiors and commercial development, alongside growing hospitality. We make bespoke luxury rugs, custom broadloom and contract carpets for the city\'s designers and developers, produced in Bhadohi.',
    sections: [
      { h2: 'HNI Residential & Luxury Rugs', body: 'For Surat\'s affluent residences we develop bespoke luxury rugs — fine hand knotted and wool-silk — to exact colour, size and design.' },
      { h2: 'Commercial & Hospitality', body: 'For the city\'s commercial developments and hotels we manufacture custom broadloom and made-to-order contract carpets to specification.' },
    ],
    applications: [
      { title: 'HNI Residences', desc: 'Bespoke luxury rugs for Surat\'s premium homes.' },
      { title: 'Commercial Projects', desc: 'Custom broadloom for commercial developments.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets.' },
      { title: 'Interior Designers', desc: 'Bespoke rugs to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Luxury Craft', desc: 'Fine hand knotting and premium materials.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and colour.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply luxury rugs in Surat?', a: 'Yes. We manufacture bespoke hand knotted and wool-silk rugs to exact colour, size and design in Bhadohi, for supply to Surat.' },
      { q: 'Can you supply commercial and hospitality projects?', a: 'Yes. We make custom broadloom and made-to-order contract carpets to specification.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you work with Surat designers directly?', a: 'Yes. We supply designers and private clients directly, with samples approved before production.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'shaggy-rugs'],
    relatedIndustries: ['villa-carpets', 'hotel-carpets', 'office-carpets'],
    relatedSolutions: ['luxury-carpets', 'custom-carpets'],
    relatedIndia: ['ahmedabad', 'mumbai', 'jaipur'],
  },

  // ── Goa ─────────────────────────────────────────────────────────────────────
  {
    slug: 'goa',
    kind: 'india',
    label: 'Goa',
    heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Carpets & Rugs for Goa',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Goa\'s resorts, luxury villas and hospitality projects.',
    seoTitle: 'Carpet Manufacturer for Goa | Resort & Villa Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Goa. Custom hand tufted, natural-fibre and hospitality carpets from our Bhadohi factory for resorts, luxury villas, hotels and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Goa', 'resort carpet supplier Goa', 'villa rugs Goa', 'custom carpets Goa', 'hotel carpet Goa'],
    h1: 'Carpet & Rug Manufacturer for Goa',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Goa — beach and boutique resorts, luxury villas and hospitality projects. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Goa\'s tourism-driven economy centres on resorts, boutique hotels and a booming luxury-villa market, where relaxed, natural, characterful interiors prevail. We make resort and villa carpets, natural-fibre rugs and bespoke pieces for the region\'s designers and hospitality developers, produced in Bhadohi.',
    sections: [
      { h2: 'Resorts & Hospitality', body: 'For Goa\'s resorts and boutique hotels we manufacture made-to-order contract carpets and rugs to specification, in relaxed, characterful designs suited to coastal hospitality.' },
      { h2: 'Luxury Villas & Natural Fibres', body: 'For Goa\'s luxury villas we develop bespoke rugs and natural-fibre (jute, sisal) pieces to exact colour and size, matched to relaxed coastal interiors.' },
    ],
    applications: [
      { title: 'Resorts & Boutique Hotels', desc: 'Made-to-order carpets for Goa hospitality.' },
      { title: 'Luxury Villas', desc: 'Bespoke rugs for Goa\'s villa market.' },
      { title: 'Natural-Fibre Interiors', desc: 'Jute and sisal rugs for coastal schemes.' },
      { title: 'Interior Designers', desc: 'Characterful pieces to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Coastal Character', desc: 'Relaxed, natural, characterful designs.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply resort carpets in Goa?', a: 'Yes. We manufacture made-to-order contract carpets and rugs to specification in Bhadohi, for supply to Goa.' },
      { q: 'Can you make natural-fibre rugs for villas?', a: 'Yes. We craft jute, sisal and wool rugs to exact colour and size for Goa\'s villa interiors.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you work with hospitality developers?', a: 'Yes. We supply hospitality developers and designers directly, with samples approved before production.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is made to your project\'s requirements.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'hand-tufted-carpet', 'shaggy-rugs'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'spa-wellness-carpets'],
    relatedSolutions: ['custom-carpets', 'contract-carpet-supplier'],
    relatedIndia: ['mumbai', 'pune', 'bengaluru'],
  },

  // ── Lucknow ─────────────────────────────────────────────────────────────────
  {
    slug: 'lucknow',
    kind: 'india',
    label: 'Lucknow',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'Carpets & Rugs for Lucknow',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Lucknow\'s hospitality, government and heritage interiors.',
    seoTitle: 'Carpet Manufacturer for Lucknow | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Lucknow. Custom hand knotted, hand tufted and institutional carpets from our Bhadohi factory for hotels, government buildings, institutions and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Lucknow', 'government carpet supplier Lucknow', 'hotel carpet Lucknow', 'custom rugs Lucknow', 'institutional carpet UP'],
    h1: 'Carpet & Rug Manufacturer for Lucknow',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi — in the same Uttar Pradesh carpet belt — and produces for buyers across Lucknow: hotels, government and institutional buildings, and heritage interiors. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'As Uttar Pradesh\'s capital, Lucknow combines Nawabi heritage and refined hospitality with substantial government and institutional buildings. Being in the same state as our Bhadohi factory, we are well placed to make custom contract carpets, institutional flooring and bespoke rugs for the city\'s hotels, government projects and institutions.',
    sections: [
      { h2: 'Government & Institutional', body: 'For Lucknow\'s government and institutional buildings we manufacture made-to-order institutional and auditorium carpets to specification and tender requirements.' },
      { h2: 'Nawabi Hospitality & Heritage', body: 'For the city\'s hotels and heritage interiors we develop bespoke hand knotted rugs and contract carpets, realising refined, ornate designs where required.' },
    ],
    applications: [
      { title: 'Government & Institutions', desc: 'Made-to-order institutional carpets to spec.' },
      { title: 'Hotels & Hospitality', desc: 'Custom contract carpets for Lucknow hotels.' },
      { title: 'Heritage Interiors', desc: 'Bespoke ornate rugs to exact brief.' },
      { title: 'Auditoria & Halls', desc: 'Made-to-order auditorium carpets.' },
    ],
    whyPoints: [
      { title: 'Same-State Base', desc: 'Manufactured in Bhadohi, UP — nearby.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Tender-Ready', desc: 'Specification support for tender requirements.' },
    ],
    faqs: [
      { q: 'Do you supply government and institutional carpets in Lucknow?', a: 'Yes. We manufacture made-to-order institutional and auditorium carpets to specification and tender requirements in Bhadohi, for supply to Lucknow.' },
      { q: 'Can you supply Lucknow hotels?', a: 'Yes. We produce made-to-order contract carpets and bespoke rugs to specification.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Are you based near Lucknow?', a: 'We manufacture in Bhadohi, in the same state (Uttar Pradesh). We do not operate a retail showroom in Lucknow; we produce to order.' },
      { q: 'Do you hold ready stock?', a: 'No. Every carpet and rug is made to your project\'s requirements.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['government-carpets', 'hotel-carpets', 'auditorium-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'custom-carpets'],
    relatedIndia: ['delhi-ncr', 'kolkata', 'jaipur'],
  },

  // ── Kochi ───────────────────────────────────────────────────────────────────
  {
    slug: 'kochi',
    kind: 'india',
    label: 'Kochi',
    heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Carpets & Rugs for Kochi',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Kochi\'s hospitality, backwater resorts and commercial projects.',
    seoTitle: 'Carpet Manufacturer for Kochi | Resort & Hospitality Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Kochi. Custom hand tufted, natural-fibre and hospitality carpets from our Bhadohi factory for resorts, hotels, commercial projects and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Kochi', 'resort carpet supplier Kerala', 'hotel carpet Kochi', 'custom rugs Kochi', 'commercial carpet Kochi'],
    h1: 'Carpet & Rug Manufacturer for Kochi',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Kochi and Kerala — hotels, backwater resorts, commercial projects and designers. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Kochi anchors Kerala\'s tourism and hospitality economy — heritage hotels, backwater and beach resorts and growing commercial development, with interiors that favour natural materials and a relaxed tropical aesthetic. We make hospitality carpets, natural-fibre rugs and custom pieces for the region\'s designers and developers, produced in Bhadohi.',
    sections: [
      { h2: 'Hospitality & Resorts', body: 'For Kochi\'s hotels and backwater resorts we manufacture made-to-order contract carpets and rugs to specification, in relaxed designs suited to tropical hospitality.' },
      { h2: 'Natural Fibres & Commercial', body: 'For Kerala interiors we develop natural-fibre (jute, sisal, coir) rugs to exact size, plus custom carpets for commercial projects.' },
    ],
    applications: [
      { title: 'Hotels & Resorts', desc: 'Made-to-order carpets for Kochi hospitality.' },
      { title: 'Natural-Fibre Interiors', desc: 'Jute, sisal and coir rugs for tropical schemes.' },
      { title: 'Commercial Projects', desc: 'Custom broadloom for commercial fit-outs.' },
      { title: 'Interior Designers', desc: 'Bespoke pieces to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Tropical Materials', desc: 'Natural fibres suited to Kerala interiors.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply resort carpets in Kochi?', a: 'Yes. We manufacture made-to-order contract carpets and rugs to specification in Bhadohi, for supply to Kochi.' },
      { q: 'Can you make natural-fibre rugs?', a: 'Yes. We craft jute, sisal and coir rugs to exact size for Kerala interiors.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you work with Kerala hospitality developers?', a: 'Yes. We supply developers and designers directly, with samples approved before production.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is made to your project\'s requirements.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'coco-coir', 'hand-tufted-carpet'],
    relatedIndustries: ['hotel-carpets', 'spa-wellness-carpets', 'restaurant-carpets'],
    relatedSolutions: ['custom-carpets', 'contract-carpet-supplier'],
    relatedIndia: ['chennai', 'bengaluru', 'goa'],
  },

  // ── Chandigarh ──────────────────────────────────────────────────────────────
  {
    slug: 'chandigarh',
    kind: 'india',
    label: 'Chandigarh',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for Chandigarh',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Chandigarh\'s government, corporate and premium residential projects.',
    seoTitle: 'Carpet Manufacturer for Chandigarh | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Chandigarh. Custom office broadloom, hand tufted and modern rugs from our Bhadohi factory for government, corporates, hotels and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Chandigarh', 'office carpet supplier Chandigarh', 'government carpet Chandigarh', 'custom rugs Chandigarh', 'modern rugs Chandigarh'],
    h1: 'Carpet & Rug Manufacturer for Chandigarh',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Chandigarh and the tricity — government offices, corporates, hotels and premium residences. We make to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Chandigarh — India\'s planned, modernist city — pairs significant government and administrative demand with affluent residential neighbourhoods and a clean, design-conscious sensibility. We make custom office broadloom, government and institutional carpets, and modern bespoke rugs for the tricity\'s architects and procurement teams, produced in Bhadohi.',
    sections: [
      { h2: 'Government & Corporate', body: 'For Chandigarh\'s government and corporate buildings we manufacture made-to-order institutional and office carpets to specification and tender requirements.' },
      { h2: 'Modern Residential & Hospitality', body: 'For the city\'s affluent homes and hotels we develop modern, clean bespoke rugs and made-to-order hospitality carpets to exact colour and size.' },
    ],
    applications: [
      { title: 'Government & Institutions', desc: 'Made-to-order institutional carpets to spec.' },
      { title: 'Corporate Offices', desc: 'Custom broadloom for corporate fit-outs.' },
      { title: 'Premium Residential', desc: 'Modern bespoke rugs to exact brief.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets.' },
    ],
    whyPoints: [
      { title: 'Tender-Ready', desc: 'Specification support for tender requirements.' },
      { title: 'Clean, Modern Design', desc: 'Contemporary palettes to brief.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
    ],
    faqs: [
      { q: 'Do you supply government carpets in Chandigarh?', a: 'Yes. We manufacture made-to-order institutional and office carpets to specification and tender requirements in Bhadohi, for supply to Chandigarh.' },
      { q: 'Can you supply corporate and residential projects?', a: 'Yes. We make custom broadloom and modern bespoke rugs to exact colour and size.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you serve the wider tricity (Mohali, Panchkula)?', a: 'Yes. We produce for the Chandigarh tricity region, manufacturer-direct from Bhadohi.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'carpet-tiles'],
    relatedIndustries: ['government-carpets', 'office-carpets', 'hotel-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'modern-rugs'],
    relatedIndia: ['delhi-ncr', 'gurugram', 'jaipur'],
  },

  // ── Gurugram (NCR corporate/luxury sub-market) ──────────────────────────────
  {
    slug: 'gurugram',
    kind: 'india',
    label: 'Gurugram',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for Gurugram',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Gurugram\'s corporate towers, luxury hospitality and high-rise residential.',
    seoTitle: 'Carpet Manufacturer for Gurugram | Corporate & Luxury Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Gurugram (Gurgaon). Custom office broadloom, carpet tiles, hand knotted and luxury rugs from our Bhadohi factory for MNC offices, luxury hotels and high-rise residences. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Gurugram', 'office carpet supplier Gurgaon', 'corporate carpet Gurugram', 'luxury rugs Gurgaon', 'carpet tiles Gurugram'],
    h1: 'Carpet & Rug Manufacturer for Gurugram',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Gurugram — MNC corporate towers, luxury hotels and high-rise residential. We make to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Gurugram is the corporate heart of Delhi NCR — dense with multinational headquarters, Grade-A office towers, luxury hospitality and premium high-rise residential. We make custom office broadloom and carpet tiles, luxury hospitality carpets and bespoke residential rugs for the city\'s fit-out contractors and designers, produced in Bhadohi.',
    sections: [
      { h2: 'Corporate Fit-Outs', body: 'For Gurugram\'s MNC offices and Grade-A towers we manufacture durable custom broadloom and carpet tiles in modular, workspace-appropriate formats, made to specification and coordinated with fit-out schedules.' },
      { h2: 'Luxury Hospitality & High-Rise Residential', body: 'For the city\'s luxury hotels and premium apartments we develop made-to-order contract carpets and bespoke rugs to exact colour, size and specification.' },
    ],
    applications: [
      { title: 'MNC & Corporate Offices', desc: 'Custom broadloom and tiles for Gurugram towers.' },
      { title: 'Luxury Hotels', desc: 'Made-to-order contract carpets to specification.' },
      { title: 'High-Rise Residential', desc: 'Bespoke rugs for premium apartments.' },
      { title: 'Fit-Out Contractors', desc: 'Custom supply coordinated with project schedules.' },
    ],
    whyPoints: [
      { title: 'Scale & Consistency', desc: 'Bulk broadloom and tiles to a single specification.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and specification.' },
      { title: 'Manufacturer-Direct', desc: 'Produced in our own Bhadohi facility.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets and tiles in Gurugram?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification in Bhadohi, for supply to Gurugram.' },
      { q: 'Can you supply luxury hotels in Gurugram?', a: 'Yes. We produce made-to-order contract carpets to specification; fire-safety and technical requirements are specified per project.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Can production be coordinated with a fit-out schedule?', a: 'Yes. We coordinate production and dispatch with your installation programme where possible; details are agreed at the quotation stage.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is manufactured to your project\'s requirements.' },
    ],
    relatedProducts: ['carpet-tiles', 'wall-to-wall-carpets', 'hand-knotted-carpet'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'coworking-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'luxury-carpets'],
    relatedIndia: ['delhi-ncr', 'noida', 'mumbai'],
  },

  // ── Noida (NCR commercial/institutional sub-market) ─────────────────────────
  {
    slug: 'noida',
    kind: 'india',
    label: 'Noida',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Noida',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Noida\'s IT, commercial, institutional and residential projects.',
    seoTitle: 'Carpet Manufacturer for Noida | Office & Commercial Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Noida & Greater Noida. Custom office broadloom, carpet tiles, institutional and residential carpets from our Bhadohi factory for IT parks, institutions, hotels and developers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Noida', 'office carpet supplier Noida', 'commercial carpet Noida', 'carpet tiles Greater Noida', 'institutional carpet Noida'],
    h1: 'Carpet & Rug Manufacturer for Noida',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Noida and Greater Noida — IT parks, commercial and institutional buildings, media houses and residential developments. We make to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Noida and Greater Noida form a fast-growing commercial, IT, institutional and expo hub within Delhi NCR, with steady office, education and residential development. We make custom office broadloom and carpet tiles, institutional and auditorium carpets, and residential rugs for the region\'s developers and procurement teams, produced in Bhadohi.',
    sections: [
      { h2: 'IT, Commercial & Institutional', body: 'For Noida\'s IT parks, commercial buildings and institutions we manufacture durable custom broadloom, carpet tiles and institutional/auditorium carpets to specification and, where relevant, tender requirements.' },
      { h2: 'Residential & Hospitality', body: 'For the region\'s residential developments and hotels we develop made-to-order rugs and contract carpets to exact colour and size.' },
    ],
    applications: [
      { title: 'IT Parks & Offices', desc: 'Custom broadloom and tiles for Noida workspaces.' },
      { title: 'Institutions & Auditoria', desc: 'Made-to-order institutional carpets to spec.' },
      { title: 'Residential Developers', desc: 'Coordinated rug supply for developments.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets.' },
    ],
    whyPoints: [
      { title: 'Commercial-Ready', desc: 'Durable broadloom, tiles and institutional carpets.' },
      { title: 'Tender Support', desc: 'Specification support where required.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets in Noida?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification in Bhadohi, for supply to Noida and Greater Noida.' },
      { q: 'Can you supply institutional and auditorium carpets?', a: 'Yes. We produce made-to-order institutional and auditorium carpets to specification and tender requirements.' },
      { q: 'How are lead times decided?', a: 'Every order is made to order, so the timeline reflects design, size, quantity and finish and is confirmed at quotation.' },
      { q: 'Do you serve Greater Noida too?', a: 'Yes. We produce for Noida and Greater Noida, manufacturer-direct from Bhadohi.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is manufactured to your project\'s requirements.' },
    ],
    relatedProducts: ['carpet-tiles', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['office-carpets', 'auditorium-carpets', 'school-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'contract-carpet-supplier'],
    relatedIndia: ['delhi-ncr', 'gurugram', 'lucknow'],
  },
]
