import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// Pan-India commercial market landing pages — /india/[location]
//
// Business model, stated honestly on every page: Tapis Global International
// MANUFACTURES made-to-order carpets and rugs in Bhadohi, Uttar Pradesh, and
// SUPPLIES them to B2B buyers and projects in each city below. We are NOT a
// ready-stock retailer. Except for Bhadohi (our actual manufacturing base), no
// page claims a local office, showroom, warehouse, factory, staff, completed
// projects or customers in the city — pages describe the city's commercial
// demand and how we serve it from Bhadohi. No LocalBusiness schema is emitted
// for these cities (only WebPage + BreadcrumbList + FAQPage).
//
// Typical made-to-order production/dispatch timeline is ~3–4 weeks depending on
// design, size, quantity and specification — stated as a norm, never a guarantee.
// ─────────────────────────────────────────────────────────────────────────────

/** Shared hub intro (used by the /india hub page). */
export const INDIA_HUB_INTRO =
  'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi, Uttar Pradesh, and supplies commercial buyers and projects across India. We are a manufacturer and supplier — not a ready-stock retailer — producing to each project\'s design, size, colour, material, quality and quantity for architects, interior designers, hotels, developers, procurement teams and trade buyers nationwide.'

export const INDIA_LOCATIONS: SeoLanding[] = [
  // ── Delhi NCR (regional hub city; parent of Gurugram / Noida sub-markets) ──
  {
    slug: 'delhi-ncr',
    kind: 'india',
    label: 'Delhi NCR',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for Delhi NCR',
    tagline: 'Made-to-order carpet and rug manufacturer supplying architects, hotels, developers and procurement teams across Delhi NCR.',
    seoTitle: 'Carpet Manufacturer in Delhi NCR | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Delhi NCR. Custom hand tufted, hand knotted and wall-to-wall carpets from our Bhadohi factory for architects, hotels, corporates, developers and procurement teams. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Delhi NCR', 'custom carpet supplier Delhi', 'hotel carpet supplier Delhi', 'rug manufacturer Delhi NCR', 'commercial carpet Delhi'],
    h1: 'Carpet & Rug Manufacturer for Delhi NCR',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Delhi NCR — architects, interior designers, hotels, corporate offices, developers and procurement teams. We produce to your design, size and specification; we do not hold ready stock.',
    overview: 'Delhi NCR is India\'s largest concentrated commercial and institutional market — the capital\'s corporate headquarters, luxury and business hotels, government and diplomatic buildings, and premium residential development all specify carpet and rug at scale. As a manufacturer we serve this demand with custom hand tufted and hand knotted carpets, wall-to-wall broadloom and bespoke rugs, made to project requirements in Bhadohi and dispatched to NCR. Typical made-to-order production is around 3–4 weeks depending on design, size and quantity.',
    sections: [
      { h2: 'Made-to-Order for NCR Projects', body: 'From corporate fit-outs in central Delhi to luxury hotels and premium apartments across Gurugram and Noida, we manufacture to the architect\'s or designer\'s exact brief — colour, size, pile, construction and quantity — with samples approved before production. Nothing is off-the-shelf.' },
      { h2: 'Architects, Hospitality & Procurement', body: 'We work directly with NCR architects, interior designers, hospitality groups and procurement teams, supplying custom carpets and rugs for offices, hotels, banquet and residential projects, with fire-safety construction where a project specifies it.' },
    ],
    applications: [
      { title: 'Architects & Designers', desc: 'Custom carpets and rugs to exact NCR project briefs.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets for Delhi & Gurugram hotels.' },
      { title: 'Corporate & Offices', desc: 'Broadloom and tiles for NCR corporate fit-outs.' },
      { title: 'Developers & Procurement', desc: 'Coordinated custom supply for residential and commercial projects.' },
    ],
    whyPoints: [
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control from Bhadohi.' },
      { title: 'Fully Custom', desc: 'Made to your design, size, colour and quantity.' },
      { title: 'Project-Ready', desc: 'Samples, specification support and phased dispatch.' },
    ],
    faqs: [
      { q: 'Do you have a showroom or office in Delhi NCR?', a: 'We manufacture in Bhadohi and supply projects across Delhi NCR. We do not operate a ready-stock retail showroom; we work to order with samples, catalogues and specification support, and can arrange to present material to your project team.' },
      { q: 'Can you supply custom carpets for a Delhi or Gurugram hotel?', a: 'Yes. We manufacture made-to-order contract carpets to your design, size and specification, including fire-safety construction where required, and dispatch to NCR.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification. Exact timelines are confirmed at order.' },
      { q: 'Do you work with architects and procurement teams?', a: 'Yes. We supply architects, interior designers, developers and procurement teams directly, with samples and lab-dips approved before production.' },
      { q: 'Do you hold ready stock?', a: 'No. Every carpet and rug is manufactured to the specific requirements of your project — design, size, colour, material and quantity.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'wall-to-wall-carpets', 'hand-knotted-carpet'],
    relatedIndustries: ['hotel-carpets', 'office-carpets', 'banquet-hall-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'custom-carpets'],
    relatedIndia: ['gurugram', 'noida', 'jaipur'],
  },

  // ── Mumbai ──────────────────────────────────────────────────────────────────
  {
    slug: 'mumbai',
    kind: 'india',
    label: 'Mumbai',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for Mumbai',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Mumbai\'s luxury residential, five-star hospitality and corporate projects.',
    seoTitle: 'Carpet Manufacturer in Mumbai | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Mumbai. Custom hand knotted, hand tufted and wall-to-wall carpets from our Bhadohi factory for luxury residences, five-star hotels, corporates and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Mumbai', 'custom rug supplier Mumbai', 'luxury carpet Mumbai', 'hotel carpet supplier Mumbai', 'designer rugs Mumbai'],
    h1: 'Carpet & Rug Manufacturer for Mumbai',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Mumbai — luxury residences, five-star hospitality, corporate offices and design studios. We produce to your exact brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'As India\'s financial capital, Mumbai concentrates high-value luxury residential towers, flagship five-star hotels and premium corporate interiors where specification and finish matter enormously. As a manufacturer we develop bespoke hand knotted and hand tufted rugs, luxury custom pieces and contract carpets to designer briefs, made in Bhadohi and dispatched to Mumbai — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Luxury Residential & Design', body: 'Mumbai\'s premium apartments and villas call for refined, bespoke rugs. We develop fine hand knotted and wool-silk pieces to exact colour, size and design for the city\'s interior designers and private clients.' },
      { h2: 'Five-Star Hospitality & Corporate', body: 'For Mumbai\'s luxury hotels and corporate headquarters we manufacture made-to-order contract carpets — durable, design-led and specification-exact — with fire-safety construction where required.' },
    ],
    applications: [
      { title: 'Luxury Residential', desc: 'Bespoke rugs for Mumbai\'s premium homes and towers.' },
      { title: 'Five-Star Hotels', desc: 'Made-to-order contract carpets for flagship hospitality.' },
      { title: 'Corporate Interiors', desc: 'Custom broadloom for premium office fit-outs.' },
      { title: 'Interior Designers', desc: 'Fine bespoke pieces to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Refined Craft', desc: 'Fine hand knotting and premium materials.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and colour.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply luxury rugs in Mumbai?', a: 'Yes. We manufacture bespoke hand knotted and wool-silk rugs to exact colour, size and design, made in Bhadohi and dispatched to Mumbai. We do not hold ready stock.' },
      { q: 'Can you supply carpets for a Mumbai five-star hotel?', a: 'Yes. We produce made-to-order contract carpets to specification, including fire-safety construction where required.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you work with Mumbai interior designers directly?', a: 'Yes. We work directly with designers and private clients, with lab-dips and samples approved before production.' },
      { q: 'Are you a retail carpet store?', a: 'No. We are a manufacturer and supplier producing made-to-order carpets and rugs for projects and trade buyers.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'leather-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'office-carpets'],
    relatedSolutions: ['luxury-carpets', 'designer-rugs'],
    relatedIndia: ['pune', 'ahmedabad', 'goa'],
  },

  // ── Bengaluru ───────────────────────────────────────────────────────────────
  {
    slug: 'bengaluru',
    kind: 'india',
    label: 'Bengaluru',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Bengaluru',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Bengaluru\'s tech campuses, coworking, hospitality and modern residential projects.',
    seoTitle: 'Carpet Manufacturer in Bengaluru | Office & Custom Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Bengaluru. Custom office broadloom, carpet tiles, hand tufted and modern rugs from our Bhadohi factory for tech campuses, coworking, hotels and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Bengaluru', 'office carpet supplier Bangalore', 'carpet tiles Bengaluru', 'custom rugs Bangalore', 'commercial carpet Bengaluru'],
    h1: 'Carpet & Rug Manufacturer for Bengaluru',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Bengaluru — tech campuses, coworking operators, hospitality and modern residential projects. Everything is produced to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Bengaluru\'s vast IT and startup economy drives sustained demand for office broadloom, carpet tiles and coworking flooring, alongside a modern residential and boutique-hospitality market that favours contemporary design. As a manufacturer we supply custom office carpets, carpet tiles and contemporary rugs to the city\'s architects and fit-out contractors, made in Bhadohi and dispatched to Bengaluru — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Workspace & Coworking Flooring', body: 'For Bengaluru\'s tech campuses and coworking spaces we manufacture durable custom broadloom and carpet tiles in modular, easy-maintenance formats and current palettes, made to specification.' },
      { h2: 'Modern Residential & Hospitality', body: 'For the city\'s contemporary homes and boutique hotels we develop modern and contemporary rugs to exact colour and size, plus made-to-order hospitality carpets.' },
    ],
    applications: [
      { title: 'Tech Campuses & Offices', desc: 'Custom broadloom and carpet tiles for workspaces.' },
      { title: 'Coworking Operators', desc: 'Durable, modular flooring for coworking floors.' },
      { title: 'Hospitality', desc: 'Made-to-order carpets for boutique hotels.' },
      { title: 'Modern Residential', desc: 'Contemporary rugs to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Workspace-Ready', desc: 'Durable broadloom and tiles for high traffic.' },
      { title: 'Contemporary Design', desc: 'Modern palettes and patterns to brief.' },
      { title: 'Fully Custom', desc: 'Made to your size, colour and quantity.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets and tiles in Bengaluru?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification, produced in Bhadohi and dispatched to Bengaluru.' },
      { q: 'Can you supply coworking and tech campus fit-outs?', a: 'Yes. We provide durable, modular custom carpet for high-traffic workspaces, made to your requirement.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you make modern residential rugs?', a: 'Yes. We develop contemporary rugs to exact colour and size for Bengaluru homes.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is manufactured to your project\'s design, size, material and quantity.' },
    ],
    relatedProducts: ['carpet-tiles', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['office-carpets', 'coworking-carpets', 'hotel-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'modern-rugs'],
    relatedIndia: ['hyderabad', 'chennai', 'pune'],
  },

  // ── Hyderabad ───────────────────────────────────────────────────────────────
  {
    slug: 'hyderabad',
    kind: 'india',
    label: 'Hyderabad',
    heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Carpets & Rugs for Hyderabad',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Hyderabad\'s IT corridors, hospitality and heritage-luxury interiors.',
    seoTitle: 'Carpet Manufacturer in Hyderabad | Custom & Office Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Hyderabad. Custom office broadloom, tiles, hand knotted and hospitality carpets from our Bhadohi factory for HITEC City, hotels, palaces and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Hyderabad', 'office carpet supplier Hyderabad', 'hotel carpet Hyderabad', 'custom rugs Hyderabad', 'commercial carpet HITEC City'],
    h1: 'Carpet & Rug Manufacturer for Hyderabad',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Hyderabad — IT-corridor offices, hotels, and the city\'s distinctive heritage-luxury interiors. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Hyderabad pairs a large IT corridor (HITEC City, Gachibowli) generating office and coworking demand with a hospitality sector and a heritage-luxury tradition rooted in the city\'s palatial interiors. As a manufacturer we supply custom office carpets and tiles, contract hospitality carpets and opulent hand knotted rugs, made in Bhadohi and dispatched to Hyderabad — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'IT Corridor & Commercial', body: 'For Hyderabad\'s office parks and coworking spaces we manufacture durable custom broadloom and carpet tiles to specification, in contemporary, workspace-appropriate designs.' },
      { h2: 'Hospitality & Heritage Luxury', body: 'For the city\'s hotels and heritage-luxury interiors we develop bespoke hand knotted rugs and made-to-order contract carpets, rich or restrained, to exact colour and dimension.' },
    ],
    applications: [
      { title: 'IT & Office Parks', desc: 'Custom broadloom and tiles for HITEC City workspaces.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets for Hyderabad hotels.' },
      { title: 'Heritage-Luxury Interiors', desc: 'Opulent hand knotted rugs to exact brief.' },
      { title: 'Interior Designers', desc: 'Bespoke pieces for residential and commercial schemes.' },
    ],
    whyPoints: [
      { title: 'Custom Craft', desc: 'From workspace tiles to opulent hand knots.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets in Hyderabad?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification, produced in Bhadohi and dispatched to Hyderabad.' },
      { q: 'Can you make opulent hand knotted rugs for heritage interiors?', a: 'Yes. We craft bespoke hand knotted rugs to exact colour, motif and dimension.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you supply hotels and hospitality projects?', a: 'Yes. We produce made-to-order contract carpets to specification for Hyderabad hospitality.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'carpet-tiles', 'wall-to-wall-carpets'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'villa-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'luxury-carpets'],
    relatedIndia: ['bengaluru', 'chennai', 'mumbai'],
  },

  // ── Chennai ─────────────────────────────────────────────────────────────────
  {
    slug: 'chennai',
    kind: 'india',
    label: 'Chennai',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'Carpets & Rugs for Chennai',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Chennai\'s hospitality, commercial and residential projects.',
    seoTitle: 'Carpet Manufacturer in Chennai | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Chennai. Custom hand tufted, wall-to-wall and hospitality carpets from our Bhadohi factory for hotels, offices, developers and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Chennai', 'hotel carpet supplier Chennai', 'office carpet Chennai', 'custom rugs Chennai', 'commercial carpet Chennai'],
    h1: 'Carpet & Rug Manufacturer for Chennai',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Chennai — hotels, commercial developments, offices and residential projects. We produce to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Chennai combines a substantial manufacturing and commercial base with a steady hospitality sector and residential growth along its expanding corridors. As a manufacturer we supply made-to-order hospitality carpets, office broadloom and bespoke rugs to the city\'s architects, developers and procurement teams, produced in Bhadohi and dispatched to Chennai — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Hospitality & Commercial Supply', body: 'For Chennai\'s hotels, offices and commercial developments we manufacture durable made-to-order carpets to specification, with fire-safety construction where a project requires it.' },
      { h2: 'Residential & Designer Rugs', body: 'For Chennai designers and residential projects we develop bespoke rugs to exact colour and size, from traditional to contemporary.' },
    ],
    applications: [
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets for Chennai hotels.' },
      { title: 'Offices & Commercial', desc: 'Custom broadloom and tiles for commercial fit-outs.' },
      { title: 'Developers & Procurement', desc: 'Coordinated custom supply for projects.' },
      { title: 'Interior Designers', desc: 'Bespoke rugs to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Contract-Ready', desc: 'Durable carpets built to specification.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and colour.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply hotel carpets in Chennai?', a: 'Yes. We manufacture made-to-order contract carpets to specification, produced in Bhadohi and dispatched to Chennai.' },
      { q: 'Can you supply office and commercial fit-outs?', a: 'Yes. We provide custom broadloom and carpet tiles for Chennai commercial projects.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you work with Chennai designers and developers?', a: 'Yes. We supply designers, developers and procurement teams directly, with samples approved before production.' },
      { q: 'Do you hold ready stock?', a: 'No. Every carpet and rug is made to your project\'s requirements.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'jute-sisal-rugs'],
    relatedIndustries: ['hotel-carpets', 'office-carpets', 'restaurant-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'contract-carpet-supplier'],
    relatedIndia: ['bengaluru', 'kochi', 'hyderabad'],
  },

  // ── Kolkata ─────────────────────────────────────────────────────────────────
  {
    slug: 'kolkata',
    kind: 'india',
    label: 'Kolkata',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Carpets & Rugs for Kolkata',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Kolkata\'s hospitality, heritage interiors and cultural institutions.',
    seoTitle: 'Carpet Manufacturer in Kolkata | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Kolkata. Custom hand knotted, hand tufted and hospitality carpets from our Bhadohi factory for hotels, clubs, institutions and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Kolkata', 'hotel carpet supplier Kolkata', 'custom rugs Kolkata', 'club carpet Kolkata', 'commercial carpet Kolkata'],
    h1: 'Carpet & Rug Manufacturer for Kolkata',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Kolkata — hotels, heritage clubs, cultural institutions and residential projects. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Kolkata\'s deep cultural heritage shapes a market that values traditional craft, rich interiors and institutional grandeur — heritage hotels, gentlemen\'s clubs, auditoria and cultural buildings, alongside contemporary commercial growth. As a manufacturer we supply bespoke hand knotted rugs, made-to-order hospitality carpets and auditorium/institutional carpets, produced in Bhadohi and dispatched to Kolkata — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Heritage & Institutional Interiors', body: 'For Kolkata\'s heritage hotels, clubs, auditoria and cultural institutions we manufacture bespoke and contract carpets to exact design and dimension, honouring traditional aesthetics where required.' },
      { h2: 'Hospitality & Residential', body: 'For the city\'s hotels and residences we develop made-to-order rugs and carpets to specification, from classical to contemporary.' },
    ],
    applications: [
      { title: 'Heritage Hotels & Clubs', desc: 'Bespoke carpets for Kolkata\'s heritage venues.' },
      { title: 'Cultural Institutions', desc: 'Made-to-order auditorium and institutional carpets.' },
      { title: 'Hospitality', desc: 'Custom contract carpets for hotels.' },
      { title: 'Interior Designers', desc: 'Bespoke rugs to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Traditional Craft', desc: 'Classical designs realised faithfully.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply carpets for Kolkata heritage hotels and clubs?', a: 'Yes. We manufacture bespoke and contract carpets to exact design and dimension, produced in Bhadohi and dispatched to Kolkata.' },
      { q: 'Can you make auditorium and institutional carpets?', a: 'Yes. We produce made-to-order auditorium and institutional carpets to specification.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you make traditional designs?', a: 'Yes. We realise classical and traditional designs faithfully, alongside contemporary work.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'auditorium-carpets', 'clubhouse-carpets'],
    relatedSolutions: ['custom-carpets', 'commercial-carpet-manufacturer'],
    relatedIndia: ['delhi-ncr', 'mumbai', 'lucknow'],
  },

  // ── Pune ────────────────────────────────────────────────────────────────────
  {
    slug: 'pune',
    kind: 'india',
    label: 'Pune',
    heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Carpets & Rugs for Pune',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Pune\'s offices, residential real estate and hospitality projects.',
    seoTitle: 'Carpet Manufacturer in Pune | Office & Custom Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Pune. Custom office broadloom, tiles, hand tufted and residential rugs from our Bhadohi factory for offices, developers, hotels and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Pune', 'office carpet supplier Pune', 'custom rugs Pune', 'residential carpet Pune', 'commercial carpet Pune'],
    h1: 'Carpet & Rug Manufacturer for Pune',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Pune — offices, residential developers, hotels and designers. We produce to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Pune combines a strong IT and automotive economy with one of India\'s most active residential real-estate markets and a growing hospitality sector. As a manufacturer we supply custom office broadloom and tiles, residential rugs for new developments, and made-to-order hospitality carpets, produced in Bhadohi and dispatched to Pune — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Offices & Commercial', body: 'For Pune\'s office parks and commercial fit-outs we manufacture durable custom broadloom and carpet tiles to specification.' },
      { h2: 'Residential Real Estate & Hospitality', body: 'For Pune\'s residential developers and hotels we develop made-to-order rugs and contract carpets to exact colour and size, coordinated with project timelines.' },
    ],
    applications: [
      { title: 'Offices & IT Parks', desc: 'Custom broadloom and tiles for Pune workspaces.' },
      { title: 'Residential Developers', desc: 'Coordinated rug supply for new developments.' },
      { title: 'Hospitality', desc: 'Made-to-order carpets for Pune hotels.' },
      { title: 'Interior Designers', desc: 'Bespoke rugs to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Workspace-Ready', desc: 'Durable broadloom and tiles to spec.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets in Pune?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification, produced in Bhadohi and dispatched to Pune.' },
      { q: 'Can you coordinate rug supply for residential developers?', a: 'Yes. We provide custom rugs and carpets coordinated with your project timeline.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you supply hotels in Pune?', a: 'Yes. We produce made-to-order contract carpets to specification for Pune hospitality.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is made to your project\'s requirements.' },
    ],
    relatedProducts: ['carpet-tiles', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['office-carpets', 'apartment-carpets', 'hotel-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'custom-carpets'],
    relatedIndia: ['mumbai', 'bengaluru', 'ahmedabad'],
  },

  // ── Ahmedabad ───────────────────────────────────────────────────────────────
  {
    slug: 'ahmedabad',
    kind: 'india',
    label: 'Ahmedabad',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for Ahmedabad',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Ahmedabad\'s commercial, hospitality and premium residential projects.',
    seoTitle: 'Carpet Manufacturer in Ahmedabad | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Ahmedabad. Custom hand tufted, wall-to-wall and commercial carpets from our Bhadohi factory for offices, hotels, developers and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Ahmedabad', 'office carpet supplier Ahmedabad', 'custom rugs Ahmedabad', 'commercial carpet Ahmedabad', 'hotel carpet Ahmedabad'],
    h1: 'Carpet & Rug Manufacturer for Ahmedabad',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Ahmedabad — commercial developments, offices, hotels and premium residences. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Ahmedabad — a historic textile city with a strong entrepreneurial and commercial base and the emerging GIFT City hub — has growing demand for office, hospitality and premium residential flooring. As a manufacturer with textile roots ourselves, we supply custom broadloom, contract carpets and bespoke rugs to the city\'s architects and developers, produced in Bhadohi and dispatched to Ahmedabad — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Commercial & Office Supply', body: 'For Ahmedabad\'s commercial and office developments we manufacture durable custom broadloom and carpet tiles to specification.' },
      { h2: 'Hospitality & Premium Residential', body: 'For the city\'s hotels and premium homes we develop made-to-order contract carpets and bespoke rugs to exact colour and size.' },
    ],
    applications: [
      { title: 'Offices & Commercial', desc: 'Custom broadloom and tiles for Ahmedabad fit-outs.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets.' },
      { title: 'Premium Residential', desc: 'Bespoke rugs for premium homes.' },
      { title: 'Developers & Designers', desc: 'Coordinated custom supply to brief.' },
    ],
    whyPoints: [
      { title: 'Textile Heritage', desc: 'A manufacturer that understands cloth and craft.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and colour.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply commercial carpets in Ahmedabad?', a: 'Yes. We manufacture made-to-order broadloom and carpet tiles to specification, produced in Bhadohi and dispatched to Ahmedabad.' },
      { q: 'Can you supply hotels and premium residences?', a: 'Yes. We produce made-to-order contract carpets and bespoke rugs to exact colour and size.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you work with developers and designers?', a: 'Yes. We supply developers and designers directly, with samples approved before production.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'carpet-tiles'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'retail-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'custom-carpets'],
    relatedIndia: ['surat', 'mumbai', 'jaipur'],
  },

  // ── Jaipur ──────────────────────────────────────────────────────────────────
  {
    slug: 'jaipur',
    kind: 'india',
    label: 'Jaipur',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for Jaipur',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Jaipur\'s heritage hotels, palaces and luxury hospitality.',
    seoTitle: 'Carpet Manufacturer in Jaipur | Heritage & Luxury Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Jaipur. Custom hand knotted, hand tufted and hospitality carpets from our Bhadohi factory for heritage hotels, palaces, resorts and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Jaipur', 'heritage hotel carpet Jaipur', 'luxury rugs Jaipur', 'custom carpets Jaipur', 'palace carpet supplier Rajasthan'],
    h1: 'Carpet & Rug Manufacturer for Jaipur',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Jaipur — heritage hotels, palace conversions, luxury resorts and designers. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Jaipur is one of India\'s premier heritage-tourism and luxury-hospitality destinations, where palace hotels, boutique resorts and Rajasthani interiors demand rich, bespoke carpets. As a manufacturer we develop opulent hand knotted rugs, custom hospitality carpets and heritage-inspired designs to exact colour and dimension, produced in Bhadohi and dispatched to Jaipur — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Heritage & Palace Hospitality', body: 'For Jaipur\'s heritage and palace hotels we manufacture bespoke hand knotted and custom contract carpets — rich, intricate and specification-exact — realising traditional Rajasthani and classical motifs faithfully.' },
      { h2: 'Luxury Resorts & Designers', body: 'For the city\'s luxury resorts and interior designers we develop made-to-order rugs to exact colour, motif and size, with fire-safety construction where required.' },
    ],
    applications: [
      { title: 'Heritage & Palace Hotels', desc: 'Opulent bespoke carpets for Jaipur\'s heritage venues.' },
      { title: 'Luxury Resorts', desc: 'Made-to-order contract carpets to specification.' },
      { title: 'Interior Designers', desc: 'Bespoke heritage-inspired rugs to brief.' },
      { title: 'Palace Residences', desc: 'Custom rugs for luxury Rajasthani interiors.' },
    ],
    whyPoints: [
      { title: 'Heritage Craft', desc: 'Rich, intricate designs realised faithfully.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and motif.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply carpets for Jaipur heritage and palace hotels?', a: 'Yes. We manufacture bespoke hand knotted and custom contract carpets to exact design and dimension, produced in Bhadohi and dispatched to Jaipur.' },
      { q: 'Can you realise traditional Rajasthani motifs?', a: 'Yes. We faithfully realise heritage and classical motifs, with samples approved before production.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you supply luxury resorts?', a: 'Yes. We produce made-to-order contract carpets to specification for Jaipur hospitality.' },
      { q: 'Do you hold ready stock?', a: 'No. Every carpet and rug is made to your project\'s requirements.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'restaurant-carpets'],
    relatedSolutions: ['luxury-carpets', 'custom-carpets'],
    relatedIndia: ['delhi-ncr', 'ahmedabad', 'lucknow'],
  },

  // ── Surat ───────────────────────────────────────────────────────────────────
  {
    slug: 'surat',
    kind: 'india',
    label: 'Surat',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Surat',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Surat\'s commercial, hospitality and HNI residential projects.',
    seoTitle: 'Carpet Manufacturer in Surat | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Surat. Custom hand tufted, wall-to-wall and luxury rugs from our Bhadohi factory for commercial projects, hotels, HNI residences and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Surat', 'custom rugs Surat', 'luxury carpet Surat', 'commercial carpet Surat', 'hotel carpet Surat'],
    h1: 'Carpet & Rug Manufacturer for Surat',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Surat — commercial developments, hotels and high-net-worth residences. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Surat\'s diamond and textile wealth drives a strong market for premium residential interiors and commercial development, alongside growing hospitality. As a manufacturer we supply bespoke luxury rugs, custom broadloom and contract carpets to the city\'s designers and developers, produced in Bhadohi and dispatched to Surat — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'HNI Residential & Luxury Rugs', body: 'For Surat\'s affluent residences we develop bespoke luxury rugs — fine hand knotted and wool-silk — to exact colour, size and design.' },
      { h2: 'Commercial & Hospitality', body: 'For the city\'s commercial developments and hotels we manufacture custom broadloom and made-to-order contract carpets to specification.' },
    ],
    applications: [
      { title: 'HNI Residences', desc: 'Bespoke luxury rugs for Surat\'s premium homes.' },
      { title: 'Commercial Projects', desc: 'Custom broadloom for commercial developments.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets.' },
      { title: 'Interior Designers', desc: 'Bespoke rugs to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Luxury Craft', desc: 'Fine hand knotting and premium materials.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and colour.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply luxury rugs in Surat?', a: 'Yes. We manufacture bespoke hand knotted and wool-silk rugs to exact colour, size and design, produced in Bhadohi and dispatched to Surat.' },
      { q: 'Can you supply commercial and hospitality projects?', a: 'Yes. We produce custom broadloom and made-to-order contract carpets to specification.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you work with Surat designers directly?', a: 'Yes. We supply designers and private clients directly, with samples approved before production.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'shaggy-rugs'],
    relatedIndustries: ['villa-carpets', 'hotel-carpets', 'office-carpets'],
    relatedSolutions: ['luxury-carpets', 'custom-carpets'],
    relatedIndia: ['ahmedabad', 'mumbai', 'jaipur'],
  },

  // ── Goa ─────────────────────────────────────────────────────────────────────
  {
    slug: 'goa',
    kind: 'india',
    label: 'Goa',
    heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Carpets & Rugs for Goa',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Goa\'s resorts, luxury villas and hospitality projects.',
    seoTitle: 'Carpet Manufacturer for Goa | Resort & Villa Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Goa. Custom hand tufted, natural-fibre and hospitality carpets from our Bhadohi factory for resorts, luxury villas, hotels and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Goa', 'resort carpet supplier Goa', 'villa rugs Goa', 'custom carpets Goa', 'hotel carpet Goa'],
    h1: 'Carpet & Rug Manufacturer for Goa',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Goa — beach and boutique resorts, luxury villas and hospitality projects. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Goa\'s tourism-driven economy centres on resorts, boutique hotels and a booming luxury-villa market, where relaxed, natural, characterful interiors prevail. As a manufacturer we supply made-to-order resort and villa carpets, natural-fibre rugs and bespoke pieces to the region\'s designers and hospitality developers, produced in Bhadohi and dispatched to Goa — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Resorts & Hospitality', body: 'For Goa\'s resorts and boutique hotels we manufacture made-to-order contract carpets and rugs to specification, in relaxed, characterful designs suited to coastal hospitality.' },
      { h2: 'Luxury Villas & Natural Fibres', body: 'For Goa\'s luxury villas we develop bespoke rugs and natural-fibre (jute, sisal) pieces to exact colour and size, matched to relaxed coastal interiors.' },
    ],
    applications: [
      { title: 'Resorts & Boutique Hotels', desc: 'Made-to-order carpets for Goa hospitality.' },
      { title: 'Luxury Villas', desc: 'Bespoke rugs for Goa\'s villa market.' },
      { title: 'Natural-Fibre Interiors', desc: 'Jute and sisal rugs for coastal schemes.' },
      { title: 'Interior Designers', desc: 'Characterful pieces to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Coastal Character', desc: 'Relaxed, natural, characterful designs.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply resort carpets in Goa?', a: 'Yes. We manufacture made-to-order contract carpets and rugs to specification, produced in Bhadohi and dispatched to Goa.' },
      { q: 'Can you make natural-fibre rugs for villas?', a: 'Yes. We craft jute, sisal and wool rugs to exact colour and size for Goa\'s villa interiors.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you work with hospitality developers?', a: 'Yes. We supply hospitality developers and designers directly, with samples approved before production.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is made to your project\'s requirements.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'hand-tufted-carpet', 'shaggy-rugs'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'spa-wellness-carpets'],
    relatedSolutions: ['custom-carpets', 'contract-carpet-supplier'],
    relatedIndia: ['mumbai', 'pune', 'bengaluru'],
  },

  // ── Lucknow ─────────────────────────────────────────────────────────────────
  {
    slug: 'lucknow',
    kind: 'india',
    label: 'Lucknow',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'Carpets & Rugs for Lucknow',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Lucknow\'s hospitality, government and heritage interiors.',
    seoTitle: 'Carpet Manufacturer in Lucknow | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Lucknow. Custom hand knotted, hand tufted and institutional carpets from our Bhadohi factory for hotels, government buildings, institutions and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Lucknow', 'government carpet supplier Lucknow', 'hotel carpet Lucknow', 'custom rugs Lucknow', 'institutional carpet UP'],
    h1: 'Carpet & Rug Manufacturer for Lucknow',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi — in the same Uttar Pradesh carpet belt — and supplies buyers across Lucknow: hotels, government and institutional buildings, and heritage interiors. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'As Uttar Pradesh\'s capital, Lucknow combines Nawabi heritage and refined hospitality with substantial government and institutional buildings. Being in the same state as our Bhadohi factory, we are well placed to supply the city\'s hotels, government projects and institutions with custom contract carpets, institutional flooring and bespoke rugs — typically around 3–4 weeks for made-to-order production depending on the order.',
    sections: [
      { h2: 'Government & Institutional', body: 'For Lucknow\'s government and institutional buildings we manufacture made-to-order institutional and auditorium carpets to specification and tender requirements.' },
      { h2: 'Nawabi Hospitality & Heritage', body: 'For the city\'s hotels and heritage interiors we develop bespoke hand knotted rugs and contract carpets, realising refined, ornate designs where required.' },
    ],
    applications: [
      { title: 'Government & Institutions', desc: 'Made-to-order institutional carpets to spec.' },
      { title: 'Hotels & Hospitality', desc: 'Custom contract carpets for Lucknow hotels.' },
      { title: 'Heritage Interiors', desc: 'Bespoke ornate rugs to exact brief.' },
      { title: 'Auditoria & Halls', desc: 'Made-to-order auditorium carpets.' },
    ],
    whyPoints: [
      { title: 'Same-State Base', desc: 'Manufactured in Bhadohi, UP — nearby.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Tender-Ready', desc: 'Documentation and specification support.' },
    ],
    faqs: [
      { q: 'Do you supply government and institutional carpets in Lucknow?', a: 'Yes. We manufacture made-to-order institutional and auditorium carpets to specification and tender requirements, produced in Bhadohi and dispatched to Lucknow.' },
      { q: 'Can you supply Lucknow hotels?', a: 'Yes. We produce made-to-order contract carpets and bespoke rugs to specification.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Are you based near Lucknow?', a: 'We manufacture in Bhadohi, in the same state (Uttar Pradesh). We do not operate a retail showroom in Lucknow; we supply to order.' },
      { q: 'Do you hold ready stock?', a: 'No. Every carpet and rug is made to your project\'s requirements.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['government-carpets', 'hotel-carpets', 'auditorium-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'custom-carpets'],
    relatedIndia: ['delhi-ncr', 'kolkata', 'jaipur'],
  },

  // ── Bhadohi (actual manufacturing base) ─────────────────────────────────────
  {
    slug: 'bhadohi',
    kind: 'india',
    label: 'Bhadohi',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Our Manufacturing Base',
    tagline: 'Carpet and rug manufacturer based in Bhadohi — India\'s carpet belt — supplying buyers, exporters and trade sourcing at source.',
    seoTitle: 'Carpet Manufacturer in Bhadohi | Manufacturing Base — Tapis Global International',
    seoDescription: 'Tapis Global International is a carpet and rug manufacturer based in Bhadohi, Uttar Pradesh — India\'s carpet-weaving belt. Made-to-order hand knotted, hand tufted and custom carpets for trade buyers, exporters and projects sourcing at source. Request a catalogue.',
    seoKeywords: ['carpet manufacturer Bhadohi', 'Bhadohi carpet supplier', 'hand knotted carpet Bhadohi', 'rug manufacturer Bhadohi', 'carpet belt India manufacturer'],
    h1: 'Carpet & Rug Manufacturer in Bhadohi',
    intro: 'Bhadohi is our home. Tapis Global International manufactures made-to-order carpets and rugs here, in Uttar Pradesh\'s historic carpet-weaving belt, supplying trade buyers, exporters and projects that prefer to source directly at the point of production.',
    overview: 'Bhadohi — often called the carpet city of India — is the country\'s largest hand-knotted and hand-tufted carpet manufacturing cluster, and the location of our production. Sourcing here means buying manufacturer-direct at source: full control over design, materials, construction and quality, without intermediaries. We produce hand knotted, hand tufted, wall-to-wall and custom carpets to order, for domestic trade, projects and export. Typical made-to-order production is around 3–4 weeks depending on design, size and quantity.',
    sections: [
      { h2: 'Sourcing at Source', body: 'Buyers and trade sourcing from Bhadohi work directly with the maker — reviewing materials, construction and samples, and specifying design, size and quality without layers of intermediaries. As a Bhadohi manufacturer, that is exactly how we operate.' },
      { h2: 'The Bhadohi Carpet Belt', body: 'The region\'s generations-deep weaving skill underpins the quality of Indian handmade carpets. We draw on this local craft base to produce hand knotted and hand tufted carpets to exacting, made-to-order specification.' },
    ],
    applications: [
      { title: 'Trade & Wholesale Buyers', desc: 'Manufacturer-direct sourcing at source in Bhadohi.' },
      { title: 'Exporters & Importers', desc: 'Made-to-order production for export programmes.' },
      { title: 'Projects & Procurement', desc: 'Custom carpets specified directly with the maker.' },
      { title: 'Designers', desc: 'Bespoke development at the point of production.' },
    ],
    whyPoints: [
      { title: 'At Source', desc: 'Buy manufacturer-direct in the carpet belt.' },
      { title: 'Full Control', desc: 'Design, material, construction and quality.' },
      { title: 'Made to Order', desc: 'Your specification and quantity.' },
    ],
    faqs: [
      { q: 'Are you actually based in Bhadohi?', a: 'Yes. Bhadohi, Uttar Pradesh is our manufacturing base — India\'s carpet-weaving belt. We produce hand knotted, hand tufted and custom carpets to order here.' },
      { q: 'Can trade buyers source directly from Bhadohi?', a: 'Yes. We work manufacturer-direct with trade buyers, exporters and projects sourcing at source, with samples and specification support.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you export from Bhadohi?', a: 'Yes. We manufacture in Bhadohi and export worldwide; see our export markets for country-specific information.' },
      { q: 'Do you hold ready stock?', a: 'No. We manufacture to order — every carpet is made to your specification.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'office-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'wholesale-carpet-supplier'],
    relatedCompany: ['why-bhadohi', 'factory'],
    relatedIndia: ['delhi-ncr', 'lucknow', 'mumbai'],
  },

  // ── Kochi ───────────────────────────────────────────────────────────────────
  {
    slug: 'kochi',
    kind: 'india',
    label: 'Kochi',
    heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Carpets & Rugs for Kochi',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Kochi\'s hospitality, backwater resorts and commercial projects.',
    seoTitle: 'Carpet Manufacturer for Kochi | Resort & Hospitality Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Kochi. Custom hand tufted, natural-fibre and hospitality carpets from our Bhadohi factory for resorts, hotels, commercial projects and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Kochi', 'resort carpet supplier Kerala', 'hotel carpet Kochi', 'custom rugs Kochi', 'commercial carpet Kochi'],
    h1: 'Carpet & Rug Manufacturer for Kochi',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Kochi and Kerala — hotels, backwater resorts, commercial projects and designers. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Kochi anchors Kerala\'s tourism and hospitality economy — heritage hotels, backwater and beach resorts and growing commercial development, with interiors that favour natural materials and a relaxed tropical aesthetic. As a manufacturer we supply made-to-order hospitality carpets, natural-fibre rugs and custom pieces to the region\'s designers and developers, produced in Bhadohi and dispatched to Kochi — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Hospitality & Resorts', body: 'For Kochi\'s hotels and backwater resorts we manufacture made-to-order contract carpets and rugs to specification, in relaxed designs suited to tropical hospitality.' },
      { h2: 'Natural Fibres & Commercial', body: 'For Kerala interiors we develop natural-fibre (jute, sisal, coir) rugs to exact size, plus custom carpets for commercial projects.' },
    ],
    applications: [
      { title: 'Hotels & Resorts', desc: 'Made-to-order carpets for Kochi hospitality.' },
      { title: 'Natural-Fibre Interiors', desc: 'Jute, sisal and coir rugs for tropical schemes.' },
      { title: 'Commercial Projects', desc: 'Custom broadloom for commercial fit-outs.' },
      { title: 'Interior Designers', desc: 'Bespoke pieces to exact design briefs.' },
    ],
    whyPoints: [
      { title: 'Tropical Materials', desc: 'Natural fibres suited to Kerala interiors.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply resort carpets in Kochi?', a: 'Yes. We manufacture made-to-order contract carpets and rugs to specification, produced in Bhadohi and dispatched to Kochi.' },
      { q: 'Can you make natural-fibre rugs?', a: 'Yes. We craft jute, sisal and coir rugs to exact size for Kerala interiors.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you work with Kerala hospitality developers?', a: 'Yes. We supply developers and designers directly, with samples approved before production.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is made to your project\'s requirements.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'coco-coir', 'hand-tufted-carpet'],
    relatedIndustries: ['hotel-carpets', 'spa-wellness-carpets', 'restaurant-carpets'],
    relatedSolutions: ['custom-carpets', 'contract-carpet-supplier'],
    relatedIndia: ['chennai', 'bengaluru', 'goa'],
  },

  // ── Chandigarh ──────────────────────────────────────────────────────────────
  {
    slug: 'chandigarh',
    kind: 'india',
    label: 'Chandigarh',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for Chandigarh',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Chandigarh\'s government, corporate and premium residential projects.',
    seoTitle: 'Carpet Manufacturer for Chandigarh | Custom Carpets & Rugs — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Chandigarh. Custom office broadloom, hand tufted and modern rugs from our Bhadohi factory for government, corporates, hotels and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Chandigarh', 'office carpet supplier Chandigarh', 'government carpet Chandigarh', 'custom rugs Chandigarh', 'modern rugs Chandigarh'],
    h1: 'Carpet & Rug Manufacturer for Chandigarh',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Chandigarh and the tricity — government offices, corporates, hotels and premium residences. We produce to your brief; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Chandigarh — India\'s planned, modernist city — pairs significant government and administrative demand with affluent residential neighbourhoods and a clean, design-conscious sensibility. As a manufacturer we supply custom office broadloom, government and institutional carpets, and modern bespoke rugs to the tricity\'s architects and procurement teams, produced in Bhadohi and dispatched to Chandigarh — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Government & Corporate', body: 'For Chandigarh\'s government and corporate buildings we manufacture made-to-order institutional and office carpets to specification and tender requirements.' },
      { h2: 'Modern Residential & Hospitality', body: 'For the city\'s affluent homes and hotels we develop modern, clean bespoke rugs and made-to-order hospitality carpets to exact colour and size.' },
    ],
    applications: [
      { title: 'Government & Institutions', desc: 'Made-to-order institutional carpets to spec.' },
      { title: 'Corporate Offices', desc: 'Custom broadloom for corporate fit-outs.' },
      { title: 'Premium Residential', desc: 'Modern bespoke rugs to exact brief.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets.' },
    ],
    whyPoints: [
      { title: 'Tender-Ready', desc: 'Documentation and specification support.' },
      { title: 'Clean, Modern Design', desc: 'Contemporary palettes to brief.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
    ],
    faqs: [
      { q: 'Do you supply government carpets in Chandigarh?', a: 'Yes. We manufacture made-to-order institutional and office carpets to specification and tender requirements, produced in Bhadohi and dispatched to Chandigarh.' },
      { q: 'Can you supply corporate and residential projects?', a: 'Yes. We produce custom broadloom and modern bespoke rugs to exact colour and size.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you serve the wider tricity (Mohali, Panchkula)?', a: 'Yes. We supply the Chandigarh tricity region, manufacturer-direct from Bhadohi.' },
      { q: 'Are you a retail store?', a: 'No. We are a manufacturer and supplier producing carpets and rugs to order.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'carpet-tiles'],
    relatedIndustries: ['government-carpets', 'office-carpets', 'hotel-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'modern-rugs'],
    relatedIndia: ['delhi-ncr', 'gurugram', 'jaipur'],
  },

  // ── Gurugram (NCR corporate/luxury sub-market) ──────────────────────────────
  {
    slug: 'gurugram',
    kind: 'india',
    label: 'Gurugram',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for Gurugram',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Gurugram\'s corporate towers, luxury hospitality and high-rise residential.',
    seoTitle: 'Carpet Manufacturer in Gurugram | Corporate & Luxury Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Gurugram (Gurgaon). Custom office broadloom, carpet tiles, hand knotted and luxury rugs from our Bhadohi factory for MNC offices, luxury hotels and high-rise residences. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Gurugram', 'office carpet supplier Gurgaon', 'corporate carpet Gurugram', 'luxury rugs Gurgaon', 'carpet tiles Gurugram'],
    h1: 'Carpet & Rug Manufacturer for Gurugram',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Gurugram — MNC corporate towers, luxury hotels and high-rise residential. We produce to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Gurugram is the corporate heart of Delhi NCR — dense with multinational headquarters, Grade-A office towers, luxury hospitality and premium high-rise residential. As a manufacturer we supply custom office broadloom and carpet tiles at scale, luxury hospitality carpets and bespoke residential rugs to the city\'s fit-out contractors and designers, produced in Bhadohi and dispatched to Gurugram — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'Corporate Fit-Outs at Scale', body: 'For Gurugram\'s MNC offices and Grade-A towers we manufacture durable custom broadloom and carpet tiles in modular, workspace-appropriate formats, made to specification and phased to fit-out schedules.' },
      { h2: 'Luxury Hospitality & High-Rise Residential', body: 'For the city\'s luxury hotels and premium apartments we develop made-to-order contract carpets and bespoke rugs to exact colour, size and specification.' },
    ],
    applications: [
      { title: 'MNC & Corporate Offices', desc: 'Custom broadloom and tiles for Gurugram towers.' },
      { title: 'Luxury Hotels', desc: 'Made-to-order contract carpets to specification.' },
      { title: 'High-Rise Residential', desc: 'Bespoke rugs for premium apartments.' },
      { title: 'Fit-Out Contractors', desc: 'Phased custom supply to project schedules.' },
    ],
    whyPoints: [
      { title: 'Scale & Consistency', desc: 'Bulk broadloom and tiles, held dye-lots.' },
      { title: 'Fully Custom', desc: 'Made to your design, size and specification.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets and tiles in Gurugram?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles at scale to specification, produced in Bhadohi and dispatched to Gurugram.' },
      { q: 'Can you supply luxury hotels in Gurugram?', a: 'Yes. We produce made-to-order contract carpets to specification, with fire-safety construction where required.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Can you phase delivery to a fit-out schedule?', a: 'Yes. We hold dye-lots and coordinate phased dispatch aligned to your installation programme.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is manufactured to your project\'s requirements.' },
    ],
    relatedProducts: ['carpet-tiles', 'wall-to-wall-carpets', 'hand-knotted-carpet'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'coworking-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'luxury-carpets'],
    relatedIndia: ['delhi-ncr', 'noida', 'mumbai'],
  },

  // ── Noida (NCR commercial/institutional sub-market) ─────────────────────────
  {
    slug: 'noida',
    kind: 'india',
    label: 'Noida',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Noida',
    tagline: 'Made-to-order carpet and rug manufacturer supplying Noida\'s IT, commercial, institutional and residential projects.',
    seoTitle: 'Carpet Manufacturer in Noida | Office & Commercial Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer supplying Noida & Greater Noida. Custom office broadloom, carpet tiles, institutional and residential carpets from our Bhadohi factory for IT parks, institutions, hotels and developers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Noida', 'office carpet supplier Noida', 'commercial carpet Noida', 'carpet tiles Greater Noida', 'institutional carpet Noida'],
    h1: 'Carpet & Rug Manufacturer for Noida',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and supplies buyers across Noida and Greater Noida — IT parks, commercial and institutional buildings, media houses and residential developments. We produce to your specification; we are a manufacturer, not a ready-stock retailer.',
    overview: 'Noida and Greater Noida form a fast-growing commercial, IT, institutional and expo hub within Delhi NCR, with steady office, education and residential development. As a manufacturer we supply custom office broadloom and carpet tiles, institutional and auditorium carpets, and residential rugs to the region\'s developers and procurement teams, produced in Bhadohi and dispatched to Noida — typically around 3–4 weeks depending on the order.',
    sections: [
      { h2: 'IT, Commercial & Institutional', body: 'For Noida\'s IT parks, commercial buildings and institutions we manufacture durable custom broadloom, carpet tiles and institutional/auditorium carpets to specification and, where relevant, tender requirements.' },
      { h2: 'Residential & Hospitality', body: 'For the region\'s residential developments and hotels we develop made-to-order rugs and contract carpets to exact colour and size.' },
    ],
    applications: [
      { title: 'IT Parks & Offices', desc: 'Custom broadloom and tiles for Noida workspaces.' },
      { title: 'Institutions & Auditoria', desc: 'Made-to-order institutional carpets to spec.' },
      { title: 'Residential Developers', desc: 'Coordinated rug supply for developments.' },
      { title: 'Hotels & Hospitality', desc: 'Made-to-order contract carpets.' },
    ],
    whyPoints: [
      { title: 'Commercial-Ready', desc: 'Durable broadloom, tiles and institutional carpets.' },
      { title: 'Tender Support', desc: 'Specification and documentation where required.' },
      { title: 'Made to Order', desc: 'Your design, size, colour and quantity.' },
    ],
    faqs: [
      { q: 'Do you supply office carpets in Noida?', a: 'Yes. We manufacture made-to-order office broadloom and carpet tiles to specification, produced in Bhadohi and dispatched to Noida and Greater Noida.' },
      { q: 'Can you supply institutional and auditorium carpets?', a: 'Yes. We produce made-to-order institutional and auditorium carpets to specification and tender requirements.' },
      { q: 'What is the typical production timeline?', a: 'Made-to-order production and dispatch typically takes around 3–4 weeks depending on design, size, quantity and specification.' },
      { q: 'Do you serve Greater Noida too?', a: 'Yes. We supply Noida and Greater Noida, manufacturer-direct from Bhadohi.' },
      { q: 'Do you hold ready stock?', a: 'No. Every order is manufactured to your project\'s requirements.' },
    ],
    relatedProducts: ['carpet-tiles', 'wall-to-wall-carpets', 'hand-tufted-carpet'],
    relatedIndustries: ['office-carpets', 'auditorium-carpets', 'school-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'contract-carpet-supplier'],
    relatedIndia: ['delhi-ncr', 'gurugram', 'lucknow'],
  },
]
