import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// Industry / application landing pages — /industries/[industry]
// Highest commercial-intent B2B cluster. Each entry is hand-written and unique.
// ─────────────────────────────────────────────────────────────────────────────

export const INDUSTRIES: SeoLanding[] = [
  {
    slug: 'hotel-carpets',
    kind: 'industry',
    label: 'Hotels & Resorts',
    heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Hospitality Flooring',
    tagline: 'Custom hotel carpets manufactured in Bhadohi for lobbies, guest rooms, corridors and banquet halls.',
    seoTitle: 'Hotel Carpet Manufacturer & Supplier India | Custom Hospitality Carpets — Tapis Global',
    seoDescription: 'Hotel carpet manufacturer and supplier in India. Custom hand tufted, axminster and broadloom hospitality carpets from Bhadohi for lobbies, guest rooms, corridors and banquet halls. Fire-rated, phased delivery. Request a catalogue.',
    seoKeywords: ['hotel carpet manufacturer India', 'hospitality carpet supplier', 'custom hotel carpets', 'resort carpet manufacturer', 'banquet hall carpet supplier', 'guest room carpet manufacturer'],
    h1: 'Hotel & Hospitality Carpet Manufacturer in India',
    intro: 'Tapis Global International manufactures custom hotel carpets for hospitality groups, architects and procurement teams across India and international markets. From statement lobby medallions to durable corridor runs and guest-room broadloom, we supply specification-led carpets engineered for the demands of 5-star and boutique properties.',
    overview: 'Hospitality flooring is a discipline of its own — it must balance design impact with heavy-traffic durability, fire-safety compliance, acoustic performance and phased installation across an operating property. As a direct manufacturer in Bhadohi, we control yarn dyeing, tufting, weaving and finishing in-house, giving hotel projects consistent quality, accurate colour matching across large runs, and a single accountable partner from sample to final dispatch.',
    sections: [
      { h2: 'Carpets for Every Zone of a Hotel', body: 'We develop dedicated specifications for each area of a property: high-density cut-pile for lobbies and pre-function spaces, patterned broadloom and carpet tiles for corridors that hide wear and guide circulation, comfortable hand tufted carpets for guest rooms and suites, and bold custom medallions for ballrooms and banquet halls. Each zone is specified for the right weight, pile and backing so the carpet performs for years, not seasons.' },
      { h2: 'Fire-Rated & Compliance-Ready', body: 'Hotel carpets must meet fire-safety and performance standards for public buildings. We manufacture fire-rated constructions, provide test documentation, and advise on the correct traffic classification for each space. Our export programmes ship with the compliance paperwork international hospitality buyers require.' },
      { h2: 'Phased Delivery for Live Properties', body: 'Refurbishments and multi-tower openings rarely happen all at once. We coordinate phased production and dispatch aligned to your installation programme, holding dye-lots so a carpet delivered in phase three matches phase one exactly.' },
    ],
    applications: [
      { title: 'Lobbies & Pre-Function', desc: 'Statement hand tufted medallions and bespoke patterns that define a property\'s arrival experience.' },
      { title: 'Guest Rooms & Suites', desc: 'Comfortable, durable broadloom and rugs specified for acoustic comfort and long service life.' },
      { title: 'Corridors & Circulation', desc: 'Patterned broadloom and carpet tiles engineered to mask traffic and guide movement.' },
      { title: 'Ballrooms & Banquet Halls', desc: 'Large-format custom medallions and fire-rated event flooring for high-occupancy spaces.' },
    ],
    whyPoints: [
      { title: 'Direct Manufacturer', desc: 'Buy direct from the Bhadohi factory — better pricing, full QC and no trading middlemen.' },
      { title: 'Dye-Lot Consistency', desc: 'Colour held across large and phased runs so every area matches.' },
      { title: 'Project Coordination', desc: 'Measurement guidance, installation drawings and phased dispatch for live properties.' },
    ],
    faqs: [
      { q: 'Do you manufacture fire-rated carpets for hotels?', a: 'Yes. We produce fire-rated hospitality carpets to the relevant contract standards and supply test documentation. Share your project specification and we will match the required performance class for each space.' },
      { q: 'Can you match an architect\'s custom design and colours for a hotel project?', a: 'Yes — as a custom manufacturer we develop carpets from artwork, mood boards and Pantone references, create lab-dips for approval, and reproduce the design accurately across the whole property.' },
      { q: 'Can you supply carpets in phases for a hotel refurbishment?', a: 'Yes. We hold dye-lots and coordinate phased production and dispatch aligned to your installation programme so later phases match earlier ones exactly.' },
      { q: 'What carpet constructions are best for hotel corridors?', a: 'Patterned broadloom or carpet tiles in solution-dyed nylon or wool-nylon blends are ideal for corridors — they hide traffic, are easy to maintain and carry high durability ratings. We advise per zone.' },
      { q: 'Do you supply hotels internationally?', a: 'Yes. Alongside extensive pan-India hospitality supply, we export hotel carpets internationally with full compliance documentation and coordinated freight.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'hand-knotted-carpet'],
    relatedIndustries: ['auditorium-carpets', 'restaurant-carpets', 'office-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'custom-carpets'],
  },

  {
    slug: 'auditorium-carpets',
    kind: 'industry',
    label: 'Auditoriums & Cinemas',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Acoustic & High-Traffic Flooring',
    tagline: 'Auditorium and cinema carpets manufactured for acoustics, durability and bold design at scale.',
    seoTitle: 'Auditorium Carpet Manufacturer India | Cinema & Theatre Carpet Supplier — Tapis Global',
    seoDescription: 'Auditorium carpet manufacturer and supplier in India. Custom high-traffic, acoustic carpets from Bhadohi for cinemas, theatres, convention centres and concert halls. Fire-rated, bold patterns, bulk supply. Request a catalogue.',
    seoKeywords: ['auditorium carpet manufacturer India', 'cinema carpet supplier', 'theatre carpet manufacturer', 'convention centre carpet', 'concert hall carpet supplier'],
    h1: 'Auditorium & Cinema Carpet Manufacturer in India',
    intro: 'Tapis Global International manufactures auditorium and cinema carpets engineered for acoustics, heavy footfall and dramatic visual impact. We supply theatres, multiplexes, convention centres and concert halls across India and international markets with custom designs produced to specification in Bhadohi.',
    overview: 'Auditorium flooring works hard: it absorbs sound, withstands constant foot traffic on raked aisles and steps, hides soiling under low lighting, and frequently carries bold, brand-defining patterns. We manufacture dense, fire-rated constructions in custom colourways and large repeats, with the durability classification these public spaces demand.',
    sections: [
      { h2: 'Acoustic Performance', body: 'Carpet is a primary acoustic surface in any auditorium. We specify pile weight and backing systems that contribute to sound absorption and reduce reverberation, helping deliver the controlled acoustic environment theatres and concert halls require.' },
      { h2: 'Bold Custom Patterns at Scale', body: 'Auditorium carpets are often a signature design element with large-scale patterns visible from balconies and entrances. Our studio develops bespoke repeats and reproduces them accurately across thousands of square metres without colour drift.' },
      { h2: 'Durability for Raked & Stepped Floors', body: 'Aisles, steps and raked seating areas concentrate wear. We build high-density constructions and recommend pattern and colour strategies that mask traffic and extend the refurbishment cycle.' },
    ],
    applications: [
      { title: 'Cinemas & Multiplexes', desc: 'Bold, soil-hiding patterns and durable constructions for high-turnover auditoriums and foyers.' },
      { title: 'Theatres & Concert Halls', desc: 'Acoustic, fire-rated carpets in bespoke designs for prestige performance venues.' },
      { title: 'Convention & Conference Centres', desc: 'Large-format flooring engineered for flexible, high-occupancy event spaces.' },
      { title: 'Auditoriums & Lecture Halls', desc: 'Hard-wearing carpets for educational and institutional assembly spaces.' },
    ],
    whyPoints: [
      { title: 'Large-Repeat Capability', desc: 'Bespoke patterns reproduced accurately across very large areas.' },
      { title: 'Fire-Rated & Documented', desc: 'Public-building compliance with supporting test documentation.' },
      { title: 'Bulk Manufacturing', desc: '80,000 sq ft campus geared for high-volume contract orders.' },
    ],
    faqs: [
      { q: 'Are your auditorium carpets acoustic?', a: 'Yes. We specify pile weight and backing to contribute to sound absorption, supporting the acoustic performance theatres, cinemas and concert halls require.' },
      { q: 'Can you produce a large custom pattern for an auditorium?', a: 'Yes — our studio develops bespoke large-repeat designs and reproduces them accurately across thousands of square metres with strict dye-lot control.' },
      { q: 'Are the carpets fire-rated for public venues?', a: 'Yes. We manufacture fire-rated constructions suitable for public assembly buildings and provide the supporting documentation.' },
      { q: 'Can you handle a full multiplex or convention-centre order?', a: 'Yes. Our Bhadohi campus is built for bulk contract volumes with phased delivery aligned to your fit-out schedule.' },
      { q: 'Which constructions suit high-traffic aisles and steps?', a: 'Dense cut-pile and patterned broadloom in durable fibres mask traffic and resist wear on raked and stepped floors. We recommend the right specification per zone.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'flat-weaves'],
    relatedIndustries: ['hotel-carpets', 'office-carpets', 'school-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'contract-carpet-supplier'],
  },

  {
    slug: 'mosque-carpets',
    kind: 'industry',
    label: 'Mosques',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Prayer Hall Flooring',
    tagline: 'Custom mosque carpets with prayer-row (saff) layouts, manufactured for comfort, durability and devotion.',
    seoTitle: 'Mosque Carpet Manufacturer & Supplier India | Custom Prayer Carpets — Tapis Global',
    seoDescription: 'Mosque carpet manufacturer and supplier from India. Custom prayer-row (saff) carpets from Bhadohi for mosques, musallas and prayer halls — comfortable, durable, custom colours and dimensions. Bulk supply and export. Request a catalogue.',
    seoKeywords: ['mosque carpet manufacturer India', 'mosque carpet supplier', 'prayer carpet manufacturer', 'saff carpet supplier', 'masjid carpet manufacturer'],
    h1: 'Mosque Carpet Manufacturer & Supplier in India',
    intro: 'Tapis Global International manufactures custom mosque carpets with accurate prayer-row (saff) layouts for mosques, musallas and prayer halls across India and international markets. Produced in Bhadohi, our prayer carpets combine comfort underfoot, dignified design and the durability required for daily congregational use.',
    overview: 'A mosque carpet must do more than cover a floor — its prayer rows must be precisely spaced to organise worshippers, its pile must be comfortable for prostration, and its colours and motifs must reflect the dignity of the space. We develop custom saff designs to exact hall dimensions, manufacture in durable, easy-to-maintain constructions, and supply at the scale large prayer halls require.',
    sections: [
      { h2: 'Accurate Saff (Prayer Row) Layouts', body: 'We design prayer rows to the precise dimensions of your hall so worshippers align correctly, with the mihrab orientation and row spacing set to your requirements. Custom borders, medallions and motifs are developed to complement the architecture.' },
      { h2: 'Comfort & Durability for Daily Use', body: 'Prayer carpets endure intensive daily use. We specify resilient pile and backing that stay comfortable for prostration while resisting matting and soiling, with constructions chosen for easy maintenance in high-footfall halls.' },
      { h2: 'Custom Colours, Dimensions & Bulk Supply', body: 'From a single musalla to a grand congregational mosque, we manufacture to custom colourways and dimensions and supply in bulk, with export programmes for international mosque projects.' },
    ],
    applications: [
      { title: 'Congregational Mosques', desc: 'Large-format custom saff carpets for main prayer halls with precise row alignment.' },
      { title: 'Musallas & Prayer Rooms', desc: 'Comfortable, dignified prayer carpets for offices, airports, malls and institutions.' },
      { title: 'Islamic Centres & Schools', desc: 'Durable prayer flooring for community and educational facilities.' },
      { title: 'Eidgahs & Multipurpose Halls', desc: 'Hard-wearing carpets for high-occupancy seasonal and multipurpose prayer spaces.' },
    ],
    whyPoints: [
      { title: 'Custom Saff Design', desc: 'Prayer rows engineered to your exact hall dimensions and orientation.' },
      { title: 'Comfort & Longevity', desc: 'Resilient pile specified for prostration comfort and daily durability.' },
      { title: 'Bulk & Export Ready', desc: 'Large-volume manufacturing with international supply and documentation.' },
    ],
    faqs: [
      { q: 'Can you make mosque carpets with custom prayer rows (saff)?', a: 'Yes. We design saff layouts to your exact hall dimensions and mihrab orientation, with custom row spacing, borders and motifs developed to suit the architecture.' },
      { q: 'What pile is best for a prayer carpet?', a: 'We specify a resilient, comfortable pile that supports prostration while resisting matting and soiling under intensive daily use. We recommend the right construction for your footfall.' },
      { q: 'Can you supply large congregational mosques in bulk?', a: 'Yes. Our Bhadohi campus manufactures large-volume mosque carpet orders and we coordinate phased delivery for major projects.' },
      { q: 'Do you export mosque carpets internationally?', a: 'Yes — we supply mosque carpets to international projects with custom designs, bulk capacity and full export documentation.' },
      { q: 'Can you match specific colours for our mosque?', a: 'Yes. We develop custom colourways with lab-dip approval so the carpet matches your interior scheme and design intent.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'wall-to-wall-carpets', 'hand-knotted-carpet'],
    relatedIndustries: ['hotel-carpets', 'office-carpets', 'school-carpets'],
    relatedSolutions: ['custom-carpets', 'wholesale-carpet-supplier'],
  },

  {
    slug: 'office-carpets',
    kind: 'industry',
    label: 'Offices & Corporate',
    heroImage: '/images/tufting-carpet.webp',
    eyebrow: 'Corporate & Workplace Flooring',
    tagline: 'Office and corporate carpets and carpet tiles manufactured for durability, acoustics and brand identity.',
    seoTitle: 'Office Carpet Manufacturer & Supplier India | Corporate Carpet Tiles — Tapis Global',
    seoDescription: 'Office carpet manufacturer and supplier in India. Durable corporate broadloom and carpet tiles from Bhadohi for workplaces, boardrooms and headquarters — acoustic, branded, easy to maintain. Bulk and contract supply. Request a catalogue.',
    seoKeywords: ['office carpet manufacturer India', 'corporate carpet supplier', 'office carpet tiles manufacturer', 'workplace carpet supplier', 'boardroom carpet manufacturer'],
    h1: 'Office & Corporate Carpet Manufacturer in India',
    intro: 'Tapis Global International manufactures office and corporate carpets for workplaces, headquarters and commercial fit-outs across India and international markets. We supply durable broadloom and modular carpet tiles — produced in Bhadohi — engineered for acoustics, easy maintenance and brand-aligned design.',
    overview: 'The modern workplace asks a lot of its flooring: it must dampen noise in open-plan spaces, withstand chair castors and constant footfall, allow quick tile replacement in high-wear zones, and reinforce the company\'s visual identity. As a direct manufacturer we deliver contract-grade carpets and tiles in custom colours with the durability ratings corporate projects require.',
    sections: [
      { h2: 'Carpet Tiles for Flexible Workplaces', body: 'Modular carpet tiles let facilities teams replace individual worn tiles, run cabling beneath access floors and reconfigure layouts without re-carpeting. We manufacture tiles in coordinated colourways with broadloom so boardrooms and open-plan areas read as one scheme.' },
      { h2: 'Acoustic Comfort in Open-Plan Spaces', body: 'Open offices live or die on acoustics. Our constructions contribute to noise absorption, reducing distraction and improving speech privacy across workstations, meeting rooms and breakout areas.' },
      { h2: 'Brand-Aligned Custom Design', body: 'From subtle corporate neutrals to logo medallions in reception, we develop custom colours and patterns that reinforce brand identity, with dye-lot consistency across multi-floor headquarters.' },
    ],
    applications: [
      { title: 'Open-Plan Workspaces', desc: 'Acoustic, hard-wearing carpet tiles and broadloom for high-density work floors.' },
      { title: 'Boardrooms & Executive Suites', desc: 'Premium hand tufted carpets and custom designs for prestige corporate spaces.' },
      { title: 'Reception & Lobbies', desc: 'Branded medallions and statement flooring for corporate arrival areas.' },
      { title: 'Co-working & Breakout', desc: 'Flexible, replaceable modular tiles for evolving workplace layouts.' },
    ],
    whyPoints: [
      { title: 'Contract-Grade Durability', desc: 'Constructions rated for castors, footfall and intensive workplace use.' },
      { title: 'Tile + Broadloom Match', desc: 'Coordinated dye-lots across modular tiles and broadloom for one scheme.' },
      { title: 'Bulk Project Supply', desc: 'Multi-floor headquarters supplied with phased, colour-consistent delivery.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpet tiles for offices?', a: 'Yes. We produce modular carpet tiles in contract-grade constructions, colour-coordinated with broadloom, so facilities teams can replace tiles and reconfigure layouts easily.' },
      { q: 'Are your office carpets acoustic?', a: 'Yes — our constructions contribute to noise absorption, improving speech privacy and reducing distraction in open-plan workplaces.' },
      { q: 'Can you incorporate our company branding?', a: 'Yes. We develop custom colours and logo medallions for reception and feature areas, with dye-lot consistency across multi-floor projects.' },
      { q: 'Can you supply a large corporate headquarters?', a: 'Yes. We manufacture bulk contract volumes and coordinate phased, colour-consistent delivery across multiple floors.' },
      { q: 'Which is better for offices — tiles or broadloom?', a: 'Tiles suit high-wear and cabled access-floor zones for easy replacement; broadloom suits boardrooms and feature spaces. We often combine both and advise per area.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'flat-weaves'],
    relatedIndustries: ['hotel-carpets', 'auditorium-carpets', 'retail-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'contract-carpet-supplier'],
  },

  {
    slug: 'school-carpets',
    kind: 'industry',
    label: 'Schools & Universities',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Education Flooring',
    tagline: 'School and university carpets manufactured for durability, safety and acoustic learning environments.',
    seoTitle: 'School Carpet Manufacturer & Supplier India | University & Education Carpets — Tapis Global',
    seoDescription: 'School and university carpet manufacturer in India. Durable, safe, acoustic carpets from Bhadohi for classrooms, libraries, auditoriums and campus spaces. Bulk education supply and export. Request a catalogue.',
    seoKeywords: ['school carpet manufacturer India', 'university carpet supplier', 'classroom carpet manufacturer', 'education carpet supplier', 'library carpet manufacturer'],
    h1: 'School & University Carpet Manufacturer in India',
    intro: 'Tapis Global International manufactures carpets for schools, universities and educational institutions across India and international markets. From classrooms and libraries to auditoriums and campus common areas, we supply durable, safe and acoustic flooring produced in Bhadohi for the realities of education environments.',
    overview: 'Education spaces combine heavy footfall with the need for quiet, safe, hygienic surfaces. School flooring must resist intensive daily use, contribute to calm acoustic learning environments, and be easy to clean and maintain. As a direct manufacturer we supply contract-grade education carpets in custom colours at the volumes campuses require.',
    sections: [
      { h2: 'Acoustic, Calm Learning Spaces', body: 'Carpet reduces noise and reverberation in classrooms, libraries and study halls, supporting concentration and quieter circulation. We specify constructions that balance acoustic performance with durability.' },
      { h2: 'Durable & Easy to Maintain', body: 'Schools demand flooring that survives years of intensive use and frequent cleaning. We build hard-wearing, soil-resistant constructions and advise on maintenance for high-traffic education settings.' },
      { h2: 'Campus-Wide Bulk Supply', body: 'From a single library to a full campus, we manufacture in bulk with colour consistency across buildings and coordinate phased delivery around academic calendars.' },
    ],
    applications: [
      { title: 'Classrooms & Libraries', desc: 'Acoustic, easy-clean carpets that support quiet, focused learning.' },
      { title: 'Auditoriums & Halls', desc: 'Durable, fire-rated flooring for assembly and performance spaces.' },
      { title: 'Administrative & Staff Areas', desc: 'Professional, hard-wearing carpets for offices and faculty spaces.' },
      { title: 'Campus Common Areas', desc: 'High-traffic constructions for corridors, lounges and shared spaces.' },
    ],
    whyPoints: [
      { title: 'Education-Grade Durability', desc: 'Constructions built for intensive daily institutional use.' },
      { title: 'Acoustic Comfort', desc: 'Noise reduction for calmer, more focused learning environments.' },
      { title: 'Bulk Campus Supply', desc: 'Colour-consistent volume manufacturing on academic timelines.' },
    ],
    faqs: [
      { q: 'Are your school carpets durable enough for heavy use?', a: 'Yes. We manufacture contract-grade, soil-resistant constructions built for the intensive daily footfall of classrooms, libraries and campus circulation.' },
      { q: 'Do carpets help with classroom acoustics?', a: 'Yes — carpet reduces noise and reverberation, supporting calmer, more focused learning. We specify constructions that balance acoustics with durability.' },
      { q: 'Can you supply a whole campus?', a: 'Yes. We manufacture in bulk with colour consistency across buildings and phase delivery around academic calendars.' },
      { q: 'Are the carpets easy to clean and maintain?', a: 'Yes. We select soil-resistant, easy-maintenance constructions suited to frequent institutional cleaning and provide care guidance.' },
      { q: 'Can you supply fire-rated carpets for school auditoriums?', a: 'Yes. We manufacture fire-rated carpets for assembly and performance spaces and provide supporting documentation.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'flat-weaves', 'hand-tufted-carpet'],
    relatedIndustries: ['auditorium-carpets', 'office-carpets', 'hospital-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'wholesale-carpet-supplier'],
  },

  {
    slug: 'airport-carpets',
    kind: 'industry',
    label: 'Airports & Transit',
    heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Transit & Aviation Flooring',
    tagline: 'Airport and transit carpets manufactured for extreme traffic, wayfinding and acoustic comfort.',
    seoTitle: 'Airport Carpet Manufacturer & Supplier India | Transit & Aviation Carpets — Tapis Global',
    seoDescription: 'Airport carpet manufacturer and supplier in India. Extreme-traffic, fire-rated carpets and tiles from Bhadohi for terminals, lounges and transit hubs — wayfinding patterns, acoustic comfort, bulk contract supply. Request a catalogue.',
    seoKeywords: ['airport carpet manufacturer India', 'transit carpet supplier', 'aviation carpet manufacturer', 'lounge carpet supplier', 'terminal carpet manufacturer'],
    h1: 'Airport & Transit Carpet Manufacturer in India',
    intro: 'Tapis Global International manufactures airport and transit carpets engineered for the most demanding public environments. We supply terminals, lounges and transit hubs across India and international markets with extreme-traffic, fire-rated constructions produced in Bhadohi.',
    overview: 'Few floors work harder than an airport. Carpet in terminals and lounges must survive 24/7 footfall and rolling luggage, support wayfinding through pattern and colour, contribute to acoustic comfort in vast volumes, and meet stringent fire-safety standards. We manufacture the heavy-duty constructions and large bespoke patterns these spaces require, with the documentation aviation projects demand.',
    sections: [
      { h2: 'Extreme-Traffic Durability', body: 'Terminal and gate-area carpets endure relentless footfall and wheeled luggage. We build the densest, most resilient constructions and recommend pattern strategies that mask wear and extend service life in 24/7 operations.' },
      { h2: 'Wayfinding Through Design', body: 'In large terminals, carpet pattern and colour guide passengers and delineate zones. Our studio develops bespoke designs that support wayfinding while reinforcing the airport or airline brand.' },
      { h2: 'Premium Lounge Comfort', body: 'Airline and business lounges balance durability with hospitality-grade luxury. We manufacture refined hand tufted and custom carpets that elevate premium passenger spaces.' },
    ],
    applications: [
      { title: 'Terminals & Gate Areas', desc: 'Extreme-traffic, fire-rated constructions for 24/7 public circulation.' },
      { title: 'Airline & Business Lounges', desc: 'Premium custom carpets that combine luxury with heavy-duty performance.' },
      { title: 'Transit Hubs & Stations', desc: 'Durable wayfinding flooring for high-volume transport interchanges.' },
      { title: 'VIP & First-Class Suites', desc: 'Bespoke hand tufted carpets for the most prestigious passenger spaces.' },
    ],
    whyPoints: [
      { title: 'Heavy-Duty Constructions', desc: 'Engineered for relentless footfall and rolling luggage.' },
      { title: 'Fire-Rated & Documented', desc: 'Compliance and documentation for aviation environments.' },
      { title: 'Large-Format Bespoke', desc: 'Wayfinding patterns reproduced accurately across vast areas.' },
    ],
    faqs: [
      { q: 'Can your carpets withstand airport-level traffic?', a: 'Yes. We build the densest, most resilient constructions for 24/7 footfall and rolling luggage, and recommend patterns that mask wear to extend service life.' },
      { q: 'Do you support wayfinding designs for terminals?', a: 'Yes — our studio develops bespoke patterns and colour zones that guide passengers and reinforce the airport or airline brand.' },
      { q: 'Are airport carpets fire-rated?', a: 'Yes. We manufacture fire-rated constructions suitable for aviation environments and provide the supporting documentation.' },
      { q: 'Can you supply premium airline lounges?', a: 'Yes. We produce refined hand tufted and custom carpets that combine hospitality-grade luxury with heavy-duty performance.' },
      { q: 'Can you handle large terminal contract volumes?', a: 'Yes. Our Bhadohi campus manufactures large contract volumes with phased delivery aligned to construction programmes.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'coco-coir'],
    relatedIndustries: ['hotel-carpets', 'office-carpets', 'retail-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'contract-carpet-supplier'],
  },

  {
    slug: 'villa-carpets',
    kind: 'industry',
    label: 'Villas & Luxury Homes',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Luxury Residential Flooring',
    tagline: 'Bespoke carpets and rugs for villas and luxury homes — hand knotted, hand tufted and custom.',
    seoTitle: 'Villa & Luxury Home Carpet Manufacturer India | Bespoke Residential Rugs — Tapis Global',
    seoDescription: 'Luxury villa carpet and rug manufacturer in India. Bespoke hand knotted and hand tufted carpets from Bhadohi for villas, penthouses and luxury homes — custom sizes, colours and designs. Request a catalogue.',
    seoKeywords: ['villa carpet manufacturer India', 'luxury home carpet supplier', 'bespoke residential rugs', 'penthouse carpet manufacturer', 'custom home rugs India'],
    h1: 'Villa & Luxury Home Carpet Manufacturer in India',
    intro: 'Tapis Global International creates bespoke carpets and rugs for villas, penthouses and luxury homes across India and international markets. From heirloom hand knotted pieces to plush custom hand tufted carpets, every floor is developed to the homeowner\'s and designer\'s vision and crafted in Bhadohi.',
    overview: 'Luxury residential flooring is deeply personal. It must complement architecture and interior schemes, deliver tactile comfort, and often become an heirloom in its own right. As a direct manufacturer we offer complete bespoke control — material, knot density, colour, size and design — for distinguished homes and the designers who specify them.',
    sections: [
      { h2: 'Heirloom Hand Knotted Pieces', body: 'For statement living and formal spaces we hand-knot rugs in silk, wool and wool-silk blends that last generations and often appreciate in value — classical reproductions or contemporary commissions, all bespoke.' },
      { h2: 'Plush Custom Hand Tufted Carpets', body: 'For bedrooms, lounges and family spaces we produce custom hand tufted carpets in any size, colour and carved texture, balancing luxury underfoot with everyday practicality.' },
      { h2: 'Designed With Your Architect', body: 'We collaborate directly with interior designers and architects — developing lab-dips, samples and bespoke designs to drawings and palettes so the finished carpet realises the scheme precisely.' },
    ],
    applications: [
      { title: 'Living & Formal Rooms', desc: 'Statement hand knotted and custom rugs that anchor luxury interiors.' },
      { title: 'Bedrooms & Suites', desc: 'Plush, comfortable custom carpets in bespoke colours and textures.' },
      { title: 'Penthouses & Apartments', desc: 'Tailored pieces for high-design urban residences.' },
      { title: 'Home Theatres & Studies', desc: 'Acoustic, refined carpets for private specialist spaces.' },
    ],
    whyPoints: [
      { title: 'Complete Bespoke Control', desc: 'Material, size, colour, knot density and design — all to your brief.' },
      { title: 'Designer Collaboration', desc: 'Lab-dips and samples developed with your architect or designer.' },
      { title: 'Heirloom Quality', desc: 'Hand knotted pieces crafted to last generations.' },
    ],
    faqs: [
      { q: 'Can you make a one-of-a-kind rug for my home?', a: 'Yes. We produce bespoke single pieces — you choose material, size, colour, knot density and design, and we develop lab-dips and a sample for approval before crafting it.' },
      { q: 'Do you work with interior designers and architects?', a: 'Yes. We collaborate directly with designers, developing carpets to drawings, mood boards and Pantone references for residential projects.' },
      { q: 'What is the difference between hand knotted and hand tufted for homes?', a: 'Hand knotted rugs are heirloom-quality and long-lasting, ideal for formal spaces; hand tufted carpets offer plush comfort and bold design at better value for bedrooms and lounges. We advise per room.' },
      { q: 'Can you match my interior colour scheme?', a: 'Yes — we develop custom colourways with lab-dip approval so the carpet matches your scheme precisely.' },
      { q: 'Do you supply luxury homes internationally?', a: 'Yes. We craft and ship bespoke residential carpets to luxury homes internationally with full documentation.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'shaggy-rugs'],
    relatedIndustries: ['hotel-carpets', 'retail-carpets', 'restaurant-carpets'],
    relatedSolutions: ['luxury-carpets', 'custom-carpets'],
  },

  {
    slug: 'restaurant-carpets',
    kind: 'industry',
    label: 'Restaurants & Cafés',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'F&B & Dining Flooring',
    tagline: 'Restaurant and café carpets manufactured for ambience, acoustics and easy maintenance.',
    seoTitle: 'Restaurant Carpet Manufacturer & Supplier India | Café & Dining Carpets — Tapis Global',
    seoDescription: 'Restaurant and café carpet manufacturer in India. Custom, easy-clean, acoustic carpets from Bhadohi for fine-dining, cafés, bars and F&B spaces — ambience-defining design, durable constructions. Request a catalogue.',
    seoKeywords: ['restaurant carpet manufacturer India', 'cafe carpet supplier', 'dining carpet manufacturer', 'F&B carpet supplier', 'bar carpet manufacturer'],
    h1: 'Restaurant & Café Carpet Manufacturer in India',
    intro: 'Tapis Global International manufactures carpets for restaurants, cafés, bars and fine-dining venues across India and international markets. Produced in Bhadohi, our F&B carpets define ambience, control acoustics and stand up to the demands of busy hospitality service.',
    overview: 'In dining spaces, carpet sets the mood and tames the noise — but it must also survive spills, constant footfall and frequent cleaning. We manufacture custom, characterful constructions that deliver atmosphere and acoustic comfort while being practical for daily F&B operations.',
    sections: [
      { h2: 'Ambience Through Bespoke Design', body: 'From intimate fine-dining to vibrant all-day cafés, carpet shapes the guest experience. Our studio develops bespoke patterns and colourways that express each venue\'s concept and brand.' },
      { h2: 'Acoustic Comfort for Dining', body: 'Hard-floored restaurants can be uncomfortably loud. Carpet absorbs sound, softening the dining environment and improving conversation comfort across the room.' },
      { h2: 'Practical for Busy Service', body: 'We specify soil- and stain-resistant constructions suited to spills and intensive cleaning, balancing atmosphere with the practicality F&B operators need.' },
    ],
    applications: [
      { title: 'Fine-Dining Restaurants', desc: 'Refined bespoke carpets that create intimate, atmospheric dining rooms.' },
      { title: 'Cafés & All-Day Dining', desc: 'Durable, easy-clean constructions for high-turnover casual spaces.' },
      { title: 'Bars & Lounges', desc: 'Characterful, acoustic carpets for evening hospitality venues.' },
      { title: 'Private Dining & Function Rooms', desc: 'Custom feature carpets for premium event and dining spaces.' },
    ],
    whyPoints: [
      { title: 'Concept-Led Design', desc: 'Bespoke patterns developed to each venue\'s brand and atmosphere.' },
      { title: 'Acoustic & Practical', desc: 'Sound-softening yet soil-resistant for busy F&B service.' },
      { title: 'Custom & Durable', desc: 'Hospitality-grade constructions in any colour or design.' },
    ],
    faqs: [
      { q: 'Are restaurant carpets practical given spills?', a: 'Yes. We specify soil- and stain-resistant constructions suited to spills and frequent cleaning, balancing atmosphere with day-to-day F&B practicality.' },
      { q: 'Can carpet improve restaurant acoustics?', a: 'Yes — carpet absorbs sound and softens hard dining environments, improving conversation comfort across the room.' },
      { q: 'Can you design a carpet to match our restaurant concept?', a: 'Yes. Our studio develops bespoke patterns and colourways that express your venue\'s concept and brand.' },
      { q: 'Do you supply café chains and multi-site operators?', a: 'Yes. We manufacture consistent custom carpets in volume for multi-site rollouts with dye-lot consistency.' },
      { q: 'What construction suits a busy café?', a: 'Durable, easy-clean cut-pile or patterned broadloom in resilient fibres suits high-turnover casual dining. We advise per venue.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'wall-to-wall-carpets', 'flat-weaves'],
    relatedIndustries: ['hotel-carpets', 'retail-carpets', 'villa-carpets'],
    relatedSolutions: ['custom-carpets', 'commercial-carpet-manufacturer'],
  },

  {
    slug: 'hospital-carpets',
    kind: 'industry',
    label: 'Hospitals & Healthcare',
    heroImage: '/images/manufacturing-rug-img.webp',
    eyebrow: 'Healthcare Flooring',
    tagline: 'Healthcare carpets manufactured for hygiene, acoustics and calming patient environments.',
    seoTitle: 'Hospital & Healthcare Carpet Manufacturer India | Clinic Carpets — Tapis Global',
    seoDescription: 'Hospital and healthcare carpet manufacturer in India. Hygienic, acoustic, easy-clean carpets from Bhadohi for clinics, care homes, waiting areas and administrative zones. Bulk healthcare supply. Request a catalogue.',
    seoKeywords: ['hospital carpet manufacturer India', 'healthcare carpet supplier', 'clinic carpet manufacturer', 'care home carpet supplier', 'medical facility carpet'],
    h1: 'Hospital & Healthcare Carpet Manufacturer in India',
    intro: 'Tapis Global International manufactures carpets for hospitals, clinics, care homes and healthcare facilities across India and international markets. Produced in Bhadohi, our healthcare carpets prioritise hygiene, acoustic calm and easy maintenance for sensitive patient environments.',
    overview: 'Healthcare flooring must reconcile comfort with strict hygiene and durability. In the right zones — waiting areas, consultation suites, administrative offices and care-home living spaces — carpet creates a calmer, quieter, more welcoming environment while meeting maintenance and safety needs. We manufacture constructions suited to these specific healthcare applications.',
    sections: [
      { h2: 'Calming Patient Environments', body: 'Quiet, warm waiting and recovery spaces support wellbeing. Carpet reduces noise and adds a reassuring, non-clinical warmth in the areas where it is appropriate, helping create a more humane healthcare experience.' },
      { h2: 'Hygiene & Easy Maintenance', body: 'We specify soil-resistant, easy-clean constructions for healthcare settings and advise on appropriate zones and maintenance regimes so flooring supports — rather than complicates — facility hygiene.' },
      { h2: 'Durable for Continuous Use', body: 'Healthcare facilities run around the clock. We build hard-wearing constructions for continuous footfall in administrative and communal areas, supplied at the volumes large facilities require.' },
    ],
    applications: [
      { title: 'Waiting & Reception Areas', desc: 'Calming, acoustic, easy-clean carpets for patient-facing spaces.' },
      { title: 'Care & Residential Homes', desc: 'Warm, comfortable, durable carpets for senior living environments.' },
      { title: 'Administrative & Office Zones', desc: 'Professional, hard-wearing carpets for healthcare back-of-house.' },
      { title: 'Consultation & Therapy Suites', desc: 'Quiet, reassuring flooring for sensitive clinical spaces.' },
    ],
    whyPoints: [
      { title: 'Hygiene-Appropriate', desc: 'Soil-resistant, easy-clean constructions for healthcare zones.' },
      { title: 'Acoustic & Calming', desc: 'Noise reduction and warmth for better patient environments.' },
      { title: 'Bulk Facility Supply', desc: 'Volume manufacturing with consistency across large facilities.' },
    ],
    faqs: [
      { q: 'Are carpets suitable for healthcare environments?', a: 'In the right zones — waiting areas, care-home living spaces, consultation suites and offices — carpet adds acoustic calm and warmth. We specify soil-resistant, easy-clean constructions and advise on appropriate areas.' },
      { q: 'Are your healthcare carpets easy to clean?', a: 'Yes. We select soil-resistant, easy-maintenance constructions suited to healthcare cleaning regimes and provide care guidance.' },
      { q: 'Can carpet help reduce noise in hospitals?', a: 'Yes — carpet absorbs sound, creating calmer, quieter waiting and recovery environments where appropriate.' },
      { q: 'Can you supply large healthcare facilities?', a: 'Yes. We manufacture in bulk with consistency across large facilities and coordinate phased delivery.' },
      { q: 'Do you make carpets for care and residential homes?', a: 'Yes. We produce warm, comfortable, durable carpets for senior living environments balancing comfort with practicality.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'flat-weaves', 'hand-tufted-carpet'],
    relatedIndustries: ['office-carpets', 'school-carpets', 'hotel-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'contract-carpet-supplier'],
  },

  {
    slug: 'retail-carpets',
    kind: 'industry',
    label: 'Retail & Showrooms',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Retail & Brand Flooring',
    tagline: 'Retail and showroom carpets manufactured to elevate brand experience and product display.',
    seoTitle: 'Retail Carpet Manufacturer & Supplier India | Showroom & Boutique Carpets — Tapis Global',
    seoDescription: 'Retail carpet manufacturer and supplier in India. Custom showroom, boutique and flagship carpets from Bhadohi — brand-led design, durable constructions, private-label and bulk supply. Request a catalogue.',
    seoKeywords: ['retail carpet manufacturer India', 'showroom carpet supplier', 'boutique carpet manufacturer', 'flagship store carpet', 'private label carpet manufacturer'],
    h1: 'Retail & Showroom Carpet Manufacturer in India',
    intro: 'Tapis Global International manufactures carpets for retail stores, showrooms, boutiques and flagship spaces across India and international markets. Produced in Bhadohi, our retail carpets elevate brand experience, frame product display and withstand high-footfall trading environments.',
    overview: 'Retail flooring is brand storytelling underfoot. It must reinforce identity, direct customers, flatter merchandise and survive intensive footfall — all while being quick to refresh as concepts evolve. As a direct manufacturer we develop bespoke and private-label carpets that bring retail concepts to life at any scale.',
    sections: [
      { h2: 'Brand-Led Bespoke Design', body: 'Our studio develops carpets that express each brand — signature colours, logos and patterns that make flagship and boutique spaces unmistakable, reproduced consistently across a store network.' },
      { h2: 'Flatter Merchandise & Guide Customers', body: 'Carpet colour, texture and zoning frame product display and direct customer flow. We specify designs that enhance merchandising and define areas within open retail floors.' },
      { h2: 'Private-Label & Rollout Ready', body: 'For retail brands and concept stores we offer private-label manufacturing with custom packaging, supplying consistent carpets in volume for multi-store rollouts.' },
    ],
    applications: [
      { title: 'Flagship & Concept Stores', desc: 'Statement bespoke carpets that define brand-defining retail spaces.' },
      { title: 'Boutiques & Showrooms', desc: 'Refined custom flooring that flatters premium merchandise.' },
      { title: 'Department & Multi-Brand Retail', desc: 'Durable zoned carpets that guide customers across large floors.' },
      { title: 'Pop-Ups & Exhibitions', desc: 'Characterful carpets for temporary and experiential retail.' },
    ],
    whyPoints: [
      { title: 'Brand-Aligned Design', desc: 'Signature colours, logos and patterns reproduced across stores.' },
      { title: 'Private-Label Capable', desc: 'OEM manufacturing with custom packaging for retail brands.' },
      { title: 'Rollout Consistency', desc: 'Volume supply with dye-lot consistency for multi-store programmes.' },
    ],
    faqs: [
      { q: 'Can you produce carpets with our retail branding?', a: 'Yes. Our studio develops signature colours, logos and patterns, and we offer private-label manufacturing with custom packaging for retail brands.' },
      { q: 'Can you supply a multi-store retail rollout?', a: 'Yes. We manufacture consistent custom carpets in volume with dye-lot consistency across a store network.' },
      { q: 'Are retail carpets durable enough for high footfall?', a: 'Yes. We build hard-wearing constructions for intensive trading environments while keeping the design refined.' },
      { q: 'Can carpet help with store zoning and customer flow?', a: 'Yes — carpet colour, texture and zoning frame merchandise and guide customers across open retail floors. We design to your layout.' },
      { q: 'Do you make carpets for showrooms and exhibitions?', a: 'Yes. We produce refined showroom carpets and characterful pieces for pop-ups, exhibitions and experiential retail.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'leather-carpets', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'office-carpets', 'restaurant-carpets'],
    relatedSolutions: ['designer-rugs', 'custom-carpets'],
  },
]
