import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// Commercial-intent / solution landing pages — /solutions/[slug]
// Targets high-value modifier searches (luxury / designer / custom / wholesale /
// commercial / exporter / contract). Each entry is unique and useful — written
// around buyer intent, not keyword-stuffed doorway copy.
// ─────────────────────────────────────────────────────────────────────────────

export const SOLUTIONS: SeoLanding[] = [
  {
    slug: 'luxury-carpets',
    kind: 'solution',
    label: 'Luxury Carpets',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Premium Positioning',
    tagline: 'Luxury carpets and rugs handcrafted in Bhadohi for the world\'s most discerning interiors.',
    seoTitle: 'Luxury Carpet Manufacturer India | Premium Handmade Rugs — Tapis Global',
    seoDescription: 'Luxury carpet and rug manufacturer in India. Premium hand knotted and hand tufted carpets in silk and wool from Bhadohi for luxury interiors, hotels and collectors. Bespoke, export quality. Request a catalogue.',
    seoKeywords: ['luxury carpet manufacturer India', 'luxury rugs manufacturer', 'premium handmade carpets', 'high end carpets India', 'silk carpet manufacturer'],
    h1: 'Luxury Carpet & Rug Manufacturer in India',
    intro: 'Tapis Global International manufactures luxury carpets and rugs for premium interiors, five-star hospitality and private collectors across India and international markets. Handcrafted in Bhadohi from the finest silk and wool, each piece is a study in material quality, craftsmanship and bespoke design.',
    overview: 'Luxury is in the details — knot density, yarn quality, finishing and the precision of a custom colour match. As a direct manufacturer we control every stage, so a luxury carpet from Tapis Global delivers genuine, verifiable quality rather than a marketing label. We work with designers, architects and discerning clients to create pieces that define a space and endure for generations.',
    sections: [
      { h2: 'The Finest Materials', body: 'We source pure mulberry silk, New Zealand wool, wool-silk blends and high-altitude Tibetan wool, batch-tested for quality. Material integrity is the foundation of a genuinely luxurious carpet — and as a manufacturer we guarantee it.' },
      { h2: 'Master Craftsmanship', body: 'Our Bhadohi weavers and finishers bring generations of expertise to every piece — from fine hand knotting at 200+ KPSI to hand-carved tufted relief. This craft cannot be rushed, and it is what separates a luxury carpet from a commodity floor covering.' },
      { h2: 'Bespoke by Default', body: 'Luxury is personal. We develop bespoke designs, colours and dimensions for each project, with lab-dips and samples approved before production — so the finished piece is unmistakably yours.' },
    ],
    applications: [
      { title: 'Luxury Residences', desc: 'Heirloom hand knotted and custom rugs for distinguished homes.' },
      { title: 'Five-Star Hospitality', desc: 'Signature pieces for prestige hotels, suites and lobbies.' },
      { title: 'Designer Projects', desc: 'Bespoke development for architects and interior designers.' },
      { title: 'Collectors & Galleries', desc: 'Fine silk masterpieces for collectors and exhibition spaces.' },
    ],
    whyPoints: [
      { title: 'Verifiable Quality', desc: 'Direct manufacturer control over materials and craftsmanship.' },
      { title: 'Finest Fibres', desc: 'Pure silk, premium wool and wool-silk blends, batch-tested.' },
      { title: 'Truly Bespoke', desc: 'Custom design, colour and dimension with lab-dip approval.' },
    ],
    faqs: [
      { q: 'What makes a carpet genuinely luxury?', a: 'Material quality, knot density, craftsmanship and finishing — not branding. As a direct manufacturer we control all of these, so our luxury carpets deliver verifiable quality rather than a label.' },
      { q: 'Do you make pure silk luxury rugs?', a: 'Yes. We hand-knot pure mulberry silk and wool-silk rugs at high knot densities for the finest luxury and collector pieces.' },
      { q: 'Can luxury carpets be fully bespoke?', a: 'Yes. We develop bespoke designs, colours and dimensions for each project, approved via lab-dips and samples before production.' },
      { q: 'Do you supply luxury carpets internationally?', a: 'Yes — we craft and export luxury carpets worldwide with full documentation and coordinated freight.' },
      { q: 'Are luxury hand knotted rugs an investment?', a: 'A well-made hand knotted rug in premium fibres can last generations and often appreciates in value. We ensure authentic construction and material transparency.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'leather-carpets'],
    relatedIndustries: ['villa-carpets', 'hotel-carpets', 'retail-carpets'],
    relatedSolutions: ['designer-rugs', 'custom-carpets'],
  },

  {
    slug: 'designer-rugs',
    kind: 'solution',
    label: 'Designer Rugs',
    heroImage: '/images/rug5.webp',
    eyebrow: 'For Architects & Designers',
    tagline: 'Designer rugs developed with architects and interior designers — concept to crafted reality.',
    seoTitle: 'Designer Rug Manufacturer India | Custom Rugs for Designers — Tapis Global',
    seoDescription: 'Designer rug manufacturer in India working with architects and interior designers. Custom contemporary and modern rugs from Bhadohi developed to artwork, mood boards and Pantone. Lab-dips, samples, export. Request a catalogue.',
    seoKeywords: ['designer rug manufacturer India', 'designer carpets', 'custom rugs for designers', 'contemporary rug manufacturer', 'rugs for interior designers'],
    h1: 'Designer Rug Manufacturer for Architects & Interior Designers',
    intro: 'Tapis Global International is the manufacturing partner behind designer rugs for architects and interior designers across India and international markets. We translate concepts, mood boards and Pantone references into precisely crafted rugs in our Bhadohi studio — a true development partner, not just a supplier.',
    overview: 'Designers need a manufacturer who speaks their language: accurate colour matching, faithful pattern reproduction, sampling that lets them present with confidence, and the flexibility to develop bespoke pieces to a brief. We provide a structured design-development service from lab-dip to final piece, so the rug on the floor matches the rug in the rendering.',
    sections: [
      { h2: 'A Structured Development Service', body: 'We turn your artwork into a production map, develop yarn lab-dips against Pantone references, and produce a sample for sign-off before bulk. Every step is documented so you can present and specify with confidence.' },
      { h2: 'Contemporary & Modern Capability', body: 'From abstract and geometric to organic and textural, we reproduce contemporary designs faithfully across hand tufted, hand knotted and flatweave constructions — at any scale.' },
      { h2: 'Built for Specification', body: 'We provide the material, construction, colour and maintenance information designers need to specify a rug into a project, plus the trade support that makes working with us straightforward.' },
    ],
    applications: [
      { title: 'Residential Schemes', desc: 'Bespoke rugs developed to each interior design concept.' },
      { title: 'Hospitality Design', desc: 'Signature designer carpets for hotels and restaurants.' },
      { title: 'Commercial Interiors', desc: 'Custom design-led flooring for corporate and retail projects.' },
      { title: 'Showroom & Display', desc: 'Statement designer pieces for showrooms and exhibitions.' },
    ],
    whyPoints: [
      { title: 'Design Partner', desc: 'Concept-to-craft development with lab-dips and samples.' },
      { title: 'Accurate Reproduction', desc: 'Faithful colour and pattern matching to your artwork.' },
      { title: 'Trade Support', desc: 'Specification info and trade service for designers.' },
    ],
    faqs: [
      { q: 'Do you develop rugs from a designer\'s artwork?', a: 'Yes. We turn artwork, mood boards and Pantone references into a production map, develop lab-dips and produce a sample for sign-off before bulk production.' },
      { q: 'Can you match a specific Pantone colour?', a: 'Yes — we develop yarn lab-dips against Pantone and RAL references and gain your approval before manufacturing.' },
      { q: 'What constructions can you produce designer rugs in?', a: 'Hand tufted, hand knotted and flatweave — contemporary, geometric, organic or textural designs reproduced faithfully at any scale.' },
      { q: 'Do you offer trade support for designers?', a: 'Yes. We provide material, construction and maintenance specification information plus dedicated trade service for architects and designers.' },
      { q: 'Can you produce one-off designer pieces and production runs?', a: 'Both. We make single bespoke pieces for individual projects and consistent production runs for rollouts and collections.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'flat-weaves', 'hand-knotted-carpet'],
    relatedIndustries: ['villa-carpets', 'retail-carpets', 'hotel-carpets'],
    relatedSolutions: ['custom-carpets', 'luxury-carpets'],
  },

  {
    slug: 'custom-carpets',
    kind: 'solution',
    label: 'Custom Carpets',
    heroImage: '/images/handtufted-img-2.webp',
    eyebrow: 'Made to Specification',
    tagline: 'Custom carpets and rugs manufactured to any size, colour, pattern and construction in Bhadohi.',
    seoTitle: 'Custom Carpet & Rug Manufacturer India | Bespoke Carpets — Tapis Global',
    seoDescription: 'Custom carpet and rug manufacturer in India. Bespoke size, colour, pattern, pile and construction from Bhadohi for projects of any scale — lab-dips, samples, OEM and private-label. Request a catalogue or quote.',
    seoKeywords: ['custom carpet manufacturer India', 'custom rug manufacturer', 'bespoke carpet manufacturer', 'made to order carpets', 'OEM carpet manufacturer India'],
    h1: 'Custom Carpet & Rug Manufacturer in India',
    intro: 'Tapis Global International is a custom carpet and rug manufacturer producing made-to-specification flooring for projects across India and international markets. Any size, colour, pattern, pile or construction — developed and crafted in our Bhadohi facility with full design-development support.',
    overview: 'Off-the-shelf rarely fits a real project. Custom manufacturing lets architects, designers, hospitality groups and retailers get exactly the carpet a space needs — the right dimensions, the exact colour, the intended pattern and the appropriate construction. As a direct manufacturer we offer complete customisation with the QC and consistency that bespoke projects demand.',
    sections: [
      { h2: 'Everything Is Customisable', body: 'Size and shape (including round, runner and oversized), Pantone/RAL colour matching, cut/loop/carved textures, pile height and density, borders and medallions — all to your specification, across hand tufted, hand knotted, flatweave and broadloom constructions.' },
      { h2: 'Lab-Dip to Final Piece', body: 'We develop lab-dips and a physical sample for approval before bulk, so there are no surprises. Production is documented and QC\'d against the approved specification.' },
      { h2: 'OEM & Private Label', body: 'For retailers and importers we offer complete OEM and private-label manufacturing — custom branding, labelling and packaging under confidentiality.' },
    ],
    applications: [
      { title: 'Architectural Projects', desc: 'Carpets manufactured to drawings and exact dimensions.' },
      { title: 'Hospitality & Commercial', desc: 'Custom designs and colourways for branded environments.' },
      { title: 'Luxury Residential', desc: 'Bespoke single pieces for distinguished homes.' },
      { title: 'OEM & Private Label', desc: 'White-label manufacturing for retailers and importers.' },
    ],
    whyPoints: [
      { title: 'Total Customisation', desc: 'Size, colour, pattern, pile and construction — all to brief.' },
      { title: 'Approve Before Bulk', desc: 'Lab-dips and samples signed off before production.' },
      { title: 'OEM Capable', desc: 'Private-label manufacturing with custom branding.' },
    ],
    faqs: [
      { q: 'What can be customised on a carpet?', a: 'Size, shape, Pantone/RAL colour, pattern, texture, pile height and density, borders, medallions and construction — across hand tufted, hand knotted, flatweave and broadloom.' },
      { q: 'Can I approve a sample before bulk production?', a: 'Yes. We develop lab-dips and a physical sample for your approval before manufacturing, and QC production against the approved specification.' },
      { q: 'Do you offer OEM and private-label manufacturing?', a: 'Yes. We provide complete OEM and private-label services with custom branding, labelling and packaging under confidentiality.' },
      { q: 'Is there a minimum order for custom carpets?', a: 'We accommodate single bespoke pieces for designers and homes as well as large project and contract volumes. MOQ varies by construction — share your requirement for details.' },
      { q: 'How long does a custom carpet take?', a: 'Lead time depends on construction, size and quantity, typically 30-90 days. Custom samples are usually ready in 2-3 weeks. Share your deadline and we will confirm.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'hand-knotted-carpet', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'office-carpets'],
    relatedSolutions: ['designer-rugs', 'luxury-carpets'],
  },

  {
    slug: 'modern-rugs',
    kind: 'solution',
    label: 'Modern Rugs',
    heroImage: '/images/rug4.webp',
    eyebrow: 'Contemporary Design',
    tagline: 'Modern and contemporary rugs manufactured in Bhadohi for today\'s interiors.',
    seoTitle: 'Modern & Contemporary Rug Manufacturer India | Tapis Global',
    seoDescription: 'Modern and contemporary rug manufacturer in India. Minimalist, abstract and textural rugs from Bhadohi for contemporary homes, retail and hospitality. Custom designs, export quality. Request a catalogue.',
    seoKeywords: ['modern rug manufacturer India', 'contemporary rugs manufacturer', 'minimalist rugs India', 'abstract rugs manufacturer', 'modern carpets supplier'],
    h1: 'Modern & Contemporary Rug Manufacturer in India',
    intro: 'Tapis Global International manufactures modern and contemporary rugs for design-forward interiors across India and international markets. From minimalist tonal pieces to bold abstract statements, our Bhadohi studio produces contemporary rugs in custom designs and constructions.',
    overview: 'Contemporary interiors call for rugs that feel current — clean lines, considered texture, restrained or expressive colour. We combine traditional handcraft with modern design sensibility to produce rugs that suit minimalist homes, lifestyle retail and boutique hospitality, all customisable to a designer\'s exact vision.',
    sections: [
      { h2: 'Minimalist to Bold', body: 'Whether the brief is a quiet tonal ground or a graphic statement, we produce contemporary designs across hand tufted, flatweave and shaggy constructions with the texture and colour control modern interiors demand.' },
      { h2: 'Texture as Design', body: 'Contemporary rugs often rely on texture — carved relief, high-low pile, plush shag or crisp flatweave. We engineer these tactile effects precisely to bring modern designs to life.' },
      { h2: 'Custom for Modern Spaces', body: 'Modern projects are rarely standard sizes. We produce contemporary rugs in custom dimensions, shapes and colourways to fit open-plan and architecturally distinctive spaces.' },
    ],
    applications: [
      { title: 'Contemporary Homes', desc: 'Minimalist and textural rugs for modern living spaces.' },
      { title: 'Lifestyle Retail', desc: 'On-trend contemporary collections for design retail.' },
      { title: 'Boutique Hospitality', desc: 'Characterful modern rugs for design-led venues.' },
      { title: 'Modern Offices', desc: 'Clean, contemporary statement pieces for workspaces.' },
    ],
    whyPoints: [
      { title: 'Current Design', desc: 'Contemporary sensibility backed by traditional handcraft.' },
      { title: 'Texture Engineering', desc: 'Carved, high-low, shag and flatweave effects, precisely made.' },
      { title: 'Custom Sizing', desc: 'Any dimension or shape for distinctive modern spaces.' },
    ],
    faqs: [
      { q: 'What styles of modern rugs do you make?', a: 'From minimalist tonal grounds to bold abstract and geometric statements, across hand tufted, flatweave and shaggy constructions — all customisable.' },
      { q: 'Can you create textural contemporary rugs?', a: 'Yes. We engineer carved relief, high-low pile, plush shag and crisp flatweave effects to bring textural modern designs to life precisely.' },
      { q: 'Can modern rugs be made in custom sizes and shapes?', a: 'Yes — we produce contemporary rugs in any dimension and shape to fit open-plan and architecturally distinctive spaces.' },
      { q: 'Do you supply contemporary retail collections?', a: 'Yes. We manufacture on-trend contemporary collections, including private-label, for lifestyle and design retail.' },
      { q: 'Can you match a contemporary colour palette?', a: 'Yes. We develop custom colourways with lab-dip approval to match modern interior palettes.' },
    ],
    relatedProducts: ['shaggy-rugs', 'flat-weaves', 'hand-tufted-carpet'],
    relatedIndustries: ['villa-carpets', 'retail-carpets', 'office-carpets'],
    relatedSolutions: ['designer-rugs', 'custom-carpets'],
  },

  {
    slug: 'commercial-carpet-manufacturer',
    kind: 'solution',
    label: 'Commercial Carpets',
    heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Contract & Commercial',
    tagline: 'Commercial carpet manufacturer supplying contract-grade flooring for projects at scale.',
    seoTitle: 'Commercial Carpet Manufacturer India | Contract Carpet Supplier — Tapis Global',
    seoDescription: 'Commercial carpet manufacturer and contract supplier in India. Durable broadloom and carpet tiles from Bhadohi for offices, hotels, retail and institutions — fire-rated, bulk, phased delivery. Request a catalogue or quote.',
    seoKeywords: ['commercial carpet manufacturer India', 'contract carpet supplier India', 'commercial carpet supplier', 'bulk carpet manufacturer', 'project carpet supplier India'],
    h1: 'Commercial Carpet Manufacturer in India',
    intro: 'Tapis Global International is a commercial carpet manufacturer supplying contract-grade flooring for projects across India and international markets. From offices and hotels to retail, institutions and transport, we manufacture durable broadloom and carpet tiles in Bhadohi at the scale and consistency commercial projects demand.',
    overview: 'Commercial flooring is judged on durability, compliance, supply reliability and total cost over its life — not just appearance. As a direct manufacturer we deliver contract-grade constructions, fire-rating, dye-lot consistency across large runs and phased delivery aligned to fit-out programmes, making us a dependable single-source partner for project teams and procurement.',
    sections: [
      { h2: 'Contract-Grade Durability', body: 'We build constructions rated for the heavy, sustained traffic of commercial environments, with fibre and backing systems chosen for service life and value — not just first cost.' },
      { h2: 'Supply Reliability at Scale', body: 'Commercial projects fail on supply gaps. Our 80,000 sq ft campus and in-house production let us hold dye-lots, manufacture in bulk and deliver in phases that match the construction programme.' },
      { h2: 'Compliance & Documentation', body: 'We provide fire-rating and the documentation commercial and institutional buyers require, and advise on the correct traffic classification for each space.' },
    ],
    applications: [
      { title: 'Offices & Workplaces', desc: 'Carpet tiles and broadloom for corporate fit-outs.' },
      { title: 'Hotels & Hospitality', desc: 'Fire-rated contract carpets for guest and public areas.' },
      { title: 'Retail & Institutions', desc: 'Durable zoned flooring for stores and public buildings.' },
      { title: 'Transport & Aviation', desc: 'Extreme-traffic constructions for terminals and transit.' },
    ],
    whyPoints: [
      { title: 'Project Reliability', desc: 'Bulk capacity, held dye-lots and phased delivery.' },
      { title: 'Compliance-Ready', desc: 'Fire-rating and documentation for commercial buyers.' },
      { title: 'Direct Pricing', desc: 'Manufacturer-direct value for contract budgets.' },
    ],
    faqs: [
      { q: 'Are you a direct commercial carpet manufacturer?', a: 'Yes. We manufacture contract-grade commercial carpets in our own Bhadohi facility — buying direct means better pricing, QC and supply control with no trading middlemen.' },
      { q: 'Can you supply fire-rated commercial carpets?', a: 'Yes. We manufacture fire-rated constructions and provide the documentation commercial and institutional buyers require.' },
      { q: 'Can you handle large project volumes and phased delivery?', a: 'Yes. Our 80,000 sq ft campus manufactures bulk volumes, holds dye-lots and delivers in phases aligned to your fit-out programme.' },
      { q: 'Do you supply both broadloom and carpet tiles?', a: 'Yes — and we hold dye-lots across both so multi-area projects stay colour-consistent.' },
      { q: 'Do you supply commercial projects internationally?', a: 'Yes. We supply contract carpets across India and export internationally with compliance documentation and coordinated freight.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'flat-weaves'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'airport-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'wholesale-carpet-supplier'],
  },

  {
    slug: 'wholesale-carpet-supplier',
    kind: 'solution',
    label: 'Wholesale Carpets',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Wholesale & Bulk',
    tagline: 'Wholesale carpet and rug supplier — bulk manufacturing direct from the Bhadohi factory.',
    seoTitle: 'Wholesale Carpet Supplier India | Bulk Carpet & Rug Manufacturer — Tapis Global',
    seoDescription: 'Wholesale carpet and rug supplier in India. Bulk manufacturing direct from Bhadohi for distributors, retailers and importers — competitive pricing, private label, consistent quality. Request a catalogue or quote.',
    seoKeywords: ['wholesale carpet supplier India', 'bulk carpet manufacturer', 'wholesale rugs supplier', 'bulk rug supplier India', 'carpet wholesaler India'],
    h1: 'Wholesale Carpet & Rug Supplier in India',
    intro: 'Tapis Global International is a wholesale carpet and rug supplier manufacturing in bulk direct from our Bhadohi factory for distributors, retailers and importers across India and international markets. Buying from the manufacturer means competitive pricing, consistent quality and private-label flexibility.',
    overview: 'Wholesale buyers need three things: dependable quality, the right price and reliable supply. Because we manufacture in-house rather than trade, we offer genuine factory pricing, batch-consistent quality across large orders, and the capacity to fulfil bulk and repeat programmes — with private-label options for retail brands.',
    sections: [
      { h2: 'Factory-Direct Pricing', body: 'No middlemen sit between you and production. Wholesale buyers get genuine manufacturer pricing with margin room intact, scaled to order volume.' },
      { h2: 'Consistent Bulk Quality', body: 'We hold dye-lots and apply multi-stage QC so large and repeat wholesale orders arrive batch-consistent — protecting your brand and your customers\' trust.' },
      { h2: 'Private Label & Repeat Supply', body: 'We offer OEM and private-label manufacturing with custom packaging, and structure repeat-supply programmes for distributors and retail chains.' },
    ],
    applications: [
      { title: 'Distributors', desc: 'Bulk, batch-consistent supply for regional distribution.' },
      { title: 'Retailers & Chains', desc: 'Private-label collections for home and lifestyle retail.' },
      { title: 'Importers', desc: 'Export-ready bulk programmes with documentation.' },
      { title: 'E-commerce Brands', desc: 'White-label rugs with custom packaging for online sellers.' },
    ],
    whyPoints: [
      { title: 'True Factory Price', desc: 'Manufacturer-direct wholesale pricing, no middlemen.' },
      { title: 'Batch Consistency', desc: 'Held dye-lots and QC across large and repeat orders.' },
      { title: 'Private Label', desc: 'OEM manufacturing with your branding and packaging.' },
    ],
    faqs: [
      { q: 'Do you sell wholesale direct from the factory?', a: 'Yes. We are the manufacturer — wholesale buyers get genuine factory-direct pricing with no trading middlemen, scaled to order volume.' },
      { q: 'Can you guarantee consistency on large wholesale orders?', a: 'Yes. We hold dye-lots and apply multi-stage QC so bulk and repeat orders arrive batch-consistent.' },
      { q: 'Do you offer private-label for retailers?', a: 'Yes. We provide OEM and private-label manufacturing with custom branding and packaging for retail and e-commerce brands.' },
      { q: 'What are your wholesale MOQs?', a: 'MOQ varies by product and construction. We structure bulk and repeat-supply programmes for distributors and chains — share your requirement for specifics.' },
      { q: 'Do you supply wholesale buyers internationally?', a: 'Yes. We manufacture export-ready bulk programmes with full documentation and coordinated freight for international importers.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'jute-sisal-rugs', 'shaggy-rugs'],
    relatedIndustries: ['retail-carpets', 'hotel-carpets', 'office-carpets'],
    relatedSolutions: ['carpet-exporter-india', 'commercial-carpet-manufacturer'],
  },

  {
    slug: 'carpet-exporter-india',
    kind: 'solution',
    label: 'Carpet Exporter',
    heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'International Supply',
    tagline: 'Carpet and rug exporter from India supplying international buyers with documentation and reliability.',
    seoTitle: 'Carpet Exporter India | Rug Exporter from Bhadohi — Tapis Global International',
    seoDescription: 'Carpet and rug exporter from India. Bhadohi-manufactured carpets exported to international buyers with full compliance documentation, export packing and coordinated freight. Request a catalogue or quote.',
    seoKeywords: ['carpet exporter India', 'rug exporter India', 'carpet exporter Bhadohi', 'Indian carpet exporter', 'export quality carpets India'],
    h1: 'Carpet & Rug Exporter from India',
    intro: 'Tapis Global International is a carpet and rug exporter based in Bhadohi, India, supplying international buyers, importers and distributors. While most of our supply serves projects across India, we run established export programmes with the documentation, packing and freight coordination international trade requires.',
    overview: 'Exporting handmade carpets reliably is about more than production — it is documentation, compliance, consistent quality and dependable logistics. As a manufacturer-exporter we handle the full chain in-house: producing to specification, meeting destination requirements, packing for international transit and coordinating freight, so overseas buyers receive the right product, on time, with the right paperwork.',
    sections: [
      { h2: 'Export Documentation & Compliance', body: 'We provide the commercial and compliance documentation international shipments require and manufacture to destination-market standards, including fire-rating where specified.' },
      { h2: 'Quality You Can Rely On Remotely', body: 'Buying from overseas means trusting quality you cannot inspect in person before dispatch. Our multi-stage QC and batch consistency give international buyers confidence in every shipment.' },
      { h2: 'Packing & Freight Coordination', body: 'We pack carpets for safe international transit and coordinate freight, working to your preferred terms so delivery is smooth and predictable.' },
    ],
    applications: [
      { title: 'International Importers', desc: 'Bulk export programmes with full documentation.' },
      { title: 'Overseas Distributors', desc: 'Consistent, repeat export supply for regional markets.' },
      { title: 'Global Hospitality', desc: 'Project carpet export for international hotel groups.' },
      { title: 'Retail & E-commerce', desc: 'Export-ready private-label rug programmes.' },
    ],
    whyPoints: [
      { title: 'Full Documentation', desc: 'Compliance and commercial paperwork for export.' },
      { title: 'Remote-Trust Quality', desc: 'Multi-stage QC and batch consistency for overseas buyers.' },
      { title: 'Logistics Handled', desc: 'Export packing and coordinated freight to your terms.' },
    ],
    faqs: [
      { q: 'Do you export carpets internationally?', a: 'Yes. Alongside extensive pan-India supply, we run established export programmes for international importers, distributors and projects with full documentation.' },
      { q: 'What documentation do you provide for exports?', a: 'We provide the commercial and compliance documentation international shipments require and manufacture to destination-market standards, including fire-rating where specified.' },
      { q: 'How do you ensure quality for overseas buyers?', a: 'Multi-stage in-house QC and held dye-lots ensure batch-consistent quality, giving international buyers confidence in every shipment.' },
      { q: 'Do you handle export packing and freight?', a: 'Yes. We pack carpets for safe international transit and coordinate freight to your preferred terms.' },
      { q: 'What payment terms do you accept for exports?', a: 'We accept bank transfer (TT), Letters of Credit (LC), DA and DP, and deal in USD, EUR, GBP and INR. Terms are negotiable for established buyers.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'hand-tufted-carpet', 'jute-sisal-rugs'],
    relatedIndustries: ['hotel-carpets', 'retail-carpets', 'villa-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'commercial-carpet-manufacturer'],
  },

  {
    slug: 'contract-carpet-supplier',
    kind: 'solution',
    label: 'Contract Carpets',
    heroImage: '/images/tufting-carpet.webp',
    eyebrow: 'Specification & Tender',
    tagline: 'Contract carpet supplier for specification-led projects, tenders and large fit-outs.',
    seoTitle: 'Contract Carpet Supplier India | Specification & Tender Carpets — Tapis Global',
    seoDescription: 'Contract carpet supplier in India for specification-led projects and tenders. Bhadohi-manufactured broadloom, tiles and custom carpets with compliance documentation, bulk capacity and phased delivery. Request a quote.',
    seoKeywords: ['contract carpet supplier India', 'tender carpet supplier', 'specification carpet manufacturer', 'project carpet supplier', 'institutional carpet supplier India'],
    h1: 'Contract Carpet Supplier for Projects & Tenders',
    intro: 'Tapis Global International is a contract carpet supplier for specification-led projects, tenders and large fit-outs across India and international markets. We manufacture to written specifications in Bhadohi and support project teams, consultants and procurement with documentation, samples and phased delivery.',
    overview: 'Contract and tender work demands precision: carpets manufactured to a written spec, compliant documentation, samples for approval, competitive pricing within budget and delivery that hits programme dates. As a direct manufacturer we meet specifications exactly and provide the support that helps consultants and procurement teams specify, approve and deliver with confidence.',
    sections: [
      { h2: 'Manufactured to Specification', body: 'We produce to your written specification — fibre, weight, construction, fire-rating, colour and pattern — and provide samples and documentation for approval and tender submission.' },
      { h2: 'Tender & Procurement Support', body: 'We support tender processes with specification sheets, samples and competitive quotations, and work transparently with consultants and procurement teams throughout.' },
      { h2: 'On-Programme Delivery', body: 'Project timelines are fixed. We plan production and phased dispatch to hit your programme dates, holding dye-lots so later phases match earlier ones.' },
    ],
    applications: [
      { title: 'Institutional Tenders', desc: 'Spec-compliant carpets for government and public projects.' },
      { title: 'Large Fit-Outs', desc: 'Bulk contract supply with phased, on-programme delivery.' },
      { title: 'Consultant-Led Projects', desc: 'Manufacturing to architect and consultant specifications.' },
      { title: 'Multi-Phase Developments', desc: 'Colour-consistent supply across long project timelines.' },
    ],
    whyPoints: [
      { title: 'Spec-Exact', desc: 'Manufactured precisely to written project specifications.' },
      { title: 'Tender-Ready', desc: 'Documentation, samples and competitive quotations.' },
      { title: 'On-Time Delivery', desc: 'Phased dispatch planned to hit programme dates.' },
    ],
    faqs: [
      { q: 'Do you manufacture to a written specification?', a: 'Yes. We produce to your exact written spec — fibre, weight, construction, fire-rating, colour and pattern — and provide samples and documentation for approval.' },
      { q: 'Can you support a tender submission?', a: 'Yes. We supply specification sheets, samples and competitive quotations, and work transparently with consultants and procurement throughout the tender.' },
      { q: 'Can you meet fixed project programme dates?', a: 'Yes. We plan production and phased dispatch to hit your programme, holding dye-lots so later phases match earlier ones.' },
      { q: 'Do you handle government and institutional projects?', a: 'Yes. We supply spec-compliant carpets for government, institutional and public-sector projects with the required documentation.' },
      { q: 'Can you provide samples for approval before contract award?', a: 'Yes. We provide samples and lab-dips for approval at specification and pre-award stages.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'coco-coir'],
    relatedIndustries: ['office-carpets', 'school-carpets', 'hospital-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'wholesale-carpet-supplier'],
  },
]
