import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// USA state landing pages — /usa/[state]
//
// Positioning (stated honestly, same discipline as lib/india.ts): Tapis Global
// International MANUFACTURES made-to-order carpets and rugs in Bhadohi, India,
// and PRODUCES FOR B2B buyers and projects across the United States. We are a
// manufacturer/supplier, not a ready-stock retailer, and have no physical
// presence in any US state — every shipment is coordinated from Bhadohi.
//
// Each state is written around ITS OWN real, defensible commercial-buyer
// profile, census division and design angle — not a templated name-swap. See
// the seo:audit near-duplicate gate (npm run seo:audit) for the mechanical
// backstop on this.
//
// Claim discipline: no fabricated state-specific statistics, no local offices/
// warehouses/showrooms, no invented client names or delivery-day promises.
// MOQ/production/delivery come from the shared lib/export-capability.ts block.
// ─────────────────────────────────────────────────────────────────────────────

export const USA_HUB_INTRO =
  'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi, India, and produces for commercial buyers and projects across the United States — hotels, interior designers, builders, luxury homes, corporate offices, hospitality groups, importers and trade buyers nationwide. We are a manufacturer and supplier, not a ready-stock retailer: every order is made to its own design, size, colour, material and quantity.'

const PRODUCTS_CORE = ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets']

export const USA_STATES: SeoLanding[] = [
  {
    slug: 'new-york',
    kind: 'usa-state',
    label: 'New York',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for New York',
    tagline: 'Made-to-order carpet and rug manufacturer producing for New York\'s corporate towers, luxury residences, hotels and design studios.',
    seoTitle: 'Carpet Manufacturer for New York | Custom Rugs & Contract Carpet — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for New York State. Custom hand knotted, hand tufted and wall-to-wall carpets from Bhadohi for corporate offices, luxury homes, hotels, designers and wholesale buyers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer New York', 'custom rug supplier New York', 'hotel carpet manufacturer NY', 'wholesale carpet supplier New York', 'contract carpet New York'],
    h1: 'Carpet & Rug Manufacturer for New York',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers and projects across New York State — global corporate headquarters, luxury residential towers, boutique and flagship hotels, top interior design studios and wholesale importers. Each order is made to your design, size and specification; we hold no ready stock.',
    overview: 'New York concentrates more global corporate headquarters, luxury high-rise residential development and design-forward hospitality than almost any other US market. As a manufacturer we make custom hand knotted and hand tufted rugs, wall-to-wall broadloom and bespoke statement pieces to the exacting brief this market expects — developed in Bhadohi and shipped to New York with full commercial and compliance documentation.',
    sections: [
      { h2: 'Corporate Towers & Luxury Residential', body: 'Manhattan and the wider state combine dense corporate fit-out demand with some of the country\'s highest-value residential real estate. We manufacture carpet tiles and broadloom to exact specification for corporate towers, and bespoke hand knotted rugs to precise colour and dimension for penthouses and luxury apartments.' },
      { h2: 'Design-Led Hospitality', body: 'New York\'s hotel and hospitality scene sets design trends nationally. We develop custom, design-forward carpets to a design studio\'s mood board and Pantone references, with fire-safety construction specified per project where required.' },
    ],
    applications: [
      { title: 'Corporate Offices', desc: 'Carpet tiles and broadloom to precise fit-out specification.' },
      { title: 'Luxury Residential', desc: 'Bespoke rugs for penthouses and high-rise apartments.' },
      { title: 'Hotels & Hospitality', desc: 'Design-forward custom carpets for New York hospitality.' },
      { title: 'Interior Design Studios', desc: 'Development to exact mood boards and Pantone references.' },
    ],
    whyPoints: [
      { title: 'Manufacturer-Direct', desc: 'Made in our own Bhadohi facility, no middlemen.' },
      { title: 'Design-Studio Ready', desc: 'Lab-dips, samples and Pantone-matched development.' },
      { title: 'Fully Custom', desc: 'Any size, colour, construction and quantity to brief.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for New York projects?', a: 'Yes. We manufacture made-to-order carpets and rugs in Bhadohi for corporate, residential, hospitality and design projects across New York State, and can advise on documentation and logistics for your enquiry.' },
      { q: 'Can you develop a rug to our design studio\'s Pantone references?', a: 'Yes. We develop lab-dips and a sample against your exact colour references before bulk production.' },
      { q: 'Do you supply carpet tiles for corporate fit-outs?', a: 'Yes. We manufacture broadloom and carpet tiles to your specification for office fit-outs, with dye-lot consistency across large orders.' },
      { q: 'Can you produce a one-of-a-kind rug for a Manhattan residence?', a: 'Yes. We craft bespoke single pieces — you choose material, size, colour and construction, and we develop a sample for approval before crafting it.' },
      { q: 'Do you offer wholesale or private-label programmes for New York importers?', a: 'Yes. We provide OEM and private-label manufacturing with custom branding and packaging, alongside bulk wholesale programmes.' },
      { q: 'How is shipping to New York handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for New York buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'villa-carpets'],
    relatedSolutions: ['designer-rugs', 'commercial-carpet-manufacturer'],
    relatedCompany: ['oem-private-label'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['new-jersey', 'pennsylvania', 'connecticut'],
    censusDivision: 'Mid-Atlantic',
    childUsaCities: ['new-york-city'],
    importProcess: 'We confirm specification, construction and quantity, then develop lab-dips and a sample for sign-off before production begins — the same process whether the order is a single bespoke rug for a residence or a bulk programme for a corporate fit-out. Production runs with staged quality checks and a documented pre-dispatch inspection before anything leaves Bhadohi.',
    shipping: 'Freight is coordinated to New York-area ports, with container programmes for importers and wholesale buyers and smaller consolidated shipments for individual design and residential orders. Documentation is prepared to support smooth US customs clearance.',
    leadTime: 'Because every piece is made to order, lead time follows the construction, size and quantity specified — confirmed once your specification and samples are approved, not before.',
    popularStyles: ['Design-forward hand-tufted rugs', 'Bespoke hand-knotted statement pieces', 'Carpet tiles for corporate fit-outs', 'Contemporary wool-viscose blends', 'Custom broadloom for luxury towers'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Carpet tiles and broadloom manufactured to precise fit-out specification for New York corporate towers.' },
      { label: 'Interior Designers', body: 'Bespoke rugs developed to mood boards and Pantone references for New York residential and boutique commercial projects.' },
      { label: 'Hotels', body: 'Design-forward custom carpet for New York hospitality guestrooms and public areas.' },
      { label: 'Luxury Homes', body: 'Opulent bespoke rugs for penthouses and high-value residential interiors.' },
      { label: 'Builders', body: 'Rug and carpet supply coordinated with fit-out schedules for residential and commercial developments.' },
      { label: 'Hospitality', body: 'Made-to-order contract carpet for New York\'s hotel, restaurant and hospitality sector.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for New York importers and distributors.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with your branding and packaging, under confidentiality.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation and phased delivery for large New York projects.' },
    ],
    customSizesNote: 'We manufacture to US standard rug dimensions and runner formats as well as fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['nz-wool', 'wool-viscose', 'bamboo-silk', 'pet'],
  },
  {
    slug: 'new-jersey',
    kind: 'usa-state',
    label: 'New Jersey',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for New Jersey',
    tagline: 'Made-to-order carpet and rug manufacturer producing for New Jersey\'s corporate campuses, suburban luxury homes and import trade.',
    seoTitle: 'Carpet Manufacturer for New Jersey | Corporate & Wholesale Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for New Jersey. Custom hand tufted, wall-to-wall and wholesale carpets from Bhadohi for corporate campuses, luxury homes and import trade buyers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer New Jersey', 'wholesale carpet supplier NJ', 'corporate carpet New Jersey', 'custom rugs New Jersey', 'import carpet supplier NJ'],
    h1: 'Carpet & Rug Manufacturer for New Jersey',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across New Jersey — corporate campuses, suburban luxury residences, hospitality projects and the state\'s substantial import and distribution trade. Each order is made to your specification; we hold no ready stock.',
    overview: 'New Jersey pairs a dense concentration of pharmaceutical, logistics and corporate campus headquarters with affluent suburban residential markets and one of the country\'s busiest import gateways. As a manufacturer we supply corporate carpet tile programmes, bespoke residential rugs and bulk wholesale/import programmes routed efficiently through the region\'s ports.',
    sections: [
      { h2: 'Corporate Campuses & Suburban Luxury', body: 'New Jersey\'s corporate campuses call for consistent, contract-grade carpet tile and broadloom across large floorplates, while its affluent suburbs specify bespoke residential rugs. We manufacture both to exact specification, with dye-lot consistency across large orders.' },
      { h2: 'Import & Distribution Gateway', body: 'As a key East Coast import corridor, New Jersey is a natural fit for our wholesale and private-label programmes — bulk, batch-consistent supply for distributors and retail buyers, with freight routed efficiently through the region\'s ports.' },
    ],
    applications: [
      { title: 'Corporate Campuses', desc: 'Contract-grade carpet tile and broadloom for large fit-outs.' },
      { title: 'Suburban Luxury Homes', desc: 'Bespoke rugs for New Jersey\'s affluent residential market.' },
      { title: 'Importers & Distributors', desc: 'Bulk, batch-consistent wholesale programmes.' },
      { title: 'Hospitality', desc: 'Made-to-order contract carpets for hotels and event venues.' },
    ],
    whyPoints: [
      { title: 'Import-Ready', desc: 'Freight routed efficiently through regional ports.' },
      { title: 'Batch Consistency', desc: 'Held dye-lots and QC across large corporate orders.' },
      { title: 'Manufacturer-Direct', desc: 'Factory-direct pricing with no trading middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for New Jersey buyers?', a: 'Yes. We manufacture made-to-order carpets and rugs in Bhadohi for corporate, residential, hospitality and wholesale buyers across New Jersey.' },
      { q: 'Can you supply large corporate campus fit-outs?', a: 'Yes. We manufacture carpet tile and broadloom to specification with held dye-lots for colour consistency across large floorplates.' },
      { q: 'Do you offer wholesale programmes for New Jersey importers?', a: 'Yes. We provide bulk, batch-consistent wholesale supply and private-label manufacturing with custom branding and packaging.' },
      { q: 'Can you develop bespoke rugs for suburban residential projects?', a: 'Yes. We develop lab-dips and samples to exact colour and size before bulk production.' },
      { q: 'How is shipping to New Jersey arranged?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for New Jersey buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['office-carpets', 'villa-carpets', 'retail-carpets'],
    relatedSolutions: ['wholesale-carpet-supplier', 'commercial-carpet-manufacturer'],
    relatedCompany: ['oem-private-label'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['new-york', 'pennsylvania', 'connecticut'],
    censusDivision: 'Mid-Atlantic',
    importProcess: 'We confirm specification and volume, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection — the same disciplined process for a bulk wholesale programme as for a single bespoke residential rug.',
    shipping: 'Freight is coordinated efficiently through East Coast ports serving New Jersey, with container programmes for importers and distributors and consolidated shipments for smaller residential and design orders.',
    leadTime: 'Production timelines follow construction, size and order volume, and are confirmed once specification and samples are approved — larger wholesale programmes are scheduled with phased dispatch where needed.',
    popularStyles: ['Contract carpet tile for corporate campuses', 'Bespoke suburban residential rugs', 'Bulk wholesale collections', 'Durable wall-to-wall broadloom', 'Private-label retail programmes'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Carpet tile and broadloom manufactured to specification for corporate campus fit-outs.' },
      { label: 'Wholesale', body: 'Bulk, batch-consistent programmes for New Jersey importers and distributors.' },
      { label: 'Luxury Homes', body: 'Bespoke rugs developed for New Jersey\'s affluent suburban residential market.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging for retail brands.' },
      { label: 'Interior Designers', body: 'Custom rugs developed to exact colour and design briefs for residential and commercial schemes.' },
      { label: 'Builders', body: 'Rug and carpet supply coordinated with build schedules for residential and commercial developments.' },
      { label: 'Hospitality', body: 'Made-to-order contract carpet for hotels and event venues.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for corporate and institutional projects.' },
    ],
    customSizesNote: 'We manufacture to US standard rug and carpet-tile dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['indian-wool', 'pet', 'jute'],
  },
  {
    slug: 'pennsylvania',
    kind: 'usa-state',
    label: 'Pennsylvania',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Pennsylvania',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Pennsylvania\'s historic institutions, corporate offices and hospitality.',
    seoTitle: 'Carpet Manufacturer for Pennsylvania | Institutional & Contract Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Pennsylvania. Custom hand tufted, wall-to-wall and contract carpets from Bhadohi for universities, historic institutions, corporate offices and hospitality. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Pennsylvania', 'contract carpet supplier PA', 'institutional carpet Pennsylvania', 'custom rugs Pennsylvania', 'hotel carpet supplier Pennsylvania'],
    h1: 'Carpet & Rug Manufacturer for Pennsylvania',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Pennsylvania — universities, historic institutions, corporate offices and a growing hospitality sector spanning Philadelphia and Pittsburgh. Each order is made to your specification; we hold no ready stock.',
    overview: 'Pennsylvania\'s market is defined by a dense concentration of historic institutional buildings, universities and hospitals alongside a revitalised corporate office sector in Philadelphia and Pittsburgh. As a manufacturer we make carpets suited to both — durable institutional constructions for heritage buildings, and contract-grade contemporary carpet for corporate fit-outs.',
    sections: [
      { h2: 'Historic Institutions & Universities', body: 'Pennsylvania\'s universities, hospitals and heritage civic buildings need carpet that respects the interior while meeting institutional durability and traffic requirements. We manufacture to specification, including classical pattern development for heritage settings.' },
      { h2: 'Corporate & Hospitality Revival', body: 'Philadelphia and Pittsburgh\'s corporate office and boutique hospitality sectors are growing steadily. We supply contract-grade broadloom and carpet tile for offices, and design-led custom carpets for boutique hotels.' },
    ],
    applications: [
      { title: 'Universities & Institutions', desc: 'Durable, specification-compliant carpet for campus and civic buildings.' },
      { title: 'Corporate Offices', desc: 'Contract-grade broadloom and tile for Philadelphia and Pittsburgh fit-outs.' },
      { title: 'Boutique Hospitality', desc: 'Design-led custom carpets for growing hotel and restaurant sectors.' },
      { title: 'Heritage Interiors', desc: 'Classical pattern development suited to historic buildings.' },
    ],
    whyPoints: [
      { title: 'Institutional-Grade', desc: 'Durable constructions for high-traffic campus and civic use.' },
      { title: 'Heritage-Appropriate', desc: 'Classical and traditional pattern development.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Pennsylvania institutions?', a: 'Yes. We manufacture made-to-order carpets to specification for universities, hospitals and civic buildings across Pennsylvania, and can advise on documentation for your enquiry.' },
      { q: 'Can you develop carpet suited to a historic building?', a: 'Yes. We develop classical and traditional pattern work suited to heritage interiors, alongside contemporary constructions for modern fit-outs.' },
      { q: 'Do you supply corporate offices in Philadelphia and Pittsburgh?', a: 'Yes. We manufacture contract-grade broadloom and carpet tile to specification for corporate fit-outs.' },
      { q: 'Can you support institutional tenders and procurement?', a: 'Yes. We produce to documented specification and can supply samples and specification sheets to support tender submissions.' },
      { q: 'How is shipping to Pennsylvania handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for Pennsylvania buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['office-carpets', 'school-carpets', 'hotel-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'commercial-carpet-manufacturer'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['new-jersey', 'new-york', 'connecticut'],
    censusDivision: 'Mid-Atlantic',
    childUsaCities: ['philadelphia'],
    importProcess: 'We confirm specification against the project\'s institutional or corporate requirements, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment.',
    shipping: 'Freight is coordinated to Pennsylvania-serving East Coast ports, with phased dispatch available for large institutional and corporate programmes.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved — institutional projects with fixed programme dates are planned with that timeline in mind from the outset.',
    popularStyles: ['Classical institutional patterns', 'Contract-grade broadloom for offices', 'Durable campus carpet tile', 'Boutique hospitality custom rugs', 'Heritage-appropriate traditional weaves'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Contract-grade broadloom and carpet tile for Philadelphia and Pittsburgh corporate fit-outs.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for institutional and civic projects.' },
      { label: 'Hospitality', body: 'Design-led custom carpet for Pennsylvania\'s growing boutique hotel and restaurant sector.' },
      { label: 'Builders', body: 'Carpet supply coordinated with build and renovation schedules for institutional and commercial projects.' },
      { label: 'Interior Designers', body: 'Heritage-appropriate and contemporary rugs developed to project-specific briefs.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Pennsylvania distributors and trade buyers.' },
      { label: 'Luxury Homes', body: 'Bespoke rugs for Pennsylvania\'s historic and contemporary luxury residences.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging, under confidentiality.' },
    ],
    customSizesNote: 'We manufacture to institutional and US standard dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['indian-wool', 'wool-viscose', 'jute'],
  },
  {
    slug: 'connecticut',
    kind: 'usa-state',
    label: 'Connecticut',
    heroImage: '/images/tgi-banner-4.webp',
    eyebrow: 'Carpets & Rugs for Connecticut',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Connecticut\'s finance-sector offices and affluent residences.',
    seoTitle: 'Carpet Manufacturer for Connecticut | Corporate & Luxury Home Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Connecticut. Custom hand knotted, hand tufted and contract carpets from Bhadohi for corporate offices, affluent homes and boutique hospitality. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Connecticut', 'luxury rug supplier Connecticut', 'corporate carpet Connecticut', 'custom rugs Connecticut', 'hotel carpet supplier CT'],
    h1: 'Carpet & Rug Manufacturer for Connecticut',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Connecticut — finance and insurance sector corporate offices, affluent residential communities and boutique hospitality. Each order is made to your specification; we hold no ready stock.',
    overview: 'Connecticut combines a dense finance and insurance corporate sector centred on Hartford and Stamford with some of the country\'s most affluent residential communities. As a manufacturer we supply understated, high-quality contract carpet for corporate offices and bespoke rugs for the state\'s luxury residential market.',
    sections: [
      { h2: 'Finance-Sector Corporate Offices', body: 'Connecticut\'s insurance and finance corporate headquarters expect refined, low-key carpet that performs in demanding office environments. We manufacture contract-grade broadloom and tile to specification, with dye-lot consistency for multi-floor fit-outs.' },
      { h2: 'Affluent Residential Communities', body: 'Connecticut\'s established residential communities favour understated, high-quality rugs over ostentation. We develop bespoke wool and wool-silk pieces to exact colour and design, working directly with the designers who specify them.' },
    ],
    applications: [
      { title: 'Corporate Offices', desc: 'Refined contract carpet for finance and insurance-sector fit-outs.' },
      { title: 'Affluent Residences', desc: 'Bespoke understated rugs for Connecticut\'s luxury homes.' },
      { title: 'Interior Designers', desc: 'Custom development to designer briefs and Pantone references.' },
      { title: 'Boutique Hospitality', desc: 'Design-led carpet for Connecticut\'s hotel and inn sector.' },
    ],
    whyPoints: [
      { title: 'Refined & Understated', desc: 'Quality-first design suited to Connecticut\'s taste.' },
      { title: 'Corporate-Ready', desc: 'Contract-grade constructions with dye-lot consistency.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Connecticut buyers?', a: 'Yes. We manufacture made-to-order carpets and rugs in Bhadohi for corporate, residential and hospitality projects across Connecticut.' },
      { q: 'Can you supply corporate office fit-outs in Hartford or Stamford?', a: 'Yes. We manufacture contract-grade broadloom and carpet tile to specification, with dye-lot consistency across multi-floor orders.' },
      { q: 'Can you develop a bespoke rug for a Connecticut residence?', a: 'Yes. We develop lab-dips and a sample against your exact colour and design references before production.' },
      { q: 'Do you work with interior designers on Connecticut projects?', a: 'Yes. We collaborate directly with designers, developing rugs to mood boards and Pantone references.' },
      { q: 'How is shipping to Connecticut arranged?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for Connecticut buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['office-carpets', 'villa-carpets', 'hotel-carpets'],
    relatedSolutions: ['luxury-carpets', 'designer-rugs'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['new-york', 'massachusetts', 'rhode-island'],
    censusDivision: 'New England',
    importProcess: 'We confirm specification and colour requirements, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection — a consistent process whether the order is a single bespoke residential rug or a multi-floor corporate programme.',
    shipping: 'Freight is coordinated to Connecticut-serving Northeast ports, with consolidated shipments for smaller design and residential orders and larger programmes for corporate fit-outs.',
    leadTime: 'Lead time follows the construction, size and quantity specified and is confirmed once specification and samples are approved.',
    popularStyles: ['Understated corporate broadloom', 'Bespoke wool and wool-silk residential rugs', 'Refined neutral-palette pieces', 'Boutique hospitality custom carpet', 'Traditional New England-appropriate weaves'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Refined contract-grade carpet for Connecticut\'s finance and insurance-sector fit-outs.' },
      { label: 'Luxury Homes', body: 'Bespoke understated rugs developed for Connecticut\'s affluent residential communities.' },
      { label: 'Interior Designers', body: 'Custom rugs developed to mood boards and Pantone references for residential and boutique projects.' },
      { label: 'Hospitality', body: 'Design-led custom carpet for Connecticut\'s hotel and inn sector.' },
      { label: 'Builders', body: 'Rug and carpet supply coordinated with build schedules for residential developments.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production for corporate and institutional projects.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Connecticut trade buyers.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging.' },
    ],
    customSizesNote: 'We manufacture to US standard rug dimensions as well as fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['nz-wool', 'wool-viscose', 'indian-wool'],
  },
  {
    slug: 'massachusetts',
    kind: 'usa-state',
    label: 'Massachusetts',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'Carpets & Rugs for Massachusetts',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Massachusetts\' universities, biotech campuses and historic residences.',
    seoTitle: 'Carpet Manufacturer for Massachusetts | Institutional & Boston Contract Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Massachusetts. Custom hand tufted, wall-to-wall and institutional carpets from Bhadohi for universities, biotech campuses, historic homes and Boston hospitality. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Massachusetts', 'contract carpet supplier Boston', 'university carpet supplier MA', 'custom rugs Massachusetts', 'hotel carpet supplier Boston'],
    h1: 'Carpet & Rug Manufacturer for Massachusetts',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Massachusetts — universities, biotech and healthcare corporate campuses, historic Back Bay and Beacon Hill residences, and Boston\'s hospitality sector. Each order is made to your specification; we hold no ready stock.',
    overview: 'Massachusetts is defined by an unusually dense concentration of universities, teaching hospitals and biotech corporate campuses, layered over historic residential neighbourhoods and a design-conscious hospitality scene. As a manufacturer we supply durable institutional carpet for campus and healthcare settings, and heritage-appropriate bespoke rugs for the state\'s historic homes.',
    sections: [
      { h2: 'Universities, Hospitals & Biotech Campuses', body: 'Massachusetts\' institutional density calls for durable, specification-compliant carpet across high-traffic academic, healthcare and corporate-campus settings. We manufacture to exact specification with documentation for procurement teams.' },
      { h2: 'Historic Residences & Boston Hospitality', body: 'Back Bay and Beacon Hill\'s historic residences favour classical, heritage-appropriate rugs, while Boston\'s hotels increasingly specify design-forward custom carpet. We develop both to precise brief.' },
    ],
    applications: [
      { title: 'Universities & Institutions', desc: 'Durable, specification-compliant carpet for academic settings.' },
      { title: 'Healthcare & Biotech Campuses', desc: 'Documented contract carpet for institutional environments.' },
      { title: 'Historic Residences', desc: 'Heritage-appropriate bespoke rugs for Back Bay and Beacon Hill.' },
      { title: 'Boston Hospitality', desc: 'Design-forward custom carpet for hotels and restaurants.' },
    ],
    whyPoints: [
      { title: 'Institutional-Grade', desc: 'Durable constructions for academic and healthcare traffic.' },
      { title: 'Heritage-Appropriate', desc: 'Classical pattern development for historic interiors.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Massachusetts institutions?', a: 'Yes. We manufacture made-to-order carpets to specification for universities, hospitals and biotech campuses across Massachusetts.' },
      { q: 'Can you develop a rug suited to a historic Back Bay or Beacon Hill home?', a: 'Yes. We develop classical and traditional pattern work to precise colour and design for heritage residential interiors.' },
      { q: 'Do you supply Boston hotels and hospitality?', a: 'Yes. We manufacture design-forward custom carpet to a hotel\'s brief, with fire-safety construction specified per project.' },
      { q: 'Can you support institutional procurement and tenders?', a: 'Yes. We produce to documented specification and can supply samples and specification sheets to support tender submissions.' },
      { q: 'How is shipping to Massachusetts handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for Massachusetts buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['school-carpets', 'office-carpets', 'hotel-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'designer-rugs'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['connecticut', 'rhode-island', 'new-hampshire'],
    censusDivision: 'New England',
    childUsaCities: ['boston'],
    importProcess: 'We confirm specification against the institution\'s or project\'s requirements, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment.',
    shipping: 'Freight is coordinated to Massachusetts-serving Northeast ports, with phased dispatch available for large institutional programmes and consolidated shipments for smaller residential orders.',
    leadTime: 'Production timelines follow construction, size and quantity, and are confirmed once specification and samples are approved — institutional projects with fixed academic-calendar or programme dates are planned around accordingly.',
    popularStyles: ['Durable institutional-grade carpet', 'Classical heritage residential rugs', 'Design-forward Boston hospitality carpet', 'Biotech and healthcare campus carpet tile', 'Traditional New England pattern work'],
    buyerSegments: [
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for university, hospital and biotech-campus projects.' },
      { label: 'Corporate Offices', body: 'Contract-grade carpet tile and broadloom for Boston-area corporate fit-outs.' },
      { label: 'Luxury Homes', body: 'Heritage-appropriate bespoke rugs for Back Bay and Beacon Hill residences.' },
      { label: 'Hospitality', body: 'Design-forward custom carpet for Boston\'s hotel and restaurant sector.' },
      { label: 'Interior Designers', body: 'Custom rugs developed to heritage and contemporary Massachusetts design briefs.' },
      { label: 'Builders', body: 'Carpet supply coordinated with build and renovation schedules for institutional and residential projects.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Massachusetts distributors.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging, under confidentiality.' },
    ],
    customSizesNote: 'We manufacture to institutional and US standard dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['indian-wool', 'nz-wool', 'jute'],
  },
  {
    slug: 'rhode-island',
    kind: 'usa-state',
    label: 'Rhode Island',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Carpets & Rugs for Rhode Island',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Rhode Island\'s historic mansions and coastal boutique hospitality.',
    seoTitle: 'Carpet Manufacturer for Rhode Island | Historic Home & Coastal Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Rhode Island. Custom hand knotted and natural-fibre carpets from Bhadohi for Newport mansions, coastal boutique hotels and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Rhode Island', 'Newport mansion carpet supplier', 'custom rugs Rhode Island', 'boutique hotel carpet Rhode Island', 'historic home rugs Providence'],
    h1: 'Carpet & Rug Manufacturer for Rhode Island',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Rhode Island — historic Newport mansions, coastal boutique hotels and inns, and Providence-area designers. Each order is made to your specification; we hold no ready stock.',
    overview: 'Rhode Island is small but distinctive: its historic Newport mansions and grand estates call for museum-quality heritage rugs, while its coastal boutique hospitality sector favours relaxed, characterful carpet. As a manufacturer we develop both from Bhadohi, working closely with the designers and property owners who specify them.',
    sections: [
      { h2: 'Newport Mansions & Grand Estates', body: 'Rhode Island\'s historic Gilded Age mansions and grand estates specify museum-quality hand knotted rugs — classical reproductions and bespoke commissions developed to exact colour and pattern for architecturally significant interiors.' },
      { h2: 'Coastal Boutique Hospitality', body: 'Providence and Rhode Island\'s coastal boutique hotels and inns favour relaxed, characterful carpet in natural fibres. We develop made-to-order pieces suited to this coastal aesthetic.' },
    ],
    applications: [
      { title: 'Historic Mansions & Estates', desc: 'Museum-quality bespoke rugs for Newport\'s grand interiors.' },
      { title: 'Coastal Boutique Hotels', desc: 'Relaxed, characterful carpet for Rhode Island\'s inn sector.' },
      { title: 'Interior Designers', desc: 'Heritage and contemporary development to exact briefs.' },
      { title: 'Luxury Homes', desc: 'Bespoke rugs for Rhode Island\'s coastal residences.' },
    ],
    whyPoints: [
      { title: 'Heritage Craft', desc: 'Museum-quality hand knotted rugs for historic interiors.' },
      { title: 'Coastal Character', desc: 'Relaxed natural-fibre pieces for boutique hospitality.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Rhode Island properties?', a: 'Yes. We manufacture made-to-order carpets and rugs in Bhadohi for historic estates, boutique hospitality and residential projects across Rhode Island.' },
      { q: 'Can you develop a rug for a historic Newport mansion?', a: 'Yes. We develop classical reproductions and bespoke hand knotted commissions to exact colour and pattern for architecturally significant interiors.' },
      { q: 'Do you supply coastal boutique hotels?', a: 'Yes. We manufacture made-to-order carpet in natural fibres suited to Rhode Island\'s relaxed coastal hospitality aesthetic.' },
      { q: 'Can you match a mansion\'s existing period pattern?', a: 'Yes. We develop lab-dips and samples to closely match colour and pattern references before production.' },
      { q: 'How is shipping to Rhode Island handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for Rhode Island buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: ['hand-knotted-carpet', 'jute-sisal-rugs', 'hand-tufted-carpet'],
    relatedIndustries: ['villa-carpets', 'hotel-carpets', 'restaurant-carpets'],
    relatedSolutions: ['luxury-carpets', 'designer-rugs'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['massachusetts', 'connecticut', 'new-hampshire'],
    censusDivision: 'New England',
    importProcess: 'We confirm the design reference — a period pattern, a mood board or a coastal-hospitality brief — develop lab-dips and a hand-knotted or hand-tufted sample for approval, then produce with staged quality checks before a documented pre-dispatch inspection.',
    shipping: 'Freight is coordinated to Rhode Island-serving Northeast ports, with individual pieces for historic-estate commissions packed to protect fine knotting during transit.',
    leadTime: 'Lead time follows the construction, size and quantity specified, and is confirmed once specification and samples are approved — bespoke heritage commissions are scheduled with the additional time fine hand-knotting requires.',
    popularStyles: ['Museum-quality classical reproductions', 'Bespoke heritage-estate commissions', 'Natural-fibre coastal hospitality pieces', 'Relaxed characterful boutique rugs', 'Hand-knotted period-pattern rugs'],
    buyerSegments: [
      { label: 'Luxury Homes', body: 'Museum-quality bespoke rugs for Newport mansions and grand coastal estates.' },
      { label: 'Interior Designers', body: 'Heritage and contemporary rugs developed to exact colour and pattern references.' },
      { label: 'Hospitality', body: 'Relaxed, natural-fibre carpet for Rhode Island\'s coastal boutique inns and hotels.' },
      { label: 'Builders', body: 'Rug supply coordinated with restoration and renovation schedules for historic properties.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct supply for Rhode Island trade and boutique retail buyers.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding for boutique hospitality and retail brands.' },
    ],
    customSizesNote: 'We manufacture fully bespoke sizes and shapes to match historic estate floor plans, with samples approved before production begins.',
    materialRecommendations: ['nz-wool', 'bamboo-silk', 'jute'],
  },
  {
    slug: 'vermont',
    kind: 'usa-state',
    label: 'Vermont',
    heroImage: '/images/tgi-banner-7.webp',
    eyebrow: 'Carpets & Rugs for Vermont',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Vermont\'s ski lodges, boutique inns and rustic-luxury homes.',
    seoTitle: 'Carpet Manufacturer for Vermont | Ski Lodge & Rustic-Luxury Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Vermont. Natural-fibre and hand tufted carpets from Bhadohi for ski lodges, boutique inns and rustic-luxury homes. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Vermont', 'ski lodge carpet supplier Vermont', 'custom rugs Vermont', 'boutique inn carpet Vermont', 'rustic luxury rugs Stowe'],
    h1: 'Carpet & Rug Manufacturer for Vermont',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Vermont — ski lodges, boutique inns, and the rustic-luxury vacation homes that define the state\'s mountain and lake communities. Each order is made to your specification; we hold no ready stock.',
    overview: 'Vermont\'s market centres on a small but design-conscious community of ski lodges, boutique inns and rustic-luxury vacation homes around Stowe and Burlington. Buyers here tend to genuinely appreciate handmade craft and natural materials — a good match for our own artisan manufacturing story. We develop natural-fibre and hand tufted pieces suited to mountain and lake interiors.',
    sections: [
      { h2: 'Ski Lodges & Mountain Hospitality', body: 'Vermont\'s ski lodges and mountain resorts need durable, characterful carpet that suits a rustic-luxury aesthetic. We manufacture made-to-order pieces in natural fibres and warm wool tones, with fire-safety construction specified per project.' },
      { h2: 'Rustic-Luxury Homes', body: 'Vermont\'s vacation and lake-house market favours natural materials and artisan character over polish. Our handmade construction and natural-fibre range suit this aesthetic directly, developed to each homeowner\'s brief.' },
    ],
    applications: [
      { title: 'Ski Lodges & Resorts', desc: 'Durable, characterful carpet for mountain hospitality.' },
      { title: 'Boutique Inns', desc: 'Made-to-order carpet suited to Vermont\'s hospitality character.' },
      { title: 'Rustic-Luxury Homes', desc: 'Natural-fibre rugs for mountain and lake vacation homes.' },
      { title: 'Interior Designers', desc: 'Artisan-appreciative development to Vermont design briefs.' },
    ],
    whyPoints: [
      { title: 'Genuine Handmade Craft', desc: 'A natural match for Vermont\'s artisan-appreciative market.' },
      { title: 'Natural Materials', desc: 'Wool, jute and sisal for mountain and lake interiors.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Vermont ski lodges and inns?', a: 'Yes. We manufacture made-to-order carpets and rugs in Bhadohi for ski lodges, boutique inns and rustic-luxury homes across Vermont.' },
      { q: 'Can you produce durable carpet for mountain-resort traffic?', a: 'Yes. We manufacture to specification with constructions suited to high-traffic hospitality use, with fire-safety requirements discussed per project.' },
      { q: 'Do you offer natural-fibre rugs for lake houses?', a: 'Yes — jute, sisal and wool rugs suit Vermont\'s rustic-luxury mountain and lake aesthetic, all customisable.' },
      { q: 'Can you develop a rug to a Stowe or Burlington design brief?', a: 'Yes. We develop lab-dips and samples to exact colour and material before bulk production.' },
      { q: 'How is shipping to Vermont handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for Vermont buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'hand-tufted-carpet', 'shaggy-rugs'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'restaurant-carpets'],
    relatedSolutions: ['custom-carpets', 'designer-rugs'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['new-hampshire', 'maine', 'massachusetts'],
    censusDivision: 'New England',
    importProcess: 'We confirm construction and material against the lodge, inn or home\'s brief, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection.',
    shipping: 'Freight is coordinated to Northeast ports serving Vermont, with consolidated shipments suited to the state\'s smaller-volume lodge, inn and residential orders.',
    leadTime: 'Lead time follows construction, size and quantity, confirmed once specification and samples are approved — resort and lodge orders can be timed to a season\'s opening where the schedule allows.',
    popularStyles: ['Natural-fibre mountain-lodge rugs', 'Warm-toned wool for rustic interiors', 'Durable ski-resort hospitality carpet', 'Handmade artisan-character pieces', 'Textured shaggy rugs for lake houses'],
    buyerSegments: [
      { label: 'Hospitality', body: 'Durable, characterful made-to-order carpet for Vermont\'s ski lodges and mountain resorts.' },
      { label: 'Luxury Homes', body: 'Natural-fibre rugs developed for Vermont\'s rustic-luxury mountain and lake vacation homes.' },
      { label: 'Interior Designers', body: 'Artisan-appreciative rug development to Vermont design briefs.' },
      { label: 'Builders', body: 'Carpet supply coordinated with lodge and resort build schedules.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct supply for Vermont hospitality and retail buyers.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding for boutique lodge and inn brands.' },
    ],
    customSizesNote: 'We manufacture to standard and fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['jute', 'sisal', 'indian-wool'],
  },
  {
    slug: 'new-hampshire',
    kind: 'usa-state',
    label: 'New Hampshire',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for New Hampshire',
    tagline: 'Made-to-order carpet and rug manufacturer producing for New Hampshire\'s lake and mountain resorts and vacation homes.',
    seoTitle: 'Carpet Manufacturer for New Hampshire | Lake & Mountain Resort Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for New Hampshire. Custom hand tufted and natural-fibre carpets from Bhadohi for lake and mountain resorts, vacation homes and designers. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer New Hampshire', 'lake resort carpet supplier NH', 'custom rugs New Hampshire', 'mountain resort carpet New Hampshire', 'vacation home rugs Manchester'],
    h1: 'Carpet & Rug Manufacturer for New Hampshire',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across New Hampshire — four-season lake and mountain resorts, vacation homes and a modest but growing corporate presence around Manchester and Portsmouth. Each order is made to your specification; we hold no ready stock.',
    overview: 'New Hampshire\'s market is shaped by year-round lake and mountain hospitality, an active vacation-home market, and steady corporate relocation activity drawn partly by the state\'s tax environment. As a manufacturer we supply durable resort-grade carpet and bespoke rugs for vacation homes, alongside contract carpet for the state\'s corporate offices.',
    sections: [
      { h2: 'Four-Season Lake & Mountain Resorts', body: 'New Hampshire\'s resorts operate through ski season and summer lake season alike, needing carpet that performs across both. We manufacture durable, made-to-order pieces suited to year-round hospitality traffic.' },
      { h2: 'Vacation Homes & Growing Corporate Presence', body: 'Alongside its resort economy, New Hampshire has a steady vacation-home market and a modest corporate base around Manchester and Portsmouth. We develop bespoke residential rugs and contract carpet for both.' },
    ],
    applications: [
      { title: 'Lake & Mountain Resorts', desc: 'Durable, made-to-order carpet for four-season hospitality.' },
      { title: 'Vacation Homes', desc: 'Bespoke rugs for New Hampshire\'s lake and mountain residences.' },
      { title: 'Corporate Offices', desc: 'Contract carpet for Manchester and Portsmouth fit-outs.' },
      { title: 'Interior Designers', desc: 'Custom development to New Hampshire design briefs.' },
    ],
    whyPoints: [
      { title: 'Four-Season Durability', desc: 'Constructions that perform across ski and lake seasons.' },
      { title: 'Made to Order', desc: 'Custom sizes and materials for resort and residential use.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for New Hampshire resorts?', a: 'Yes. We manufacture made-to-order carpets and rugs in Bhadohi for lake and mountain resorts, vacation homes and offices across New Hampshire.' },
      { q: 'Can you produce carpet that performs across ski and summer seasons?', a: 'Yes. We manufacture durable constructions suited to year-round resort traffic, with technical requirements discussed per project.' },
      { q: 'Do you supply corporate offices around Manchester?', a: 'Yes. We manufacture contract carpet to specification for New Hampshire corporate fit-outs.' },
      { q: 'Can you develop a bespoke rug for a lake house?', a: 'Yes. We develop lab-dips and samples to exact colour and material before bulk production.' },
      { q: 'How is shipping to New Hampshire handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for New Hampshire buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'jute-sisal-rugs', 'wall-to-wall-carpets'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'office-carpets'],
    relatedSolutions: ['custom-carpets', 'commercial-carpet-manufacturer'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['vermont', 'maine', 'massachusetts'],
    censusDivision: 'New England',
    importProcess: 'We confirm construction and material against the resort, home or office brief, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection.',
    shipping: 'Freight is coordinated to Northeast ports serving New Hampshire, with consolidated shipments for resort, residential and smaller corporate orders.',
    leadTime: 'Lead time follows construction, size and quantity, confirmed once specification and samples are approved — resort orders can be timed to a season\'s opening where the schedule allows.',
    popularStyles: ['Durable four-season resort carpet', 'Bespoke lake-house rugs', 'Natural-fibre mountain interiors', 'Contract carpet for corporate offices', 'Relaxed vacation-home textures'],
    buyerSegments: [
      { label: 'Hospitality', body: 'Durable, made-to-order carpet for New Hampshire\'s year-round lake and mountain resorts.' },
      { label: 'Luxury Homes', body: 'Bespoke rugs developed for New Hampshire\'s lake and mountain vacation homes.' },
      { label: 'Corporate Offices', body: 'Contract carpet manufactured to specification for Manchester and Portsmouth fit-outs.' },
      { label: 'Interior Designers', body: 'Custom rug development to New Hampshire residential and hospitality design briefs.' },
      { label: 'Builders', body: 'Carpet supply coordinated with resort and residential build schedules.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct supply for New Hampshire hospitality and retail buyers.' },
    ],
    customSizesNote: 'We manufacture to standard and fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['jute', 'indian-wool', 'sisal'],
  },
  {
    slug: 'maine',
    kind: 'usa-state',
    label: 'Maine',
    heroImage: '/images/tgi-banner-2.webp',
    eyebrow: 'Carpets & Rugs for Maine',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Maine\'s coastal inns, resorts and vacation homes.',
    seoTitle: 'Carpet Manufacturer for Maine | Coastal Inn & Resort Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Maine. Natural-fibre and hand tufted carpets from Bhadohi for coastal inns, resorts and vacation homes. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Maine', 'coastal inn carpet supplier Maine', 'custom rugs Maine', 'resort carpet supplier Portland Maine', 'vacation home rugs Bar Harbor'],
    h1: 'Carpet & Rug Manufacturer for Maine',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Maine — coastal inns and resorts, tourism-driven hospitality, and the luxury second-home market along the coast from Portland to Bar Harbor. Each order is made to your specification; we hold no ready stock.',
    overview: 'Maine\'s market is defined by a strong coastal tourism and hospitality sector — historic inns, seasonal resorts and a growing luxury second-home market — favouring relaxed, natural-fibre interiors over formality. As a manufacturer we develop jute, sisal and wool pieces suited to this coastal aesthetic, made to order in Bhadohi.',
    sections: [
      { h2: 'Coastal Inns & Seasonal Resorts', body: 'Maine\'s historic inns and seasonal coastal resorts favour relaxed, natural-fibre carpet with genuine character. We manufacture made-to-order pieces in jute, sisal and wool, with fire-safety construction specified per project.' },
      { h2: 'Luxury Coastal Second Homes', body: 'From Portland to Bar Harbor, Maine\'s coastal second-home market specifies natural, relaxed interiors. We develop bespoke rugs to each homeowner\'s brief, working with the designers who specify them.' },
    ],
    applications: [
      { title: 'Coastal Inns', desc: 'Relaxed, natural-fibre carpet for Maine\'s historic inn sector.' },
      { title: 'Seasonal Resorts', desc: 'Durable made-to-order carpet for tourism-driven hospitality.' },
      { title: 'Luxury Second Homes', desc: 'Bespoke coastal rugs from Portland to Bar Harbor.' },
      { title: 'Interior Designers', desc: 'Natural-fibre development to Maine coastal design briefs.' },
    ],
    whyPoints: [
      { title: 'Coastal Character', desc: 'Relaxed, natural-fibre pieces for Maine\'s aesthetic.' },
      { title: 'Made to Order', desc: 'Custom sizes and materials for inns, resorts and homes.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Maine inns and resorts?', a: 'Yes. We manufacture made-to-order carpets and rugs in Bhadohi for coastal inns, seasonal resorts and vacation homes across Maine.' },
      { q: 'Do you offer natural-fibre rugs for coastal homes?', a: 'Yes — jute, sisal and wool rugs suit Maine\'s relaxed coastal aesthetic, all customisable to size and colour.' },
      { q: 'Can you develop a rug to a Portland or Bar Harbor design brief?', a: 'Yes. We develop lab-dips and samples to exact colour and material before bulk production.' },
      { q: 'Can you supply seasonal resorts with durable, high-traffic carpet?', a: 'Yes. We manufacture constructions suited to seasonal hospitality traffic, with technical requirements discussed per project.' },
      { q: 'How is shipping to Maine handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'What is your minimum order quantity for Maine buyers?', a: 'Minimum order quantities depend on construction, size and customisation. Share your project brief and our team will confirm the MOQ that applies.' },
    ],
    relatedProducts: ['jute-sisal-rugs', 'hand-tufted-carpet', 'flat-weaves'],
    relatedIndustries: ['hotel-carpets', 'villa-carpets', 'restaurant-carpets'],
    relatedSolutions: ['custom-carpets', 'designer-rugs'],
    relatedCountries: ['usa'],
    relatedUsaStates: ['new-hampshire', 'vermont', 'massachusetts'],
    censusDivision: 'New England',
    importProcess: 'We confirm construction and material against the inn, resort or home\'s coastal brief, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection.',
    shipping: 'Freight is coordinated to Northeast ports serving Maine, with consolidated shipments suited to the state\'s inn, resort and residential order volumes.',
    leadTime: 'Lead time follows construction, size and quantity, confirmed once specification and samples are approved — seasonal resort orders can be timed to an opening date where the schedule allows.',
    popularStyles: ['Natural-fibre coastal interiors', 'Relaxed jute and sisal weaves', 'Durable seasonal-resort carpet', 'Bespoke second-home rugs', 'Warm wool tones for historic inns'],
    buyerSegments: [
      { label: 'Hospitality', body: 'Relaxed, natural-fibre made-to-order carpet for Maine\'s coastal inns and seasonal resorts.' },
      { label: 'Luxury Homes', body: 'Bespoke coastal rugs for Maine\'s luxury second-home market from Portland to Bar Harbor.' },
      { label: 'Interior Designers', body: 'Natural-fibre rug development to Maine\'s coastal design briefs.' },
      { label: 'Builders', body: 'Carpet supply coordinated with inn, resort and residential build schedules.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct supply for Maine hospitality and retail buyers.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding for boutique inn and resort brands.' },
    ],
    customSizesNote: 'We manufacture to standard and fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['jute', 'sisal', 'indian-wool'],
  },
]
