import type { SeoLanding } from './seo-landing'

// ─────────────────────────────────────────────────────────────────────────────
// USA city landing pages — /usa/[state]/[city]
//
// Same claim discipline as lib/usa-states.ts: made-to-order manufacturer
// positioning, no fabricated local presence/statistics, no LocalBusiness
// schema. Each city layers metro-specific character on top of (not restating)
// its parent state's framing in lib/usa-states.ts — see `parentUsaState`.
// ─────────────────────────────────────────────────────────────────────────────

const PRODUCTS_CORE = ['hand-knotted-carpet', 'hand-tufted-carpet', 'wall-to-wall-carpets']

export const USA_CITIES: SeoLanding[] = [
  {
    slug: 'new-york-city',
    kind: 'usa-city',
    label: 'New York City',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for New York City',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Manhattan\'s corporate towers, luxury residences and design studios.',
    seoTitle: 'Carpet Manufacturer for New York City | Manhattan Contract & Custom Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for New York City. Custom hand knotted, hand tufted and contract carpets from Bhadohi for Manhattan corporate towers, luxury residences, hotels and design studios. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer New York City', 'custom rug supplier Manhattan', 'hotel carpet manufacturer NYC', 'corporate carpet New York City', 'luxury rug supplier Manhattan'],
    h1: 'Carpet & Rug Manufacturer for New York City',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers and projects across New York City — Manhattan\'s corporate towers, luxury residential buildings, flagship and boutique hotels, and the design studios that specify for them. Part of our New York coverage; each order is made to your design, size and specification.',
    overview: 'New York City is the single densest concentration of corporate headquarters, ultra-luxury residential towers, flagship hospitality and top-tier interior design firms in the country. As a manufacturer we make bespoke hand knotted and hand tufted rugs and contract carpet tile to the exacting standard this market sets, developed in Bhadohi and shipped with full documentation.',
    sections: [
      { h2: 'Manhattan Corporate Towers', body: 'From Midtown headquarters to Downtown financial-sector offices, we manufacture carpet tile and broadloom to precise fit-out specification, with dye-lot consistency held across large, multi-floor orders.' },
      { h2: 'Ultra-Luxury Residential & Flagship Hospitality', body: 'For Manhattan penthouses and flagship hotels we develop bespoke hand knotted and hand tufted rugs to exact colour, pattern and dimension — working directly with the interior design firms that specify New York\'s most demanding projects.' },
    ],
    applications: [
      { title: 'Corporate Towers', desc: 'Carpet tile and broadloom for Manhattan fit-outs.' },
      { title: 'Luxury Residential', desc: 'Bespoke rugs for penthouses and high-rise apartments.' },
      { title: 'Flagship Hotels', desc: 'Design-forward custom carpet for New York City hospitality.' },
      { title: 'Design Studios', desc: 'Precise development to mood boards and Pantone references.' },
    ],
    whyPoints: [
      { title: 'Manufacturer-Direct', desc: 'Made in our own Bhadohi facility, no middlemen.' },
      { title: 'Design-Studio Ready', desc: 'Lab-dips, samples and Pantone-matched development.' },
      { title: 'Fully Custom', desc: 'Any size, colour, construction and quantity to brief.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for New York City projects?', a: 'Yes. We manufacture made-to-order carpets and rugs in Bhadohi for corporate, residential, hospitality and design projects across New York City.' },
      { q: 'Can you develop a rug to a Manhattan design studio\'s Pantone references?', a: 'Yes. We develop lab-dips and a sample against your exact colour references before bulk production.' },
      { q: 'Do you supply carpet tile for corporate tower fit-outs?', a: 'Yes. We manufacture broadloom and carpet tile to specification, with dye-lot consistency across large multi-floor orders.' },
      { q: 'Can you produce a one-of-a-kind rug for a Manhattan penthouse?', a: 'Yes. We craft bespoke single pieces — you choose material, size, colour and construction, and we develop a sample for approval before crafting it.' },
      { q: 'Do you offer wholesale or private-label programmes for New York City importers?', a: 'Yes. We provide OEM and private-label manufacturing with custom branding and packaging, alongside bulk wholesale programmes.' },
      { q: 'How is shipping to New York City handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'villa-carpets'],
    relatedSolutions: ['designer-rugs', 'commercial-carpet-manufacturer'],
    relatedCompany: ['oem-private-label'],
    parentUsaState: 'new-york',
    relatedUsaCities: ['boston', 'philadelphia'],
    censusDivision: 'Mid-Atlantic',
    importProcess: 'We confirm specification, construction and quantity, develop lab-dips and a sample for sign-off, then produce with staged quality checks and a documented pre-dispatch inspection — the same process for a single bespoke penthouse rug as for a bulk corporate-tower programme.',
    shipping: 'Freight is coordinated to New York-area ports, with container programmes for importers and wholesale buyers and smaller consolidated shipments for individual design and residential orders.',
    leadTime: 'Because every piece is made to order, lead time follows the construction, size and quantity specified — confirmed once your specification and samples are approved.',
    popularStyles: ['Design-forward hand-tufted rugs', 'Bespoke hand-knotted statement pieces', 'Carpet tile for corporate towers', 'Contemporary wool-viscose blends', 'Custom broadloom for luxury buildings'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Carpet tile and broadloom manufactured to precise fit-out specification for Manhattan towers.' },
      { label: 'Interior Designers', body: 'Bespoke rugs developed to mood boards and Pantone references for New York City projects.' },
      { label: 'Hotels', body: 'Design-forward custom carpet for flagship and boutique New York City hotels.' },
      { label: 'Luxury Homes', body: 'Opulent bespoke rugs for Manhattan penthouses and high-value residential interiors.' },
      { label: 'Hospitality', body: 'Made-to-order contract carpet for New York City\'s hotel and restaurant sector.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for New York City importers and distributors.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with your branding and packaging, under confidentiality.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for large-scale New York City projects.' },
    ],
    customSizesNote: 'We manufacture to US standard rug dimensions and runner formats as well as fully custom sizes and shapes, with samples approved before bulk production.',
    materialRecommendations: ['nz-wool', 'wool-viscose', 'bamboo-silk'],
  },
  {
    slug: 'boston',
    kind: 'usa-city',
    label: 'Boston',
    heroImage: '/images/tgi-banner-5.webp',
    eyebrow: 'Carpets & Rugs for Boston',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Boston\'s universities, biotech campuses and historic residences.',
    seoTitle: 'Carpet Manufacturer for Boston | Institutional & Historic Home Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Boston. Custom hand tufted, wall-to-wall and heritage-appropriate carpets from Bhadohi for universities, biotech campuses, Back Bay residences and hotels. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Boston', 'university carpet supplier Boston', 'custom rugs Boston', 'hotel carpet manufacturer Boston', 'Back Bay rug supplier'],
    h1: 'Carpet & Rug Manufacturer for Boston',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Boston — universities, biotech and healthcare corporate campuses, historic Back Bay and Beacon Hill residences, and the city\'s hospitality sector. Part of our Massachusetts coverage; each order is made to your specification.',
    overview: 'Boston concentrates an unusual density of universities, teaching hospitals and biotech corporate campuses within a compact, historic city fabric of Back Bay brownstones and Beacon Hill townhouses. As a manufacturer we supply durable institutional carpet for academic and healthcare settings alongside heritage-appropriate bespoke rugs for the city\'s historic residences.',
    sections: [
      { h2: 'Universities & Biotech Campuses', body: 'Boston\'s universities, teaching hospitals and biotech corporate campuses call for durable, specification-compliant carpet across demanding traffic conditions. We manufacture to exact specification with documentation for procurement teams.' },
      { h2: 'Back Bay & Beacon Hill Residences', body: 'Boston\'s historic residential neighbourhoods favour classical, heritage-appropriate rugs. We develop bespoke pieces to precise colour and pattern for these architecturally significant interiors, working directly with the designers who specify them.' },
    ],
    applications: [
      { title: 'Universities & Institutions', desc: 'Durable, specification-compliant carpet for academic settings.' },
      { title: 'Biotech & Healthcare Campuses', desc: 'Documented contract carpet for institutional environments.' },
      { title: 'Historic Residences', desc: 'Heritage-appropriate bespoke rugs for Back Bay and Beacon Hill.' },
      { title: 'Boston Hospitality', desc: 'Design-forward custom carpet for hotels and restaurants.' },
    ],
    whyPoints: [
      { title: 'Institutional-Grade', desc: 'Durable constructions for academic and healthcare traffic.' },
      { title: 'Heritage-Appropriate', desc: 'Classical pattern development for historic interiors.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Boston institutions?', a: 'Yes. We manufacture made-to-order carpets to specification for universities, hospitals and biotech campuses across Boston.' },
      { q: 'Can you develop a rug suited to a Back Bay or Beacon Hill home?', a: 'Yes. We develop classical and traditional pattern work to precise colour and design for heritage residential interiors.' },
      { q: 'Do you supply Boston hotels?', a: 'Yes. We manufacture design-forward custom carpet to a hotel\'s brief, with fire-safety construction specified per project.' },
      { q: 'Can you support institutional procurement and tenders?', a: 'Yes. We produce to documented specification and can supply samples and specification sheets to support tender submissions.' },
      { q: 'How is shipping to Boston handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'Are you part of your Massachusetts coverage?', a: 'Yes. Boston is part of our wider Massachusetts coverage — the same manufacturing and shipping process applies statewide.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['school-carpets', 'office-carpets', 'hotel-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'designer-rugs'],
    parentUsaState: 'massachusetts',
    relatedUsaCities: ['new-york-city', 'philadelphia'],
    censusDivision: 'New England',
    importProcess: 'We confirm specification against the institution\'s or project\'s requirements, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment.',
    shipping: 'Freight is coordinated to Boston-serving Northeast ports, with phased dispatch available for large institutional programmes and consolidated shipments for smaller residential orders.',
    leadTime: 'Production timelines follow construction, size and quantity, and are confirmed once specification and samples are approved — institutional projects with fixed academic-calendar dates are planned around accordingly.',
    popularStyles: ['Durable institutional-grade carpet', 'Classical heritage residential rugs', 'Design-forward hospitality carpet', 'Biotech campus carpet tile', 'Traditional New England pattern work'],
    buyerSegments: [
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for university, hospital and biotech-campus projects.' },
      { label: 'Corporate Offices', body: 'Contract-grade carpet tile and broadloom for Boston-area corporate fit-outs.' },
      { label: 'Luxury Homes', body: 'Heritage-appropriate bespoke rugs for Back Bay and Beacon Hill residences.' },
      { label: 'Hospitality', body: 'Design-forward custom carpet for Boston\'s hotel and restaurant sector.' },
      { label: 'Interior Designers', body: 'Custom rugs developed to heritage and contemporary Boston design briefs.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Boston-area distributors.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging, under confidentiality.' },
    ],
    customSizesNote: 'We manufacture to institutional and US standard dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['indian-wool', 'nz-wool', 'jute'],
  },
  {
    slug: 'philadelphia',
    kind: 'usa-city',
    label: 'Philadelphia',
    heroImage: '/images/tgi-banner-3.webp',
    eyebrow: 'Carpets & Rugs for Philadelphia',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Philadelphia\'s historic institutions, corporate offices and hospitality.',
    seoTitle: 'Carpet Manufacturer for Philadelphia | Institutional & Contract Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Philadelphia. Custom hand tufted, wall-to-wall and contract carpets from Bhadohi for universities, historic institutions, corporate offices and hotels. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Philadelphia', 'contract carpet supplier Philadelphia', 'institutional carpet Philadelphia', 'custom rugs Philadelphia', 'hotel carpet supplier Philadelphia'],
    h1: 'Carpet & Rug Manufacturer for Philadelphia',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Philadelphia — universities, hospitals and civic institutions near Independence Hall, growing corporate offices and a boutique hospitality scene. Part of our Pennsylvania coverage; each order is made to your specification.',
    overview: 'Philadelphia carries an unusually dense concentration of historic institutional buildings — universities, hospitals and civic buildings near Independence Hall — alongside a steadily growing corporate office and boutique hospitality sector. As a manufacturer we make carpets suited to both: durable institutional constructions for heritage buildings, and contract-grade contemporary carpet for corporate and hotel fit-outs.',
    sections: [
      { h2: 'Historic Institutions Near Independence Hall', body: 'Philadelphia\'s universities, hospitals and heritage civic buildings need carpet that respects the interior while meeting institutional durability and traffic requirements. We manufacture to specification, including classical pattern development for historic settings.' },
      { h2: 'Corporate & Boutique Hospitality Growth', body: 'Philadelphia\'s corporate office and boutique hospitality sectors have grown steadily in recent years. We supply contract-grade broadloom and carpet tile for offices, and design-led custom carpets for boutique hotels.' },
    ],
    applications: [
      { title: 'Universities & Institutions', desc: 'Durable, specification-compliant carpet for campus and civic buildings.' },
      { title: 'Corporate Offices', desc: 'Contract-grade broadloom and tile for Philadelphia fit-outs.' },
      { title: 'Boutique Hospitality', desc: 'Design-led custom carpets for a growing hotel sector.' },
      { title: 'Heritage Interiors', desc: 'Classical pattern development suited to historic buildings.' },
    ],
    whyPoints: [
      { title: 'Institutional-Grade', desc: 'Durable constructions for high-traffic campus and civic use.' },
      { title: 'Heritage-Appropriate', desc: 'Classical and traditional pattern development.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Philadelphia institutions?', a: 'Yes. We manufacture made-to-order carpets to specification for universities, hospitals and civic buildings across Philadelphia.' },
      { q: 'Can you develop carpet suited to a historic building near Independence Hall?', a: 'Yes. We develop classical and traditional pattern work suited to heritage interiors, alongside contemporary constructions for modern fit-outs.' },
      { q: 'Do you supply Philadelphia corporate offices?', a: 'Yes. We manufacture contract-grade broadloom and carpet tile to specification for corporate fit-outs.' },
      { q: 'Can you support institutional tenders and procurement?', a: 'Yes. We produce to documented specification and can supply samples and specification sheets to support tender submissions.' },
      { q: 'How is shipping to Philadelphia handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'Are you part of your Pennsylvania coverage?', a: 'Yes. Philadelphia is part of our wider Pennsylvania coverage — the same manufacturing and shipping process applies statewide.' },
    ],
    relatedProducts: PRODUCTS_CORE,
    relatedIndustries: ['office-carpets', 'school-carpets', 'hotel-carpets'],
    relatedSolutions: ['contract-carpet-supplier', 'commercial-carpet-manufacturer'],
    parentUsaState: 'pennsylvania',
    relatedUsaCities: ['new-york-city', 'boston'],
    censusDivision: 'Mid-Atlantic',
    importProcess: 'We confirm specification against the project\'s institutional or corporate requirements, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment.',
    shipping: 'Freight is coordinated to Philadelphia-serving East Coast ports, with phased dispatch available for large institutional and corporate programmes.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved — institutional projects with fixed programme dates are planned with that timeline in mind from the outset.',
    popularStyles: ['Classical institutional patterns', 'Contract-grade broadloom for offices', 'Durable campus carpet tile', 'Boutique hospitality custom rugs', 'Heritage-appropriate traditional weaves'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Contract-grade broadloom and carpet tile for Philadelphia corporate fit-outs.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for institutional and civic projects.' },
      { label: 'Hospitality', body: 'Design-led custom carpet for Philadelphia\'s growing boutique hotel and restaurant sector.' },
      { label: 'Interior Designers', body: 'Heritage-appropriate and contemporary rugs developed to project-specific briefs.' },
      { label: 'Luxury Homes', body: 'Bespoke rugs for Philadelphia\'s historic and contemporary luxury residences.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Philadelphia distributors and trade buyers.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging, under confidentiality.' },
    ],
    customSizesNote: 'We manufacture to institutional and US standard dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['indian-wool', 'wool-viscose', 'jute'],
  },
  {
    slug: 'chicago',
    kind: 'usa-city',
    label: 'Chicago',
    heroImage: '/images/tgi-banner-6.webp',
    eyebrow: 'Carpets & Rugs for Chicago',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Chicago\'s corporate headquarters, convention venues and luxury towers.',
    seoTitle: 'Carpet Manufacturer for Chicago | Corporate & Convention Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Chicago. Custom contract, hand tufted and wall-to-wall carpets from Bhadohi for corporate headquarters, convention venues and luxury hospitality. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Chicago', 'corporate carpet Chicago', 'convention carpet supplier Chicago', 'custom rugs Chicago', 'hotel carpet manufacturer Chicago'],
    h1: 'Carpet & Rug Manufacturer for Chicago',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers and projects across Chicago — corporate headquarters, the city\'s major convention and trade-show venues, and its architecturally significant luxury towers and hospitality scene. Part of our Illinois coverage; each order is made to your specification.',
    overview: 'Chicago concentrates one of the country\'s densest corporate headquarters markets alongside the largest convention and trade-show infrastructure in the Midwest. As a manufacturer we make large-volume contract carpet for corporate and convention fit-outs, and bold, design-forward pieces for the city\'s architecturally significant luxury residential and hospitality market.',
    sections: [
      { h2: 'Corporate Headquarters & Convention Venues', body: 'Chicago hosts one of the country\'s largest concentrations of corporate headquarters alongside major convention and trade-show venues like McCormick Place. We manufacture carpet tile and broadloom to precise specification, with the bulk capacity and dye-lot consistency large-scale programmes require.' },
      { h2: 'Luxury Towers & Design-Forward Hospitality', body: 'Chicago\'s architecturally significant residential towers and design-forward hospitality scene call for bold, custom carpet. We develop bespoke hand tufted and hand knotted rugs to exact colour and pattern for the designers who specify them.' },
    ],
    applications: [
      { title: 'Corporate Headquarters', desc: 'Bulk carpet tile and broadloom for Chicago fit-outs.' },
      { title: 'Convention & Event Venues', desc: 'Large-volume contract carpet for trade-show infrastructure.' },
      { title: 'Luxury Hospitality', desc: 'Design-forward custom carpet for Chicago hotels.' },
      { title: 'Luxury Residential Towers', desc: 'Bespoke rugs for Chicago\'s architecturally significant buildings.' },
    ],
    whyPoints: [
      { title: 'Bulk Capacity', desc: 'Large-volume production for corporate and convention orders.' },
      { title: 'Design-Forward', desc: 'Bold, custom development for Chicago\'s design culture.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Chicago corporate headquarters?', a: 'Yes. We manufacture made-to-order carpet tile and broadloom to specification for Chicago corporate fit-outs, with dye-lot consistency across large orders.' },
      { q: 'Can you supply Chicago\'s convention and trade-show venues?', a: 'Yes. We manufacture bulk, made-to-order contract carpet with the volume and consistency convention venues require.' },
      { q: 'Do you develop bespoke rugs for Chicago residences?', a: 'Yes. We develop lab-dips and samples to exact colour and pattern before bulk production.' },
      { q: 'Do you offer wholesale or private-label programmes for Chicago importers?', a: 'Yes. We provide bulk, batch-consistent wholesale supply and private-label manufacturing with custom branding and packaging.' },
      { q: 'How is shipping to Chicago handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'Are you part of your Illinois coverage?', a: 'Yes. Chicago is part of our wider Illinois coverage — the same manufacturing and shipping process applies statewide.' },
    ],
    relatedProducts: ['hand-tufted-carpet', 'wall-to-wall-carpets', 'hand-knotted-carpet'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'auditorium-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'wholesale-carpet-supplier'],
    relatedCompany: ['oem-private-label'],
    parentUsaState: 'illinois',
    relatedUsaCities: ['detroit'],
    censusDivision: 'East North Central',
    importProcess: 'We confirm specification and volume, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection — the same disciplined process for a bulk convention-venue order as for a single bespoke Chicago residence rug.',
    shipping: 'Freight is coordinated to Midwest-serving ports and inland distribution hubs, with container programmes for large corporate and convention orders and consolidated shipments for smaller residential and design orders.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved — convention and trade-show orders are scheduled around fixed event dates where required.',
    popularStyles: ['Bulk contract carpet tile', 'Bold design-forward hand-tufted rugs', 'Convention-grade broadloom', 'Bespoke luxury tower rugs', 'Durable corporate campus carpet'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Bulk carpet tile and broadloom manufactured to specification for Chicago corporate headquarters.' },
      { label: 'Hospitality', body: 'Design-forward custom carpet for Chicago\'s hotel and event-venue sector.' },
      { label: 'Interior Designers', body: 'Bespoke rugs developed to Chicago\'s architecturally significant design briefs.' },
      { label: 'Luxury Homes', body: 'Custom rugs for Chicago\'s luxury residential towers.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Chicago importers and distributors.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for large convention and corporate projects.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging, under confidentiality.' },
    ],
    customSizesNote: 'We manufacture to US standard rug and carpet-tile dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['pet', 'nz-wool', 'wool-viscose'],
  },
  {
    slug: 'detroit',
    kind: 'usa-city',
    label: 'Detroit',
    heroImage: '/images/tgi-banner-1.webp',
    eyebrow: 'Carpets & Rugs for Detroit',
    tagline: 'Made-to-order carpet and rug manufacturer producing for Detroit\'s automotive corporate campuses and revitalising downtown hospitality.',
    seoTitle: 'Carpet Manufacturer for Detroit | Corporate & Hospitality Carpets — Tapis Global',
    seoDescription: 'Made-to-order carpet and rug manufacturer producing for Detroit. Durable contract and custom carpets from Bhadohi for automotive corporate campuses and downtown hospitality. Request a catalogue or quote.',
    seoKeywords: ['carpet manufacturer Detroit', 'corporate carpet Detroit', 'custom rugs Detroit', 'hotel carpet supplier Detroit', 'contract carpet Detroit'],
    h1: 'Carpet & Rug Manufacturer for Detroit',
    intro: 'Tapis Global International manufactures made-to-order carpets and rugs in Bhadohi and produces for buyers across Detroit — automotive-industry corporate campuses and the city\'s genuinely growing downtown hospitality and corporate revitalisation. Part of our Michigan coverage; each order is made to your specification.',
    overview: 'Detroit\'s market is shaped by its automotive-industry corporate heritage and a real, ongoing downtown revitalisation that is drawing new hospitality and corporate investment into the city centre. As a manufacturer we supply durable, industrial-grade contract carpet for corporate campuses and design-forward custom carpet for the growing hotel sector.',
    sections: [
      { h2: 'Automotive Corporate Campuses', body: 'Detroit\'s automotive-industry corporate headquarters need carpet built for demanding, sustained-use corporate environments. We manufacture durable contract carpet tile and broadloom to specification, with dye-lot consistency across large orders.' },
      { h2: 'Downtown Revitalisation & Hospitality', body: 'Downtown Detroit\'s growing hospitality and corporate sector is investing in design-forward carpet as new hotels and offices open. We manufacture made-to-order carpet to each project\'s brief.' },
    ],
    applications: [
      { title: 'Automotive Corporate Campuses', desc: 'Durable contract carpet for demanding corporate environments.' },
      { title: 'Downtown Hospitality', desc: 'Design-forward custom carpet for a revitalising hotel sector.' },
      { title: 'Corporate Offices', desc: 'Contract-grade broadloom and tile for Detroit fit-outs.' },
      { title: 'Interior Designers', desc: 'Custom development to Detroit residential and commercial briefs.' },
    ],
    whyPoints: [
      { title: 'Industrial-Grade Durability', desc: 'Constructions built for demanding corporate traffic.' },
      { title: 'Revitalisation-Ready', desc: 'Design-forward carpet for Detroit\'s growing hospitality sector.' },
      { title: 'Manufacturer-Direct', desc: 'Factory pricing and quality control, no middlemen.' },
    ],
    faqs: [
      { q: 'Do you manufacture carpets for Detroit corporate campuses?', a: 'Yes. We manufacture made-to-order, durable contract carpet to specification for Detroit\'s automotive-industry corporate campuses.' },
      { q: 'Do you supply Detroit\'s downtown hospitality sector?', a: 'Yes. We manufacture design-forward custom carpet for downtown Detroit hotels, with fire-safety construction specified per project.' },
      { q: 'Do you offer wholesale or private-label programmes for Detroit buyers?', a: 'Yes. We provide OEM and private-label manufacturing alongside bulk wholesale programmes.' },
      { q: 'Can you develop a bespoke rug for a Detroit residence?', a: 'Yes. We develop lab-dips and samples to exact colour and design before production.' },
      { q: 'How is shipping to Detroit handled?', a: 'We pack for international transit and coordinate freight to your preferred US port, with documentation prepared for smooth customs clearance.' },
      { q: 'Are you part of your Michigan coverage?', a: 'Yes. Detroit is part of our wider Michigan coverage — the same manufacturing and shipping process applies statewide.' },
    ],
    relatedProducts: ['wall-to-wall-carpets', 'hand-tufted-carpet', 'jute-sisal-rugs'],
    relatedIndustries: ['office-carpets', 'hotel-carpets', 'villa-carpets'],
    relatedSolutions: ['commercial-carpet-manufacturer', 'custom-carpets'],
    parentUsaState: 'michigan',
    relatedUsaCities: ['chicago'],
    censusDivision: 'East North Central',
    importProcess: 'We confirm specification against the corporate or hospitality brief, develop lab-dips and a sample for approval, then produce with staged quality checks and a documented pre-dispatch inspection before shipment.',
    shipping: 'Freight is coordinated to Midwest-serving ports and Great Lakes inland hubs, with phased dispatch available for large corporate programmes and consolidated shipments for residential orders.',
    leadTime: 'Production timelines follow construction, size and quantity, confirmed once specification and samples are approved.',
    popularStyles: ['Durable automotive-campus contract carpet', 'Design-forward downtown hospitality carpet', 'Industrial-grade broadloom', 'Custom corporate carpet tile', 'Bespoke residential rugs'],
    buyerSegments: [
      { label: 'Corporate Offices', body: 'Durable contract carpet tile and broadloom for Detroit\'s automotive-industry corporate campuses.' },
      { label: 'Hospitality', body: 'Design-forward custom carpet for downtown Detroit\'s revitalising hotel sector.' },
      { label: 'Interior Designers', body: 'Custom rugs developed to Detroit residential and corporate briefs.' },
      { label: 'Contract Manufacturing', body: 'Specification-led production with documentation for large corporate programmes.' },
      { label: 'Wholesale', body: 'Bulk manufacturer-direct programmes for Detroit distributors and trade buyers.' },
      { label: 'OEM / Private Label', body: 'White-label manufacturing with custom branding and packaging, under confidentiality.' },
    ],
    customSizesNote: 'We manufacture to US standard rug and carpet-tile dimensions as well as fully custom sizes, with samples approved before bulk production.',
    materialRecommendations: ['pet', 'jute', 'nz-wool'],
  },
]
