/**
 * Materials module. Capability-safe: describes what a fibre is COMMONLY chosen
 * for and general considerations — never guarantees of durability, traffic
 * suitability, washability, sustainability or tested performance. Positioning is
 * categorical, never a price. The team confirms suitability per project.
 *
 * Each material also carries a structured `profile` (the Product Knowledge
 * Engine): description, advantages, disadvantages, typical applications, and
 * RELATIVE (not guaranteed) durability/softness/luxury ratings that the
 * recommendation + comparison engines rank on. Ratings are translated to words
 * before reaching the buyer — never surfaced as numbers.
 */
import type { TaraMaterial } from './types'

/** Shared, non-price pricing drivers (never quote actual prices). */
const PRICE = 'Cost depends on fibre grade, construction, knot/tuft density, size, number of colours, design complexity and quantity — the team prepares a quotation to your spec.'

export const TARA_MATERIALS: TaraMaterial[] = [
  { id: 'nz-wool', name: 'New Zealand Wool', positioning: 'Luxury', fibreType: 'natural',
    notes: 'A wool fibre commonly chosen for clean colour take-up and a soft hand-feel.',
    applications: 'Commonly considered for residential and hospitality, in hand-knotted & hand-tufted rugs.',
    properties: ['Natural protein fibre', 'Bright, even colour take-up', 'Soft, full hand-feel'],
    advantages: ['Refined appearance', 'Wide colour range', 'Suits premium projects'],
    limitations: ['A premium fibre — positioned at the higher tier', 'The team advises on use-case suitability'],
    maintenance: 'Regular gentle vacuuming; professional cleaning for deeper care.', priceFactors: PRICE, tags: ['wool', 'luxury', 'residential', 'hospitality'],
    profile: {
      description: 'A premium natural protein fibre prized for bright, even colour take-up, a soft-yet-resilient hand-feel and natural durability.',
      advantages: ['Naturally resilient and hard-wearing', 'Excellent, even colour take-up', 'Soft, full hand-feel', 'Suits premium and heritage projects'],
      disadvantages: ['Positioned at the higher price tier', 'Natural fibre — the team advises on heavy-wet-area use'],
      typicalApplications: ['Living rooms', 'Bedrooms', 'Hotel guestrooms and lobbies', 'Heritage and premium rugs'],
      durability: 5, softness: 4, luxuryLevel: 5,
      maintenance: 'Regular gentle vacuuming; occasional professional cleaning. Resists everyday soiling well for a natural fibre.',
      recommendedProjects: ['residential', 'hospitality', 'premium'], alternatives: ['indian-wool', 'wool-viscose'],
    } },

  { id: 'indian-wool', name: 'Indian Wool', positioning: 'Premium', fibreType: 'natural',
    notes: 'A widely used natural wool with a warm hand-feel, common across many rug types.',
    applications: 'Commonly considered for residential and commercial rugs at a premium tier.',
    properties: ['Natural protein fibre', 'Warm hand-feel', 'Versatile'],
    advantages: ['Good all-round choice', 'Broad availability', 'Works across constructions'],
    limitations: ['Character varies by grade — the team advises on selection'],
    maintenance: 'Gentle vacuuming; professional cleaning as needed.', priceFactors: PRICE, tags: ['wool', 'premium', 'versatile'],
    profile: {
      description: 'A versatile, widely used natural wool with a warm hand-feel that works across almost every construction and project type.',
      advantages: ['Strong all-round durability', 'Works across all constructions', 'Warm, natural hand-feel', 'Broadly available at a premium tier'],
      disadvantages: ['Character varies by grade', 'Less refined sheen than NZ wool'],
      typicalApplications: ['Living rooms', 'Bedrooms', 'Offices and commercial rugs', 'Hospitality'],
      durability: 4, softness: 4, luxuryLevel: 3,
      maintenance: 'Gentle vacuuming; professional cleaning as needed.',
      recommendedProjects: ['residential', 'commercial', 'hospitality'], alternatives: ['nz-wool', 'blended-wool'],
    } },

  { id: 'blended-wool', name: 'Blended Wool', positioning: 'Premium', fibreType: 'blend',
    notes: 'Wool combined with other fibres to balance appearance, feel and budget.',
    applications: 'Commonly considered where a balance of look and value is wanted.',
    properties: ['Wool base with blend fibres', 'Tunable appearance'], advantages: ['Balances feel and budget', 'Design flexibility'],
    limitations: ['Exact blend affects character — confirmed per project'],
    maintenance: 'Gentle vacuuming; professional cleaning as needed.', priceFactors: PRICE, tags: ['wool', 'blend'],
    profile: {
      description: 'Wool combined with other fibres to balance appearance, hand-feel and budget, with a tunable character to suit the brief.',
      advantages: ['Balances feel and value', 'Design flexibility', 'Good general durability'],
      disadvantages: ['Exact character depends on the blend', 'Not as premium as pure NZ wool'],
      typicalApplications: ['Residential rugs', 'Value-conscious hospitality', 'General-purpose interiors'],
      durability: 4, softness: 3, luxuryLevel: 3,
      maintenance: 'Gentle vacuuming; professional cleaning as needed.',
      recommendedProjects: ['residential', 'hospitality'], alternatives: ['indian-wool', 'wool-viscose'],
    } },

  { id: 'viscose', name: 'Viscose', positioning: 'Premium', fibreType: 'synthetic',
    notes: 'A fibre with a silk-like sheen and soft hand-feel, often chosen for decorative pieces.',
    applications: 'Commonly considered for feature rugs and decorative, lower-traffic interiors.',
    properties: ['Silk-like sheen', 'Soft hand-feel', 'Vivid colours'], advantages: ['Luxurious look at a friendlier tier', 'Rich colour depth'],
    limitations: ['Best kept to decorative, lower-traffic settings', 'Sensitive to moisture — the team advises on care'],
    maintenance: 'Dry-clean approach; avoid soaking. The team can share care guidance.', priceFactors: PRICE, tags: ['viscose', 'sheen', 'decorative'],
    profile: {
      description: 'A silk-like fibre chosen for its high sheen, soft hand-feel and vivid colour depth — a luxurious look at a friendlier tier than real silk.',
      advantages: ['High silk-like sheen', 'Very soft hand-feel', 'Rich, vivid colours'],
      disadvantages: ['Best kept to low-traffic, decorative use', 'Sensitive to moisture and spills', 'Needs gentle, dry-focused care'],
      typicalApplications: ['Feature and accent rugs', 'Formal low-traffic living rooms', 'Bedrooms', 'Decorative interiors'],
      durability: 2, softness: 5, luxuryLevel: 3,
      maintenance: 'Dry-clean approach; avoid soaking or heavy scrubbing.',
      recommendedProjects: ['residential', 'decorative'], alternatives: ['bamboo-silk', 'tencel'],
    } },

  { id: 'bamboo-silk', name: 'Bamboo Silk', positioning: 'Luxury', fibreType: 'synthetic',
    notes: 'A plant-based fibre with a lustrous, silk-like appearance.',
    applications: 'Commonly considered for decorative and luxury residential rugs.',
    properties: ['Lustrous sheen', 'Fine, soft surface'], advantages: ['High-shine, luxurious look'],
    limitations: ['Decorative use is typical; the team advises on placement'],
    maintenance: 'Gentle, dry-focused cleaning; the team can advise.', priceFactors: PRICE, tags: ['bamboo silk', 'sheen', 'luxury'],
    profile: {
      description: 'A plant-based fibre with an especially lustrous, silk-like surface, chosen for luxurious decorative pieces.',
      advantages: ['Very high, elegant sheen', 'Fine, soft surface', 'Luxurious appearance'],
      disadvantages: ['Best for low-traffic decorative use', 'Sensitive to moisture', 'Requires careful, gentle cleaning'],
      typicalApplications: ['Luxury feature rugs', 'Formal living rooms', 'Bedrooms', 'Decorative statement pieces'],
      durability: 2, softness: 5, luxuryLevel: 5,
      maintenance: 'Gentle, dry-focused cleaning; avoid soaking.',
      recommendedProjects: ['residential', 'decorative', 'premium'], alternatives: ['viscose', 'tencel'],
    } },

  { id: 'wool-viscose', name: 'Wool-Viscose Blend', positioning: 'Premium', fibreType: 'blend',
    notes: 'A blend combining a wool base with viscose sheen for design depth.',
    applications: 'Commonly considered for design-led residential and hospitality rugs.',
    properties: ['Wool body + viscose highlights', 'Depth of colour'], advantages: ['Combines matte and sheen', 'Design richness'],
    limitations: ['Care follows the viscose component — the team advises'],
    maintenance: 'Gentle vacuuming; professional cleaning as needed.', priceFactors: PRICE, tags: ['blend', 'wool', 'viscose'],
    profile: {
      description: 'A blend of a durable wool body with viscose highlights, giving both matte resilience and silk-like sheen in one design.',
      advantages: ['Combines wool durability with viscose sheen', 'Rich design depth', 'More resilient than pure viscose'],
      disadvantages: ['Care follows the more delicate viscose component', 'Not as hard-wearing as pure wool'],
      typicalApplications: ['Design-led living rooms', 'Hospitality feature areas', 'Premium residential rugs'],
      durability: 3, softness: 4, luxuryLevel: 4,
      maintenance: 'Gentle vacuuming; professional cleaning, treating it like a viscose-containing rug.',
      recommendedProjects: ['residential', 'hospitality'], alternatives: ['indian-wool', 'viscose'],
    } },

  { id: 'cotton', name: 'Cotton', positioning: 'Economy', fibreType: 'natural',
    notes: 'A soft natural fibre used in flatweaves and dhurries.',
    applications: 'Commonly considered for dhurries and flatweave rugs.',
    properties: ['Soft natural fibre', 'Takes colour well'], advantages: ['Friendly tier', 'Good for flatweaves'],
    limitations: ['Character suits lighter constructions — the team advises'],
    maintenance: 'The team can share care guidance for your construction.', priceFactors: PRICE, tags: ['cotton', 'dhurrie', 'flatweave'],
    profile: {
      description: 'A soft, colour-friendly natural fibre used mainly in flatweaves and dhurries at an economical tier.',
      advantages: ['Economical', 'Takes colour well', 'Light and easy to handle', 'Good for flatweaves and dhurries'],
      disadvantages: ['Less hard-wearing than wool', 'Suited to lighter constructions', 'Not ideal for heavy traffic'],
      typicalApplications: ['Dhurries', 'Flatweave rugs', 'Casual and children’s rooms'],
      durability: 3, softness: 3, luxuryLevel: 2,
      maintenance: 'Care depends on construction; many cotton flatweaves tolerate gentle washing — the team advises.',
      recommendedProjects: ['residential', 'budget'], alternatives: ['jute', 'linen'],
    } },

  { id: 'jute', name: 'Jute', positioning: 'Economy', fibreType: 'natural',
    notes: 'A natural plant fibre with an organic, textured appearance.',
    applications: 'Commonly considered for relaxed, natural-look interiors.',
    properties: ['Natural plant fibre', 'Organic texture'], advantages: ['Natural, casual aesthetic'],
    limitations: ['Sensitive to moisture — the team advises on placement'],
    maintenance: 'Keep dry; gentle dry cleaning. The team can advise.', priceFactors: PRICE, tags: ['jute', 'natural fibre'],
    profile: {
      description: 'A natural plant fibre with a warm, organic texture, chosen for relaxed, natural-look interiors at an economical tier.',
      advantages: ['Natural, casual aesthetic', 'Economical', 'Adds organic texture'],
      disadvantages: ['Sensitive to moisture', 'Coarser underfoot', 'Not for wet or very high-traffic areas'],
      typicalApplications: ['Living rooms', 'Natural-look interiors', 'Layering rugs'],
      durability: 3, softness: 2, luxuryLevel: 2,
      maintenance: 'Keep dry; gentle dry cleaning only — avoid soaking.',
      recommendedProjects: ['residential', 'budget'], alternatives: ['sisal', 'hemp'],
    } },

  { id: 'sisal', name: 'Sisal', positioning: 'Economy', fibreType: 'natural',
    notes: 'A natural plant fibre with a structured weave and matte look.',
    applications: 'Commonly considered for natural-fibre floor coverings; suitability confirmed per project.',
    properties: ['Natural plant fibre', 'Structured, matte surface'], advantages: ['Textured natural look'],
    limitations: ['Sensitive to moisture — the team advises'],
    maintenance: 'Keep dry; dry cleaning methods. The team can advise.', priceFactors: PRICE, tags: ['sisal', 'natural fibre'],
    profile: {
      description: 'A hard-wearing natural plant fibre with a structured, matte surface, chosen for textured natural-fibre floor coverings.',
      advantages: ['Hard-wearing for a natural fibre', 'Structured, textured look', 'Suits high-traffic natural interiors'],
      disadvantages: ['Firm, coarse underfoot', 'Sensitive to moisture and staining', 'Not for wet areas'],
      typicalApplications: ['Hallways and stairs', 'Living rooms', 'Natural-look, higher-traffic interiors'],
      durability: 4, softness: 1, luxuryLevel: 2,
      maintenance: 'Keep dry; dry cleaning methods only.',
      recommendedProjects: ['residential', 'commercial', 'budget'], alternatives: ['jute', 'hemp'],
    } },

  { id: 'leather', name: 'Leather', positioning: 'Premium', fibreType: 'natural',
    notes: 'Woven or patchwork leather chosen for texture and statement design.',
    applications: 'Commonly considered for feature and statement interiors.',
    properties: ['Natural material', 'Distinct texture'], advantages: ['Bold, statement look'],
    limitations: ['Specialist care; the team advises on placement'],
    maintenance: 'Specialist leather care; keep away from moisture.', priceFactors: PRICE, tags: ['leather', 'statement'],
    profile: {
      description: 'Woven or patchwork leather chosen for its distinct texture and bold, statement look in feature interiors.',
      advantages: ['Bold, statement appearance', 'Distinct texture', 'Durable when cared for'],
      disadvantages: ['Requires specialist care', 'Sensitive to moisture', 'Not a soft-underfoot option'],
      typicalApplications: ['Feature and statement rooms', 'Design-led residential', 'Boutique commercial spaces'],
      durability: 4, softness: 2, luxuryLevel: 4,
      maintenance: 'Specialist leather care; keep away from moisture and direct heat.',
      recommendedProjects: ['residential', 'commercial', 'premium'], alternatives: ['indian-wool', 'hemp'],
    } },

  { id: 'pet', name: 'PET (Recycled Polyester)', positioning: 'Economy', fibreType: 'synthetic',
    notes: 'A synthetic fibre often chosen for colour vibrancy and indoor–outdoor styles.',
    applications: 'Commonly considered for casual, indoor–outdoor and value-tier rugs.',
    properties: ['Synthetic fibre', 'Vivid colours'], advantages: ['Colour vibrancy', 'Value tier'],
    limitations: ['Look differs from natural fibres — the team advises'],
    maintenance: 'The team can share care guidance for your setting.', priceFactors: PRICE, tags: ['pet', 'synthetic', 'outdoor'],
    profile: {
      description: 'A hard-wearing, moisture-tolerant synthetic fibre often chosen for colour vibrancy and indoor–outdoor styles at a value tier.',
      advantages: ['Hard-wearing and moisture-tolerant', 'Vivid, fade-resistant colours', 'Value tier', 'Suits indoor–outdoor use'],
      disadvantages: ['Look and feel differ from natural fibres', 'Less premium hand-feel'],
      typicalApplications: ['Indoor–outdoor rugs', 'High-traffic casual areas', 'Children’s and pet-friendly rooms'],
      durability: 4, softness: 3, luxuryLevel: 1,
      maintenance: 'Tolerant of cleaning; many styles handle damp wiping — the team advises for your setting.',
      recommendedProjects: ['residential', 'outdoor', 'budget', 'commercial'], alternatives: ['sisal', 'cotton'],
    } },

  { id: 'tencel', name: 'Tencel (Lyocell)', positioning: 'Premium', fibreType: 'synthetic',
    notes: 'A wood-pulp-based fibre with a soft, subtle sheen.',
    applications: 'Commonly considered for soft, decorative rugs.',
    properties: ['Soft surface', 'Subtle sheen'], advantages: ['Silky feel', 'Refined look'],
    limitations: ['Decorative use is typical — the team advises'],
    maintenance: 'Gentle, dry-focused care; the team can advise.', priceFactors: PRICE, tags: ['tencel', 'lyocell', 'sheen'],
    profile: {
      description: 'A wood-pulp-based fibre with a silky feel and subtle, refined sheen, chosen for soft decorative rugs.',
      advantages: ['Silky, soft feel', 'Subtle, refined sheen', 'Smooth colour depth'],
      disadvantages: ['Best for low-traffic decorative use', 'Moisture-sensitive', 'Needs gentle care'],
      typicalApplications: ['Decorative living rooms', 'Bedrooms', 'Soft feature rugs'],
      durability: 2, softness: 5, luxuryLevel: 4,
      maintenance: 'Gentle, dry-focused care; avoid soaking.',
      recommendedProjects: ['residential', 'decorative'], alternatives: ['viscose', 'bamboo-silk'],
    } },

  { id: 'linen', name: 'Linen', positioning: 'Premium', fibreType: 'natural',
    notes: 'A natural flax fibre with a relaxed, matte character.',
    applications: 'Commonly considered for understated, natural-look pieces.',
    properties: ['Natural flax fibre', 'Matte, relaxed texture'], advantages: ['Natural, calm aesthetic'],
    limitations: ['Character suits lighter constructions — the team advises'],
    maintenance: 'The team can share care guidance.', priceFactors: PRICE, tags: ['linen', 'natural fibre'],
    profile: {
      description: 'A natural flax fibre with a relaxed, matte character, chosen for understated, natural-look pieces.',
      advantages: ['Calm, natural aesthetic', 'Matte, refined texture', 'Natural fibre appeal'],
      disadvantages: ['Suits lighter constructions', 'Less hard-wearing than wool', 'Moisture-sensitive'],
      typicalApplications: ['Understated living rooms', 'Bedrooms', 'Natural-look interiors'],
      durability: 3, softness: 3, luxuryLevel: 3,
      maintenance: 'Gentle care; the team can share guidance for your construction.',
      recommendedProjects: ['residential', 'decorative'], alternatives: ['cotton', 'hemp'],
    } },

  { id: 'hemp', name: 'Hemp', positioning: 'Economy', fibreType: 'natural',
    notes: 'A natural plant fibre with a rugged, organic texture.',
    applications: 'Commonly considered for natural-look, casual interiors.',
    properties: ['Natural plant fibre', 'Coarse, organic texture'], advantages: ['Rustic natural look'],
    limitations: ['Texture is coarse by nature — the team advises on fit'],
    maintenance: 'Keep dry; dry cleaning methods. The team can advise.', priceFactors: PRICE, tags: ['hemp', 'natural fibre'],
    profile: {
      description: 'A rugged, hard-wearing natural plant fibre with a coarse, organic texture for casual natural-look interiors.',
      advantages: ['Hard-wearing natural fibre', 'Rustic, organic look', 'Economical'],
      disadvantages: ['Coarse underfoot', 'Moisture-sensitive', 'Limited softness'],
      typicalApplications: ['Casual living areas', 'Natural-look, higher-traffic interiors', 'Layering'],
      durability: 4, softness: 1, luxuryLevel: 2,
      maintenance: 'Keep dry; dry cleaning methods only.',
      recommendedProjects: ['residential', 'budget'], alternatives: ['jute', 'sisal'],
    } },
]
